<a href="https://colab.research.google.com/github/MoniaO/GraphNeuralNetwork_Thesis/blob/develop/notebooks/train_setup_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Klonowanie środowiska git

In [2]:
!git clone https://github.com/MoniaO/GraphNeuralNetwork_Thesis.git
%cd GraphNeuralNetwork_Thesis
!git checkout develop

Cloning into 'GraphNeuralNetwork_Thesis'...
remote: Enumerating objects: 415, done.
remote: Counting objects: 100% (140/140), done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 415 (delta 79), reused 88 (delta 37), pack-reused 275 (from 1)
Receiving objects: 100% (415/415), 107.82 KiB | 4.31 MiB/s, done.
Resolving deltas: 100% (206/206), done.
/content/GraphNeuralNetwork_Thesis
Branch 'develop' set up to track remote branch 'develop' from 'origin'.
Switched to a new branch 'develop'

In [3]:
!pip install wandb hydra-core omegaconf torch-geometric ogb

Requirement already satisfied: wandb in /usr/local/lib/python3.12/dist-packages (0.28.0)
Collecting hydra-core
  Downloading hydra_core-1.3.4-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: omegaconf in /usr/local/lib/python3.12/dist-packages (2.3.1)
Collecting torch-geometric
  Downloading torch_geometric-2.8.0-py3-none-any.whl.metadata (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.4/64.4 kB 2.8 MB/s eta 0:00:00
Collecting ogb
  Downloading ogb-1.3.6-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: click>=8.2.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (8.4.2)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (3.1.50)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from wandb) (26.2)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from wandb) (4.10.0)
Requirement already satisfied: protobuf!=5.28.0,!=5.29.0,<8,>4.21.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (5.29.6)
Requirement already satisfied: pydantic<3,>=2.6 in /usr/local/lib/python3.12/dist-packages (from wandb) (2.13.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from wandb) (6.0.3)
Requirement already satisfied: requests<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (2.32.4)
Requirement already satisfied: sentry-sdk>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (2.63.0)
Requirement already satisfied: typing-extensions<5,>=4.8 in /usr/local/lib/python3.12/dist-packages (from wandb) (4.15.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.12/dist-packages (from hydra-core) (4.9.3)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.14.1)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (2025.3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.1.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (2.0.2)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (5.9.5)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.3.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.7.1)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from ogb) (2.11.0+cu128)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from ogb) (1.6.1)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from ogb) (2.2.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from ogb) (1.17.0)
Requirement already satisfied: urllib3>=1.24.0 in /usr/local/lib/python3.12/dist-packages (from ogb) (2.5.0)
Collecting outdated>=0.2.0 (from ogb)
  Downloading outdated-0.2.2-py2.py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.29,>=1.0.0->wandb) (4.0.12)
Requirement already satisfied: setuptools>=44 in /usr/local/lib/python3.12/dist-packages (from outdated>=0.2.0->ogb) (75.2.0)
Collecting littleutils (from outdated>=0.2.0->ogb)
  Downloading littleutils-0.2.4-py3-none-any.whl.metadata (679 bytes)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->ogb) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->ogb) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->ogb) (2026.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.6->wandb) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.6->wandb) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.6->wandb) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (2026.6.17)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.20.0->ogb) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.20.0->ogb) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.20.0->ogb) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (3.29.4)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (3.6.1)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (12.8.90)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (1.24.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch-geometric) (3.0.3)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.6.0->ogb) (1.5.5)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb) (5.0.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.6.0->ogb) (1.3.0)
Downloading hydra_core-1.3.4-py3-none-any.whl (155 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.5/155.5 kB 7.1 MB/s eta 0:00:00
Downloading torch_geometric-2.8.0-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 33.2 MB/s eta 0:00:00
Downloading ogb-1.3.6-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.8/78.8 kB 8.1 MB/s eta 0:00:00
Downloading outdated-0.2.2-py2.py3-none-any.whl (7.5 kB)
Downloading littleutils-0.2.4-py3-none-any.whl (8.1 kB)
Installing collected packages: littleutils, outdated, hydra-core, torch-geometric, ogb
Successfully installed hydra-core-1.3.4 littleutils-0.2.4 ogb-1.3.6 outdated-0.2.2 torch-geometric-2.8.0

In [4]:
import os

In [5]:
import wandb
wandb.login(key="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")
#you can find your_key in W&B under User settings -> API key"

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: [wandb.login()] Using explicit session credentials for https://api.wandb.ai.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: oskardmonika (politechnika-gnn-thesis) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

In [6]:
wandb.login(verify=True)
#additional verification of login - if everything's fine, it should return "True"

True

In [ ]:
#!git checkout src/data/load_data.py

In [18]:
!git pull origin develop

remote: Enumerating objects: 13, done.
remote: Counting objects: 100% (13/13), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 7 (delta 4), reused 7 (delta 4), pack-reused 0 (from 0)
Unpacking objects: 100% (7/7), 625 bytes | 625.00 KiB/s, done.
From https://github.com/MoniaO/GraphNeuralNetwork_Thesis
 * branch            develop    -> FETCH_HEAD
   28cf77c..64d84d4  develop    -> origin/develop
Updating 28cf77c..64d84d4
Fast-forward
 configs/data/dataset_syn.yaml | 2 +-
 src/train_lp.py               | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)

In [ ]:
#run for ogb dataset
#!python src/train.py model=gcn data=ogb_dataset

data:
  name: ogbl-ddi
  task_type: link_prediction
  metric: hits@20
  root: data/
  evaluator_type: ogb
model:
  name: gcn
  hidden_dim: 64
  num_layers: 3
  dropout: 0.2
  batch_norm: true
  activation: relu
training:
  lr: 0.001
  epochs: 20
  batch_size: 32
  optimizer: adam
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: oskardmonika (politechnika-gnn-thesis) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: ⢿ setting up run dj92bl5t (0.0s)
wandb: ⣻ setting up run dj92bl5t (0.0s)
wandb: ⣽ setting up run dj92bl5t (0.0s)
wandb: ⣾ setting up run dj92bl5t (0.0s)
wandb: ⣷ setting up run dj92bl5t (0.5s)
wandb: ⣯ setting up run dj92bl5t (0.5s)
wandb: ⣟ setting up run dj92bl5t (0.5s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260702_133719-dj92bl5t
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run gcn_ogbl-ddi_epochs20_lr0.001_adam
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/dj92bl5t
Epoch 001 | loss 1.3857 | train AUC 0.7009 | train AUPRC 0.6093 | valid AUC 0.7239 | valid AUPRC 0.6889valid hits@20 0.0000test AUC 0.7354 | test AUPRC 0.7008test hits@20 0.0000
Epoch 002 | loss 1.3844 | train AUC 0.7314 | train AUPRC 0.6388 | valid AUC 0.7545 | valid AUPRC 0.7181valid hits@20 0.0000test AUC 0.7641 | test AUPRC 0.7279test hits@20 0.0000
Epoch 003 | loss 1.3828 | train AUC 0.7563 | train AUPRC 0.6648 | valid AUC 0.7801 | valid AUPRC 0.7439valid hits@20 0.0000test AUC 0.7872 | test AUPRC 0.7514test hits@20 0.0000
Epoch 004 | loss 1.3809 | train AUC 0.7755 | train AUPRC 0.6862 | valid AUC 0.8001 | valid AUPRC 0.7653valid hits@20 0.0000test AUC 0.8050 | test AUPRC 0.7711test hits@20 0.0000
Epoch 005 | loss 1.3786 | train AUC 0.7899 | train AUPRC 0.7032 | valid AUC 0.8151 | valid AUPRC 0.7823valid hits@20 0.0000test AUC 0.8183 | test AUPRC 0.7873test hits@20 0.0000
Epoch 006 | loss 1.3759 | train AUC 0.8001 | train AUPRC 0.7162 | valid AUC 0.8262 | valid AUPRC 0.7957valid hits@20 0.0000test AUC 0.8284 | test AUPRC 0.8006test hits@20 0.0000
Epoch 007 | loss 1.3727 | train AUC 0.8081 | train AUPRC 0.7268 | valid AUC 0.8343 | valid AUPRC 0.8064valid hits@20 0.0000test AUC 0.8361 | test AUPRC 0.8113test hits@20 0.0000
Epoch 008 | loss 1.3688 | train AUC 0.8138 | train AUPRC 0.7352 | valid AUC 0.8402 | valid AUPRC 0.8151valid hits@20 0.0000test AUC 0.8420 | test AUPRC 0.8200test hits@20 0.0000
Epoch 009 | loss 1.3645 | train AUC 0.8177 | train AUPRC 0.7414 | valid AUC 0.8444 | valid AUPRC 0.8223valid hits@20 0.0000test AUC 0.8464 | test AUPRC 0.8274test hits@20 0.0000
Epoch 010 | loss 1.3593 | train AUC 0.8207 | train AUPRC 0.7478 | valid AUC 0.8471 | valid AUPRC 0.8284valid hits@20 0.0000test AUC 0.8498 | test AUPRC 0.8341test hits@20 0.0000
Epoch 011 | loss 1.3535 | train AUC 0.8223 | train AUPRC 0.7523 | valid AUC 0.8487 | valid AUPRC 0.8336valid hits@20 0.0000test AUC 0.8525 | test AUPRC 0.8401test hits@20 0.0000
Epoch 012 | loss 1.3470 | train AUC 0.8230 | train AUPRC 0.7565 | valid AUC 0.8494 | valid AUPRC 0.8383valid hits@20 0.0000test AUC 0.8547 | test AUPRC 0.8457test hits@20 0.0000
Epoch 013 | loss 1.3400 | train AUC 0.8237 | train AUPRC 0.7607 | valid AUC 0.8498 | valid AUPRC 0.8424valid hits@20 0.0000test AUC 0.8566 | test AUPRC 0.8510test hits@20 0.0000
Epoch 014 | loss 1.3326 | train AUC 0.8232 | train AUPRC 0.7624 | valid AUC 0.8499 | valid AUPRC 0.8463valid hits@20 0.0000test AUC 0.8583 | test AUPRC 0.8562test hits@20 0.0000
Epoch 015 | loss 1.3251 | train AUC 0.8239 | train AUPRC 0.7662 | valid AUC 0.8501 | valid AUPRC 0.8499valid hits@20 0.0000test AUC 0.8598 | test AUPRC 0.8610test hits@20 0.0000
Epoch 016 | loss 1.3178 | train AUC 0.8244 | train AUPRC 0.7696 | valid AUC 0.8503 | valid AUPRC 0.8532valid hits@20 0.0000test AUC 0.8612 | test AUPRC 0.8654test hits@20 0.0001
Epoch 017 | loss 1.3111 | train AUC 0.8247 | train AUPRC 0.7728 | valid AUC 0.8506 | valid AUPRC 0.8563valid hits@20 0.0000test AUC 0.8625 | test AUPRC 0.8694test hits@20 0.0001
Epoch 018 | loss 1.3050 | train AUC 0.8254 | train AUPRC 0.7751 | valid AUC 0.8511 | valid AUPRC 0.8592valid hits@20 0.0000test AUC 0.8637 | test AUPRC 0.8730test hits@20 0.0001
Epoch 019 | loss 1.2998 | train AUC 0.8254 | train AUPRC 0.7774 | valid AUC 0.8518 | valid AUPRC 0.8620valid hits@20 0.0000test AUC 0.8647 | test AUPRC 0.8762test hits@20 0.0001
Epoch 020 | loss 1.2962 | train AUC 0.8259 | train AUPRC 0.7793 | valid AUC 0.8527 | valid AUPRC 0.8647valid hits@20 0.0000test AUC 0.8656 | test AUPRC 0.8790test hits@20 0.0001
wandb: ⢿ updating run metadata (0.0s)
wandb: ⣻ updating run metadata (0.0s)
wandb: ⣽ updating run metadata (0.0s)
wandb: ⣾ updating run metadata (0.0s)
wandb: ⣷ Finishing up...
wandb: ⣯ Finishing up...
wandb: ⣟ Finishing up...
wandb: ⡿ Finishing up...
wandb: ⢿ Finishing up...
wandb: ⣻ uploading history steps 0-19, summary, console lines 1-19 (0.0s)
wandb: ⣽ uploading history steps 0-19, summary, console lines 1-19 (0.0s)
wandb: ⣾ uploading history steps 0-19, summary, console lines 1-19 (0.0s)
wandb: ⣷ uploading history steps 0-19, summary, console lines 1-19 (0.0s)
wandb: ⣯ uploading history steps 0-19, summary, console lines 1-19 (0.0s)
wandb:
wandb: Run history:
wandb:        epoch ▁▁▂▂▂▃▃▄▄▄▅▅▅▆▆▇▇▇██
wandb:         loss ████▇▇▇▇▆▆▅▅▄▄▃▃▂▂▁▁
wandb:           lr ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:     test/auc ▁▃▄▅▅▆▆▇▇▇▇▇████████
wandb:   test/auprc ▁▂▃▄▄▅▅▆▆▆▆▇▇▇▇▇████
wandb: test/hits@20 ▁▁▁▁▄▄▄▄▄▄▄▄▄▄▄▆▆▆▇█
wandb:    train/auc ▁▃▄▅▆▇▇▇████████████
wandb:  train/auprc ▁▂▃▄▅▅▆▆▆▇▇▇▇▇▇█████
wandb:    valid/auc ▁▃▄▅▆▇▇▇████████████
wandb:  valid/auprc ▁▂▃▄▅▅▆▆▆▇▇▇▇▇▇█████
wandb:           +1 ...
wandb:
wandb: Run summary:
wandb:   best_epoch 20
wandb:   best_valid 0.8647
wandb:        epoch 20
wandb:         loss 1.29616
wandb:           lr 0.001
wandb:     test/auc 0.86559
wandb:   test/auprc 0.87898
wandb: test/hits@20 7e-05
wandb:    train/auc 0.82588
wandb:  train/auprc 0.77931
wandb:           +3 ...
wandb:
wandb: 🚀 View run gcn_ogbl-ddi_epochs20_lr0.001_adam at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/dj92bl5t
wandb: ⭐️ View project at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260702_133719-dj92bl5t/logs

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [8]:
#data in MyDrive, to test if it works for Shared Drive
import os
os.environ["PHARMA_DATA_ROOT"] = "/content/drive/MyDrive/synthetic_pharmacotherapy_v2 2/synthetic_pharmacotherapy_v2_1_nn_benchmark"

In [19]:
#single run (not multiple parameters, one target)
!python src/train_lp.py model=gnn_lp model.conv_type=sage data=dataset_syn training.epochs=30

data:
  name: syn
  target:
  - AKI
  - DILI
  - Depression
  - Falls
  - Delirium
  - GI_bleeding
  - Hyponatremia
  - Hyperkalemia
  - QT_arrhythmia
  - Hospitalization
  evaluator_type: synthetic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_1_edges_audited.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_samples_no_overlap.csv
      multihospital: synthetic_pharmacotherapy_v2_samples_multihospital.csv
      hidden: synthetic_pharmacotherapy_v2_samples_hidden_confounder.csv
      doc: synthetic_pharmacotherapy_v2_samples_noisy_documentation.csv
      bias: synthetic_pharmacotherapy_v2_samples_selection_bias.csv
    scenario: clean
model:
  name: gnn_lp
  conv_type: sage
  hidden_dim: 64
  num_layers: 3
  dropout: 0.2
  batch_norm: true
  activation: relu
  aggr: sum
  heads: 4
training:
  lr: 0.001
  epochs: 30
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
  heads: 4
  dropout: 0.2
  pooling: mean
  batch_norm: true
  conv_type: gcn
  eval_per_endpoint: true
meta:
  owner_initials: MO
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: oskardmonika (politechnika-gnn-thesis) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: ⢿ setting up run kls91628 (0.0s)
wandb: ⣻ setting up run kls91628 (0.0s)
wandb: ⣽ setting up run kls91628 (0.0s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260713_201237-kls91628
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run MO_gnn_lp_syn_multitarget_sage_clean_ep30_layer3_hidden64_lr0.001_bs32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/kls91628
Epoch 001 | train loss 1.3539 | train AUC 0.3940 | train AUPRC 0.0313 | valid loss 0.7754 | test loss 0.8323 | valid AUC 0.4160 | valid AUPRC 0.0373 | test AUC 0.4069 | test AUPRC 0.0326
Epoch 002 | train loss 1.3471 | train AUC 0.4000 | train AUPRC 0.0315 | valid loss 0.7754 | test loss 0.8456 | valid AUC 0.4189 | valid AUPRC 0.0377 | test AUC 0.4062 | test AUPRC 0.0321
Epoch 003 | train loss 1.3602 | train AUC 0.4020 | train AUPRC 0.0315 | valid loss 0.7093 | test loss 0.7513 | valid AUC 0.4075 | valid AUPRC 0.0355 | test AUC 0.4089 | test AUPRC 0.0320
Epoch 004 | train loss 1.3378 | train AUC 0.4601 | train AUPRC 0.0345 | valid loss 0.6497 | test loss 0.6659 | valid AUC 0.3925 | valid AUPRC 0.0326 | test AUC 0.4206 | test AUPRC 0.0327
Epoch 005 | train loss 1.3362 | train AUC 0.5786 | train AUPRC 0.0647 | valid loss 0.6175 | test loss 0.6207 | valid AUC 0.4078 | valid AUPRC 0.0326 | test AUC 0.4933 | test AUPRC 0.0393
Epoch 006 | train loss 1.3370 | train AUC 0.5762 | train AUPRC 0.0639 | valid loss 0.6198 | test loss 0.6219 | valid AUC 0.4802 | valid AUPRC 0.0385 | test AUC 0.4835 | test AUPRC 0.0382
Epoch 007 | train loss 1.3358 | train AUC 0.5642 | train AUPRC 0.0587 | valid loss 0.6369 | test loss 0.6392 | valid AUC 0.4830 | valid AUPRC 0.0381 | test AUC 0.4619 | test AUPRC 0.0365
Epoch 008 | train loss 1.3362 | train AUC 0.5665 | train AUPRC 0.0559 | valid loss 0.6630 | test loss 0.6666 | valid AUC 0.4314 | valid AUPRC 0.0355 | test AUC 0.4911 | test AUPRC 0.0391
Epoch 009 | train loss 1.3338 | train AUC 0.5351 | train AUPRC 0.0454 | valid loss 0.6927 | test loss 0.6995 | valid AUC 0.4113 | valid AUPRC 0.0356 | test AUC 0.5112 | test AUPRC 0.0412
Epoch 010 | train loss 1.3318 | train AUC 0.5358 | train AUPRC 0.0456 | valid loss 0.7158 | test loss 0.7241 | valid AUC 0.4165 | valid AUPRC 0.0360 | test AUC 0.5014 | test AUPRC 0.0403
Epoch 011 | train loss 1.3321 | train AUC 0.5052 | train AUPRC 0.0408 | valid loss 0.7282 | test loss 0.7363 | valid AUC 0.4193 | valid AUPRC 0.0367 | test AUC 0.4874 | test AUPRC 0.0392
Epoch 012 | train loss 1.3325 | train AUC 0.4851 | train AUPRC 0.0389 | valid loss 0.7332 | test loss 0.7410 | valid AUC 0.4207 | valid AUPRC 0.0372 | test AUC 0.4939 | test AUPRC 0.0401
Epoch 013 | train loss 1.3324 | train AUC 0.4819 | train AUPRC 0.0387 | valid loss 0.7321 | test loss 0.7386 | valid AUC 0.4206 | valid AUPRC 0.0372 | test AUC 0.5024 | test AUPRC 0.0410
Epoch 014 | train loss 1.3330 | train AUC 0.4898 | train AUPRC 0.0395 | valid loss 0.7270 | test loss 0.7318 | valid AUC 0.4233 | valid AUPRC 0.0372 | test AUC 0.5148 | test AUPRC 0.0427
Epoch 015 | train loss 1.3313 | train AUC 0.4996 | train AUPRC 0.0403 | valid loss 0.7206 | test loss 0.7237 | valid AUC 0.4334 | valid AUPRC 0.0376 | test AUC 0.5287 | test AUPRC 0.0447
Epoch 016 | train loss 1.3316 | train AUC 0.5175 | train AUPRC 0.0417 | valid loss 0.7128 | test loss 0.7146 | valid AUC 0.4455 | valid AUPRC 0.0385 | test AUC 0.5505 | test AUPRC 0.0472
Epoch 017 | train loss 1.3309 | train AUC 0.5496 | train AUPRC 0.0447 | valid loss 0.7041 | test loss 0.7047 | valid AUC 0.4596 | valid AUPRC 0.0395 | test AUC 0.5727 | test AUPRC 0.0508
Epoch 018 | train loss 1.3304 | train AUC 0.5825 | train AUPRC 0.0505 | valid loss 0.6960 | test loss 0.6957 | valid AUC 0.4804 | valid AUPRC 0.0406 | test AUC 0.5825 | test AUPRC 0.0545
Epoch 019 | train loss 1.3305 | train AUC 0.5824 | train AUPRC 0.0516 | valid loss 0.6895 | test loss 0.6889 | valid AUC 0.5072 | valid AUPRC 0.0422 | test AUC 0.5806 | test AUPRC 0.0561
Epoch 020 | train loss 1.3309 | train AUC 0.5757 | train AUPRC 0.0507 | valid loss 0.6853 | test loss 0.6844 | valid AUC 0.5287 | valid AUPRC 0.0439 | test AUC 0.5756 | test AUPRC 0.0554
Epoch 021 | train loss 1.3298 | train AUC 0.5607 | train AUPRC 0.0483 | valid loss 0.6820 | test loss 0.6811 | valid AUC 0.5497 | valid AUPRC 0.0462 | test AUC 0.5687 | test AUPRC 0.0536
Epoch 022 | train loss 1.3312 | train AUC 0.5435 | train AUPRC 0.0461 | valid loss 0.6814 | test loss 0.6806 | valid AUC 0.5600 | valid AUPRC 0.0479 | test AUC 0.5634 | test AUPRC 0.0521
Epoch 023 | train loss 1.3307 | train AUC 0.5287 | train AUPRC 0.0447 | valid loss 0.6824 | test loss 0.6818 | valid AUC 0.5628 | valid AUPRC 0.0487 | test AUC 0.5602 | test AUPRC 0.0511
Epoch 024 | train loss 1.3305 | train AUC 0.5216 | train AUPRC 0.0441 | valid loss 0.6838 | test loss 0.6832 | valid AUC 0.5654 | valid AUPRC 0.0494 | test AUC 0.5588 | test AUPRC 0.0502
Epoch 025 | train loss 1.3304 | train AUC 0.5192 | train AUPRC 0.0438 | valid loss 0.6862 | test loss 0.6857 | valid AUC 0.5624 | valid AUPRC 0.0491 | test AUC 0.5586 | test AUPRC 0.0492
Epoch 026 | train loss 1.3305 | train AUC 0.5192 | train AUPRC 0.0437 | valid loss 0.6894 | test loss 0.6889 | valid AUC 0.5560 | valid AUPRC 0.0482 | test AUC 0.5572 | test AUPRC 0.0480
Epoch 027 | train loss 1.3304 | train AUC 0.5118 | train AUPRC 0.0426 | valid loss 0.6936 | test loss 0.6931 | valid AUC 0.5505 | valid AUPRC 0.0475 | test AUC 0.5524 | test AUPRC 0.0472
Epoch 028 | train loss 1.3305 | train AUC 0.5013 | train AUPRC 0.0414 | valid loss 0.6976 | test loss 0.6974 | valid AUC 0.5468 | valid AUPRC 0.0471 | test AUC 0.5375 | test AUPRC 0.0462
Epoch 029 | train loss 1.3301 | train AUC 0.4978 | train AUPRC 0.0410 | valid loss 0.7003 | test loss 0.7003 | valid AUC 0.5414 | valid AUPRC 0.0461 | test AUC 0.5296 | test AUPRC 0.0456
Epoch 030 | train loss 1.3300 | train AUC 0.4957 | train AUPRC 0.0408 | valid loss 0.7022 | test loss 0.7023 | valid AUC 0.5350 | valid AUPRC 0.0451 | test AUC 0.5244 | test AUPRC 0.0448
wandb: ⢿ updating run metadata (0.0s)
wandb: ⣻ updating run metadata (0.0s)
wandb: ⣽ updating run metadata (0.0s)
wandb: ⣾ updating run metadata (0.0s)
wandb: ⣷ uploading output.log 5.5KB/5.5KB (0.1s)
wandb: ⣷ uploading wandb-summary.json 3.2KB/3.2KB (0.1s)
wandb: ⣷ uploading config.yaml 3.7KB/3.7KB (0.1s)
wandb: ⣯ uploading output.log 5.5KB/5.5KB (0.1s)
wandb: ⣯ uploading wandb-summary.json 3.2KB/3.2KB (0.1s)
wandb: ⣯ uploading config.yaml 3.7KB/3.7KB (0.1s)
wandb:
wandb: Run history:
wandb:          best/epoch ▁▁▁▁▁▃▃▃▃▃▃▃▃▃▃▃▆▆▆▇▇▇████████
wandb:   best/valid_metric ▁▁▁▁▁▂▂▂▂▂▂▂▂▂▂▂▂▃▄▅▆▇████████
wandb:               epoch ▁▁▁▂▂▂▂▃▃▃▃▄▄▄▄▅▅▅▅▆▆▆▆▇▇▇▇███
wandb:                  lr ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:            test/auc ▁▁▁▂▄▄▃▄▅▅▄▄▅▅▆▇████▇▇▇▇▇▇▇▆▆▆
wandb:        test/auc_AKI ▂▄▂▁▂▂▁▄▅▅▄▅▅▆▇▇▇▇▇▇▇▇████████
wandb:       test/auc_DILI ▄▄▁▂▃▂▅▇▆▆▇▇█▇▇▇█████▇▇▇▇▇▇▆▆▆
wandb:   test/auc_Delirium █▆▄▃▃▄▃▂▁▁▂▃▄▄▄▅▆▆▆▆▇▇▇▆▆▆▆▆▆▆
wandb: test/auc_Depression █▆▄▂▂▂▅▂▁▂▃▂▂▂▂▁▁▁▁▂▂▂▂▂▂▂▃▂▂▁
wandb:      test/auc_Falls ▃▄▂▁▁▁▂▃▄▅▆▇▇▇█████████████▇▇▇
wandb:                 +67 ...
wandb:
wandb: Run summary:
wandb:        best/epoch 24
wandb: best/valid_metric 0.04938
wandb:        best_epoch 24
wandb:  best_valid_AUPRC 0.04938
wandb:   checkpoint_path /content/GraphNeural...
wandb:             epoch 30
wandb:                lr 0.001
wandb:          test/auc 0.5244
wandb:      test/auc_AKI 0.57144
wandb:     test/auc_DILI 0.51954
wandb:               +70 ...
wandb:
wandb: 🚀 View run MO_gnn_lp_syn_multitarget_sage_clean_ep30_layer3_hidden64_lr0.001_bs32 at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/kls91628
wandb: ⭐️ View project at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260713_201237-kls91628/logs
Saved checkpoint to: /content/GraphNeuralNetwork_Thesis/outputs/2026-07-13/20-12-36/best_model.pt
Hydra run dir: /content/GraphNeuralNetwork_Thesis/outputs/2026-07-13/20-12-36

In [20]:
!python src/train_lp.py model=gnn_lp model.conv_type=transformer data=dataset_syn training.epochs=30 data.target="Hospitalization"

data:
  name: syn
  target: Hospitalization
  evaluator_type: synthetic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_1_edges_audited.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_samples_no_overlap.csv
      multihospital: synthetic_pharmacotherapy_v2_samples_multihospital.csv
      hidden: synthetic_pharmacotherapy_v2_samples_hidden_confounder.csv
      doc: synthetic_pharmacotherapy_v2_samples_noisy_documentation.csv
      bias: synthetic_pharmacotherapy_v2_samples_selection_bias.csv
    scenario: clean
model:
  name: gnn_lp
  conv_type: transformer
  hidden_dim: 64
  num_layers: 3
  dropout: 0.2
  batch_norm: true
  activation: relu
  aggr: sum
  heads: 4
training:
  lr: 0.001
  epochs: 30
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
  heads: 4
  dropout: 0.2
  pooling: mean
  batch_norm: true
  conv_type: gcn
  eval_per_endpoint: true
meta:
  owner_initials: MO
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: oskardmonika (politechnika-gnn-thesis) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: ⢿ setting up run ta5a6k8e (0.0s)
wandb: ⣻ setting up run ta5a6k8e (0.0s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260713_202552-ta5a6k8e
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run MO_gnn_lp_syn_Hospitalization_transformer_clean_ep30_layer3_hidden64_lr0.001_bs32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/ta5a6k8e
Epoch 001 | train loss 1.2282 | train AUC 0.5327 | train AUPRC 0.1341 | valid loss 0.6551 | test loss 0.5862 | valid AUC 0.5125 | valid AUPRC 0.1273 | test AUC 0.5172 | test AUPRC 0.1293
Epoch 002 | train loss 1.2688 | train AUC 0.5321 | train AUPRC 0.1336 | valid loss 0.6902 | test loss 0.6532 | valid AUC 0.5171 | valid AUPRC 0.1283 | test AUC 0.5239 | test AUPRC 0.1321
Epoch 003 | train loss 1.2184 | train AUC 0.5347 | train AUPRC 0.1349 | valid loss 0.7267 | test loss 0.7284 | valid AUC 0.5218 | valid AUPRC 0.1294 | test AUC 0.5271 | test AUPRC 0.1344
Epoch 004 | train loss 1.2138 | train AUC 0.5320 | train AUPRC 0.1342 | valid loss 0.7617 | test loss 0.8068 | valid AUC 0.5216 | valid AUPRC 0.1306 | test AUC 0.5288 | test AUPRC 0.1345
Epoch 005 | train loss 1.2292 | train AUC 0.5311 | train AUPRC 0.1338 | valid loss 0.7612 | test loss 0.7964 | valid AUC 0.5229 | valid AUPRC 0.1306 | test AUC 0.5317 | test AUPRC 0.1350
Epoch 006 | train loss 1.2237 | train AUC 0.5334 | train AUPRC 0.1346 | valid loss 0.7444 | test loss 0.7315 | valid AUC 0.5225 | valid AUPRC 0.1306 | test AUC 0.5357 | test AUPRC 0.1381
Epoch 007 | train loss 1.2184 | train AUC 0.5322 | train AUPRC 0.1335 | valid loss 0.7251 | test loss 0.6687 | valid AUC 0.5241 | valid AUPRC 0.1309 | test AUC 0.5373 | test AUPRC 0.1382
Epoch 008 | train loss 1.2641 | train AUC 0.5223 | train AUPRC 0.1313 | valid loss 0.6995 | test loss 0.6031 | valid AUC 0.5197 | valid AUPRC 0.1295 | test AUC 0.5309 | test AUPRC 0.1368
Epoch 009 | train loss 1.2207 | train AUC 0.5228 | train AUPRC 0.1319 | valid loss 0.6898 | test loss 0.5734 | valid AUC 0.5191 | valid AUPRC 0.1292 | test AUC 0.5325 | test AUPRC 0.1370
Epoch 010 | train loss 1.2989 | train AUC 0.5266 | train AUPRC 0.1316 | valid loss 0.7000 | test loss 0.5872 | valid AUC 0.5165 | valid AUPRC 0.1281 | test AUC 0.5361 | test AUPRC 0.1392
Epoch 011 | train loss 1.2269 | train AUC 0.5280 | train AUPRC 0.1324 | valid loss 0.7155 | test loss 0.6092 | valid AUC 0.5142 | valid AUPRC 0.1274 | test AUC 0.5334 | test AUPRC 0.1392
Epoch 012 | train loss 1.2187 | train AUC 0.5320 | train AUPRC 0.1345 | valid loss 0.7329 | test loss 0.6352 | valid AUC 0.5120 | valid AUPRC 0.1273 | test AUC 0.5288 | test AUPRC 0.1405
Epoch 013 | train loss 1.2180 | train AUC 0.5232 | train AUPRC 0.1337 | valid loss 0.7454 | test loss 0.6505 | valid AUC 0.5107 | valid AUPRC 0.1273 | test AUC 0.5220 | test AUPRC 0.1382
Epoch 014 | train loss 1.2144 | train AUC 0.5230 | train AUPRC 0.1343 | valid loss 0.7554 | test loss 0.6606 | valid AUC 0.5096 | valid AUPRC 0.1276 | test AUC 0.5210 | test AUPRC 0.1352
Epoch 015 | train loss 1.2199 | train AUC 0.5235 | train AUPRC 0.1340 | valid loss 0.7583 | test loss 0.6604 | valid AUC 0.5094 | valid AUPRC 0.1278 | test AUC 0.5184 | test AUPRC 0.1332
Epoch 016 | train loss 1.2280 | train AUC 0.5257 | train AUPRC 0.1343 | valid loss 0.7623 | test loss 0.6757 | valid AUC 0.5061 | valid AUPRC 0.1269 | test AUC 0.5189 | test AUPRC 0.1330
Epoch 017 | train loss 1.2176 | train AUC 0.5243 | train AUPRC 0.1334 | valid loss 0.7616 | test loss 0.6789 | valid AUC 0.5063 | valid AUPRC 0.1267 | test AUC 0.5188 | test AUPRC 0.1335
Epoch 018 | train loss 1.2170 | train AUC 0.5283 | train AUPRC 0.1349 | valid loss 0.7611 | test loss 0.6829 | valid AUC 0.5067 | valid AUPRC 0.1268 | test AUC 0.5230 | test AUPRC 0.1360
Epoch 019 | train loss 1.2173 | train AUC 0.5322 | train AUPRC 0.1363 | valid loss 0.7588 | test loss 0.6793 | valid AUC 0.5079 | valid AUPRC 0.1272 | test AUC 0.5238 | test AUPRC 0.1373
Epoch 020 | train loss 1.2147 | train AUC 0.5354 | train AUPRC 0.1374 | valid loss 0.7572 | test loss 0.6770 | valid AUC 0.5086 | valid AUPRC 0.1274 | test AUC 0.5235 | test AUPRC 0.1379
Epoch 021 | train loss 1.2191 | train AUC 0.5360 | train AUPRC 0.1370 | valid loss 0.7518 | test loss 0.6695 | valid AUC 0.5099 | valid AUPRC 0.1278 | test AUC 0.5219 | test AUPRC 0.1373
Epoch 022 | train loss 1.2148 | train AUC 0.5329 | train AUPRC 0.1357 | valid loss 0.7468 | test loss 0.6642 | valid AUC 0.5110 | valid AUPRC 0.1281 | test AUC 0.5193 | test AUPRC 0.1339
Epoch 023 | train loss 1.2165 | train AUC 0.5309 | train AUPRC 0.1351 | valid loss 0.7431 | test loss 0.6640 | valid AUC 0.5112 | valid AUPRC 0.1280 | test AUC 0.5152 | test AUPRC 0.1316
Epoch 024 | train loss 1.2172 | train AUC 0.5264 | train AUPRC 0.1332 | valid loss 0.7381 | test loss 0.6618 | valid AUC 0.5119 | valid AUPRC 0.1282 | test AUC 0.5111 | test AUPRC 0.1311
Epoch 025 | train loss 1.2179 | train AUC 0.5240 | train AUPRC 0.1321 | valid loss 0.7322 | test loss 0.6575 | valid AUC 0.5120 | valid AUPRC 0.1279 | test AUC 0.5099 | test AUPRC 0.1309
Epoch 026 | train loss 1.2152 | train AUC 0.5217 | train AUPRC 0.1318 | valid loss 0.7261 | test loss 0.6514 | valid AUC 0.5125 | valid AUPRC 0.1278 | test AUC 0.5097 | test AUPRC 0.1307
Epoch 027 | train loss 1.2157 | train AUC 0.5191 | train AUPRC 0.1315 | valid loss 0.7215 | test loss 0.6479 | valid AUC 0.5118 | valid AUPRC 0.1274 | test AUC 0.5097 | test AUPRC 0.1306
Epoch 028 | train loss 1.2165 | train AUC 0.5191 | train AUPRC 0.1316 | valid loss 0.7185 | test loss 0.6482 | valid AUC 0.5101 | valid AUPRC 0.1269 | test AUC 0.5095 | test AUPRC 0.1305
Epoch 029 | train loss 1.2177 | train AUC 0.5196 | train AUPRC 0.1318 | valid loss 0.7177 | test loss 0.6517 | valid AUC 0.5083 | valid AUPRC 0.1264 | test AUC 0.5089 | test AUPRC 0.1304
Epoch 030 | train loss 1.2192 | train AUC 0.5191 | train AUPRC 0.1319 | valid loss 0.7155 | test loss 0.6517 | valid AUC 0.5049 | valid AUPRC 0.1255 | test AUC 0.5085 | test AUPRC 0.1303
wandb: ⢿ updating run metadata (0.0s)
wandb: ⣻ updating run metadata (0.0s)
wandb: ⣽ updating run metadata (0.0s)
wandb: ⣾ updating run metadata (0.0s)
wandb: ⣷ uploading history steps 26-29, summary, console lines 27-29 (0.1s)
wandb: ⣯ uploading history steps 26-29, summary, console lines 27-29 (0.1s)
wandb: ⣟ uploading history steps 26-29, summary, console lines 27-29 (0.1s)
wandb:
wandb: Run history:
wandb:                 best/epoch ▁▂▃▅▅▇████████████████████████
wandb:          best/valid_metric ▁▃▅▇▇▇████████████████████████
wandb:                      epoch ▁▁▁▂▂▂▂▃▃▃▃▄▄▄▄▅▅▅▅▆▆▆▆▇▇▇▇███
wandb:                         lr ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:                   test/auc ▃▅▆▆▇██▆▇█▇▆▄▄▃▄▃▅▅▅▄▄▃▂▁▁▁▁▁▁
wandb:   test/auc_Hospitalization ▃▅▆▆▇██▆▇█▇▆▄▄▃▄▃▅▅▅▄▄▃▂▁▁▁▁▁▁
wandb:                 test/auprc ▁▃▄▄▅▆▇▆▆▇▇█▇▅▃▃▄▅▆▆▆▄▂▂▂▂▂▂▂▂
wandb: test/auprc_Hospitalization ▁▃▄▄▅▆▇▆▆▇▇█▇▅▃▃▄▅▆▆▆▄▂▂▂▂▂▂▂▂
wandb:                 test/brier ▁▃▆██▆▄▂▁▁▂▃▃▄▄▄▄▄▄▄▄▄▄▄▄▃▃▃▃▃
wandb:                  test/loss ▁▃▆██▆▄▂▁▁▂▃▃▄▄▄▄▄▄▄▄▄▄▄▄▃▃▃▃▃
wandb:                        +13 ...
wandb:
wandb: Run summary:
wandb:               best/epoch 7
wandb:        best/valid_metric 0.13095
wandb:               best_epoch 7
wandb:         best_valid_AUPRC 0.13095
wandb:          checkpoint_path /content/GraphNeural...
wandb:                    epoch 30
wandb:                       lr 0.001
wandb:                 test/auc 0.50851
wandb: test/auc_Hospitalization 0.50851
wandb:               test/auprc 0.13034
wandb:                      +16 ...
wandb:
wandb: 🚀 View run MO_gnn_lp_syn_Hospitalization_transformer_clean_ep30_layer3_hidden64_lr0.001_bs32 at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/ta5a6k8e
wandb: ⭐️ View project at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260713_202552-ta5a6k8e/logs
Saved checkpoint to: /content/GraphNeuralNetwork_Thesis/outputs/2026-07-13/20-25-51/best_model.pt
Hydra run dir: /content/GraphNeuralNetwork_Thesis/outputs/2026-07-13/20-25-51

In [ ]:
#multirun
!python src/train.py --multirun model=gcn data=dataset_syn training.epochs=50 data.target="Hospitalization" model.num_layers=2,3,4,6,8,12

[2026-07-09 10:59:35,246][HYDRA] Launching 6 jobs locally
[2026-07-09 10:59:35,247][HYDRA] 	#0 : model=gcn data=dataset_syn training.epochs=50 data.target=Hospitalization model.num_layers=2
data:
  name: syn
  target: Hospitalization
  evaluator_type: synthethic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_edges.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_samples_nooverlap.csv
      multihospital: synthetic_pharmacotherapy_v2_samples_multihospital.csv
    scenario: clean
model:
  name: gcn
  hidden_dim: 64
  num_layers: 2
  dropout: 0.2
  batch_norm: true
  activation: relu
training:
  lr: 0.001
  epochs: 50
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
meta:
  owner_initials: mo
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis
  run_name: ${meta.owner_initials}_${model.name}_${data.name}_${data.target}_${data.dataset.scenario}_ep${training.epochs}_layer${model.num_layers}_hidden${model.hidden_dim}_lr${training.lr}_bs${training.batch_size}

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: oskardmonika (politechnika-gnn-thesis) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: ⢿ setting up run bdtlnkhi (0.0s)
wandb: ⣻ setting up run bdtlnkhi (0.0s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260709_105935-bdtlnkhi
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run mo_gcn_syn_Hospitalization_clean_ep50_layer2_hidden64_lr0.001_bs32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/bdtlnkhi
Epoch 001 | train loss 0.4027 | val AUC 0.4810 | val AP 0.1368 | test AUC 0.5024 | test AP 0.1580
Epoch 002 | train loss 0.3817 | val AUC 0.5418 | val AP 0.1744 | test AUC 0.5489 | test AP 0.1576
Epoch 003 | train loss 0.3780 | val AUC 0.6062 | val AP 0.2163 | test AUC 0.5836 | test AP 0.1587
Epoch 004 | train loss 0.3752 | val AUC 0.6501 | val AP 0.2282 | test AUC 0.6002 | test AP 0.1689
Epoch 005 | train loss 0.3728 | val AUC 0.6699 | val AP 0.2244 | test AUC 0.6051 | test AP 0.1671
Epoch 006 | train loss 0.3716 | val AUC 0.6744 | val AP 0.2202 | test AUC 0.6051 | test AP 0.1803
Epoch 007 | train loss 0.3716 | val AUC 0.6735 | val AP 0.2197 | test AUC 0.6038 | test AP 0.1832
Epoch 008 | train loss 0.3701 | val AUC 0.6745 | val AP 0.2213 | test AUC 0.6062 | test AP 0.1854
Epoch 009 | train loss 0.3700 | val AUC 0.6728 | val AP 0.2218 | test AUC 0.6066 | test AP 0.1899
Epoch 010 | train loss 0.3700 | val AUC 0.6691 | val AP 0.2193 | test AUC 0.6046 | test AP 0.1917
Epoch 011 | train loss 0.3692 | val AUC 0.6715 | val AP 0.2219 | test AUC 0.6071 | test AP 0.1927
Epoch 012 | train loss 0.3691 | val AUC 0.6727 | val AP 0.2235 | test AUC 0.6082 | test AP 0.1931
Epoch 013 | train loss 0.3694 | val AUC 0.6695 | val AP 0.2227 | test AUC 0.6076 | test AP 0.1962
Epoch 014 | train loss 0.3691 | val AUC 0.6690 | val AP 0.2222 | test AUC 0.6069 | test AP 0.1961
Epoch 015 | train loss 0.3682 | val AUC 0.6702 | val AP 0.2237 | test AUC 0.6090 | test AP 0.1975
Epoch 016 | train loss 0.3691 | val AUC 0.6664 | val AP 0.2223 | test AUC 0.6071 | test AP 0.1983
Epoch 017 | train loss 0.3678 | val AUC 0.6721 | val AP 0.2285 | test AUC 0.6123 | test AP 0.2004
Epoch 018 | train loss 0.3677 | val AUC 0.6682 | val AP 0.2252 | test AUC 0.6109 | test AP 0.1993
Epoch 019 | train loss 0.3683 | val AUC 0.6702 | val AP 0.2275 | test AUC 0.6128 | test AP 0.2014
Epoch 020 | train loss 0.3666 | val AUC 0.6726 | val AP 0.2327 | test AUC 0.6157 | test AP 0.2038
Epoch 021 | train loss 0.3672 | val AUC 0.6684 | val AP 0.2292 | test AUC 0.6141 | test AP 0.2035
Epoch 022 | train loss 0.3670 | val AUC 0.6738 | val AP 0.2370 | test AUC 0.6181 | test AP 0.2071
Epoch 023 | train loss 0.3663 | val AUC 0.6758 | val AP 0.2397 | test AUC 0.6193 | test AP 0.2079
Epoch 024 | train loss 0.3661 | val AUC 0.6718 | val AP 0.2367 | test AUC 0.6196 | test AP 0.2084
Epoch 025 | train loss 0.3655 | val AUC 0.6727 | val AP 0.2401 | test AUC 0.6206 | test AP 0.2091
Epoch 026 | train loss 0.3647 | val AUC 0.6722 | val AP 0.2381 | test AUC 0.6213 | test AP 0.2109
Epoch 027 | train loss 0.3657 | val AUC 0.6767 | val AP 0.2473 | test AUC 0.6244 | test AP 0.2122
Epoch 028 | train loss 0.3650 | val AUC 0.6755 | val AP 0.2477 | test AUC 0.6247 | test AP 0.2127
Epoch 029 | train loss 0.3642 | val AUC 0.6749 | val AP 0.2452 | test AUC 0.6254 | test AP 0.2137
Epoch 030 | train loss 0.3642 | val AUC 0.6770 | val AP 0.2488 | test AUC 0.6274 | test AP 0.2150
Epoch 031 | train loss 0.3648 | val AUC 0.6767 | val AP 0.2469 | test AUC 0.6278 | test AP 0.2164
Epoch 032 | train loss 0.3644 | val AUC 0.6748 | val AP 0.2452 | test AUC 0.6268 | test AP 0.2170
Epoch 033 | train loss 0.3642 | val AUC 0.6749 | val AP 0.2463 | test AUC 0.6275 | test AP 0.2194
Epoch 034 | train loss 0.3643 | val AUC 0.6786 | val AP 0.2513 | test AUC 0.6312 | test AP 0.2193
Epoch 035 | train loss 0.3649 | val AUC 0.6806 | val AP 0.2566 | test AUC 0.6330 | test AP 0.2205
Epoch 036 | train loss 0.3625 | val AUC 0.6832 | val AP 0.2590 | test AUC 0.6356 | test AP 0.2234
Epoch 037 | train loss 0.3636 | val AUC 0.6829 | val AP 0.2625 | test AUC 0.6355 | test AP 0.2224
Epoch 038 | train loss 0.3633 | val AUC 0.6814 | val AP 0.2573 | test AUC 0.6343 | test AP 0.2262
Epoch 039 | train loss 0.3606 | val AUC 0.6841 | val AP 0.2607 | test AUC 0.6380 | test AP 0.2285
Epoch 040 | train loss 0.3626 | val AUC 0.6838 | val AP 0.2586 | test AUC 0.6378 | test AP 0.2305
Epoch 041 | train loss 0.3608 | val AUC 0.6881 | val AP 0.2659 | test AUC 0.6427 | test AP 0.2315
Epoch 042 | train loss 0.3599 | val AUC 0.6888 | val AP 0.2674 | test AUC 0.6436 | test AP 0.2336
Epoch 043 | train loss 0.3589 | val AUC 0.6915 | val AP 0.2712 | test AUC 0.6462 | test AP 0.2353
Epoch 044 | train loss 0.3613 | val AUC 0.6918 | val AP 0.2704 | test AUC 0.6466 | test AP 0.2361
Epoch 045 | train loss 0.3579 | val AUC 0.6953 | val AP 0.2767 | test AUC 0.6506 | test AP 0.2387
Epoch 046 | train loss 0.3606 | val AUC 0.6948 | val AP 0.2762 | test AUC 0.6509 | test AP 0.2393
Epoch 047 | train loss 0.3581 | val AUC 0.6943 | val AP 0.2758 | test AUC 0.6497 | test AP 0.2387
Epoch 048 | train loss 0.3596 | val AUC 0.6998 | val AP 0.2820 | test AUC 0.6569 | test AP 0.2472
Epoch 049 | train loss 0.3572 | val AUC 0.6989 | val AP 0.2824 | test AUC 0.6552 | test AP 0.2451
Epoch 050 | train loss 0.3564 | val AUC 0.7043 | val AP 0.2881 | test AUC 0.6624 | test AP 0.2505
wandb: ⢿ updating run metadata (0.0s)
wandb: ⣻ updating run metadata (0.0s)
wandb: ⣽ updating run metadata (0.0s)
wandb: ⣾ updating run metadata (0.0s)
wandb: ⣷ updating run metadata (0.0s)
wandb: ⣯ uploading output.log 4.8KB/4.8KB (0.1s)
wandb: ⣯ uploading wandb-summary.json 364B/364B (0.1s)
wandb: ⣯ uploading config.yaml 3.5KB/3.5KB (0.1s)
wandb: ⣟ uploading output.log 4.8KB/4.8KB (0.1s)
wandb: ⣟ uploading wandb-summary.json 364B/364B (0.1s)
wandb: ⣟ uploading config.yaml 3.5KB/3.5KB (0.1s)
wandb: ⡿ uploading output.log 4.8KB/4.8KB (0.1s)
wandb: ⡿ uploading wandb-summary.json 364B/364B (0.1s)
wandb: ⡿ uploading config.yaml 3.5KB/3.5KB (0.1s)
wandb:
wandb: Run history:
wandb:      epoch ▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:    test/ap ▁▁▁▂▂▃▃▃▄▄▄▄▄▄▄▄▄▄▅▅▅▅▅▅▅▅▅▆▆▆▆▆▆▆▇▇▇▇██
wandb:   test/auc ▁▃▅▅▅▅▆▆▅▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▇▇▇▇▇▇▇▇▇▇▇▇█
wandb:  test/loss █▆▅▅▅▅▄▅▅▅▄▄▅▅▄▄▅▄▆▄▅▄▃▃▄▃▃▄▆▃▂▃▂▂▂▂▁▃▁▁
wandb: train/loss █▅▄▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▂▁▁▁
wandb:     val/ap ▁▃▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▆▆▆▆▆▆▆▆▆▆▇▇▇▇▇▇▇▇▇▇██
wandb:    val/auc ▁▃▅▆▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇██████
wandb:   val/loss █▇▆▅▅▄▄▄▄▄▃▃▃▄▃▃▄▃▃▃▃▃▂▃▂▃▂▃▄▂▂▂▂▁▁▁▁▂▁▁
wandb:
wandb: Run summary:
wandb:   best_epoch 50
wandb: best_val_auc 0.70435
wandb:        epoch 50
wandb:      test/ap 0.25053
wandb:     test/auc 0.66237
wandb:    test/loss 0.35887
wandb:   train/loss 0.35635
wandb:       val/ap 0.28809
wandb:      val/auc 0.70435
wandb:     val/loss 0.35343
wandb:
wandb: 🚀 View run mo_gcn_syn_Hospitalization_clean_ep50_layer2_hidden64_lr0.001_bs32 at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/bdtlnkhi
wandb: ⭐️ View project at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260709_105935-bdtlnkhi/logs
[2026-07-09 10:59:54,822][HYDRA] 	#1 : model=gcn data=dataset_syn training.epochs=50 data.target=Hospitalization model.num_layers=3
data:
  name: syn
  target: Hospitalization
  evaluator_type: synthethic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_edges.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_samples_nooverlap.csv
      multihospital: synthetic_pharmacotherapy_v2_samples_multihospital.csv
    scenario: clean
model:
  name: gcn
  hidden_dim: 64
  num_layers: 3
  dropout: 0.2
  batch_norm: true
  activation: relu
training:
  lr: 0.001
  epochs: 50
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
meta:
  owner_initials: mo
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis
  run_name: ${meta.owner_initials}_${model.name}_${data.name}_${data.target}_${data.dataset.scenario}_ep${training.epochs}_layer${model.num_layers}_hidden${model.hidden_dim}_lr${training.lr}_bs${training.batch_size}

wandb: ⢿ setting up run zt1026ll (0.0s)
wandb: ⣻ setting up run zt1026ll (0.0s)
wandb: ⣽ setting up run zt1026ll (0.0s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260709_105954-zt1026ll
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run mo_gcn_syn_Hospitalization_clean_ep50_layer3_hidden64_lr0.001_bs32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/zt1026ll
Epoch 001 | train loss 0.3955 | val AUC 0.5143 | val AP 0.1530 | test AUC 0.5337 | test AP 0.1632
Epoch 002 | train loss 0.3789 | val AUC 0.6116 | val AP 0.2083 | test AUC 0.5839 | test AP 0.1571
Epoch 003 | train loss 0.3741 | val AUC 0.6626 | val AP 0.2126 | test AUC 0.5978 | test AP 0.1624
Epoch 004 | train loss 0.3727 | val AUC 0.6708 | val AP 0.2143 | test AUC 0.6005 | test AP 0.1685
Epoch 005 | train loss 0.3734 | val AUC 0.6719 | val AP 0.2144 | test AUC 0.6005 | test AP 0.1750
Epoch 006 | train loss 0.3712 | val AUC 0.6716 | val AP 0.2129 | test AUC 0.6021 | test AP 0.1789
Epoch 007 | train loss 0.3711 | val AUC 0.6723 | val AP 0.2143 | test AUC 0.6051 | test AP 0.1798
Epoch 008 | train loss 0.3723 | val AUC 0.6729 | val AP 0.2164 | test AUC 0.6060 | test AP 0.1822
Epoch 009 | train loss 0.3709 | val AUC 0.6735 | val AP 0.2178 | test AUC 0.6076 | test AP 0.1826
Epoch 010 | train loss 0.3702 | val AUC 0.6734 | val AP 0.2197 | test AUC 0.6104 | test AP 0.1872
Epoch 011 | train loss 0.3691 | val AUC 0.6746 | val AP 0.2220 | test AUC 0.6121 | test AP 0.1893
Epoch 012 | train loss 0.3699 | val AUC 0.6763 | val AP 0.2259 | test AUC 0.6167 | test AP 0.1937
Epoch 013 | train loss 0.3699 | val AUC 0.6758 | val AP 0.2267 | test AUC 0.6187 | test AP 0.1974
Epoch 014 | train loss 0.3679 | val AUC 0.6736 | val AP 0.2277 | test AUC 0.6200 | test AP 0.2009
Epoch 015 | train loss 0.3682 | val AUC 0.6751 | val AP 0.2315 | test AUC 0.6226 | test AP 0.2027
Epoch 016 | train loss 0.3681 | val AUC 0.6751 | val AP 0.2347 | test AUC 0.6244 | test AP 0.2020
Epoch 017 | train loss 0.3665 | val AUC 0.6761 | val AP 0.2386 | test AUC 0.6260 | test AP 0.2043
Epoch 018 | train loss 0.3668 | val AUC 0.6804 | val AP 0.2429 | test AUC 0.6290 | test AP 0.2060
Epoch 019 | train loss 0.3671 | val AUC 0.6737 | val AP 0.2406 | test AUC 0.6290 | test AP 0.2089
Epoch 020 | train loss 0.3670 | val AUC 0.6811 | val AP 0.2470 | test AUC 0.6323 | test AP 0.2101
Epoch 021 | train loss 0.3640 | val AUC 0.6805 | val AP 0.2471 | test AUC 0.6338 | test AP 0.2122
Epoch 022 | train loss 0.3646 | val AUC 0.6831 | val AP 0.2540 | test AUC 0.6371 | test AP 0.2119
Epoch 023 | train loss 0.3667 | val AUC 0.6838 | val AP 0.2545 | test AUC 0.6394 | test AP 0.2154
Epoch 024 | train loss 0.3638 | val AUC 0.6840 | val AP 0.2567 | test AUC 0.6413 | test AP 0.2194
Epoch 025 | train loss 0.3646 | val AUC 0.6875 | val AP 0.2603 | test AUC 0.6436 | test AP 0.2214
Epoch 026 | train loss 0.3619 | val AUC 0.6898 | val AP 0.2655 | test AUC 0.6471 | test AP 0.2235
Epoch 027 | train loss 0.3618 | val AUC 0.6934 | val AP 0.2706 | test AUC 0.6526 | test AP 0.2272
Epoch 028 | train loss 0.3635 | val AUC 0.6915 | val AP 0.2667 | test AUC 0.6504 | test AP 0.2261
Epoch 029 | train loss 0.3597 | val AUC 0.6941 | val AP 0.2708 | test AUC 0.6562 | test AP 0.2296
Epoch 030 | train loss 0.3597 | val AUC 0.7025 | val AP 0.2807 | test AUC 0.6669 | test AP 0.2348
Epoch 031 | train loss 0.3606 | val AUC 0.7044 | val AP 0.2943 | test AUC 0.6689 | test AP 0.2382
Epoch 032 | train loss 0.3624 | val AUC 0.7040 | val AP 0.3036 | test AUC 0.6682 | test AP 0.2396
Epoch 033 | train loss 0.3575 | val AUC 0.7096 | val AP 0.3081 | test AUC 0.6771 | test AP 0.2437
Epoch 034 | train loss 0.3620 | val AUC 0.7100 | val AP 0.3034 | test AUC 0.6784 | test AP 0.2432
Epoch 035 | train loss 0.3584 | val AUC 0.7083 | val AP 0.3032 | test AUC 0.6737 | test AP 0.2430
Epoch 036 | train loss 0.3562 | val AUC 0.7138 | val AP 0.3094 | test AUC 0.6811 | test AP 0.2458
Epoch 037 | train loss 0.3544 | val AUC 0.7185 | val AP 0.3125 | test AUC 0.6890 | test AP 0.2502
Epoch 038 | train loss 0.3546 | val AUC 0.7241 | val AP 0.3275 | test AUC 0.6935 | test AP 0.2578
Epoch 039 | train loss 0.3510 | val AUC 0.7392 | val AP 0.3485 | test AUC 0.7147 | test AP 0.2743
Epoch 040 | train loss 0.3525 | val AUC 0.7400 | val AP 0.3437 | test AUC 0.7175 | test AP 0.2709
Epoch 041 | train loss 0.3483 | val AUC 0.7414 | val AP 0.3421 | test AUC 0.7148 | test AP 0.2727
Epoch 042 | train loss 0.3465 | val AUC 0.7487 | val AP 0.3508 | test AUC 0.7240 | test AP 0.2786
Epoch 043 | train loss 0.3441 | val AUC 0.7563 | val AP 0.3581 | test AUC 0.7330 | test AP 0.2844
Epoch 044 | train loss 0.3433 | val AUC 0.7692 | val AP 0.3786 | test AUC 0.7502 | test AP 0.2981
Epoch 045 | train loss 0.3395 | val AUC 0.7781 | val AP 0.3883 | test AUC 0.7588 | test AP 0.3080
Epoch 046 | train loss 0.3392 | val AUC 0.7816 | val AP 0.3972 | test AUC 0.7624 | test AP 0.3124
Epoch 047 | train loss 0.3406 | val AUC 0.7867 | val AP 0.4274 | test AUC 0.7655 | test AP 0.3206
Epoch 048 | train loss 0.3357 | val AUC 0.8022 | val AP 0.4354 | test AUC 0.7938 | test AP 0.3422
Epoch 049 | train loss 0.3304 | val AUC 0.8067 | val AP 0.4438 | test AUC 0.7925 | test AP 0.3417
Epoch 050 | train loss 0.3267 | val AUC 0.8214 | val AP 0.4450 | test AUC 0.8134 | test AP 0.3587
wandb: ⢿ updating run metadata (0.0s)
wandb: ⣻ updating run metadata (0.0s)
wandb: ⣽ updating run metadata (0.0s)
wandb: ⣾ updating run metadata (0.0s)
wandb: ⣷ Finishing up...
wandb: ⣯ Finishing up...
wandb: ⣟ Finishing up...
wandb: ⡿ Finishing up...
wandb: ⢿ Finishing up...
wandb: ⣻ uploading history steps 37-49, summary, console lines 38-49 (0.3s)
wandb: ⣽ uploading history steps 37-49, summary, console lines 38-49 (0.3s)
wandb: ⣾ uploading history steps 37-49, summary, console lines 38-49 (0.3s)
wandb: ⣷ uploading history steps 37-49, summary, console lines 38-49 (0.3s)
wandb: ⣯ uploading history steps 37-49, summary, console lines 38-49 (0.3s)
wandb:
wandb: Run history:
wandb:      epoch ▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:    test/ap ▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▃▃▃▃▃▃▃▄▄▄▄▄▄▄▄▅▅▅▅▅▆▆▇▇█
wandb:   test/auc ▁▂▃▃▃▃▃▃▃▃▃▃▃▃▃▄▄▄▄▄▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇██
wandb:  test/loss ███▇███▇█▇▇▇▇▇█▇▇▇▇▇▇▇▇▇▇▇▆▆▆▆▆▅▅▅▄▄▅▄▂▁
wandb: train/loss █▆▆▆▆▆▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▄▄▄▄▅▄▄▄▃▄▃▃▃▂▂▂▂▁
wandb:     val/ap ▁▂▂▂▂▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇███
wandb:    val/auc ▁▃▄▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇██
wandb:   val/loss █▇▇▇▆▇▇▆▆▆▆▆▆▆▇▆▆▆▆▆▅▆▅▆▅▅▅▅▅▅▄▄▄▄▄▃▄▃▂▁
wandb:
wandb: Run summary:
wandb:   best_epoch 50
wandb: best_val_auc 0.82144
wandb:        epoch 50
wandb:      test/ap 0.35866
wandb:     test/auc 0.81336
wandb:    test/loss 0.32065
wandb:   train/loss 0.32674
wandb:       val/ap 0.44498
wandb:      val/auc 0.82144
wandb:     val/loss 0.3157
wandb:
wandb: 🚀 View run mo_gcn_syn_Hospitalization_clean_ep50_layer3_hidden64_lr0.001_bs32 at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/zt1026ll
wandb: ⭐️ View project at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260709_105954-zt1026ll/logs
[2026-07-09 11:00:17,727][HYDRA] 	#2 : model=gcn data=dataset_syn training.epochs=50 data.target=Hospitalization model.num_layers=4
data:
  name: syn
  target: Hospitalization
  evaluator_type: synthethic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_edges.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_samples_nooverlap.csv
      multihospital: synthetic_pharmacotherapy_v2_samples_multihospital.csv
    scenario: clean
model:
  name: gcn
  hidden_dim: 64
  num_layers: 4
  dropout: 0.2
  batch_norm: true
  activation: relu
training:
  lr: 0.001
  epochs: 50
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
meta:
  owner_initials: mo
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis
  run_name: ${meta.owner_initials}_${model.name}_${data.name}_${data.target}_${data.dataset.scenario}_ep${training.epochs}_layer${model.num_layers}_hidden${model.hidden_dim}_lr${training.lr}_bs${training.batch_size}

wandb: ⢿ setting up run m00r2515 (0.0s)
wandb: ⣻ setting up run m00r2515 (0.0s)
wandb: ⣽ setting up run m00r2515 (0.0s)
wandb: ⣾ setting up run m00r2515 (0.0s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260709_110017-m00r2515
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run mo_gcn_syn_Hospitalization_clean_ep50_layer4_hidden64_lr0.001_bs32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/m00r2515
Epoch 001 | train loss 0.4096 | val AUC 0.5091 | val AP 0.1515 | test AUC 0.5307 | test AP 0.1641
Epoch 002 | train loss 0.3802 | val AUC 0.6041 | val AP 0.2066 | test AUC 0.5801 | test AP 0.1558
Epoch 003 | train loss 0.3770 | val AUC 0.6469 | val AP 0.2084 | test AUC 0.5907 | test AP 0.1590
Epoch 004 | train loss 0.3748 | val AUC 0.6654 | val AP 0.2087 | test AUC 0.5979 | test AP 0.1633
Epoch 005 | train loss 0.3752 | val AUC 0.6674 | val AP 0.2096 | test AUC 0.5972 | test AP 0.1648
Epoch 006 | train loss 0.3728 | val AUC 0.6720 | val AP 0.2120 | test AUC 0.5991 | test AP 0.1717
Epoch 007 | train loss 0.3718 | val AUC 0.6713 | val AP 0.2118 | test AUC 0.5997 | test AP 0.1740
Epoch 008 | train loss 0.3716 | val AUC 0.6716 | val AP 0.2130 | test AUC 0.6016 | test AP 0.1754

In [ ]:
#multirun gin
!python src/train.py --multirun model=gin data=dataset_syn training.epochs=50 data.target="Hospitalization" model.num_layers=2,3,4,6

[2026-07-09 13:09:45,748][HYDRA] Launching 4 jobs locally
[2026-07-09 13:09:45,748][HYDRA] 	#0 : model=gin data=dataset_syn training.epochs=50 data.target=Hospitalization model.num_layers=2
data:
  name: syn
  target: Hospitalization
  evaluator_type: synthetic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_edges.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_samples_nooverlap.csv
      multihospital: synthetic_pharmacotherapy_v2_samples_multihospital.csv
    scenario: clean
model:
  name: gin
  hidden_dim: 64
  num_layers: 2
  dropout: 0.2
  batch_norm: true
  activation: relu
training:
  lr: 0.001
  epochs: 50
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
  heads: 4
  dropout: 0.0
  pooling: mean
  batch_norm: true
meta:
  owner_initials: mo
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis
  run_name: ${meta.owner_initials}_${model.name}_${data.name}_${data.target}_${data.dataset.scenario}_ep${training.epochs}_layer${model.num_layers}_hidden${model.hidden_dim}_lr${training.lr}_bs${training.batch_size}

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: oskardmonika (politechnika-gnn-thesis) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: ⢿ setting up run gls11sow (0.0s)
wandb: ⣻ setting up run gls11sow (0.0s)
wandb: ⣽ setting up run gls11sow (0.0s)
wandb: ⣾ setting up run gls11sow (0.0s)
wandb: ⣷ setting up run gls11sow (0.5s)
wandb: ⣯ setting up run gls11sow (0.5s)
wandb: ⣟ setting up run gls11sow (0.5s)
wandb: ⡿ setting up run gls11sow (0.5s)
wandb: ⢿ setting up run gls11sow (0.5s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260709_130946-gls11sow
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run mo_gin_syn_Hospitalization_clean_ep50_layer2_hidden64_lr0.001_bs32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/gls11sow
Epoch 001 | train loss 0.3931 | train AUC 0.5244 | train AUPRC 0.1344 | val AUC 0.5599 | val AUPRC 0.1742 | test AUC 0.5405 | test AUPRC 0.1526
Epoch 002 | train loss 0.3798 | train AUC 0.5716 | train AUPRC 0.1499 | val AUC 0.6207 | val AUPRC 0.2373 | test AUC 0.5752 | test AUPRC 0.1608
Epoch 003 | train loss 0.3764 | train AUC 0.5898 | train AUPRC 0.1612 | val AUC 0.6460 | val AUPRC 0.2265 | test AUC 0.5855 | test AUPRC 0.1631
Epoch 004 | train loss 0.3745 | train AUC 0.6021 | train AUPRC 0.1702 | val AUC 0.6512 | val AUPRC 0.2159 | test AUC 0.5986 | test AUPRC 0.1579
Epoch 005 | train loss 0.3756 | train AUC 0.6098 | train AUPRC 0.1756 | val AUC 0.6588 | val AUPRC 0.2150 | test AUC 0.6026 | test AUPRC 0.1624
Epoch 006 | train loss 0.3753 | train AUC 0.6130 | train AUPRC 0.1781 | val AUC 0.6611 | val AUPRC 0.2090 | test AUC 0.6027 | test AUPRC 0.1643
Epoch 007 | train loss 0.3718 | train AUC 0.6170 | train AUPRC 0.1810 | val AUC 0.6573 | val AUPRC 0.2055 | test AUC 0.6063 | test AUPRC 0.1687
Epoch 008 | train loss 0.3726 | train AUC 0.6200 | train AUPRC 0.1832 | val AUC 0.6592 | val AUPRC 0.2060 | test AUC 0.6073 | test AUPRC 0.1719
Epoch 009 | train loss 0.3722 | train AUC 0.6269 | train AUPRC 0.1889 | val AUC 0.6650 | val AUPRC 0.2115 | test AUC 0.6128 | test AUPRC 0.1758
Epoch 010 | train loss 0.3722 | train AUC 0.6302 | train AUPRC 0.1916 | val AUC 0.6656 | val AUPRC 0.2130 | test AUC 0.6141 | test AUPRC 0.1786
Epoch 011 | train loss 0.3707 | train AUC 0.6375 | train AUPRC 0.1985 | val AUC 0.6688 | val AUPRC 0.2180 | test AUC 0.6203 | test AUPRC 0.1836
Epoch 012 | train loss 0.3691 | train AUC 0.6414 | train AUPRC 0.2025 | val AUC 0.6719 | val AUPRC 0.2238 | test AUC 0.6216 | test AUPRC 0.1846
Epoch 013 | train loss 0.3651 | train AUC 0.6558 | train AUPRC 0.2201 | val AUC 0.6832 | val AUPRC 0.2441 | test AUC 0.6345 | test AUPRC 0.1948
Epoch 014 | train loss 0.3632 | train AUC 0.6696 | train AUPRC 0.2354 | val AUC 0.6939 | val AUPRC 0.2663 | test AUC 0.6494 | test AUPRC 0.2076
Epoch 015 | train loss 0.3604 | train AUC 0.6826 | train AUPRC 0.2467 | val AUC 0.7052 | val AUPRC 0.2728 | test AUC 0.6639 | test AUPRC 0.2172
Epoch 016 | train loss 0.3573 | train AUC 0.6993 | train AUPRC 0.2573 | val AUC 0.7192 | val AUPRC 0.2784 | test AUC 0.6824 | test AUPRC 0.2303
Epoch 017 | train loss 0.3509 | train AUC 0.7214 | train AUPRC 0.2753 | val AUC 0.7372 | val AUPRC 0.2887 | test AUC 0.7103 | test AUPRC 0.2500
Epoch 018 | train loss 0.3490 | train AUC 0.7229 | train AUPRC 0.2999 | val AUC 0.7384 | val AUPRC 0.3195 | test AUC 0.7102 | test AUPRC 0.2509
Epoch 019 | train loss 0.3454 | train AUC 0.7410 | train AUPRC 0.3420 | val AUC 0.7536 | val AUPRC 0.3450 | test AUC 0.7281 | test AUPRC 0.2632
Epoch 020 | train loss 0.3425 | train AUC 0.7602 | train AUPRC 0.3480 | val AUC 0.7698 | val AUPRC 0.3417 | test AUC 0.7473 | test AUPRC 0.2761
Epoch 021 | train loss 0.3339 | train AUC 0.7720 | train AUPRC 0.3904 | val AUC 0.7832 | val AUPRC 0.3794 | test AUC 0.7619 | test AUPRC 0.2856
Epoch 022 | train loss 0.3272 | train AUC 0.7848 | train AUPRC 0.3909 | val AUC 0.7930 | val AUPRC 0.3730 | test AUC 0.7738 | test AUPRC 0.2966
Epoch 023 | train loss 0.3258 | train AUC 0.7921 | train AUPRC 0.4190 | val AUC 0.8017 | val AUPRC 0.3975 | test AUC 0.7781 | test AUPRC 0.3180
Epoch 024 | train loss 0.3195 | train AUC 0.8025 | train AUPRC 0.4227 | val AUC 0.8111 | val AUPRC 0.3971 | test AUC 0.7895 | test AUPRC 0.3296
Epoch 025 | train loss 0.3145 | train AUC 0.8123 | train AUPRC 0.4426 | val AUC 0.8209 | val AUPRC 0.4129 | test AUC 0.8008 | test AUPRC 0.3456
Epoch 026 | train loss 0.3078 | train AUC 0.8230 | train AUPRC 0.4646 | val AUC 0.8323 | val AUPRC 0.4400 | test AUC 0.8133 | test AUPRC 0.3516
Epoch 027 | train loss 0.3003 | train AUC 0.8245 | train AUPRC 0.4649 | val AUC 0.8385 | val AUPRC 0.4486 | test AUC 0.8106 | test AUPRC 0.3473
Epoch 028 | train loss 0.2993 | train AUC 0.8483 | train AUPRC 0.4976 | val AUC 0.8566 | val AUPRC 0.4712 | test AUC 0.8408 | test AUPRC 0.3875
Epoch 029 | train loss 0.2860 | train AUC 0.8540 | train AUPRC 0.5023 | val AUC 0.8644 | val AUPRC 0.4935 | test AUC 0.8465 | test AUPRC 0.4005
Epoch 030 | train loss 0.2827 | train AUC 0.8673 | train AUPRC 0.5244 | val AUC 0.8763 | val AUPRC 0.5213 | test AUC 0.8640 | test AUPRC 0.4322
Epoch 031 | train loss 0.2751 | train AUC 0.8801 | train AUPRC 0.5516 | val AUC 0.8879 | val AUPRC 0.5284 | test AUC 0.8777 | test AUPRC 0.4575
Epoch 032 | train loss 0.2673 | train AUC 0.8893 | train AUPRC 0.5605 | val AUC 0.8971 | val AUPRC 0.5680 | test AUC 0.8845 | test AUPRC 0.4813
Epoch 033 | train loss 0.2570 | train AUC 0.9023 | train AUPRC 0.5875 | val AUC 0.9107 | val AUPRC 0.5962 | test AUC 0.8986 | test AUPRC 0.5127
Epoch 034 | train loss 0.2447 | train AUC 0.9092 | train AUPRC 0.6153 | val AUC 0.9205 | val AUPRC 0.6295 | test AUC 0.9089 | test AUPRC 0.5420
Epoch 035 | train loss 0.2410 | train AUC 0.9206 | train AUPRC 0.6615 | val AUC 0.9323 | val AUPRC 0.6802 | test AUC 0.9252 | test AUPRC 0.6044
Epoch 036 | train loss 0.2329 | train AUC 0.9260 | train AUPRC 0.6723 | val AUC 0.9369 | val AUPRC 0.6947 | test AUC 0.9289 | test AUPRC 0.6175
Epoch 037 | train loss 0.2206 | train AUC 0.9321 | train AUPRC 0.6863 | val AUC 0.9423 | val AUPRC 0.7000 | test AUC 0.9335 | test AUPRC 0.6356
Epoch 038 | train loss 0.2170 | train AUC 0.9351 | train AUPRC 0.6988 | val AUC 0.9465 | val AUPRC 0.7105 | test AUC 0.9345 | test AUPRC 0.6385
Epoch 039 | train loss 0.2085 | train AUC 0.9358 | train AUPRC 0.6962 | val AUC 0.9486 | val AUPRC 0.7312 | test AUC 0.9380 | test AUPRC 0.6577
Epoch 040 | train loss 0.2036 | train AUC 0.9409 | train AUPRC 0.7308 | val AUC 0.9539 | val AUPRC 0.7465 | test AUC 0.9417 | test AUPRC 0.6757
Epoch 041 | train loss 0.1979 | train AUC 0.9423 | train AUPRC 0.7363 | val AUC 0.9564 | val AUPRC 0.7622 | test AUC 0.9449 | test AUPRC 0.6936
Epoch 042 | train loss 0.1918 | train AUC 0.9469 | train AUPRC 0.7557 | val AUC 0.9591 | val AUPRC 0.7599 | test AUC 0.9453 | test AUPRC 0.6919
Epoch 043 | train loss 0.1904 | train AUC 0.9506 | train AUPRC 0.7628 | val AUC 0.9615 | val AUPRC 0.7636 | test AUC 0.9489 | test AUPRC 0.7049
Epoch 044 | train loss 0.1874 | train AUC 0.9484 | train AUPRC 0.7856 | val AUC 0.9638 | val AUPRC 0.8056 | test AUC 0.9486 | test AUPRC 0.7107
Epoch 045 | train loss 0.1791 | train AUC 0.9545 | train AUPRC 0.7826 | val AUC 0.9656 | val AUPRC 0.8007 | test AUC 0.9554 | test AUPRC 0.7281
Epoch 046 | train loss 0.1809 | train AUC 0.9542 | train AUPRC 0.7948 | val AUC 0.9682 | val AUPRC 0.8335 | test AUC 0.9593 | test AUPRC 0.7522
Epoch 047 | train loss 0.1730 | train AUC 0.9556 | train AUPRC 0.8182 | val AUC 0.9706 | val AUPRC 0.8449 | test AUC 0.9591 | test AUPRC 0.7555
Epoch 048 | train loss 0.1658 | train AUC 0.9591 | train AUPRC 0.8242 | val AUC 0.9713 | val AUPRC 0.8426 | test AUC 0.9629 | test AUPRC 0.7663
Epoch 049 | train loss 0.1689 | train AUC 0.9628 | train AUPRC 0.8107 | val AUC 0.9712 | val AUPRC 0.8176 | test AUC 0.9650 | test AUPRC 0.7755
Epoch 050 | train loss 0.1604 | train AUC 0.9634 | train AUPRC 0.8125 | val AUC 0.9725 | val AUPRC 0.8317 | test AUC 0.9633 | test AUPRC 0.7610
wandb: ⢿ updating run metadata (0.0s)
wandb: ⣻ updating run metadata (0.0s)
wandb: ⣽ updating run metadata (0.0s)
wandb: ⣾ updating run metadata (0.0s)
wandb: ⣷ Finishing up...
wandb: ⣯ Finishing up...
wandb: ⣟ Finishing up...
wandb: ⡿ Finishing up...
wandb: ⢿ Finishing up...
wandb: ⣻ uploading history steps 34-49, summary, console lines 35-49 (0.2s)
wandb: ⣽ uploading history steps 34-49, summary, console lines 35-49 (0.2s)
wandb: ⣾ uploading history steps 34-49, summary, console lines 35-49 (0.2s)
wandb:
wandb: Run history:
wandb:       epoch ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:    test/auc ▁▂▂▂▂▂▂▂▂▂▃▃▃▃▄▄▄▅▅▅▅▆▅▆▆▇▇▇▇███████████
wandb:  test/auprc ▁▁▁▁▁▁▁▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▅▅▅▆▆▇▇▇▇▇█████
wandb:  test/brier ██████████▇▇▇▇▇▇▇▇▇▇█▆▆▅▅▄▄▅▃▃▂▂▂▂▂▂▂▁▁▁
wandb:   test/loss ████████▇▇▇▇▇▇▇▇▇▆▆▆▆▇▅▅▅▄▄▄▃▂▂▂▂▂▂▁▁▁▁▁
wandb:   train/auc ▁▂▂▂▂▃▃▃▃▃▃▄▄▄▄▅▅▅▅▆▆▆▆▆▇▇▇▇▇███████████
wandb: train/auprc ▁▁▁▁▁▁▁▂▂▂▂▂▂▂▂▃▃▄▄▄▄▄▄▅▅▅▅▆▆▆▇▇▇▇▇█████
wandb: train/brier ██████████▇▇▇▇▇▇▆▆▆▆▇▅▅▅▅▄▄▅▄▃▃▂▂▂▂▂▂▁▁▁
wandb:  train/loss ██▇▇▇▇▇▇▇▇▇▇▇▇▇▇▆▆▆▆▅▅▅▅▅▄▄▃▃▃▂▂▂▂▂▂▂▁▁▁
wandb:     val/auc ▁▂▂▃▃▃▃▃▃▃▃▃▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇██████████
wandb:          +3 ...
wandb:
wandb: Run summary:
wandb:     best_epoch 47
wandb:   best_val_auc -1
wandb: best_val_auprc 0.84492
wandb:          epoch 50
wandb:       test/auc 0.9633
wandb:     test/auprc 0.76096
wandb:     test/brier 0.05034
wandb:      test/loss 0.17628
wandb:      train/auc 0.96341
wandb:    train/auprc 0.81245
wandb:             +6 ...
wandb:
wandb: 🚀 View run mo_gin_syn_Hospitalization_clean_ep50_layer2_hidden64_lr0.001_bs32 at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/gls11sow
wandb: ⭐️ View project at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260709_130946-gls11sow/logs
[2026-07-09 13:10:11,704][HYDRA] 	#1 : model=gin data=dataset_syn training.epochs=50 data.target=Hospitalization model.num_layers=3
data:
  name: syn
  target: Hospitalization
  evaluator_type: synthetic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_edges.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_samples_nooverlap.csv
      multihospital: synthetic_pharmacotherapy_v2_samples_multihospital.csv
    scenario: clean
model:
  name: gin
  hidden_dim: 64
  num_layers: 3
  dropout: 0.2
  batch_norm: true
  activation: relu
training:
  lr: 0.001
  epochs: 50
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
  heads: 4
  dropout: 0.0
  pooling: mean
  batch_norm: true
meta:
  owner_initials: mo
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis
  run_name: ${meta.owner_initials}_${model.name}_${data.name}_${data.target}_${data.dataset.scenario}_ep${training.epochs}_layer${model.num_layers}_hidden${model.hidden_dim}_lr${training.lr}_bs${training.batch_size}

wandb: ⢿ setting up run zai6zkdg (0.0s)
wandb: ⣻ setting up run zai6zkdg (0.0s)
wandb: ⣽ setting up run zai6zkdg (0.0s)
wandb: ⣾ setting up run zai6zkdg (0.0s)
wandb: ⣷ setting up run zai6zkdg (0.5s)
wandb: ⣯ setting up run zai6zkdg (0.5s)
wandb: ⣟ setting up run zai6zkdg (0.5s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260709_131012-zai6zkdg
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run mo_gin_syn_Hospitalization_clean_ep50_layer3_hidden64_lr0.001_bs32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/zai6zkdg
Epoch 001 | train loss 0.4006 | train AUC 0.5087 | train AUPRC 0.1317 | val AUC 0.5371 | val AUPRC 0.1612 | test AUC 0.5319 | test AUPRC 0.1550
Epoch 002 | train loss 0.3811 | train AUC 0.5665 | train AUPRC 0.1483 | val AUC 0.6095 | val AUPRC 0.2175 | test AUC 0.5774 | test AUPRC 0.1725
Epoch 003 | train loss 0.3777 | train AUC 0.5824 | train AUPRC 0.1571 | val AUC 0.6352 | val AUPRC 0.2015 | test AUC 0.5845 | test AUPRC 0.1636
Epoch 004 | train loss 0.3788 | train AUC 0.5876 | train AUPRC 0.1607 | val AUC 0.6390 | val AUPRC 0.1964 | test AUC 0.5875 | test AUPRC 0.1645
Epoch 005 | train loss 0.3748 | train AUC 0.5962 | train AUPRC 0.1660 | val AUC 0.6472 | val AUPRC 0.1923 | test AUC 0.5904 | test AUPRC 0.1683
Epoch 006 | train loss 0.3746 | train AUC 0.5971 | train AUPRC 0.1671 | val AUC 0.6441 | val AUPRC 0.1921 | test AUC 0.5922 | test AUPRC 0.1700
Epoch 007 | train loss 0.3762 | train AUC 0.5984 | train AUPRC 0.1681 | val AUC 0.6458 | val AUPRC 0.1938 | test AUC 0.5918 | test AUPRC 0.1707
Epoch 008 | train loss 0.3754 | train AUC 0.6002 | train AUPRC 0.1699 | val AUC 0.6472 | val AUPRC 0.1954 | test AUC 0.5919 | test AUPRC 0.1716
Epoch 009 | train loss 0.3752 | train AUC 0.6016 | train AUPRC 0.1715 | val AUC 0.6487 | val AUPRC 0.1961 | test AUC 0.5934 | test AUPRC 0.1755
Epoch 010 | train loss 0.3747 | train AUC 0.6025 | train AUPRC 0.1723 | val AUC 0.6480 | val AUPRC 0.1944 | test AUC 0.5932 | test AUPRC 0.1760
Epoch 011 | train loss 0.3753 | train AUC 0.6038 | train AUPRC 0.1733 | val AUC 0.6471 | val AUPRC 0.1922 | test AUC 0.5924 | test AUPRC 0.1763
Epoch 012 | train loss 0.3743 | train AUC 0.6038 | train AUPRC 0.1734 | val AUC 0.6472 | val AUPRC 0.1940 | test AUC 0.5929 | test AUPRC 0.1763
Epoch 013 | train loss 0.3727 | train AUC 0.6047 | train AUPRC 0.1743 | val AUC 0.6465 | val AUPRC 0.1957 | test AUC 0.5951 | test AUPRC 0.1763
Epoch 014 | train loss 0.3736 | train AUC 0.6059 | train AUPRC 0.1763 | val AUC 0.6466 | val AUPRC 0.1931 | test AUC 0.5931 | test AUPRC 0.1765
Epoch 015 | train loss 0.3730 | train AUC 0.6054 | train AUPRC 0.1762 | val AUC 0.6436 | val AUPRC 0.1922 | test AUC 0.5934 | test AUPRC 0.1765
Epoch 016 | train loss 0.3728 | train AUC 0.6067 | train AUPRC 0.1778 | val AUC 0.6445 | val AUPRC 0.1934 | test AUC 0.5947 | test AUPRC 0.1685
Epoch 017 | train loss 0.3735 | train AUC 0.6072 | train AUPRC 0.1781 | val AUC 0.6455 | val AUPRC 0.1950 | test AUC 0.5948 | test AUPRC 0.1676
Epoch 018 | train loss 0.3727 | train AUC 0.6090 | train AUPRC 0.1781 | val AUC 0.6479 | val AUPRC 0.1972 | test AUC 0.5964 | test AUPRC 0.1674
Epoch 019 | train loss 0.3724 | train AUC 0.6110 | train AUPRC 0.1797 | val AUC 0.6501 | val AUPRC 0.1986 | test AUC 0.5982 | test AUPRC 0.1696
Epoch 020 | train loss 0.3731 | train AUC 0.6114 | train AUPRC 0.1802 | val AUC 0.6494 | val AUPRC 0.1990 | test AUC 0.5984 | test AUPRC 0.1694
Epoch 021 | train loss 0.3732 | train AUC 0.6135 | train AUPRC 0.1819 | val AUC 0.6497 | val AUPRC 0.2009 | test AUC 0.6010 | test AUPRC 0.1700
Epoch 022 | train loss 0.3730 | train AUC 0.6146 | train AUPRC 0.1824 | val AUC 0.6486 | val AUPRC 0.1987 | test AUC 0.6010 | test AUPRC 0.1704
Epoch 023 | train loss 0.3723 | train AUC 0.6163 | train AUPRC 0.1839 | val AUC 0.6496 | val AUPRC 0.2004 | test AUC 0.6030 | test AUPRC 0.1717
Epoch 024 | train loss 0.3716 | train AUC 0.6160 | train AUPRC 0.1842 | val AUC 0.6505 | val AUPRC 0.2030 | test AUC 0.6032 | test AUPRC 0.1712
Epoch 025 | train loss 0.3715 | train AUC 0.6186 | train AUPRC 0.1859 | val AUC 0.6518 | val AUPRC 0.2014 | test AUC 0.6053 | test AUPRC 0.1732
Epoch 026 | train loss 0.3716 | train AUC 0.6212 | train AUPRC 0.1879 | val AUC 0.6541 | val AUPRC 0.2034 | test AUC 0.6083 | test AUPRC 0.1752
Epoch 027 | train loss 0.3717 | train AUC 0.6229 | train AUPRC 0.1895 | val AUC 0.6543 | val AUPRC 0.2044 | test AUC 0.6099 | test AUPRC 0.1758
Epoch 028 | train loss 0.3703 | train AUC 0.6251 | train AUPRC 0.1925 | val AUC 0.6568 | val AUPRC 0.2080 | test AUC 0.6124 | test AUPRC 0.1766
Epoch 029 | train loss 0.3694 | train AUC 0.6453 | train AUPRC 0.2107 | val AUC 0.6732 | val AUPRC 0.2277 | test AUC 0.6379 | test AUPRC 0.1992
Epoch 030 | train loss 0.3640 | train AUC 0.7002 | train AUPRC 0.2692 | val AUC 0.7207 | val AUPRC 0.3164 | test AUC 0.7081 | test AUPRC 0.2664
Epoch 031 | train loss 0.3543 | train AUC 0.7829 | train AUPRC 0.3864 | val AUC 0.7893 | val AUPRC 0.4363 | test AUC 0.7874 | test AUPRC 0.3974
Epoch 032 | train loss 0.2835 | train AUC 0.9408 | train AUPRC 0.7238 | val AUC 0.9435 | val AUPRC 0.7625 | test AUC 0.9554 | test AUPRC 0.8095
Epoch 033 | train loss 0.1908 | train AUC 0.9736 | train AUPRC 0.8591 | val AUC 0.9825 | val AUPRC 0.9014 | test AUC 0.9772 | test AUPRC 0.9154
Epoch 034 | train loss 0.1536 | train AUC 0.9826 | train AUPRC 0.9054 | val AUC 0.9902 | val AUPRC 0.9387 | test AUC 0.9808 | test AUPRC 0.9255
Epoch 035 | train loss 0.1188 | train AUC 0.9902 | train AUPRC 0.9537 | val AUC 0.9953 | val AUPRC 0.9740 | test AUC 0.9854 | test AUPRC 0.9517
Epoch 036 | train loss 0.0957 | train AUC 0.9959 | train AUPRC 0.9776 | val AUC 0.9987 | val AUPRC 0.9922 | test AUC 0.9915 | test AUPRC 0.9629
Epoch 037 | train loss 0.0625 | train AUC 0.9979 | train AUPRC 0.9863 | val AUC 0.9995 | val AUPRC 0.9971 | test AUC 0.9951 | test AUPRC 0.9758
Epoch 038 | train loss 0.0566 | train AUC 0.9985 | train AUPRC 0.9931 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 0.9970 | test AUPRC 0.9863
Epoch 039 | train loss 0.0363 | train AUC 0.9991 | train AUPRC 0.9960 | val AUC 0.9998 | val AUPRC 0.9987 | test AUC 0.9979 | test AUPRC 0.9901
Epoch 040 | train loss 0.0308 | train AUC 0.9978 | train AUPRC 0.9919 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 0.9964 | test AUPRC 0.9839
Epoch 041 | train loss 0.0255 | train AUC 0.9999 | train AUPRC 0.9992 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 0.9991 | test AUPRC 0.9954
Epoch 042 | train loss 0.0131 | train AUC 0.9999 | train AUPRC 0.9996 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 0.9997 | test AUPRC 0.9980
Epoch 043 | train loss 0.0155 | train AUC 0.9997 | train AUPRC 0.9985 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 0.9993 | test AUPRC 0.9960
Epoch 044 | train loss 0.0078 | train AUC 0.9999 | train AUPRC 0.9995 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 0.9998 | test AUPRC 0.9987
Epoch 045 | train loss 0.0099 | train AUC 0.9999 | train AUPRC 0.9995 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 0.9997 | test AUPRC 0.9982

In [ ]:
#multirun gat
!python src/train.py --multirun model=gat data=dataset_syn training.epochs=50 data.target="Hospitalization" model.num_layers=2,4,6

[2026-07-09 13:21:23,984][HYDRA] Launching 3 jobs locally
[2026-07-09 13:21:23,985][HYDRA] 	#0 : model=gat data=dataset_syn training.epochs=50 data.target=Hospitalization model.num_layers=2
data:
  name: syn
  target: Hospitalization
  evaluator_type: synthetic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_edges.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_samples_nooverlap.csv
      multihospital: synthetic_pharmacotherapy_v2_samples_multihospital.csv
    scenario: clean
model:
  name: gat
  hidden_dim: 64
  num_layers: 2
  dropout: 0.2
  batch_norm: true
  activation: relu
  heads: 4
training:
  lr: 0.001
  epochs: 50
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
  heads: 4
  dropout: 0.0
  pooling: mean
  batch_norm: true
meta:
  owner_initials: mo
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis
  run_name: ${meta.owner_initials}_${model.name}_${data.name}_${data.target}_${data.dataset.scenario}_ep${training.epochs}_layer${model.num_layers}_hidden${model.hidden_dim}_lr${training.lr}_bs${training.batch_size}

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: oskardmonika (politechnika-gnn-thesis) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: ⢿ setting up run f0t15u5i (0.0s)
wandb: ⣻ setting up run f0t15u5i (0.0s)
wandb: ⣽ setting up run f0t15u5i (0.0s)
wandb: ⣾ setting up run f0t15u5i (0.0s)
wandb: ⣷ setting up run f0t15u5i (0.5s)
wandb: ⣯ setting up run f0t15u5i (0.5s)
wandb: ⣟ setting up run f0t15u5i (0.5s)
wandb: ⡿ setting up run f0t15u5i (0.5s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260709_132124-f0t15u5i
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run mo_gat_syn_Hospitalization_clean_ep50_layer2_hidden64_lr0.001_bs32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/f0t15u5i
Epoch 001 | train loss 0.4178 | train AUC 0.4645 | train AUPRC 0.1195 | val AUC 0.4741 | val AUPRC 0.1453 | test AUC 0.4980 | test AUPRC 0.1447
Epoch 002 | train loss 0.3847 | train AUC 0.4692 | train AUPRC 0.1210 | val AUC 0.4805 | val AUPRC 0.1521 | test AUC 0.5025 | test AUPRC 0.1465
Epoch 003 | train loss 0.3836 | train AUC 0.4812 | train AUPRC 0.1246 | val AUC 0.4944 | val AUPRC 0.1733 | test AUC 0.5119 | test AUPRC 0.1499
Epoch 004 | train loss 0.3813 | train AUC 0.5041 | train AUPRC 0.1313 | val AUC 0.5241 | val AUPRC 0.1968 | test AUC 0.5306 | test AUPRC 0.1544
Epoch 005 | train loss 0.3800 | train AUC 0.5341 | train AUPRC 0.1413 | val AUC 0.5624 | val AUPRC 0.2043 | test AUC 0.5546 | test AUPRC 0.1491
Epoch 006 | train loss 0.3780 | train AUC 0.5691 | train AUPRC 0.1545 | val AUC 0.6066 | val AUPRC 0.2079 | test AUC 0.5820 | test AUPRC 0.1633
Epoch 007 | train loss 0.3762 | train AUC 0.6059 | train AUPRC 0.1723 | val AUC 0.6514 | val AUPRC 0.2087 | test AUC 0.6060 | test AUPRC 0.1579
Epoch 008 | train loss 0.3766 | train AUC 0.6195 | train AUPRC 0.1807 | val AUC 0.6657 | val AUPRC 0.2153 | test AUC 0.6133 | test AUPRC 0.1638
Epoch 009 | train loss 0.3731 | train AUC 0.6266 | train AUPRC 0.1860 | val AUC 0.6713 | val AUPRC 0.2170 | test AUC 0.6145 | test AUPRC 0.1692
Epoch 010 | train loss 0.3725 | train AUC 0.6293 | train AUPRC 0.1894 | val AUC 0.6714 | val AUPRC 0.2165 | test AUC 0.6131 | test AUPRC 0.1731
Epoch 011 | train loss 0.3720 | train AUC 0.6311 | train AUPRC 0.1924 | val AUC 0.6717 | val AUPRC 0.2159 | test AUC 0.6125 | test AUPRC 0.1776
Epoch 012 | train loss 0.3712 | train AUC 0.6293 | train AUPRC 0.1922 | val AUC 0.6696 | val AUPRC 0.2136 | test AUC 0.6072 | test AUPRC 0.1777
Epoch 013 | train loss 0.3706 | train AUC 0.6283 | train AUPRC 0.1921 | val AUC 0.6679 | val AUPRC 0.2118 | test AUC 0.6045 | test AUPRC 0.1785
Epoch 014 | train loss 0.3712 | train AUC 0.6284 | train AUPRC 0.1923 | val AUC 0.6680 | val AUPRC 0.2117 | test AUC 0.6055 | test AUPRC 0.1792
Epoch 015 | train loss 0.3699 | train AUC 0.6290 | train AUPRC 0.1926 | val AUC 0.6686 | val AUPRC 0.2121 | test AUC 0.6066 | test AUPRC 0.1788
Epoch 016 | train loss 0.3710 | train AUC 0.6277 | train AUPRC 0.1921 | val AUC 0.6667 | val AUPRC 0.2102 | test AUC 0.6035 | test AUPRC 0.1797
Epoch 017 | train loss 0.3694 | train AUC 0.6286 | train AUPRC 0.1925 | val AUC 0.6682 | val AUPRC 0.2117 | test AUC 0.6064 | test AUPRC 0.1786
Epoch 018 | train loss 0.3707 | train AUC 0.6273 | train AUPRC 0.1922 | val AUC 0.6664 | val AUPRC 0.2094 | test AUC 0.6039 | test AUPRC 0.1795
Epoch 019 | train loss 0.3700 | train AUC 0.6271 | train AUPRC 0.1924 | val AUC 0.6656 | val AUPRC 0.2089 | test AUC 0.6032 | test AUPRC 0.1791
Epoch 020 | train loss 0.3694 | train AUC 0.6268 | train AUPRC 0.1926 | val AUC 0.6649 | val AUPRC 0.2080 | test AUC 0.6019 | test AUPRC 0.1791
Epoch 021 | train loss 0.3693 | train AUC 0.6258 | train AUPRC 0.1920 | val AUC 0.6633 | val AUPRC 0.2057 | test AUC 0.6003 | test AUPRC 0.1791
Epoch 022 | train loss 0.3698 | train AUC 0.6263 | train AUPRC 0.1924 | val AUC 0.6641 | val AUPRC 0.2069 | test AUC 0.6012 | test AUPRC 0.1790
Epoch 023 | train loss 0.3695 | train AUC 0.6268 | train AUPRC 0.1927 | val AUC 0.6643 | val AUPRC 0.2073 | test AUC 0.6017 | test AUPRC 0.1792
Epoch 024 | train loss 0.3695 | train AUC 0.6266 | train AUPRC 0.1928 | val AUC 0.6641 | val AUPRC 0.2072 | test AUC 0.6016 | test AUPRC 0.1789
Epoch 025 | train loss 0.3701 | train AUC 0.6256 | train AUPRC 0.1920 | val AUC 0.6633 | val AUPRC 0.2064 | test AUC 0.6004 | test AUPRC 0.1791
Epoch 026 | train loss 0.3693 | train AUC 0.6255 | train AUPRC 0.1923 | val AUC 0.6635 | val AUPRC 0.2062 | test AUC 0.6004 | test AUPRC 0.1794
Epoch 027 | train loss 0.3691 | train AUC 0.6261 | train AUPRC 0.1926 | val AUC 0.6634 | val AUPRC 0.2069 | test AUC 0.6006 | test AUPRC 0.1793
Epoch 028 | train loss 0.3697 | train AUC 0.6261 | train AUPRC 0.1925 | val AUC 0.6634 | val AUPRC 0.2066 | test AUC 0.6002 | test AUPRC 0.1792
Epoch 029 | train loss 0.3697 | train AUC 0.6259 | train AUPRC 0.1925 | val AUC 0.6628 | val AUPRC 0.2059 | test AUC 0.5999 | test AUPRC 0.1798
Epoch 030 | train loss 0.3688 | train AUC 0.6276 | train AUPRC 0.1936 | val AUC 0.6654 | val AUPRC 0.2092 | test AUC 0.6030 | test AUPRC 0.1817
Epoch 031 | train loss 0.3692 | train AUC 0.6265 | train AUPRC 0.1931 | val AUC 0.6629 | val AUPRC 0.2067 | test AUC 0.6000 | test AUPRC 0.1815
Epoch 032 | train loss 0.3694 | train AUC 0.6261 | train AUPRC 0.1932 | val AUC 0.6622 | val AUPRC 0.2060 | test AUC 0.5996 | test AUPRC 0.1815
Epoch 033 | train loss 0.3692 | train AUC 0.6266 | train AUPRC 0.1936 | val AUC 0.6624 | val AUPRC 0.2068 | test AUC 0.5999 | test AUPRC 0.1810
Epoch 034 | train loss 0.3689 | train AUC 0.6271 | train AUPRC 0.1937 | val AUC 0.6628 | val AUPRC 0.2074 | test AUC 0.6004 | test AUPRC 0.1819
Epoch 035 | train loss 0.3690 | train AUC 0.6271 | train AUPRC 0.1940 | val AUC 0.6624 | val AUPRC 0.2079 | test AUC 0.6006 | test AUPRC 0.1817
Epoch 036 | train loss 0.3689 | train AUC 0.6272 | train AUPRC 0.1941 | val AUC 0.6617 | val AUPRC 0.2069 | test AUC 0.5998 | test AUPRC 0.1821
Epoch 037 | train loss 0.3684 | train AUC 0.6274 | train AUPRC 0.1942 | val AUC 0.6621 | val AUPRC 0.2075 | test AUC 0.6000 | test AUPRC 0.1826
Epoch 038 | train loss 0.3687 | train AUC 0.6272 | train AUPRC 0.1942 | val AUC 0.6617 | val AUPRC 0.2070 | test AUC 0.5991 | test AUPRC 0.1825
Epoch 039 | train loss 0.3687 | train AUC 0.6281 | train AUPRC 0.1949 | val AUC 0.6622 | val AUPRC 0.2092 | test AUC 0.6010 | test AUPRC 0.1848
Epoch 040 | train loss 0.3692 | train AUC 0.6282 | train AUPRC 0.1949 | val AUC 0.6627 | val AUPRC 0.2098 | test AUC 0.6017 | test AUPRC 0.1848
Epoch 041 | train loss 0.3690 | train AUC 0.6270 | train AUPRC 0.1946 | val AUC 0.6611 | val AUPRC 0.2072 | test AUC 0.5982 | test AUPRC 0.1837
Epoch 042 | train loss 0.3682 | train AUC 0.6282 | train AUPRC 0.1950 | val AUC 0.6620 | val AUPRC 0.2088 | test AUC 0.6010 | test AUPRC 0.1855
Epoch 043 | train loss 0.3685 | train AUC 0.6274 | train AUPRC 0.1950 | val AUC 0.6613 | val AUPRC 0.2078 | test AUC 0.5989 | test AUPRC 0.1852
Epoch 044 | train loss 0.3681 | train AUC 0.6269 | train AUPRC 0.1947 | val AUC 0.6605 | val AUPRC 0.2078 | test AUC 0.5981 | test AUPRC 0.1844
Epoch 045 | train loss 0.3693 | train AUC 0.6274 | train AUPRC 0.1950 | val AUC 0.6612 | val AUPRC 0.2083 | test AUC 0.5988 | test AUPRC 0.1859
Epoch 046 | train loss 0.3684 | train AUC 0.6281 | train AUPRC 0.1953 | val AUC 0.6618 | val AUPRC 0.2089 | test AUC 0.5994 | test AUPRC 0.1858
Epoch 047 | train loss 0.3683 | train AUC 0.6276 | train AUPRC 0.1953 | val AUC 0.6607 | val AUPRC 0.2086 | test AUC 0.5993 | test AUPRC 0.1872
Epoch 048 | train loss 0.3681 | train AUC 0.6288 | train AUPRC 0.1958 | val AUC 0.6622 | val AUPRC 0.2104 | test AUC 0.6001 | test AUPRC 0.1854
Epoch 049 | train loss 0.3683 | train AUC 0.6285 | train AUPRC 0.1956 | val AUC 0.6619 | val AUPRC 0.2093 | test AUC 0.5999 | test AUPRC 0.1859
Epoch 050 | train loss 0.3698 | train AUC 0.6264 | train AUPRC 0.1949 | val AUC 0.6597 | val AUPRC 0.2066 | test AUC 0.5962 | test AUPRC 0.1857
wandb: ⢿ updating run metadata (0.0s)
wandb: ⣻ updating run metadata (0.0s)
wandb: ⣽ updating run metadata (0.0s)
wandb: ⣾ updating run metadata (0.0s)
wandb: ⣷ updating run metadata (0.5s)
wandb: ⣯ updating run metadata (0.5s)
wandb: ⣟ updating run metadata (0.5s)
wandb: ⡿ updating run metadata (0.5s)
wandb: ⢿ updating run metadata (0.5s)
wandb: ⣻ updating run metadata (1.0s)
wandb: ⣽ updating run metadata (1.0s)
wandb: ⣾ updating run metadata (1.0s)
wandb: ⣷ updating run metadata (1.0s)
wandb: ⣯ updating run metadata (1.0s)
wandb: ⣟ uploading output.log 7.0KB/7.0KB (0.1s)
wandb: ⣟ uploading wandb-summary.json 560B/560B (0.1s)
wandb: ⣟ uploading config.yaml 3.6KB/3.6KB (0.1s)
wandb: ⡿ uploading output.log 7.0KB/7.0KB (0.1s)
wandb: ⡿ uploading wandb-summary.json 560B/560B (0.1s)
wandb: ⡿ uploading config.yaml 3.6KB/3.6KB (0.1s)
wandb: ⢿ uploading output.log 7.0KB/7.0KB (0.1s)
wandb: ⢿ uploading wandb-summary.json 560B/560B (0.1s)
wandb: ⢿ uploading config.yaml 3.6KB/3.6KB (0.1s)
wandb: ⣻ uploading output.log 7.0KB/7.0KB (0.1s)
wandb: ⣻ uploading wandb-summary.json 560B/560B (0.1s)
wandb: ⣻ uploading config.yaml 3.6KB/3.6KB (0.1s)
wandb: ⣽ uploading output.log 7.0KB/7.0KB (0.1s)
wandb: ⣽ uploading wandb-summary.json 560B/560B (0.1s)
wandb: ⣽ uploading config.yaml 3.6KB/3.6KB (0.1s)
wandb: ⣾ uploading history steps 44-49, summary, console lines 45-49 (0.3s)
wandb: ⣷ uploading history steps 44-49, summary, console lines 45-49 (0.3s)
wandb: ⣯ uploading history steps 44-49, summary, console lines 45-49 (0.3s)
wandb: ⣟ uploading history steps 44-49, summary, console lines 45-49 (0.3s)
wandb: ⡿ uploading history steps 44-49, summary, console lines 45-49 (0.3s)
wandb: ⢿ uploading history steps 44-49, summary, console lines 45-49 (0.8s)
wandb: ⣻ uploading history steps 44-49, summary, console lines 45-49 (0.8s)
wandb:
wandb: Run history:
wandb:       epoch ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:    test/auc ▁▁▂▃▄▇████▇▇█▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇
wandb:  test/auprc ▁▁▂▃▂▃▄▅▆▆▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇██▇███████
wandb:  test/brier ▇█▆▆▆▄▃▃▃▃▃▂▂▂▃▁▁▂▁▁▁▁▁▁▃▁▁▁▁▁▁▁▁▂▁▃▂▁▁▄
wandb:   test/loss ▇█▅▅▅▄▃▂▂▂▃▂▁▂▃▁▁▂▁▁▁▁▁▁▃▁▁▁▁▁▁▁▂▁▁▁▁▁▁▄
wandb:   train/auc ▁▁▂▃▄▇██████████████████████████████████
wandb: train/auprc ▁▁▁▂▃▆▇▇▇███████████████████████████████
wandb: train/brier ▇█▆▆▄▃▃▃▂▃▂▂▃▂▂▂▁▂▁▁▂▁▁▃▁▁▁▁▁▁▁▂▂▁▁▁▁▁▁▃
wandb:  train/loss █▃▃▃▃▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:     val/auc ▁▂▃▄▆███████████████████████████████████
wandb:          +3 ...
wandb:
wandb: Run summary:
wandb:     best_epoch 9
wandb:   best_val_auc -1
wandb: best_val_auprc 0.21698
wandb:          epoch 50
wandb:       test/auc 0.59619
wandb:     test/auprc 0.18569
wandb:     test/brier 0.10889
wandb:      test/loss 0.37383
wandb:      train/auc 0.62635
wandb:    train/auprc 0.1949
wandb:             +6 ...
wandb:
wandb: 🚀 View run mo_gat_syn_Hospitalization_clean_ep50_layer2_hidden64_lr0.001_bs32 at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/f0t15u5i
wandb: ⭐️ View project at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260709_132124-f0t15u5i/logs
[2026-07-09 13:22:02,543][HYDRA] 	#1 : model=gat data=dataset_syn training.epochs=50 data.target=Hospitalization model.num_layers=4
data:
  name: syn
  target: Hospitalization
  evaluator_type: synthetic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_edges.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_samples_nooverlap.csv
      multihospital: synthetic_pharmacotherapy_v2_samples_multihospital.csv
    scenario: clean
model:
  name: gat
  hidden_dim: 64
  num_layers: 4
  dropout: 0.2
  batch_norm: true
  activation: relu
  heads: 4
training:
  lr: 0.001
  epochs: 50
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
  heads: 4
  dropout: 0.0
  pooling: mean
  batch_norm: true
meta:
  owner_initials: mo
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis
  run_name: ${meta.owner_initials}_${model.name}_${data.name}_${data.target}_${data.dataset.scenario}_ep${training.epochs}_layer${model.num_layers}_hidden${model.hidden_dim}_lr${training.lr}_bs${training.batch_size}

wandb: ⢿ setting up run 1fnuy4dc (0.0s)
wandb: ⣻ setting up run 1fnuy4dc (0.0s)
wandb: ⣽ setting up run 1fnuy4dc (0.0s)
wandb: ⣾ setting up run 1fnuy4dc (0.0s)
wandb: ⣷ setting up run 1fnuy4dc (0.5s)
wandb: ⣯ setting up run 1fnuy4dc (0.5s)
wandb: ⣟ setting up run 1fnuy4dc (0.5s)
wandb: ⡿ setting up run 1fnuy4dc (0.5s)
wandb: ⢿ setting up run 1fnuy4dc (0.5s)
wandb: ⣻ setting up run 1fnuy4dc (1.0s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260709_132202-1fnuy4dc
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run mo_gat_syn_Hospitalization_clean_ep50_layer4_hidden64_lr0.001_bs32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/1fnuy4dc
Epoch 001 | train loss 0.4346 | train AUC 0.4635 | train AUPRC 0.1224 | val AUC 0.4717 | val AUPRC 0.1419 | test AUC 0.5002 | test AUPRC 0.1503
Epoch 002 | train loss 0.3850 | train AUC 0.5128 | train AUPRC 0.1347 | val AUC 0.5263 | val AUPRC 0.1696 | test AUC 0.5447 | test AUPRC 0.1568
Epoch 003 | train loss 0.3783 | train AUC 0.5713 | train AUPRC 0.1532 | val AUC 0.6160 | val AUPRC 0.1992 | test AUC 0.5815 | test AUPRC 0.1488
Epoch 004 | train loss 0.3756 | train AUC 0.6223 | train AUPRC 0.1871 | val AUC 0.6828 | val AUPRC 0.2224 | test AUC 0.6022 | test AUPRC 0.1644
Epoch 005 | train loss 0.3736 | train AUC 0.6273 | train AUPRC 0.1931 | val AUC 0.6822 | val AUPRC 0.2240 | test AUC 0.6037 | test AUPRC 0.1690
Epoch 006 | train loss 0.3721 | train AUC 0.6303 | train AUPRC 0.1978 | val AUC 0.6822 | val AUPRC 0.2267 | test AUC 0.6050 | test AUPRC 0.1720
Epoch 007 | train loss 0.3710 | train AUC 0.6366 | train AUPRC 0.2077 | val AUC 0.6860 | val AUPRC 0.2371 | test AUC 0.6103 | test AUPRC 0.1786
Epoch 008 | train loss 0.3710 | train AUC 0.6402 | train AUPRC 0.2127 | val AUC 0.6888 | val AUPRC 0.2416 | test AUC 0.6126 | test AUPRC 0.1817
Epoch 009 | train loss 0.3716 | train AUC 0.6416 | train AUPRC 0.2177 | val AUC 0.6851 | val AUPRC 0.2374 | test AUC 0.6126 | test AUPRC 0.1869
Epoch 010 | train loss 0.3701 | train AUC 0.6437 | train AUPRC 0.2221 | val AUC 0.6847 | val AUPRC 0.2391 | test AUC 0.6132 | test AUPRC 0.1900
Epoch 011 | train loss 0.3708 | train AUC 0.6453 | train AUPRC 0.2245 | val AUC 0.6850 | val AUPRC 0.2419 | test AUC 0.6138 | test AUPRC 0.1908
Epoch 012 | train loss 0.3676 | train AUC 0.6473 | train AUPRC 0.2314 | val AUC 0.6807 | val AUPRC 0.2439 | test AUC 0.6144 | test AUPRC 0.1941
Epoch 013 | train loss 0.3663 | train AUC 0.6483 | train AUPRC 0.2348 | val AUC 0.6766 | val AUPRC 0.2446 | test AUC 0.6150 | test AUPRC 0.1965
Epoch 014 | train loss 0.3667 | train AUC 0.6485 | train AUPRC 0.2350 | val AUC 0.6764 | val AUPRC 0.2462 | test AUC 0.6148 | test AUPRC 0.1968
Epoch 015 | train loss 0.3643 | train AUC 0.6489 | train AUPRC 0.2371 | val AUC 0.6748 | val AUPRC 0.2463 | test AUC 0.6142 | test AUPRC 0.1969
Epoch 016 | train loss 0.3655 | train AUC 0.6496 | train AUPRC 0.2383 | val AUC 0.6743 | val AUPRC 0.2477 | test AUC 0.6147 | test AUPRC 0.1966
Epoch 017 | train loss 0.3648 | train AUC 0.6501 | train AUPRC 0.2419 | val AUC 0.6704 | val AUPRC 0.2482 | test AUC 0.6126 | test AUPRC 0.1945
Epoch 018 | train loss 0.3682 | train AUC 0.6490 | train AUPRC 0.2370 | val AUC 0.6746 | val AUPRC 0.2457 | test AUC 0.6137 | test AUPRC 0.1965
Epoch 019 | train loss 0.3647 | train AUC 0.6492 | train AUPRC 0.2365 | val AUC 0.6740 | val AUPRC 0.2480 | test AUC 0.6144 | test AUPRC 0.1953
Epoch 020 | train loss 0.3644 | train AUC 0.6500 | train AUPRC 0.2405 | val AUC 0.6718 | val AUPRC 0.2475 | test AUC 0.6142 | test AUPRC 0.1963
Epoch 021 | train loss 0.3648 | train AUC 0.6503 | train AUPRC 0.2407 | val AUC 0.6726 | val AUPRC 0.2484 | test AUC 0.6150 | test AUPRC 0.1976
Epoch 022 | train loss 0.3671 | train AUC 0.6497 | train AUPRC 0.2397 | val AUC 0.6724 | val AUPRC 0.2464 | test AUC 0.6134 | test AUPRC 0.1977
Epoch 023 | train loss 0.3639 | train AUC 0.6502 | train AUPRC 0.2387 | val AUC 0.6727 | val AUPRC 0.2494 | test AUC 0.6166 | test AUPRC 0.1978
Epoch 024 | train loss 0.3642 | train AUC 0.6501 | train AUPRC 0.2420 | val AUC 0.6681 | val AUPRC 0.2471 | test AUC 0.6106 | test AUPRC 0.1944
Epoch 025 | train loss 0.3640 | train AUC 0.6501 | train AUPRC 0.2403 | val AUC 0.6723 | val AUPRC 0.2470 | test AUC 0.6140 | test AUPRC 0.1976
Epoch 026 | train loss 0.3644 | train AUC 0.6499 | train AUPRC 0.2413 | val AUC 0.6708 | val AUPRC 0.2446 | test AUC 0.6127 | test AUPRC 0.1965
Epoch 027 | train loss 0.3638 | train AUC 0.6504 | train AUPRC 0.2413 | val AUC 0.6697 | val AUPRC 0.2477 | test AUC 0.6150 | test AUPRC 0.1971
Epoch 028 | train loss 0.3680 | train AUC 0.6501 | train AUPRC 0.2409 | val AUC 0.6715 | val AUPRC 0.2472 | test AUC 0.6139 | test AUPRC 0.1968
Epoch 029 | train loss 0.3635 | train AUC 0.6506 | train AUPRC 0.2415 | val AUC 0.6709 | val AUPRC 0.2480 | test AUC 0.6148 | test AUPRC 0.1975
Epoch 030 | train loss 0.3649 | train AUC 0.6508 | train AUPRC 0.2417 | val AUC 0.6715 | val AUPRC 0.2487 | test AUC 0.6151 | test AUPRC 0.1967
Epoch 031 | train loss 0.3630 | train AUC 0.6507 | train AUPRC 0.2429 | val AUC 0.6671 | val AUPRC 0.2484 | test AUC 0.6119 | test AUPRC 0.1939
Epoch 032 | train loss 0.3636 | train AUC 0.6507 | train AUPRC 0.2429 | val AUC 0.6677 | val AUPRC 0.2450 | test AUC 0.6119 | test AUPRC 0.1949
Epoch 033 | train loss 0.3658 | train AUC 0.6322 | train AUPRC 0.2156 | val AUC 0.6557 | val AUPRC 0.2361 | test AUC 0.5935 | test AUPRC 0.1813
Epoch 034 | train loss 0.3673 | train AUC 0.6478 | train AUPRC 0.2368 | val AUC 0.6702 | val AUPRC 0.2481 | test AUC 0.6132 | test AUPRC 0.1963
Epoch 035 | train loss 0.3659 | train AUC 0.6527 | train AUPRC 0.2446 | val AUC 0.6722 | val AUPRC 0.2501 | test AUC 0.6164 | test AUPRC 0.1980

In [ ]:
#multirun sage
!python src/train.py --multirun meta.owner_initials="MO" model=sage data=dataset_syn training.epochs=50 data.target="Hospitalization" model.num_layers=2,4,6

[2026-07-09 13:28:56,636][HYDRA] Launching 3 jobs locally
[2026-07-09 13:28:56,636][HYDRA] 	#0 : meta.owner_initials=MO model=sage data=dataset_syn training.epochs=50 data.target=Hospitalization model.num_layers=2
data:
  name: syn
  target: Hospitalization
  evaluator_type: synthetic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_edges.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_samples_nooverlap.csv
      multihospital: synthetic_pharmacotherapy_v2_samples_multihospital.csv
    scenario: clean
model:
  name: sage
  hidden_dim: 64
  num_layers: 2
  dropout: 0.2
  batch_norm: true
  activation: relu
training:
  lr: 0.001
  epochs: 50
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
  heads: 4
  dropout: 0.0
  pooling: mean
  batch_norm: true
meta:
  owner_initials: MO
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis
  run_name: ${meta.owner_initials}_${model.name}_${data.name}_${data.target}_${data.dataset.scenario}_ep${training.epochs}_layer${model.num_layers}_hidden${model.hidden_dim}_lr${training.lr}_bs${training.batch_size}

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: oskardmonika (politechnika-gnn-thesis) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: ⢿ setting up run wmk0tr5y (0.0s)
wandb: ⣻ setting up run wmk0tr5y (0.0s)
wandb: ⣽ setting up run wmk0tr5y (0.0s)
wandb: ⣾ setting up run wmk0tr5y (0.0s)
wandb: ⣷ setting up run wmk0tr5y (0.5s)
wandb: ⣯ setting up run wmk0tr5y (0.5s)
wandb: ⣟ setting up run wmk0tr5y (0.5s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260709_132856-wmk0tr5y
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run MO_sage_syn_Hospitalization_clean_ep50_layer2_hidden64_lr0.001_bs32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/wmk0tr5y
Epoch 001 | train loss 0.3994 | train AUC 0.4790 | train AUPRC 0.1250 | val AUC 0.5030 | val AUPRC 0.1342 | test AUC 0.5057 | test AUPRC 0.1517
Epoch 002 | train loss 0.3823 | train AUC 0.5306 | train AUPRC 0.1372 | val AUC 0.5697 | val AUPRC 0.1807 | test AUC 0.5465 | test AUPRC 0.1565
Epoch 003 | train loss 0.3790 | train AUC 0.5890 | train AUPRC 0.1615 | val AUC 0.6478 | val AUPRC 0.2162 | test AUC 0.5899 | test AUPRC 0.1601
Epoch 004 | train loss 0.3757 | train AUC 0.6030 | train AUPRC 0.1730 | val AUC 0.6631 | val AUPRC 0.2318 | test AUC 0.5937 | test AUPRC 0.1558
Epoch 005 | train loss 0.3747 | train AUC 0.6116 | train AUPRC 0.1821 | val AUC 0.6682 | val AUPRC 0.2264 | test AUC 0.5939 | test AUPRC 0.1638
Epoch 006 | train loss 0.3759 | train AUC 0.6177 | train AUPRC 0.1878 | val AUC 0.6696 | val AUPRC 0.2210 | test AUC 0.5967 | test AUPRC 0.1699
Epoch 007 | train loss 0.3717 | train AUC 0.6202 | train AUPRC 0.1906 | val AUC 0.6687 | val AUPRC 0.2178 | test AUC 0.5979 | test AUPRC 0.1731
Epoch 008 | train loss 0.3721 | train AUC 0.6224 | train AUPRC 0.1919 | val AUC 0.6716 | val AUPRC 0.2207 | test AUC 0.6010 | test AUPRC 0.1734
Epoch 009 | train loss 0.3707 | train AUC 0.6259 | train AUPRC 0.1941 | val AUC 0.6765 | val AUPRC 0.2284 | test AUC 0.6077 | test AUPRC 0.1766
Epoch 010 | train loss 0.3709 | train AUC 0.6233 | train AUPRC 0.1948 | val AUC 0.6654 | val AUPRC 0.2166 | test AUC 0.5981 | test AUPRC 0.1776
Epoch 011 | train loss 0.3712 | train AUC 0.6289 | train AUPRC 0.1991 | val AUC 0.6719 | val AUPRC 0.2205 | test AUC 0.6063 | test AUPRC 0.1806
Epoch 012 | train loss 0.3701 | train AUC 0.6317 | train AUPRC 0.2012 | val AUC 0.6747 | val AUPRC 0.2241 | test AUC 0.6084 | test AUPRC 0.1817
Epoch 013 | train loss 0.3700 | train AUC 0.6322 | train AUPRC 0.2021 | val AUC 0.6734 | val AUPRC 0.2242 | test AUC 0.6075 | test AUPRC 0.1830
Epoch 014 | train loss 0.3684 | train AUC 0.6369 | train AUPRC 0.2066 | val AUC 0.6785 | val AUPRC 0.2276 | test AUC 0.6148 | test AUPRC 0.1846
Epoch 015 | train loss 0.3693 | train AUC 0.6378 | train AUPRC 0.2060 | val AUC 0.6770 | val AUPRC 0.2270 | test AUC 0.6138 | test AUPRC 0.1860
Epoch 016 | train loss 0.3683 | train AUC 0.6410 | train AUPRC 0.2100 | val AUC 0.6791 | val AUPRC 0.2288 | test AUC 0.6182 | test AUPRC 0.1896
Epoch 017 | train loss 0.3676 | train AUC 0.6436 | train AUPRC 0.2125 | val AUC 0.6810 | val AUPRC 0.2313 | test AUC 0.6222 | test AUPRC 0.1913
Epoch 018 | train loss 0.3667 | train AUC 0.6455 | train AUPRC 0.2140 | val AUC 0.6822 | val AUPRC 0.2317 | test AUC 0.6243 | test AUPRC 0.1932
Epoch 019 | train loss 0.3684 | train AUC 0.6470 | train AUPRC 0.2154 | val AUC 0.6817 | val AUPRC 0.2318 | test AUC 0.6243 | test AUPRC 0.1965
Epoch 020 | train loss 0.3649 | train AUC 0.6504 | train AUPRC 0.2184 | val AUC 0.6844 | val AUPRC 0.2343 | test AUC 0.6299 | test AUPRC 0.1990
Epoch 021 | train loss 0.3661 | train AUC 0.6522 | train AUPRC 0.2199 | val AUC 0.6856 | val AUPRC 0.2358 | test AUC 0.6312 | test AUPRC 0.2007
Epoch 022 | train loss 0.3660 | train AUC 0.6561 | train AUPRC 0.2236 | val AUC 0.6886 | val AUPRC 0.2376 | test AUC 0.6382 | test AUPRC 0.2036
Epoch 023 | train loss 0.3642 | train AUC 0.6581 | train AUPRC 0.2253 | val AUC 0.6896 | val AUPRC 0.2389 | test AUC 0.6407 | test AUPRC 0.2063
Epoch 024 | train loss 0.3629 | train AUC 0.6609 | train AUPRC 0.2277 | val AUC 0.6918 | val AUPRC 0.2409 | test AUC 0.6453 | test AUPRC 0.2082
Epoch 025 | train loss 0.3628 | train AUC 0.6634 | train AUPRC 0.2302 | val AUC 0.6931 | val AUPRC 0.2423 | test AUC 0.6473 | test AUPRC 0.2112
Epoch 026 | train loss 0.3624 | train AUC 0.6648 | train AUPRC 0.2312 | val AUC 0.6929 | val AUPRC 0.2397 | test AUC 0.6482 | test AUPRC 0.2121
Epoch 027 | train loss 0.3634 | train AUC 0.6685 | train AUPRC 0.2357 | val AUC 0.6957 | val AUPRC 0.2429 | test AUC 0.6533 | test AUPRC 0.2152
Epoch 028 | train loss 0.3623 | train AUC 0.6693 | train AUPRC 0.2361 | val AUC 0.6966 | val AUPRC 0.2445 | test AUC 0.6525 | test AUPRC 0.2152
Epoch 029 | train loss 0.3600 | train AUC 0.6732 | train AUPRC 0.2407 | val AUC 0.6998 | val AUPRC 0.2481 | test AUC 0.6581 | test AUPRC 0.2186
Epoch 030 | train loss 0.3598 | train AUC 0.6738 | train AUPRC 0.2413 | val AUC 0.6991 | val AUPRC 0.2450 | test AUC 0.6570 | test AUPRC 0.2191
Epoch 031 | train loss 0.3608 | train AUC 0.6777 | train AUPRC 0.2454 | val AUC 0.7020 | val AUPRC 0.2496 | test AUC 0.6626 | test AUPRC 0.2225
Epoch 032 | train loss 0.3585 | train AUC 0.6800 | train AUPRC 0.2479 | val AUC 0.7038 | val AUPRC 0.2537 | test AUC 0.6659 | test AUPRC 0.2254
Epoch 033 | train loss 0.3576 | train AUC 0.6827 | train AUPRC 0.2517 | val AUC 0.7052 | val AUPRC 0.2567 | test AUC 0.6694 | test AUPRC 0.2261
Epoch 034 | train loss 0.3575 | train AUC 0.6845 | train AUPRC 0.2534 | val AUC 0.7059 | val AUPRC 0.2566 | test AUC 0.6713 | test AUPRC 0.2283
Epoch 035 | train loss 0.3561 | train AUC 0.6861 | train AUPRC 0.2551 | val AUC 0.7070 | val AUPRC 0.2574 | test AUC 0.6728 | test AUPRC 0.2296
Epoch 036 | train loss 0.3553 | train AUC 0.6894 | train AUPRC 0.2587 | val AUC 0.7095 | val AUPRC 0.2626 | test AUC 0.6774 | test AUPRC 0.2321
Epoch 037 | train loss 0.3540 | train AUC 0.6922 | train AUPRC 0.2618 | val AUC 0.7127 | val AUPRC 0.2747 | test AUC 0.6829 | test AUPRC 0.2324
Epoch 038 | train loss 0.3583 | train AUC 0.6941 | train AUPRC 0.2642 | val AUC 0.7131 | val AUPRC 0.2723 | test AUC 0.6836 | test AUPRC 0.2360
Epoch 039 | train loss 0.3535 | train AUC 0.6947 | train AUPRC 0.2640 | val AUC 0.7133 | val AUPRC 0.2670 | test AUC 0.6823 | test AUPRC 0.2381
Epoch 040 | train loss 0.3522 | train AUC 0.6979 | train AUPRC 0.2674 | val AUC 0.7159 | val AUPRC 0.2738 | test AUC 0.6867 | test AUPRC 0.2389
Epoch 041 | train loss 0.3552 | train AUC 0.6993 | train AUPRC 0.2692 | val AUC 0.7163 | val AUPRC 0.2712 | test AUC 0.6873 | test AUPRC 0.2420
Epoch 042 | train loss 0.3530 | train AUC 0.7014 | train AUPRC 0.2716 | val AUC 0.7186 | val AUPRC 0.2736 | test AUC 0.6895 | test AUPRC 0.2443
Epoch 043 | train loss 0.3526 | train AUC 0.7041 | train AUPRC 0.2761 | val AUC 0.7206 | val AUPRC 0.2834 | test AUC 0.6955 | test AUPRC 0.2471
Epoch 044 | train loss 0.3510 | train AUC 0.7059 | train AUPRC 0.2776 | val AUC 0.7221 | val AUPRC 0.2853 | test AUC 0.6967 | test AUPRC 0.2482
Epoch 045 | train loss 0.3510 | train AUC 0.7078 | train AUPRC 0.2810 | val AUC 0.7227 | val AUPRC 0.2914 | test AUC 0.7004 | test AUPRC 0.2505
Epoch 046 | train loss 0.3498 | train AUC 0.7102 | train AUPRC 0.2837 | val AUC 0.7242 | val AUPRC 0.2925 | test AUC 0.7021 | test AUPRC 0.2515
Epoch 047 | train loss 0.3487 | train AUC 0.7120 | train AUPRC 0.2850 | val AUC 0.7262 | val AUPRC 0.2893 | test AUC 0.7014 | test AUPRC 0.2544
Epoch 048 | train loss 0.3483 | train AUC 0.7111 | train AUPRC 0.2825 | val AUC 0.7256 | val AUPRC 0.2812 | test AUC 0.6968 | test AUPRC 0.2543
Epoch 049 | train loss 0.3512 | train AUC 0.7152 | train AUPRC 0.2890 | val AUC 0.7290 | val AUPRC 0.2943 | test AUC 0.7042 | test AUPRC 0.2582
Epoch 050 | train loss 0.3496 | train AUC 0.7168 | train AUPRC 0.2904 | val AUC 0.7300 | val AUPRC 0.2954 | test AUC 0.7047 | test AUPRC 0.2589
wandb: ⢿ updating run metadata (0.0s)
wandb: ⣻ updating run metadata (0.0s)
wandb: ⣽ updating run metadata (0.0s)
wandb: ⣾ updating run metadata (0.0s)
wandb: ⣷ Finishing up...
wandb: ⣯ Finishing up...
wandb: ⣟ Finishing up...
wandb: ⡿ Finishing up...
wandb: ⢿ Finishing up...
wandb: ⣻ uploading history steps 34-49, summary, console lines 35-49 (0.2s)
wandb: ⣽ uploading history steps 34-49, summary, console lines 35-49 (0.2s)
wandb:
wandb: Run history:
wandb:       epoch ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:    test/auc ▁▂▄▄▄▄▄▅▄▅▅▅▅▅▅▅▅▅▆▆▆▆▆▆▆▇▇▇▇▇▇▇▇▇██████
wandb:  test/auprc ▁▁▂▁▂▂▂▃▃▃▃▃▃▃▄▄▄▄▅▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇████
wandb:  test/brier █▇▇▆▆▆▇█▆▆▆▅▅▅▅▅▅▅▄▄▄▅▄▄▃▃▃▃▂▃▂▂▂▃▂▂▂▁█▂
wandb:   test/loss ███▆▆▆▆██▆▆▆▅▅▅▆▅▅▅▅▄▄▅▄▄▃▃▃▂▃▂▂▂▃▁▂▁▁▆▂
wandb:   train/auc ▁▃▄▅▅▅▅▅▅▅▆▆▆▆▆▆▆▆▆▆▆▇▇▇▇▇▇▇▇▇▇▇▇▇██████
wandb: train/auprc ▁▂▃▃▃▄▄▄▄▄▄▄▄▅▅▅▅▅▅▅▅▆▆▆▆▆▆▆▇▇▇▇▇▇▇█████
wandb: train/brier ██▇▇▆▆▆▇▇▆▆▅▅▅▅▅▅▅▅▄▄▄▄▄▄▃▃▃▃▄▂▂▂▂▂▃▂▁▅▁
wandb:  train/loss █▆▅▅▅▄▄▄▄▄▄▄▄▄▄▃▃▃▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁
wandb:     val/auc ▁▃▅▆▆▆▆▆▆▆▆▆▆▆▆▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇█████████
wandb:          +3 ...
wandb:
wandb: Run summary:
wandb:     best_epoch 50
wandb:   best_val_auc -1
wandb: best_val_auprc 0.29535
wandb:          epoch 50
wandb:       test/auc 0.70471
wandb:     test/auprc 0.25887
wandb:     test/brier 0.1039
wandb:      test/loss 0.35325
wandb:      train/auc 0.71682
wandb:    train/auprc 0.29044
wandb:             +6 ...
wandb:
wandb: 🚀 View run MO_sage_syn_Hospitalization_clean_ep50_layer2_hidden64_lr0.001_bs32 at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/wmk0tr5y
wandb: ⭐️ View project at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260709_132856-wmk0tr5y/logs
[2026-07-09 13:29:22,236][HYDRA] 	#1 : meta.owner_initials=MO model=sage data=dataset_syn training.epochs=50 data.target=Hospitalization model.num_layers=4
data:
  name: syn
  target: Hospitalization
  evaluator_type: synthetic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_edges.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_samples_nooverlap.csv
      multihospital: synthetic_pharmacotherapy_v2_samples_multihospital.csv
    scenario: clean
model:
  name: sage
  hidden_dim: 64
  num_layers: 4
  dropout: 0.2
  batch_norm: true
  activation: relu
training:
  lr: 0.001
  epochs: 50
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
  heads: 4
  dropout: 0.0
  pooling: mean
  batch_norm: true
meta:
  owner_initials: MO
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis
  run_name: ${meta.owner_initials}_${model.name}_${data.name}_${data.target}_${data.dataset.scenario}_ep${training.epochs}_layer${model.num_layers}_hidden${model.hidden_dim}_lr${training.lr}_bs${training.batch_size}

wandb: ⢿ setting up run t3b0k0m5 (0.0s)
wandb: ⣻ setting up run t3b0k0m5 (0.0s)
wandb: ⣽ setting up run t3b0k0m5 (0.0s)
wandb: ⣾ setting up run t3b0k0m5 (0.0s)
wandb: ⣷ setting up run t3b0k0m5 (0.5s)
wandb: ⣯ setting up run t3b0k0m5 (0.5s)
wandb: ⣟ setting up run t3b0k0m5 (0.5s)
wandb: ⡿ setting up run t3b0k0m5 (0.5s)
wandb: ⢿ setting up run t3b0k0m5 (0.5s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260709_132922-t3b0k0m5
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run MO_sage_syn_Hospitalization_clean_ep50_layer4_hidden64_lr0.001_bs32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/t3b0k0m5
Epoch 001 | train loss 0.3966 | train AUC 0.5047 | train AUPRC 0.1323 | val AUC 0.5270 | val AUPRC 0.1538 | test AUC 0.5356 | test AUPRC 0.1591
Epoch 002 | train loss 0.3815 | train AUC 0.5825 | train AUPRC 0.1575 | val AUC 0.6414 | val AUPRC 0.2089 | test AUC 0.5796 | test AUPRC 0.1600
Epoch 003 | train loss 0.3759 | train AUC 0.6047 | train AUPRC 0.1732 | val AUC 0.6659 | val AUPRC 0.2057 | test AUC 0.5882 | test AUPRC 0.1569
Epoch 004 | train loss 0.3748 | train AUC 0.6089 | train AUPRC 0.1775 | val AUC 0.6690 | val AUPRC 0.2092 | test AUC 0.5923 | test AUPRC 0.1608
Epoch 005 | train loss 0.3739 | train AUC 0.6133 | train AUPRC 0.1830 | val AUC 0.6723 | val AUPRC 0.2110 | test AUC 0.5977 | test AUPRC 0.1647
Epoch 006 | train loss 0.3723 | train AUC 0.6164 | train AUPRC 0.1860 | val AUC 0.6731 | val AUPRC 0.2111 | test AUC 0.6013 | test AUPRC 0.1704
Epoch 007 | train loss 0.3729 | train AUC 0.6203 | train AUPRC 0.1899 | val AUC 0.6769 | val AUPRC 0.2155 | test AUC 0.6068 | test AUPRC 0.1736
Epoch 008 | train loss 0.3731 | train AUC 0.6211 | train AUPRC 0.1906 | val AUC 0.6761 | val AUPRC 0.2162 | test AUC 0.6074 | test AUPRC 0.1755
Epoch 009 | train loss 0.3750 | train AUC 0.6239 | train AUPRC 0.1951 | val AUC 0.6773 | val AUPRC 0.2180 | test AUC 0.6090 | test AUPRC 0.1764
Epoch 010 | train loss 0.3702 | train AUC 0.6292 | train AUPRC 0.2014 | val AUC 0.6802 | val AUPRC 0.2231 | test AUC 0.6143 | test AUPRC 0.1825
Epoch 011 | train loss 0.3713 | train AUC 0.6366 | train AUPRC 0.2095 | val AUC 0.6825 | val AUPRC 0.2310 | test AUC 0.6210 | test AUPRC 0.1918
Epoch 012 | train loss 0.3688 | train AUC 0.6449 | train AUPRC 0.2204 | val AUC 0.6828 | val AUPRC 0.2391 | test AUC 0.6290 | test AUPRC 0.2018
Epoch 013 | train loss 0.3673 | train AUC 0.6673 | train AUPRC 0.2456 | val AUC 0.7012 | val AUPRC 0.2727 | test AUC 0.6543 | test AUPRC 0.2240
Epoch 014 | train loss 0.3622 | train AUC 0.6884 | train AUPRC 0.2667 | val AUC 0.7118 | val AUPRC 0.3018 | test AUC 0.6783 | test AUPRC 0.2417
Epoch 015 | train loss 0.3572 | train AUC 0.7130 | train AUPRC 0.2958 | val AUC 0.7294 | val AUPRC 0.3489 | test AUC 0.7091 | test AUPRC 0.2590
Epoch 016 | train loss 0.3441 | train AUC 0.7622 | train AUPRC 0.3581 | val AUC 0.7620 | val AUPRC 0.3862 | test AUC 0.7512 | test AUPRC 0.3162
Epoch 017 | train loss 0.3362 | train AUC 0.8122 | train AUPRC 0.4316 | val AUC 0.8019 | val AUPRC 0.4449 | test AUC 0.7982 | test AUPRC 0.3727
Epoch 018 | train loss 0.3107 | train AUC 0.8643 | train AUPRC 0.5262 | val AUC 0.8514 | val AUPRC 0.5138 | test AUC 0.8490 | test AUPRC 0.4813
Epoch 019 | train loss 0.2889 | train AUC 0.9146 | train AUPRC 0.6459 | val AUC 0.9020 | val AUPRC 0.6102 | test AUC 0.8979 | test AUPRC 0.6023
Epoch 020 | train loss 0.2447 | train AUC 0.9683 | train AUPRC 0.8100 | val AUC 0.9605 | val AUPRC 0.7697 | test AUC 0.9578 | test AUPRC 0.7940
Epoch 021 | train loss 0.1804 | train AUC 0.9894 | train AUPRC 0.9002 | val AUC 0.9842 | val AUPRC 0.8622 | test AUC 0.9853 | test AUPRC 0.8966
Epoch 022 | train loss 0.1228 | train AUC 0.9943 | train AUPRC 0.9331 | val AUC 0.9904 | val AUPRC 0.9020 | test AUC 0.9934 | test AUPRC 0.9304
Epoch 023 | train loss 0.0792 | train AUC 0.9968 | train AUPRC 0.9645 | val AUC 0.9944 | val AUPRC 0.9484 | test AUC 0.9967 | test AUPRC 0.9716
Epoch 024 | train loss 0.0732 | train AUC 0.9976 | train AUPRC 0.9750 | val AUC 0.9957 | val AUPRC 0.9606 | test AUC 0.9977 | test AUPRC 0.9809
Epoch 025 | train loss 0.0425 | train AUC 0.9989 | train AUPRC 0.9899 | val AUC 0.9980 | val AUPRC 0.9852 | test AUC 0.9993 | test AUPRC 0.9947
Epoch 026 | train loss 0.0323 | train AUC 0.9995 | train AUPRC 0.9961 | val AUC 0.9993 | val AUPRC 0.9954 | test AUC 0.9996 | test AUPRC 0.9969
Epoch 027 | train loss 0.0247 | train AUC 0.9997 | train AUPRC 0.9980 | val AUC 0.9996 | val AUPRC 0.9971 | test AUC 0.9998 | test AUPRC 0.9988
Epoch 028 | train loss 0.0231 | train AUC 1.0000 | train AUPRC 0.9997 | val AUC 0.9998 | val AUPRC 0.9990 | test AUC 0.9999 | test AUPRC 0.9996
Epoch 029 | train loss 0.0228 | train AUC 1.0000 | train AUPRC 0.9998 | val AUC 0.9998 | val AUPRC 0.9990 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 030 | train loss 0.0128 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 0.9998 | test AUC 0.9999 | test AUPRC 0.9996
Epoch 031 | train loss 0.0103 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 0.9999 | val AUPRC 0.9997 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 032 | train loss 0.0091 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 033 | train loss 0.0066 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 034 | train loss 0.0057 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 035 | train loss 0.0048 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 036 | train loss 0.0093 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 037 | train loss 0.0031 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 038 | train loss 0.0024 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 039 | train loss 0.0018 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 040 | train loss 0.0015 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 041 | train loss 0.0012 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 042 | train loss 0.0037 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 043 | train loss 0.0011 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 044 | train loss 0.0018 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 045 | train loss 0.0008 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000

In [9]:
import sys
sys.path.insert(0, "/content/GraphNeuralNetwork_Thesis/src")

In [ ]:
train = 0
test = 0
valid = 0

In [ ]:
from omegaconf import OmegaConf
from data.load_split_benchmark_data import load_split_benchmark_data
from data.load_split_benchmark_data import build_combined_splits

cfg = OmegaConf.create({
    "data": {
        "name": "syn",
        "target": "DILI",
        "dataset": {
            "root_dir": "/content/drive/MyDrive/synthetic_pharmacotherapy_v2 2/synthetic_pharmacotherapy_v2_1_nn_benchmark",
            "nodes_file": "synthetic_pharmacotherapy_v2_nodes.csv",
            "edges_file": "synthetic_pharmacotherapy_v2_1_edges_audited.csv",
            "include_external_test": False,
            "keep_scenario": False,
            "scenarios": {
                "clean": "synthetic_pharmacotherapy_v2_samples_clean.csv",
                "no_overlap": "synthetic_pharmacotherapy_v2_samples_no_overlap.csv",
                "multihospital": "synthetic_pharmacotherapy_v2_samples_multihospital.csv",
                "hidden":   "synthetic_pharmacotherapy_v2_samples_hidden_confounder.csv",
                "doc": "synthetic_pharmacotherapy_v2_samples_noisy_documentation.csv",
                "bias": "synthetic_pharmacotherapy_v2_samples_selection_bias.csv"
            },
        }
    }
})

#train, valid, test = load_split_benchmark_data(cfg)
x,y,z,a=build_combined_splits(cfg)

In [10]:
import pandas as pd

In [11]:
clean=pd.read_csv("/content/drive/MyDrive/synthetic_pharmacotherapy_v2 2/synthetic_pharmacotherapy_v2_1_nn_benchmark/synthetic_pharmacotherapy_v2_samples_clean.csv")

In [12]:
nodes=pd.read_csv("/content/drive/MyDrive/synthetic_pharmacotherapy_v2 2/synthetic_pharmacotherapy_v2_1_nn_benchmark/synthetic_pharmacotherapy_v2_nodes.csv")

In [13]:
columns = clean.columns.tolist()

In [14]:
columns

['patient_id',
 'hospital_id',
 'age',
 'alcohol_use',
 'baseline_alt_ast',
 'baseline_egfr',
 'baseline_mood_vulnerability',
 'baseline_potassium',
 'baseline_qt_risk',
 'baseline_sodium',
 'ckd',
 'depression_history',
 'diabetes',
 'frailty',
 'heart_failure',
 'infection',
 'liver_disease',
 'monitoring_intensity',
 'polypharmacy_burden',
 'sex_female',
 'unobserved_severity',
 'acei_arb',
 'aminoglycoside',
 'antibiotic_hepatic_risk',
 'anticholinergic',
 'anticoagulant',
 'antiplatelet',
 'benzodiazepine',
 'beta_blocker',
 'contrast_agent',
 'corticosteroid',
 'diuretic',
 'hepatotoxic_drug_A',
 'herbal_exposure',
 'nsaid',
 'opioid',
 'ppi',
 'qt_prolonging_drug',
 'snri',
 'ssri',
 'thiazide',
 'valproate_like_drug',
 'anticholinergic_burden',
 'cardiac_repolarization_delay',
 'cholestatic_pattern',
 'cns_sedation',
 'coagulation_impairment',
 'electrolyte_disturbance',
 'fatigue_pathway',
 'gastric_mucosal_injury',
 'gastric_protection',
 'hepatic_metabolic_stress',
 'hepatocellular_injury',
 'monoamine_disruption',
 'nephrotoxic_stress',
 'oxidative_hepatic_stress',
 'platelet_inhibition',
 'potassium_retention',
 'psychomotor_impairment',
 'reduced_renal_perfusion',
 'serotonergic_shift',
 'sleep_disruption',
 'sodium_water_imbalance',
 'tubular_injury',
 'volume_depletion',
 'alt_ast_rise',
 'anhedonia_like_symptom',
 'bilirubin_rise',
 'cognitive_slowing',
 'confusion_state',
 'creatinine_rise',
 'dehydration',
 'dizziness',
 'fatigue_symptom',
 'gi_irritation',
 'hyperkalemia_state',
 'hyponatremia_state',
 'hypotension',
 'jaundice',
 'mood_lowering',
 'nausea',
 'occult_bleeding',
 'overt_bleeding',
 'qt_prolongation_state',
 'sedation_state',
 'sleep_disturbance_symptom',
 'adr_reported',
 'creatinine_tested',
 'ecg_performed',
 'electrolyte_abnormality_recorded',
 'electrolytes_tested',
 'elevated_alt_ast_recorded',
 'elevated_creatinine_recorded',
 'fall_reported',
 'hospital_contact',
 'lft_tested',
 'mood_screening_done',
 'qt_recorded',
 'AKI',
 'DILI',
 'Delirium',
 'Depression',
 'Falls',
 'GI_bleeding',
 'Hospitalization',
 'Hyperkalemia',
 'Hyponatremia',
 'QT_arrhythmia',
 'replicate_id',
 'generation_seed',
 'benchmark_split',
 'paired_patient_key',
 'benchmark_scenario']

In [20]:
nodes[nodes['node'].isin(columns)]

,node,node_type,layer,description,base_prevalence,frequency_class,severity_weight,observability,rarity_weight,node_priority_weight,is_endpoint,is_rare_signal,is_latent,recommended_use
0,age,patient_context,1_patient_context,"Age in years, continuous",NaN,NaN,1,1.00,NaN,NaN,False,False,False,feature_or_target
1,alcohol_use,patient_context,1_patient_context,Alcohol exposure/risk marker,0.110,common,3,0.65,1.371,4.473,False,False,False,feature_or_target
2,baseline_alt_ast,patient_context,1_patient_context,Continuous baseline liver enzymes,NaN,NaN,4,0.75,NaN,NaN,False,False,False,feature_or_target
3,baseline_egfr,patient_context,1_patient_context,Continuous baseline kidney function,NaN,NaN,4,0.90,NaN,NaN,False,False,False,feature_or_target
4,baseline_mood_vulnerability,patient_context,1_patient_context,Synthetic latent-ish mood vulnerability proxy,0.120,common,3,0.65,1.312,4.280,False,False,False,feature_or_target
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,GI_bleeding,clinical_endpoint,6_endpoints,GI bleeding,0.020,occasional,5,0.75,3.214,10.000,True,True,False,feature_or_target
102,Hospitalization,clinical_endpoint,6_endpoints,Hospitalization or prolongation of stay,0.120,common,3,0.85,1.312,4.084,True,False,False,feature_or_target
103,Hyperkalemia,clinical_endpoint,6_endpoints,Hyperkalemia endpoint,0.040,occasional,5,0.85,2.273,10.000,True,True,False,feature_or_target
104,Hyponatremia,clinical_endpoint,6_endpoints,Hyponatremia endpoint,0.060,frequent,4,0.85,1.856,7.702,True,False,False,feature_or_target
105,QT_arrhythmia,clinical_endpoint,6_endpoints,QT prolongation / arrhythmia endpoint,0.012,occasional,5,0.60,4.149,10.000,True,True,False,feature_or_target

In [ ]:
train['node_features']['value'].isna() == True

0           False
1           False
2           False
3           False
4           False
            ...
17870575    False
17870576    False
17870577    False
17870578    False
17870579    False
Name: value, Length: 17870580, dtype: bool

In [ ]:
import torch

In [ ]:
import torch
import pandas as pd

# The original code expected `train` to be a torch_geometric.data.HeteroData object,
# where 'patient_id' and 'variable' would be node types and
# ('patient_id', 'has', 'variable') an edge type.
# However, `train` is a dictionary of pandas DataFrames.

# To check for NaNs and Infs in the relevant numeric columns of the DataFrames:

# Check 'node_features' DataFrame's 'value' column
if 'node_features' in train and 'value' in train['node_features'].columns:
    node_features_values = torch.tensor(train['node_features']['value'].values, dtype=torch.float32)
    print(f"Node features (all nodes): NaN presence: {torch.isnan(node_features_values).any()}, Inf presence: {torch.isinf(node_features_values).any()}")
else:
    print("Warning: 'node_features' or 'value' column not found in train dictionary.")

# Check 'feature_edges' DataFrame's 'value' column
if 'feature_edges' in train and 'value' in train['feature_edges'].columns:
    edge_attributes_values = torch.tensor(train['feature_edges']['value'].values, dtype=torch.float32)
    print(f"Edge attributes (all edges): NaN presence: {torch.isnan(edge_attributes_values).any()}, Inf presence: {torch.isinf(edge_attributes_values).any()}")
else:
    print("Warning: 'feature_edges' or 'value' column not found in train dictionary.")

# Note: 'patient_id' and 'variable' are not direct keys for node types in the current
# `train` dictionary structure, nor is `("patient_id", "has", "variable")` an edge type key.

Node features (all nodes): NaN presence: True, Inf presence: False
Edge attributes (all edges): NaN presence: False, Inf presence: False

In [ ]:
type(train)

dict

In [ ]:
ENDPOINTS = [
    "AKI", "DILI", "Depression", "Falls", "Delirium",
    "GI_bleeding", "Hyponatremia", "Hyperkalemia",
    "QT_arrhythmia", "Hospitalization",
]

N_total = len(samples)
stats = []

for ep in ENDPOINTS:
    #if ep not in samples.columns:
    #    continue
    N_pos = samples[ep].sum()
    N_neg = N_total - N_pos
    prevalence = N_pos / N_total
    stats.append((ep, int(N_pos), int(N_neg), prevalence))

for ep, N_pos, N_neg, prev in stats:
    print(f"{ep}: pos={N_pos}, neg={N_neg}, prev={prev:.4f}")

KeyError: 'AKI'

In [ ]:
import pandas as pd

ENDPOINTS = [
    "AKI", "DILI", "Depression", "Falls", "Delirium",
    "GI_bleeding", "Hyponatremia", "Hyperkalemia",
    "QT_arrhythmia", "Hospitalization",
]

# tylko endpointy
E = samples[ENDPOINTS].astype(int)

# macierz współwystępowania: liczba pacjentów z ep_i=1 i ep_j=1
coocc_counts = pd.DataFrame(index=ENDPOINTS, columns=ENDPOINTS, dtype=int)

for ep_i in ENDPOINTS:
    for ep_j in ENDPOINTS:
        coocc_counts.loc[ep_i, ep_j] = ((E[ep_i] == 1) & (E[ep_j] == 1)).sum()

print(coocc_counts)

                   AKI  DILI  Depression  Falls  Delirium  GI_bleeding  \
AKI              225.0   3.0        12.0   18.0      11.0          3.0
DILI               3.0  64.0         2.0    4.0       4.0          2.0
Depression        12.0   2.0       258.0   18.0       9.0          4.0
Falls             18.0   4.0        18.0  411.0      23.0          1.0
Delirium          11.0   4.0         9.0   23.0     233.0          0.0
GI_bleeding        3.0   2.0         4.0    1.0       0.0         58.0
Hyponatremia       8.0   2.0        11.0   15.0       6.0          0.0
Hyperkalemia       9.0   1.0         8.0   11.0       5.0          1.0
QT_arrhythmia      1.0   0.0         0.0    3.0       2.0          0.0
Hospitalization   61.0  22.0        39.0  106.0      74.0          6.0

                 Hyponatremia  Hyperkalemia  QT_arrhythmia  Hospitalization
AKI                       8.0           9.0            1.0             61.0
DILI                      2.0           1.0            0.0             22.0
Depression               11.0           8.0            0.0             39.0
Falls                    15.0          11.0            3.0            106.0
Delirium                  6.0           5.0            2.0             74.0
GI_bleeding               0.0           1.0            0.0              6.0
Hyponatremia            228.0           5.0            2.0             27.0
Hyperkalemia              5.0         181.0            0.0             21.0
QT_arrhythmia             2.0           0.0           41.0             10.0
Hospitalization          27.0          21.0           10.0            756.0