<a href="https://colab.research.google.com/github/MoniaO/GraphNeuralNetwork_Thesis/blob/task-a/notebooks/train_setup_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Klonowanie środowiska git

In [1]:
!git clone https://github.com/MoniaO/GraphNeuralNetwork_Thesis.git
%cd GraphNeuralNetwork_Thesis
!git checkout task-b #Marta task-a

Cloning into 'GraphNeuralNetwork_Thesis'...
remote: Enumerating objects: 689, done.
remote: Counting objects: 100% (103/103), done.
remote: Compressing objects: 100% (72/72), done.
remote: Total 689 (delta 56), reused 66 (delta 29), pack-reused 586 (from 1)
Receiving objects: 100% (689/689), 232.12 KiB | 12.90 MiB/s, done.
Resolving deltas: 100% (375/375), done.
/content/GraphNeuralNetwork_Thesis
Branch 'task-b' set up to track remote branch 'task-b' from 'origin'.
Switched to a new branch 'task-b'

In [2]:
!pip install wandb hydra-core omegaconf torch-geometric ogb

Requirement already satisfied: wandb in /usr/local/lib/python3.12/dist-packages (0.28.0)
Collecting hydra-core
  Downloading hydra_core-1.3.4-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: omegaconf in /usr/local/lib/python3.12/dist-packages (2.3.1)
Collecting torch-geometric
  Downloading torch_geometric-2.8.0.post1-py3-none-any.whl.metadata (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.4/64.4 kB 7.0 MB/s eta 0:00:00
Collecting ogb
  Downloading ogb-1.3.6-py3-none-any.whl.metadata (6.2 kB)
Requirement already satisfied: click>=8.2.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (8.4.2)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (3.1.51)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from wandb) (26.2)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from wandb) (4.10.0)
Requirement already satisfied: protobuf!=5.28.0,!=5.29.0,<8,>4.21.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (5.29.6)
Requirement already satisfied: pydantic<3,>=2.6 in /usr/local/lib/python3.12/dist-packages (from wandb) (2.13.4)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from wandb) (6.0.3)
Requirement already satisfied: requests<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (2.32.4)
Requirement already satisfied: sentry-sdk>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from wandb) (2.65.0)
Requirement already satisfied: typing-extensions<5,>=4.8 in /usr/local/lib/python3.12/dist-packages (from wandb) (4.16.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.12/dist-packages (from hydra-core) (4.9.3)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.14.1)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (2025.3.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.1.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (2.0.2)
Requirement already satisfied: psutil>=5.8.0 in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (5.9.5)
Requirement already satisfied: pyparsing in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.3.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from torch-geometric) (3.8.1)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from ogb) (2.11.0+cu128)
Requirement already satisfied: scikit-learn>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from ogb) (1.6.1)
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from ogb) (2.2.2)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from ogb) (1.17.0)
Requirement already satisfied: urllib3>=1.24.0 in /usr/local/lib/python3.12/dist-packages (from ogb) (2.5.0)
Collecting outdated>=0.2.0 (from ogb)
  Downloading outdated-0.2.2-py2.py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.29,>=1.0.0->wandb) (4.0.12)
Requirement already satisfied: setuptools>=44 in /usr/local/lib/python3.12/dist-packages (from outdated>=0.2.0->ogb) (75.2.0)
Collecting littleutils (from outdated>=0.2.0->ogb)
  Downloading littleutils-0.2.4-py3-none-any.whl.metadata (679 bytes)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->ogb) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->ogb) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->ogb) (2026.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.6->wandb) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.6->wandb) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.6->wandb) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.0.0->wandb) (2026.6.17)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.20.0->ogb) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.20.0->ogb) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.20.0->ogb) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (3.29.7)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (3.6.1)
Requirement already satisfied: cuda-toolkit==12.8.1 in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (12.8.1)
Requirement already satisfied: cuda-bindings<13,>=12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (12.9.7)
Requirement already satisfied: nvidia-cudnn-cu12==9.19.0.56 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (9.19.0.56)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.28.9 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (2.28.9)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (3.4.5)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.6.0->ogb) (3.6.0)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (12.8.4.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (12.8.90)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (11.3.3.83)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (1.13.1.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (12.8.90)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (12.5.8.93)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (12.8.93)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (12.8.93)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90.* in /usr/local/lib/python3.12/dist-packages (from cuda-toolkit[cublas,cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==12.8.1; platform_system == "Linux"->torch>=1.6.0->ogb) (12.8.90)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp->torch-geometric) (1.24.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch-geometric) (3.0.3)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings<13,>=12.9.4->torch>=1.6.0->ogb) (1.5.6)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb) (5.0.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.6.0->ogb) (1.3.0)
Downloading hydra_core-1.3.4-py3-none-any.whl (155 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.5/155.5 kB 16.7 MB/s eta 0:00:00
Downloading torch_geometric-2.8.0.post1-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 76.0 MB/s eta 0:00:00
Downloading ogb-1.3.6-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.8/78.8 kB 8.2 MB/s eta 0:00:00
Downloading outdated-0.2.2-py2.py3-none-any.whl (7.5 kB)
Downloading littleutils-0.2.4-py3-none-any.whl (8.1 kB)
Installing collected packages: littleutils, outdated, hydra-core, torch-geometric, ogb
Successfully installed hydra-core-1.3.4 littleutils-0.2.4 ogb-1.3.6 outdated-0.2.2 torch-geometric-2.8.0.post1

In [3]:
import os

In [4]:
import wandb
wandb.login(key="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")
#you can find your_key in W&B under User settings -> API key"

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: [wandb.login()] Using explicit session credentials for https://api.wandb.ai.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: oskardmonika (politechnika-gnn-thesis) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

In [5]:
wandb.login(verify=True)
#additional verification if login is successful - if everything's fine, it should return "True"

True

In [ ]:
#!git checkout src/data/load_data.py

In [12]:
!git pull origin task-b

remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0 (from 0)
Unpacking objects: 100% (4/4), 404 bytes | 404.00 KiB/s, done.
From https://github.com/MoniaO/GraphNeuralNetwork_Thesis
 * branch            task-b     -> FETCH_HEAD
   ce7a001..5868483  task-b     -> origin/task-b
Updating ce7a001..5868483
Fast-forward
 src/train_taskA.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

In [ ]:
#run for ogb dataset
#!python src/train.py model=gcn data=ogb_dataset

data:
  name: ogbl-ddi
  task_type: link_prediction
  metric: hits@20
  root: data/
  evaluator_type: ogb
model:
  name: gcn
  hidden_dim: 64
  num_layers: 3
  dropout: 0.2
  batch_norm: true
  activation: relu
training:
  lr: 0.001
  epochs: 20
  batch_size: 32
  optimizer: adam
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: oskardmonika (politechnika-gnn-thesis) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: ⢿ setting up run dj92bl5t (0.0s)
wandb: ⣻ setting up run dj92bl5t (0.0s)
wandb: ⣽ setting up run dj92bl5t (0.0s)
wandb: ⣾ setting up run dj92bl5t (0.0s)
wandb: ⣷ setting up run dj92bl5t (0.5s)
wandb: ⣯ setting up run dj92bl5t (0.5s)
wandb: ⣟ setting up run dj92bl5t (0.5s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260702_133719-dj92bl5t
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run gcn_ogbl-ddi_epochs20_lr0.001_adam
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/dj92bl5t
Epoch 001 | loss 1.3857 | train AUC 0.7009 | train AUPRC 0.6093 | valid AUC 0.7239 | valid AUPRC 0.6889valid hits@20 0.0000test AUC 0.7354 | test AUPRC 0.7008test hits@20 0.0000
Epoch 002 | loss 1.3844 | train AUC 0.7314 | train AUPRC 0.6388 | valid AUC 0.7545 | valid AUPRC 0.7181valid hits@20 0.0000test AUC 0.7641 | test AUPRC 0.7279test hits@20 0.0000
Epoch 003 | loss 1.3828 | train AUC 0.7563 | train AUPRC 0.6648 | valid AUC 0.7801 | valid AUPRC 0.7439valid hits@20 0.0000test AUC 0.7872 | test AUPRC 0.7514test hits@20 0.0000
Epoch 004 | loss 1.3809 | train AUC 0.7755 | train AUPRC 0.6862 | valid AUC 0.8001 | valid AUPRC 0.7653valid hits@20 0.0000test AUC 0.8050 | test AUPRC 0.7711test hits@20 0.0000
Epoch 005 | loss 1.3786 | train AUC 0.7899 | train AUPRC 0.7032 | valid AUC 0.8151 | valid AUPRC 0.7823valid hits@20 0.0000test AUC 0.8183 | test AUPRC 0.7873test hits@20 0.0000
Epoch 006 | loss 1.3759 | train AUC 0.8001 | train AUPRC 0.7162 | valid AUC 0.8262 | valid AUPRC 0.7957valid hits@20 0.0000test AUC 0.8284 | test AUPRC 0.8006test hits@20 0.0000
Epoch 007 | loss 1.3727 | train AUC 0.8081 | train AUPRC 0.7268 | valid AUC 0.8343 | valid AUPRC 0.8064valid hits@20 0.0000test AUC 0.8361 | test AUPRC 0.8113test hits@20 0.0000
Epoch 008 | loss 1.3688 | train AUC 0.8138 | train AUPRC 0.7352 | valid AUC 0.8402 | valid AUPRC 0.8151valid hits@20 0.0000test AUC 0.8420 | test AUPRC 0.8200test hits@20 0.0000
Epoch 009 | loss 1.3645 | train AUC 0.8177 | train AUPRC 0.7414 | valid AUC 0.8444 | valid AUPRC 0.8223valid hits@20 0.0000test AUC 0.8464 | test AUPRC 0.8274test hits@20 0.0000
Epoch 010 | loss 1.3593 | train AUC 0.8207 | train AUPRC 0.7478 | valid AUC 0.8471 | valid AUPRC 0.8284valid hits@20 0.0000test AUC 0.8498 | test AUPRC 0.8341test hits@20 0.0000
Epoch 011 | loss 1.3535 | train AUC 0.8223 | train AUPRC 0.7523 | valid AUC 0.8487 | valid AUPRC 0.8336valid hits@20 0.0000test AUC 0.8525 | test AUPRC 0.8401test hits@20 0.0000
Epoch 012 | loss 1.3470 | train AUC 0.8230 | train AUPRC 0.7565 | valid AUC 0.8494 | valid AUPRC 0.8383valid hits@20 0.0000test AUC 0.8547 | test AUPRC 0.8457test hits@20 0.0000
Epoch 013 | loss 1.3400 | train AUC 0.8237 | train AUPRC 0.7607 | valid AUC 0.8498 | valid AUPRC 0.8424valid hits@20 0.0000test AUC 0.8566 | test AUPRC 0.8510test hits@20 0.0000
Epoch 014 | loss 1.3326 | train AUC 0.8232 | train AUPRC 0.7624 | valid AUC 0.8499 | valid AUPRC 0.8463valid hits@20 0.0000test AUC 0.8583 | test AUPRC 0.8562test hits@20 0.0000
Epoch 015 | loss 1.3251 | train AUC 0.8239 | train AUPRC 0.7662 | valid AUC 0.8501 | valid AUPRC 0.8499valid hits@20 0.0000test AUC 0.8598 | test AUPRC 0.8610test hits@20 0.0000
Epoch 016 | loss 1.3178 | train AUC 0.8244 | train AUPRC 0.7696 | valid AUC 0.8503 | valid AUPRC 0.8532valid hits@20 0.0000test AUC 0.8612 | test AUPRC 0.8654test hits@20 0.0001
Epoch 017 | loss 1.3111 | train AUC 0.8247 | train AUPRC 0.7728 | valid AUC 0.8506 | valid AUPRC 0.8563valid hits@20 0.0000test AUC 0.8625 | test AUPRC 0.8694test hits@20 0.0001
Epoch 018 | loss 1.3050 | train AUC 0.8254 | train AUPRC 0.7751 | valid AUC 0.8511 | valid AUPRC 0.8592valid hits@20 0.0000test AUC 0.8637 | test AUPRC 0.8730test hits@20 0.0001
Epoch 019 | loss 1.2998 | train AUC 0.8254 | train AUPRC 0.7774 | valid AUC 0.8518 | valid AUPRC 0.8620valid hits@20 0.0000test AUC 0.8647 | test AUPRC 0.8762test hits@20 0.0001
Epoch 020 | loss 1.2962 | train AUC 0.8259 | train AUPRC 0.7793 | valid AUC 0.8527 | valid AUPRC 0.8647valid hits@20 0.0000test AUC 0.8656 | test AUPRC 0.8790test hits@20 0.0001
wandb: ⢿ updating run metadata (0.0s)
wandb: ⣻ updating run metadata (0.0s)
wandb: ⣽ updating run metadata (0.0s)
wandb: ⣾ updating run metadata (0.0s)
wandb: ⣷ Finishing up...
wandb: ⣯ Finishing up...
wandb: ⣟ Finishing up...
wandb: ⡿ Finishing up...
wandb: ⢿ Finishing up...
wandb: ⣻ uploading history steps 0-19, summary, console lines 1-19 (0.0s)
wandb: ⣽ uploading history steps 0-19, summary, console lines 1-19 (0.0s)
wandb: ⣾ uploading history steps 0-19, summary, console lines 1-19 (0.0s)
wandb: ⣷ uploading history steps 0-19, summary, console lines 1-19 (0.0s)
wandb: ⣯ uploading history steps 0-19, summary, console lines 1-19 (0.0s)
wandb:
wandb: Run history:
wandb:        epoch ▁▁▂▂▂▃▃▄▄▄▅▅▅▆▆▇▇▇██
wandb:         loss ████▇▇▇▇▆▆▅▅▄▄▃▃▂▂▁▁
wandb:           lr ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:     test/auc ▁▃▄▅▅▆▆▇▇▇▇▇████████
wandb:   test/auprc ▁▂▃▄▄▅▅▆▆▆▆▇▇▇▇▇████
wandb: test/hits@20 ▁▁▁▁▄▄▄▄▄▄▄▄▄▄▄▆▆▆▇█
wandb:    train/auc ▁▃▄▅▆▇▇▇████████████
wandb:  train/auprc ▁▂▃▄▅▅▆▆▆▇▇▇▇▇▇█████
wandb:    valid/auc ▁▃▄▅▆▇▇▇████████████
wandb:  valid/auprc ▁▂▃▄▅▅▆▆▆▇▇▇▇▇▇█████
wandb:           +1 ...
wandb:
wandb: Run summary:
wandb:   best_epoch 20
wandb:   best_valid 0.8647
wandb:        epoch 20
wandb:         loss 1.29616
wandb:           lr 0.001
wandb:     test/auc 0.86559
wandb:   test/auprc 0.87898
wandb: test/hits@20 7e-05
wandb:    train/auc 0.82588
wandb:  train/auprc 0.77931
wandb:           +3 ...
wandb:
wandb: 🚀 View run gcn_ogbl-ddi_epochs20_lr0.001_adam at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/dj92bl5t
wandb: ⭐️ View project at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260702_133719-dj92bl5t/logs

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
#data in MyDrive, to test if it works for Shared Drive
import os
os.environ["PHARMA_DATA_ROOT"] = "/content/drive/MyDrive/GSN Graphs dysertation 2026/2. Data/dataset_v2_2"

In [13]:
#Marta new codes: multirun run for hetero_sage (not multiple parameters, one target)
!python src/train_taskA.py --multirun model=TaskA_hetero_sage data=dataset_syn training.epochs=200 data.target="edge_label" model.num_layers=2,3,4

[2026-07-23 05:39:46,775][HYDRA] Launching 3 jobs locally
[2026-07-23 05:39:46,775][HYDRA] 	#0 : model=TaskA_hetero_sage data=dataset_syn training.epochs=200 data.target=edge_label model.num_layers=2
data:
  name: syn
  negative_ratio: 3
  edge_repeat: 1
  target: edge_label
  evaluator_type: synthetic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_2_edges_audited.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_2_samples_no_overlap.csv
      multihospital: synthetic_pharmacotherapy_v2_2_samples_multihospital.csv
      hidden: synthetic_pharmacotherapy_v2_2_samples_hidden_confounder.csv
      doc: synthetic_pharmacotherapy_v2_2_samples_noisy_documentation.csv
      bias: synthetic_pharmacotherapy_v2_2_samples_selection_bias.csv
    scenario: clean
model:
  name: hetero_sage
  conv_type: hetero_sage
  hidden_channels: 32
  num_layers: 2
training:
  lr: 0.001
  epochs: 200
  batch_size: 32
  optimizer: adam
  seed: 42
  eval_per_endpoint: true
  early_stopping_patience: 50
  early_stopping_min_delta: 0.0
  weight_decay: 0.0005
  oversmoothing_excluded_models:
  - linear
  auto_threshold: true
  eval_threshold: 0.5
  selection_metric: auprc
  track_oversmoothing: true
  oversmoothing_sample_size: 2000
  grad_clip: 0.0
meta:
  owner_initials: MO
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: oskardmonika (politechnika-gnn-thesis) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: ⢿ setting up run iyh5ea6s (0.0s)
wandb: ⣻ setting up run iyh5ea6s (0.0s)
wandb: ⣽ setting up run iyh5ea6s (0.0s)
wandb: ⣾ setting up run iyh5ea6s (0.0s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260723_053948-iyh5ea6s
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run MO_TaskA_hetero_sage__clean_ep200_lr0.001_layers2_hidden32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/iyh5ea6s
Epoch 001 | train loss 1.0177 | valid AUPRC 0.3524 | test AUPRC 0.4409 | valid AUC 0.6607 | test AUC 0.6863
Epoch 002 | train loss 0.9218 | valid AUPRC 0.3885 | test AUPRC 0.4991 | valid AUC 0.6800 | test AUC 0.7020
Epoch 003 | train loss 0.8836 | valid AUPRC 0.4140 | test AUPRC 0.5045 | valid AUC 0.6916 | test AUC 0.7015
Epoch 004 | train loss 0.8655 | valid AUPRC 0.4296 | test AUPRC 0.5050 | valid AUC 0.6935 | test AUC 0.6964
Epoch 005 | train loss 0.8247 | valid AUPRC 0.4336 | test AUPRC 0.5146 | valid AUC 0.6938 | test AUC 0.7032
Epoch 006 | train loss 0.8057 | valid AUPRC 0.4247 | test AUPRC 0.5349 | valid AUC 0.6914 | test AUC 0.7194
Epoch 007 | train loss 0.7613 | valid AUPRC 0.4238 | test AUPRC 0.5508 | valid AUC 0.6972 | test AUC 0.7259
Epoch 008 | train loss 0.7490 | valid AUPRC 0.4166 | test AUPRC 0.5486 | valid AUC 0.6988 | test AUC 0.7324
Epoch 009 | train loss 0.7157 | valid AUPRC 0.4068 | test AUPRC 0.5564 | valid AUC 0.7003 | test AUC 0.7367
Epoch 010 | train loss 0.6943 | valid AUPRC 0.4140 | test AUPRC 0.5645 | valid AUC 0.6993 | test AUC 0.7406
Epoch 011 | train loss 0.6507 | valid AUPRC 0.4323 | test AUPRC 0.5388 | valid AUC 0.7066 | test AUC 0.7389
Epoch 012 | train loss 0.6109 | valid AUPRC 0.4341 | test AUPRC 0.5314 | valid AUC 0.7107 | test AUC 0.7377
Epoch 013 | train loss 0.6071 | valid AUPRC 0.4399 | test AUPRC 0.5287 | valid AUC 0.7136 | test AUC 0.7360
Epoch 014 | train loss 0.5642 | valid AUPRC 0.4457 | test AUPRC 0.5241 | valid AUC 0.7194 | test AUC 0.7358
Epoch 015 | train loss 0.5717 | valid AUPRC 0.4458 | test AUPRC 0.5239 | valid AUC 0.7208 | test AUC 0.7365
Epoch 016 | train loss 0.5232 | valid AUPRC 0.4427 | test AUPRC 0.5279 | valid AUC 0.7201 | test AUC 0.7384
Epoch 017 | train loss 0.5151 | valid AUPRC 0.4442 | test AUPRC 0.5320 | valid AUC 0.7247 | test AUC 0.7379
Epoch 018 | train loss 0.4653 | valid AUPRC 0.4408 | test AUPRC 0.5289 | valid AUC 0.7215 | test AUC 0.7331
Epoch 019 | train loss 0.4488 | valid AUPRC 0.4441 | test AUPRC 0.5164 | valid AUC 0.7215 | test AUC 0.7222
Epoch 020 | train loss 0.4363 | valid AUPRC 0.4412 | test AUPRC 0.5148 | valid AUC 0.7157 | test AUC 0.7148
Epoch 021 | train loss 0.4362 | valid AUPRC 0.4533 | test AUPRC 0.5131 | valid AUC 0.7157 | test AUC 0.7116
Epoch 022 | train loss 0.4169 | valid AUPRC 0.4498 | test AUPRC 0.5134 | valid AUC 0.7167 | test AUC 0.7095
Epoch 023 | train loss 0.3741 | valid AUPRC 0.4431 | test AUPRC 0.5223 | valid AUC 0.7167 | test AUC 0.7049
Epoch 024 | train loss 0.3851 | valid AUPRC 0.4335 | test AUPRC 0.5192 | valid AUC 0.7121 | test AUC 0.6991
Epoch 025 | train loss 0.3556 | valid AUPRC 0.4284 | test AUPRC 0.5110 | valid AUC 0.7056 | test AUC 0.6931
Epoch 026 | train loss 0.3495 | valid AUPRC 0.4266 | test AUPRC 0.5102 | valid AUC 0.7034 | test AUC 0.6904
Epoch 027 | train loss 0.3344 | valid AUPRC 0.4238 | test AUPRC 0.5103 | valid AUC 0.7022 | test AUC 0.6947
Epoch 028 | train loss 0.2900 | valid AUPRC 0.4295 | test AUPRC 0.4996 | valid AUC 0.7027 | test AUC 0.6974
Epoch 029 | train loss 0.2928 | valid AUPRC 0.4210 | test AUPRC 0.4907 | valid AUC 0.7039 | test AUC 0.6979
Epoch 030 | train loss 0.2785 | valid AUPRC 0.4200 | test AUPRC 0.4964 | valid AUC 0.7020 | test AUC 0.6984
Epoch 031 | train loss 0.2539 | valid AUPRC 0.4178 | test AUPRC 0.4950 | valid AUC 0.6979 | test AUC 0.6957
Epoch 032 | train loss 0.2595 | valid AUPRC 0.4309 | test AUPRC 0.5081 | valid AUC 0.6988 | test AUC 0.6988
Epoch 033 | train loss 0.2503 | valid AUPRC 0.4333 | test AUPRC 0.5159 | valid AUC 0.7029 | test AUC 0.7017
Epoch 034 | train loss 0.2397 | valid AUPRC 0.4399 | test AUPRC 0.5180 | valid AUC 0.7051 | test AUC 0.7032
Epoch 035 | train loss 0.2256 | valid AUPRC 0.4425 | test AUPRC 0.5224 | valid AUC 0.7140 | test AUC 0.7075
Epoch 036 | train loss 0.2202 | valid AUPRC 0.4439 | test AUPRC 0.5261 | valid AUC 0.7157 | test AUC 0.7090
Epoch 037 | train loss 0.2105 | valid AUPRC 0.4448 | test AUPRC 0.5282 | valid AUC 0.7131 | test AUC 0.7116
Epoch 038 | train loss 0.2081 | valid AUPRC 0.4386 | test AUPRC 0.5282 | valid AUC 0.7107 | test AUC 0.7140
Epoch 039 | train loss 0.1756 | valid AUPRC 0.4538 | test AUPRC 0.5314 | valid AUC 0.7080 | test AUC 0.7143
Epoch 040 | train loss 0.1715 | valid AUPRC 0.4332 | test AUPRC 0.5294 | valid AUC 0.6988 | test AUC 0.7114
Epoch 041 | train loss 0.1909 | valid AUPRC 0.4287 | test AUPRC 0.5209 | valid AUC 0.6969 | test AUC 0.7090
Epoch 042 | train loss 0.1699 | valid AUPRC 0.4260 | test AUPRC 0.5359 | valid AUC 0.6986 | test AUC 0.7085
Epoch 043 | train loss 0.1570 | valid AUPRC 0.4239 | test AUPRC 0.5336 | valid AUC 0.6998 | test AUC 0.7090
Epoch 044 | train loss 0.1529 | valid AUPRC 0.4257 | test AUPRC 0.5297 | valid AUC 0.7003 | test AUC 0.7078
Epoch 045 | train loss 0.1551 | valid AUPRC 0.4222 | test AUPRC 0.5180 | valid AUC 0.6996 | test AUC 0.7068
Epoch 046 | train loss 0.1486 | valid AUPRC 0.4212 | test AUPRC 0.5152 | valid AUC 0.7005 | test AUC 0.7037
Epoch 047 | train loss 0.1273 | valid AUPRC 0.4383 | test AUPRC 0.5239 | valid AUC 0.7003 | test AUC 0.7017
Epoch 048 | train loss 0.1256 | valid AUPRC 0.4365 | test AUPRC 0.5232 | valid AUC 0.7013 | test AUC 0.6998
Epoch 049 | train loss 0.1308 | valid AUPRC 0.4349 | test AUPRC 0.5145 | valid AUC 0.6998 | test AUC 0.6959
Epoch 050 | train loss 0.1104 | valid AUPRC 0.4358 | test AUPRC 0.5071 | valid AUC 0.6974 | test AUC 0.6940
Epoch 051 | train loss 0.1131 | valid AUPRC 0.4303 | test AUPRC 0.5092 | valid AUC 0.6959 | test AUC 0.6984
Epoch 052 | train loss 0.1287 | valid AUPRC 0.4293 | test AUPRC 0.5086 | valid AUC 0.6976 | test AUC 0.6988
Epoch 053 | train loss 0.1062 | valid AUPRC 0.4353 | test AUPRC 0.5088 | valid AUC 0.7015 | test AUC 0.6959
Epoch 054 | train loss 0.0962 | valid AUPRC 0.4315 | test AUPRC 0.5097 | valid AUC 0.6993 | test AUC 0.6906
Epoch 055 | train loss 0.1055 | valid AUPRC 0.4410 | test AUPRC 0.5224 | valid AUC 0.6967 | test AUC 0.6926
Epoch 056 | train loss 0.0956 | valid AUPRC 0.4439 | test AUPRC 0.5268 | valid AUC 0.6943 | test AUC 0.6969
Epoch 057 | train loss 0.1284 | valid AUPRC 0.4387 | test AUPRC 0.5037 | valid AUC 0.6976 | test AUC 0.7086
Epoch 058 | train loss 0.0879 | valid AUPRC 0.4258 | test AUPRC 0.4993 | valid AUC 0.7035 | test AUC 0.7122
Epoch 059 | train loss 0.0668 | valid AUPRC 0.4194 | test AUPRC 0.5034 | valid AUC 0.7051 | test AUC 0.7149
Epoch 060 | train loss 0.0814 | valid AUPRC 0.4258 | test AUPRC 0.5162 | valid AUC 0.7090 | test AUC 0.7185
Epoch 061 | train loss 0.0784 | valid AUPRC 0.4235 | test AUPRC 0.5271 | valid AUC 0.7054 | test AUC 0.7171
Epoch 062 | train loss 0.0740 | valid AUPRC 0.4235 | test AUPRC 0.5343 | valid AUC 0.7002 | test AUC 0.7139
Epoch 063 | train loss 0.0817 | valid AUPRC 0.4249 | test AUPRC 0.5371 | valid AUC 0.6992 | test AUC 0.7159
Epoch 064 | train loss 0.0917 | valid AUPRC 0.4246 | test AUPRC 0.5266 | valid AUC 0.7021 | test AUC 0.7157
Epoch 065 | train loss 0.0569 | valid AUPRC 0.4218 | test AUPRC 0.5109 | valid AUC 0.7025 | test AUC 0.7128
Epoch 066 | train loss 0.0586 | valid AUPRC 0.4211 | test AUPRC 0.5034 | valid AUC 0.6996 | test AUC 0.7124
Epoch 067 | train loss 0.0560 | valid AUPRC 0.4181 | test AUPRC 0.4993 | valid AUC 0.6945 | test AUC 0.7073
Epoch 068 | train loss 0.0646 | valid AUPRC 0.4193 | test AUPRC 0.5039 | valid AUC 0.6911 | test AUC 0.7067
Epoch 069 | train loss 0.0474 | valid AUPRC 0.4270 | test AUPRC 0.5254 | valid AUC 0.6915 | test AUC 0.7075
Epoch 070 | train loss 0.0724 | valid AUPRC 0.4398 | test AUPRC 0.5388 | valid AUC 0.6923 | test AUC 0.7080
Epoch 071 | train loss 0.0531 | valid AUPRC 0.4292 | test AUPRC 0.5379 | valid AUC 0.6904 | test AUC 0.7092
Epoch 072 | train loss 0.0572 | valid AUPRC 0.4259 | test AUPRC 0.5276 | valid AUC 0.6918 | test AUC 0.7063
Epoch 073 | train loss 0.0479 | valid AUPRC 0.4222 | test AUPRC 0.5224 | valid AUC 0.6899 | test AUC 0.7051
Epoch 074 | train loss 0.0502 | valid AUPRC 0.4184 | test AUPRC 0.5186 | valid AUC 0.6875 | test AUC 0.7029
Epoch 075 | train loss 0.0526 | valid AUPRC 0.4130 | test AUPRC 0.5212 | valid AUC 0.6865 | test AUC 0.7025
Epoch 076 | train loss 0.0429 | valid AUPRC 0.4179 | test AUPRC 0.5292 | valid AUC 0.6880 | test AUC 0.7015
Epoch 077 | train loss 0.0369 | valid AUPRC 0.4208 | test AUPRC 0.5433 | valid AUC 0.6889 | test AUC 0.7005
Epoch 078 | train loss 0.0507 | valid AUPRC 0.4239 | test AUPRC 0.5287 | valid AUC 0.6914 | test AUC 0.6972
Epoch 079 | train loss 0.0489 | valid AUPRC 0.4294 | test AUPRC 0.5319 | valid AUC 0.6976 | test AUC 0.6970
Epoch 080 | train loss 0.0276 | valid AUPRC 0.4330 | test AUPRC 0.5173 | valid AUC 0.7003 | test AUC 0.6952
Epoch 081 | train loss 0.0354 | valid AUPRC 0.4229 | test AUPRC 0.5183 | valid AUC 0.7034 | test AUC 0.6940
Epoch 082 | train loss 0.0384 | valid AUPRC 0.4195 | test AUPRC 0.5233 | valid AUC 0.7043 | test AUC 0.6964
Epoch 083 | train loss 0.0321 | valid AUPRC 0.4231 | test AUPRC 0.5256 | valid AUC 0.7060 | test AUC 0.6981
Epoch 084 | train loss 0.0367 | valid AUPRC 0.4261 | test AUPRC 0.5289 | valid AUC 0.7069 | test AUC 0.6979
Epoch 085 | train loss 0.0246 | valid AUPRC 0.4287 | test AUPRC 0.5235 | valid AUC 0.7079 | test AUC 0.6973
Epoch 086 | train loss 0.0283 | valid AUPRC 0.4299 | test AUPRC 0.5152 | valid AUC 0.7091 | test AUC 0.6945
Epoch 087 | train loss 0.0313 | valid AUPRC 0.4258 | test AUPRC 0.5158 | valid AUC 0.7081 | test AUC 0.6952
Epoch 088 | train loss 0.0310 | valid AUPRC 0.4240 | test AUPRC 0.5149 | valid AUC 0.7101 | test AUC 0.6959
Epoch 089 | train loss 0.0211 | valid AUPRC 0.4213 | test AUPRC 0.5181 | valid AUC 0.7084 | test AUC 0.6950
Early stopping at epoch 89: no improvement in valid/auprc for 50 epochs.
wandb: ⢿ updating run metadata (0.1s)
wandb: ⣻ updating run metadata (0.1s)
wandb: ⣽ updating run metadata (0.1s)
wandb: ⣾ updating run metadata (0.1s)
wandb: ⣷ Finishing up...
wandb: ⣯ Finishing up...
wandb: ⣟ Finishing up...
wandb: ⡿ Finishing up...
wandb: ⢿ Finishing up...
wandb: ⣻ uploading output.log 9.5KB/9.5KB (0.3s)
wandb: ⣻ uploading wandb-summary.json 6.9KB/6.9KB (0.3s)
wandb: ⣻ uploading config.yaml 4.0KB/4.0KB (0.3s)
wandb: ⣽ uploading output.log 9.5KB/9.5KB (0.3s)
wandb: ⣽ uploading wandb-summary.json 6.9KB/6.9KB (0.3s)
wandb: ⣽ uploading config.yaml 4.0KB/4.0KB (0.3s)
wandb: ⣾ uploading output.log 9.5KB/9.5KB (0.3s)
wandb: ⣾ uploading wandb-summary.json 6.9KB/6.9KB (0.3s)
wandb: ⣾ uploading config.yaml 4.0KB/4.0KB (0.3s)
wandb: ⣷ uploading output.log 9.5KB/9.5KB (0.3s)
wandb: ⣷ uploading wandb-summary.json 6.9KB/6.9KB (0.3s)
wandb: ⣷ uploading config.yaml 4.0KB/4.0KB (0.3s)
wandb: ⣯ uploading output.log 9.5KB/9.5KB (0.3s)
wandb: ⣯ uploading wandb-summary.json 6.9KB/6.9KB (0.3s)
wandb: ⣯ uploading config.yaml 4.0KB/4.0KB (0.3s)
wandb: ⣟ uploading history steps 84-88, summary, console lines 85-89 (0.2s)
wandb: ⡿ uploading history steps 84-88, summary, console lines 85-89 (0.2s)
wandb: ⢿ uploading history steps 84-88, summary, console lines 85-89 (0.2s)
wandb: ⣻ uploading history steps 84-88, summary, console lines 85-89 (0.2s)
wandb: ⣽ uploading history steps 84-88, summary, console lines 85-89 (0.2s)
wandb: ⣾ uploading history steps 84-88, summary, console lines 85-89 (0.7s)
wandb: ⣷ uploading history steps 84-88, summary, console lines 85-89 (0.7s)
wandb: ⣯ uploading history steps 84-88, summary, console lines 85-89 (0.7s)
wandb: ⣟ uploading history steps 84-88, summary, console lines 85-89 (0.7s)
wandb: ⡿ uploading history steps 84-88, summary, console lines 85-89 (0.7s)
wandb: ⢿ uploading history steps 84-88, summary, console lines 85-89 (1.2s)
wandb: ⣻ uploading history steps 84-88, summary, console lines 85-89 (1.2s)
wandb: ⣽ uploading history steps 84-88, summary, console lines 85-89 (1.2s)
wandb: ⣾ uploading history steps 84-88, summary, console lines 85-89 (1.2s)
wandb: ⣷ uploading history steps 84-88, summary, console lines 85-89 (1.2s)
wandb: ⣯ uploading history steps 84-88, summary, console lines 85-89 (1.7s)
wandb: ⣟ uploading history steps 84-88, summary, console lines 85-89 (1.7s)
wandb: ⡿ uploading history steps 84-88, summary, console lines 85-89 (1.7s)
wandb: ⢿ uploading history steps 84-88, summary, console lines 85-89 (1.7s)
wandb: ⣻ uploading history steps 84-88, summary, console lines 85-89 (1.7s)
wandb: ⣽ uploading history steps 84-88, summary, console lines 85-89 (2.2s)
wandb: ⣾ uploading history steps 84-88, summary, console lines 85-89 (2.2s)
wandb: ⣷ uploading history steps 84-88, summary, console lines 85-89 (2.2s)
wandb: ⣯ uploading history steps 84-88, summary, console lines 85-89 (2.2s)
wandb: ⣟ uploading history steps 84-88, summary, console lines 85-89 (2.2s)
wandb: ⡿ uploading history steps 84-88, summary, console lines 85-89 (2.7s)
wandb: ⢿ uploading history steps 84-88, summary, console lines 85-89 (2.7s)
wandb: ⣻ uploading history steps 84-88, summary, console lines 85-89 (2.7s)
wandb: ⣽ uploading history steps 84-88, summary, console lines 85-89 (2.7s)
wandb: ⣾ uploading history steps 84-88, summary, console lines 85-89 (2.7s)
wandb: ⣷ uploading history steps 84-88, summary, console lines 85-89 (3.2s)
wandb: ⣯ uploading history steps 84-88, summary, console lines 85-89 (3.2s)
wandb: ⣟ uploading history steps 84-88, summary, console lines 85-89 (3.2s)
wandb: ⡿ uploading history steps 84-88, summary, console lines 85-89 (3.2s)
wandb: ⢿ uploading history steps 84-88, summary, console lines 85-89 (3.2s)
wandb: ⣻ uploading history steps 84-88, summary, console lines 85-89 (3.7s)
wandb: ⣽ uploading history steps 84-88, summary, console lines 85-89 (3.7s)
wandb: ⣾ uploading history steps 84-88, summary, console lines 85-89 (3.7s)
wandb: ⣷ uploading history steps 84-88, summary, console lines 85-89 (3.7s)
wandb: ⣯ uploading history steps 84-88, summary, console lines 85-89 (3.7s)
wandb: ⣟ uploading history steps 84-88, summary, console lines 85-89 (4.2s)
wandb: ⡿ uploading history steps 84-88, summary, console lines 85-89 (4.2s)
wandb: ⢿ uploading history steps 84-88, summary, console lines 85-89 (4.2s)
wandb: ⣻ uploading history steps 84-88, summary, console lines 85-89 (4.2s)
wandb: ⣽ uploading history steps 84-88, summary, console lines 85-89 (4.2s)
wandb: ⣾ uploading history steps 84-88, summary, console lines 85-89 (4.7s)
wandb: ⣷ uploading history steps 84-88, summary, console lines 85-89 (4.7s)
wandb: ⣯ uploading history steps 84-88, summary, console lines 85-89 (4.7s)
wandb: ⣟ uploading history steps 84-88, summary, console lines 85-89 (4.7s)
wandb: ⡿ uploading history steps 84-88, summary, console lines 85-89 (4.7s)
wandb: ⢿ uploading history steps 84-88, summary, console lines 85-89 (5.2s)
wandb: ⣻ uploading history steps 84-88, summary, console lines 85-89 (5.2s)
wandb: ⣽ uploading history steps 84-88, summary, console lines 85-89 (5.2s)
wandb: ⣾ uploading history steps 84-88, summary, console lines 85-89 (5.2s)
wandb: ⣷ uploading history steps 84-88, summary, console lines 85-89 (5.2s)
wandb: ⣯ uploading history steps 84-88, summary, console lines 85-89 (5.7s)
wandb: ⣟ uploading history steps 84-88, summary, console lines 85-89 (5.7s)
wandb: ⡿ uploading history steps 84-88, summary, console lines 85-89 (5.7s)
wandb: ⢿ uploading history steps 84-88, summary, console lines 85-89 (5.7s)
wandb: ⣻ uploading history steps 84-88, summary, console lines 85-89 (5.7s)
wandb: ⣽ uploading history steps 84-88, summary, console lines 85-89 (6.2s)
wandb: ⣾ uploading history steps 84-88, summary, console lines 85-89 (6.2s)
wandb: ⣷ uploading history steps 84-88, summary, console lines 85-89 (6.2s)
wandb: ⣯ uploading history steps 84-88, summary, console lines 85-89 (6.2s)
wandb: ⣟ uploading history steps 84-88, summary, console lines 85-89 (6.2s)
wandb: ⡿ uploading history steps 84-88, summary, console lines 85-89 (6.7s)
wandb: ⢿ uploading history steps 84-88, summary, console lines 85-89 (6.7s)
wandb: ⣻ uploading history steps 84-88, summary, console lines 85-89 (6.7s)
wandb: ⣽ uploading history steps 84-88, summary, console lines 85-89 (6.7s)
wandb: ⣾ uploading history steps 84-88, summary, console lines 85-89 (6.7s)
wandb: ⣷ uploading history steps 84-88, summary, console lines 85-89 (7.2s)
wandb: ⣯ uploading history steps 84-88, summary, console lines 85-89 (7.2s)
wandb: ⣟ uploading history steps 84-88, summary, console lines 85-89 (7.2s)
wandb: ⡿ uploading history steps 84-88, summary, console lines 85-89 (7.2s)
wandb: ⢿ uploading history steps 84-88, summary, console lines 85-89 (7.2s)
wandb: ⣻ uploading history steps 84-88, summary, console lines 85-89 (7.7s)
wandb: ⣽ uploading history steps 84-88, summary, console lines 85-89 (7.7s)
wandb: ⣾ uploading history steps 84-88, summary, console lines 85-89 (7.7s)
wandb: ⣷ uploading history steps 84-88, summary, console lines 85-89 (7.7s)
wandb: ⣯ uploading history steps 84-88, summary, console lines 85-89 (7.7s)
wandb: ⣟ uploading history steps 84-88, summary, console lines 85-89 (8.2s)
wandb: ⡿ uploading history steps 84-88, summary, console lines 85-89 (8.2s)
wandb: ⢿ uploading history steps 84-88, summary, console lines 85-89 (8.2s)
wandb: ⣻ uploading history steps 84-88, summary, console lines 85-89 (8.2s)
wandb: ⣽ uploading history steps 84-88, summary, console lines 85-89 (8.2s)
wandb: ⣾ uploading history steps 84-88, summary, console lines 85-89 (8.7s)
wandb: ⣷ uploading history steps 84-88, summary, console lines 85-89 (8.7s)
wandb: ⣯ uploading history steps 84-88, summary, console lines 85-89 (8.7s)
wandb: ⣟ uploading history steps 84-88, summary, console lines 85-89 (8.7s)

In [14]:
#Marta new codes: multirun run for rgcn (not multiple parameters, one target)
!python src/train_taskA.py --multirun model=TaskA_rgcn data=dataset_syn training.epochs=200 data.target="edge_label" model.num_layers=2,3,4

[2026-07-23 05:47:17,399][HYDRA] Launching 3 jobs locally
[2026-07-23 05:47:17,399][HYDRA] 	#0 : model=TaskA_rgcn data=dataset_syn training.epochs=200 data.target=edge_label model.num_layers=2
data:
  name: syn
  negative_ratio: 3
  edge_repeat: 1
  target: edge_label
  evaluator_type: synthetic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_2_edges_audited.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_2_samples_no_overlap.csv
      multihospital: synthetic_pharmacotherapy_v2_2_samples_multihospital.csv
      hidden: synthetic_pharmacotherapy_v2_2_samples_hidden_confounder.csv
      doc: synthetic_pharmacotherapy_v2_2_samples_noisy_documentation.csv
      bias: synthetic_pharmacotherapy_v2_2_samples_selection_bias.csv
    scenario: clean
model:
  name: rgcn
  conv_type: rgcn
  hidden_channels: 32
  num_layers: 2
  num_bases: 8
training:
  lr: 0.001
  epochs: 200
  batch_size: 32
  optimizer: adam
  seed: 42
  eval_per_endpoint: true
  early_stopping_patience: 50
  early_stopping_min_delta: 0.0
  weight_decay: 0.0005
  oversmoothing_excluded_models:
  - linear
  auto_threshold: true
  eval_threshold: 0.5
  selection_metric: auprc
  track_oversmoothing: true
  oversmoothing_sample_size: 2000
  grad_clip: 0.0
meta:
  owner_initials: MO
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: oskardmonika (politechnika-gnn-thesis) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: ⢿ setting up run em65lc7w (0.0s)
wandb: ⣻ setting up run em65lc7w (0.0s)
wandb: ⣽ setting up run em65lc7w (0.0s)
wandb: ⣾ setting up run em65lc7w (0.0s)
wandb: ⣷ setting up run em65lc7w (0.5s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260723_054718-em65lc7w
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run MO_TaskA_rgcn__clean_ep200_lr0.001_layers2_hidden32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/em65lc7w
Epoch 001 | train loss 1.0630 | valid AUPRC 0.2499 | test AUPRC 0.2455 | valid AUC 0.4348 | test AUC 0.4720
Epoch 002 | train loss 1.0536 | valid AUPRC 0.2485 | test AUPRC 0.2542 | valid AUC 0.4626 | test AUC 0.5060
Epoch 003 | train loss 1.0460 | valid AUPRC 0.2686 | test AUPRC 0.2766 | valid AUC 0.4870 | test AUC 0.5475
Epoch 004 | train loss 1.0387 | valid AUPRC 0.2951 | test AUPRC 0.3316 | valid AUC 0.5065 | test AUC 0.5878
Epoch 005 | train loss 1.0252 | valid AUPRC 0.3129 | test AUPRC 0.3657 | valid AUC 0.5212 | test AUC 0.6086
Epoch 006 | train loss 1.0240 | valid AUPRC 0.3349 | test AUPRC 0.3837 | valid AUC 0.5468 | test AUC 0.6076
Epoch 007 | train loss 1.0191 | valid AUPRC 0.3401 | test AUPRC 0.3953 | valid AUC 0.5615 | test AUC 0.6137
Epoch 008 | train loss 1.0122 | valid AUPRC 0.3471 | test AUPRC 0.4147 | valid AUC 0.5767 | test AUC 0.6166
Epoch 009 | train loss 1.0060 | valid AUPRC 0.3561 | test AUPRC 0.4496 | valid AUC 0.5922 | test AUC 0.6175
Epoch 010 | train loss 0.9968 | valid AUPRC 0.3597 | test AUPRC 0.4620 | valid AUC 0.6014 | test AUC 0.6185
Epoch 011 | train loss 0.9920 | valid AUPRC 0.3630 | test AUPRC 0.4686 | valid AUC 0.6091 | test AUC 0.6187
Epoch 012 | train loss 0.9873 | valid AUPRC 0.3653 | test AUPRC 0.4762 | valid AUC 0.6108 | test AUC 0.6185
Epoch 013 | train loss 0.9792 | valid AUPRC 0.3660 | test AUPRC 0.4893 | valid AUC 0.6100 | test AUC 0.6187
Epoch 014 | train loss 0.9612 | valid AUPRC 0.3711 | test AUPRC 0.4915 | valid AUC 0.6141 | test AUC 0.6180
Epoch 015 | train loss 0.9610 | valid AUPRC 0.3769 | test AUPRC 0.4945 | valid AUC 0.6156 | test AUC 0.6207
Epoch 016 | train loss 0.9533 | valid AUPRC 0.3790 | test AUPRC 0.4967 | valid AUC 0.6156 | test AUC 0.6233
Epoch 017 | train loss 0.9444 | valid AUPRC 0.3827 | test AUPRC 0.4988 | valid AUC 0.6166 | test AUC 0.6250
Epoch 018 | train loss 0.9400 | valid AUPRC 0.3849 | test AUPRC 0.5082 | valid AUC 0.6180 | test AUC 0.6260
Epoch 019 | train loss 0.9276 | valid AUPRC 0.3882 | test AUPRC 0.5090 | valid AUC 0.6194 | test AUC 0.6274
Epoch 020 | train loss 0.9154 | valid AUPRC 0.3916 | test AUPRC 0.5064 | valid AUC 0.6209 | test AUC 0.6269
Epoch 021 | train loss 0.9060 | valid AUPRC 0.3963 | test AUPRC 0.5057 | valid AUC 0.6223 | test AUC 0.6257
Epoch 022 | train loss 0.8887 | valid AUPRC 0.4003 | test AUPRC 0.5103 | valid AUC 0.6243 | test AUC 0.6260
Epoch 023 | train loss 0.8743 | valid AUPRC 0.4054 | test AUPRC 0.5131 | valid AUC 0.6274 | test AUC 0.6260
Epoch 024 | train loss 0.8694 | valid AUPRC 0.4072 | test AUPRC 0.5116 | valid AUC 0.6286 | test AUC 0.6260
Epoch 025 | train loss 0.8569 | valid AUPRC 0.4144 | test AUPRC 0.5132 | valid AUC 0.6298 | test AUC 0.6301
Epoch 026 | train loss 0.8417 | valid AUPRC 0.4159 | test AUPRC 0.5135 | valid AUC 0.6306 | test AUC 0.6325
Epoch 027 | train loss 0.8347 | valid AUPRC 0.4209 | test AUPRC 0.5192 | valid AUC 0.6356 | test AUC 0.6349
Epoch 028 | train loss 0.8080 | valid AUPRC 0.4275 | test AUPRC 0.5202 | valid AUC 0.6371 | test AUC 0.6373
Epoch 029 | train loss 0.8077 | valid AUPRC 0.4310 | test AUPRC 0.5179 | valid AUC 0.6404 | test AUC 0.6368
Epoch 030 | train loss 0.7814 | valid AUPRC 0.4340 | test AUPRC 0.5166 | valid AUC 0.6417 | test AUC 0.6390
Epoch 031 | train loss 0.7718 | valid AUPRC 0.4365 | test AUPRC 0.5215 | valid AUC 0.6424 | test AUC 0.6419
Epoch 032 | train loss 0.7606 | valid AUPRC 0.4352 | test AUPRC 0.5242 | valid AUC 0.6429 | test AUC 0.6429
Epoch 033 | train loss 0.7447 | valid AUPRC 0.4410 | test AUPRC 0.5200 | valid AUC 0.6443 | test AUC 0.6417
Epoch 034 | train loss 0.7385 | valid AUPRC 0.4433 | test AUPRC 0.5188 | valid AUC 0.6436 | test AUC 0.6417
Epoch 035 | train loss 0.7147 | valid AUPRC 0.4450 | test AUPRC 0.5153 | valid AUC 0.6417 | test AUC 0.6400
Epoch 036 | train loss 0.7075 | valid AUPRC 0.4467 | test AUPRC 0.5139 | valid AUC 0.6412 | test AUC 0.6380
Epoch 037 | train loss 0.6872 | valid AUPRC 0.4430 | test AUPRC 0.5144 | valid AUC 0.6400 | test AUC 0.6347
Epoch 038 | train loss 0.6822 | valid AUPRC 0.4386 | test AUPRC 0.5159 | valid AUC 0.6397 | test AUC 0.6359
Epoch 039 | train loss 0.6613 | valid AUPRC 0.4399 | test AUPRC 0.5139 | valid AUC 0.6375 | test AUC 0.6351
Epoch 040 | train loss 0.6477 | valid AUPRC 0.4403 | test AUPRC 0.5157 | valid AUC 0.6342 | test AUC 0.6378
Epoch 041 | train loss 0.6325 | valid AUPRC 0.4369 | test AUPRC 0.5107 | valid AUC 0.6332 | test AUC 0.6400
Epoch 042 | train loss 0.6287 | valid AUPRC 0.4355 | test AUPRC 0.5141 | valid AUC 0.6298 | test AUC 0.6395
Epoch 043 | train loss 0.6101 | valid AUPRC 0.4286 | test AUPRC 0.5094 | valid AUC 0.6274 | test AUC 0.6397
Epoch 044 | train loss 0.6006 | valid AUPRC 0.4282 | test AUPRC 0.5086 | valid AUC 0.6274 | test AUC 0.6371
Epoch 045 | train loss 0.5849 | valid AUPRC 0.4287 | test AUPRC 0.5128 | valid AUC 0.6250 | test AUC 0.6375
Epoch 046 | train loss 0.5734 | valid AUPRC 0.4221 | test AUPRC 0.5077 | valid AUC 0.6219 | test AUC 0.6363
Epoch 047 | train loss 0.5473 | valid AUPRC 0.4341 | test AUPRC 0.4984 | valid AUC 0.6216 | test AUC 0.6356
Epoch 048 | train loss 0.5227 | valid AUPRC 0.4279 | test AUPRC 0.4949 | valid AUC 0.6209 | test AUC 0.6344
Epoch 049 | train loss 0.5290 | valid AUPRC 0.4329 | test AUPRC 0.4944 | valid AUC 0.6204 | test AUC 0.6347
Epoch 050 | train loss 0.5173 | valid AUPRC 0.4285 | test AUPRC 0.4949 | valid AUC 0.6175 | test AUC 0.6347
Epoch 051 | train loss 0.4893 | valid AUPRC 0.4275 | test AUPRC 0.4935 | valid AUC 0.6190 | test AUC 0.6342
Epoch 052 | train loss 0.4814 | valid AUPRC 0.4332 | test AUPRC 0.4874 | valid AUC 0.6187 | test AUC 0.6371
Epoch 053 | train loss 0.4597 | valid AUPRC 0.4317 | test AUPRC 0.4878 | valid AUC 0.6180 | test AUC 0.6392
Epoch 054 | train loss 0.4595 | valid AUPRC 0.4291 | test AUPRC 0.4913 | valid AUC 0.6197 | test AUC 0.6419
Epoch 055 | train loss 0.4515 | valid AUPRC 0.4330 | test AUPRC 0.4788 | valid AUC 0.6219 | test AUC 0.6450
Epoch 056 | train loss 0.4164 | valid AUPRC 0.4333 | test AUPRC 0.4780 | valid AUC 0.6219 | test AUC 0.6482
Epoch 057 | train loss 0.4132 | valid AUPRC 0.4374 | test AUPRC 0.4751 | valid AUC 0.6243 | test AUC 0.6482
Epoch 058 | train loss 0.4041 | valid AUPRC 0.4359 | test AUPRC 0.4736 | valid AUC 0.6250 | test AUC 0.6513
Epoch 059 | train loss 0.3964 | valid AUPRC 0.4340 | test AUPRC 0.4664 | valid AUC 0.6277 | test AUC 0.6532
Epoch 060 | train loss 0.3622 | valid AUPRC 0.4313 | test AUPRC 0.4682 | valid AUC 0.6277 | test AUC 0.6540
Epoch 061 | train loss 0.3611 | valid AUPRC 0.4277 | test AUPRC 0.4683 | valid AUC 0.6296 | test AUC 0.6559
Epoch 062 | train loss 0.3366 | valid AUPRC 0.4274 | test AUPRC 0.4706 | valid AUC 0.6310 | test AUC 0.6566
Epoch 063 | train loss 0.3288 | valid AUPRC 0.4320 | test AUPRC 0.4724 | valid AUC 0.6334 | test AUC 0.6612
Epoch 064 | train loss 0.3231 | valid AUPRC 0.4349 | test AUPRC 0.4745 | valid AUC 0.6371 | test AUC 0.6655
Epoch 065 | train loss 0.2997 | valid AUPRC 0.4294 | test AUPRC 0.4758 | valid AUC 0.6395 | test AUC 0.6667
Epoch 066 | train loss 0.2974 | valid AUPRC 0.4257 | test AUPRC 0.4755 | valid AUC 0.6419 | test AUC 0.6651
Epoch 067 | train loss 0.2762 | valid AUPRC 0.4222 | test AUPRC 0.4785 | valid AUC 0.6424 | test AUC 0.6665
Epoch 068 | train loss 0.2753 | valid AUPRC 0.4102 | test AUPRC 0.4698 | valid AUC 0.6431 | test AUC 0.6665
Epoch 069 | train loss 0.2519 | valid AUPRC 0.4163 | test AUPRC 0.4694 | valid AUC 0.6443 | test AUC 0.6675
Epoch 070 | train loss 0.2421 | valid AUPRC 0.4183 | test AUPRC 0.4671 | valid AUC 0.6465 | test AUC 0.6663
Epoch 071 | train loss 0.2532 | valid AUPRC 0.4132 | test AUPRC 0.4629 | valid AUC 0.6462 | test AUC 0.6665
Epoch 072 | train loss 0.2410 | valid AUPRC 0.4153 | test AUPRC 0.4635 | valid AUC 0.6496 | test AUC 0.6670
Epoch 073 | train loss 0.2276 | valid AUPRC 0.4227 | test AUPRC 0.4580 | valid AUC 0.6489 | test AUC 0.6667
Epoch 074 | train loss 0.2204 | valid AUPRC 0.4205 | test AUPRC 0.4650 | valid AUC 0.6445 | test AUC 0.6677
Epoch 075 | train loss 0.2023 | valid AUPRC 0.4242 | test AUPRC 0.4660 | valid AUC 0.6443 | test AUC 0.6680
Epoch 076 | train loss 0.1946 | valid AUPRC 0.4238 | test AUPRC 0.4654 | valid AUC 0.6436 | test AUC 0.6680
Epoch 077 | train loss 0.1839 | valid AUPRC 0.4270 | test AUPRC 0.4652 | valid AUC 0.6448 | test AUC 0.6675
Epoch 078 | train loss 0.1831 | valid AUPRC 0.4233 | test AUPRC 0.4649 | valid AUC 0.6450 | test AUC 0.6677
Epoch 079 | train loss 0.1802 | valid AUPRC 0.4253 | test AUPRC 0.4593 | valid AUC 0.6462 | test AUC 0.6658
Epoch 080 | train loss 0.1748 | valid AUPRC 0.4296 | test AUPRC 0.4582 | valid AUC 0.6462 | test AUC 0.6651
Epoch 081 | train loss 0.1548 | valid AUPRC 0.4275 | test AUPRC 0.4556 | valid AUC 0.6470 | test AUC 0.6636
Epoch 082 | train loss 0.1437 | valid AUPRC 0.4264 | test AUPRC 0.4502 | valid AUC 0.6470 | test AUC 0.6610
Epoch 083 | train loss 0.1471 | valid AUPRC 0.4248 | test AUPRC 0.4610 | valid AUC 0.6455 | test AUC 0.6593
Epoch 084 | train loss 0.1272 | valid AUPRC 0.4194 | test AUPRC 0.4595 | valid AUC 0.6448 | test AUC 0.6578
Epoch 085 | train loss 0.1262 | valid AUPRC 0.4224 | test AUPRC 0.4581 | valid AUC 0.6429 | test AUC 0.6573
Epoch 086 | train loss 0.1290 | valid AUPRC 0.4293 | test AUPRC 0.4588 | valid AUC 0.6407 | test AUC 0.6573
Early stopping at epoch 86: no improvement in valid/auprc for 50 epochs.
wandb: ⢿ updating run metadata (0.0s)
wandb: ⣻ updating run metadata (0.0s)
wandb: ⣽ updating run metadata (0.0s)
wandb: ⣾ updating run metadata (0.0s)
wandb: ⣷ Finishing up...
wandb: ⣯ Finishing up...
wandb: ⣟ Finishing up...
wandb: ⡿ Finishing up...
wandb: ⢿ Finishing up...
wandb: ⣻ uploading wandb-summary.json 6.9KB/6.9KB (0.4s)
wandb: ⣻ uploading config.yaml 4.0KB/4.0KB (0.4s)
wandb: ⣽ uploading wandb-summary.json 6.9KB/6.9KB (0.4s)
wandb: ⣽ uploading config.yaml 4.0KB/4.0KB (0.4s)
wandb: ⣾ uploading wandb-summary.json 6.9KB/6.9KB (0.4s)
wandb: ⣾ uploading config.yaml 4.0KB/4.0KB (0.4s)
wandb: ⣷ uploading wandb-summary.json 6.9KB/6.9KB (0.4s)
wandb: ⣷ uploading config.yaml 4.0KB/4.0KB (0.4s)
wandb: ⣯ uploading wandb-summary.json 6.9KB/6.9KB (0.4s)
wandb: ⣯ uploading config.yaml 4.0KB/4.0KB (0.4s)
wandb: ⣟ uploading wandb-summary.json 6.9KB/6.9KB (0.9s)
wandb: ⣟ uploading config.yaml 4.0KB/4.0KB (0.9s)
wandb: ⡿ uploading wandb-summary.json 6.9KB/6.9KB (0.9s)
wandb: ⡿ uploading config.yaml 4.0KB/4.0KB (0.9s)
wandb: ⢿ uploading wandb-summary.json 6.9KB/6.9KB (0.9s)
wandb: ⢿ uploading config.yaml 4.0KB/4.0KB (0.9s)
wandb: ⣻ uploading wandb-summary.json 6.9KB/6.9KB (0.9s)
wandb: ⣻ uploading config.yaml 4.0KB/4.0KB (0.9s)
wandb: ⣽ uploading wandb-summary.json 6.9KB/6.9KB (0.9s)
wandb: ⣽ uploading config.yaml 4.0KB/4.0KB (0.9s)
wandb: ⣾ uploading history steps 79-85, summary, console lines 80-86 (0.2s)
wandb: ⣷ uploading history steps 79-85, summary, console lines 80-86 (0.2s)
wandb: ⣯ uploading history steps 79-85, summary, console lines 80-86 (0.2s)
wandb: ⣟ uploading history steps 79-85, summary, console lines 80-86 (0.2s)
wandb: ⡿ uploading history steps 79-85, summary, console lines 80-86 (0.2s)
wandb: ⢿ uploading history steps 79-85, summary, console lines 80-86 (0.7s)
wandb: ⣻ uploading history steps 79-85, summary, console lines 80-86 (0.7s)
wandb: ⣽ uploading history steps 79-85, summary, console lines 80-86 (0.7s)
wandb: ⣾ uploading history steps 79-85, summary, console lines 80-86 (0.7s)
wandb: ⣷ uploading history steps 79-85, summary, console lines 80-86 (0.7s)
wandb: ⣯ uploading history steps 79-85, summary, console lines 80-86 (1.2s)
wandb: ⣟ uploading history steps 79-85, summary, console lines 80-86 (1.2s)
wandb: ⡿ uploading history steps 79-85, summary, console lines 80-86 (1.2s)
wandb: ⢿ uploading history steps 79-85, summary, console lines 80-86 (1.2s)
wandb: ⣻ uploading history steps 79-85, summary, console lines 80-86 (1.2s)
wandb: ⣽ uploading history steps 79-85, summary, console lines 80-86 (1.7s)
wandb: ⣾ uploading history steps 79-85, summary, console lines 80-86 (1.7s)
wandb: ⣷ uploading history steps 79-85, summary, console lines 80-86 (1.7s)
wandb: ⣯ uploading history steps 79-85, summary, console lines 80-86 (1.7s)
wandb: ⣟ uploading history steps 79-85, summary, console lines 80-86 (1.7s)
wandb: ⡿ uploading history steps 79-85, summary, console lines 80-86 (2.2s)
wandb: ⢿ uploading history steps 79-85, summary, console lines 80-86 (2.2s)
wandb: ⣻ uploading history steps 79-85, summary, console lines 80-86 (2.2s)
wandb: ⣽ uploading history steps 79-85, summary, console lines 80-86 (2.2s)
wandb: ⣾ uploading history steps 79-85, summary, console lines 80-86 (2.2s)
wandb: ⣷ uploading history steps 79-85, summary, console lines 80-86 (2.7s)
wandb: ⣯ uploading history steps 79-85, summary, console lines 80-86 (2.7s)
wandb: ⣟ uploading history steps 79-85, summary, console lines 80-86 (2.7s)
wandb: ⡿ uploading history steps 79-85, summary, console lines 80-86 (2.7s)
wandb: ⢿ uploading history steps 79-85, summary, console lines 80-86 (2.7s)
wandb: ⣻ uploading history steps 79-85, summary, console lines 80-86 (3.2s)
wandb: ⣽ uploading history steps 79-85, summary, console lines 80-86 (3.2s)
wandb: ⣾ uploading history steps 79-85, summary, console lines 80-86 (3.2s)
wandb: ⣷ uploading history steps 79-85, summary, console lines 80-86 (3.2s)
wandb: ⣯ uploading history steps 79-85, summary, console lines 80-86 (3.2s)
wandb: ⣟ uploading history steps 79-85, summary, console lines 80-86 (3.7s)
wandb: ⡿ uploading history steps 79-85, summary, console lines 80-86 (3.7s)
wandb: ⢿ uploading history steps 79-85, summary, console lines 80-86 (3.7s)
wandb: ⣻ uploading history steps 79-85, summary, console lines 80-86 (3.7s)
wandb: ⣽ uploading history steps 79-85, summary, console lines 80-86 (3.7s)
wandb: ⣾ uploading history steps 79-85, summary, console lines 80-86 (4.2s)
wandb: ⣷ uploading history steps 79-85, summary, console lines 80-86 (4.2s)
wandb: ⣯ uploading history steps 79-85, summary, console lines 80-86 (4.2s)
wandb: ⣟ uploading history steps 79-85, summary, console lines 80-86 (4.2s)
wandb: ⡿ uploading history steps 79-85, summary, console lines 80-86 (4.2s)
wandb: ⢿ uploading history steps 79-85, summary, console lines 80-86 (4.7s)
wandb: ⣻ uploading history steps 79-85, summary, console lines 80-86 (4.7s)
wandb: ⣽ uploading history steps 79-85, summary, console lines 80-86 (4.7s)
wandb: ⣾ uploading history steps 79-85, summary, console lines 80-86 (4.7s)
wandb: ⣷ uploading history steps 79-85, summary, console lines 80-86 (4.7s)
wandb: ⣯ uploading history steps 79-85, summary, console lines 80-86 (5.2s)
wandb: ⣟ uploading history steps 79-85, summary, console lines 80-86 (5.2s)
wandb: ⡿ uploading history steps 79-85, summary, console lines 80-86 (5.2s)
wandb: ⢿ uploading history steps 79-85, summary, console lines 80-86 (5.2s)
wandb: ⣻ uploading history steps 79-85, summary, console lines 80-86 (5.2s)
wandb: ⣽ uploading history steps 79-85, summary, console lines 80-86 (5.7s)
wandb: ⣾ uploading history steps 79-85, summary, console lines 80-86 (5.7s)
wandb: ⣷ uploading history steps 79-85, summary, console lines 80-86 (5.7s)
wandb: ⣯ uploading history steps 79-85, summary, console lines 80-86 (5.7s)
wandb: ⣟ uploading history steps 79-85, summary, console lines 80-86 (5.7s)
wandb: ⡿ uploading history steps 79-85, summary, console lines 80-86 (6.2s)
wandb: ⢿ uploading history steps 79-85, summary, console lines 80-86 (6.2s)
wandb: ⣻ uploading history steps 79-85, summary, console lines 80-86 (6.2s)
wandb: ⣽ uploading history steps 79-85, summary, console lines 80-86 (6.2s)
wandb: ⣾ uploading history steps 79-85, summary, console lines 80-86 (6.2s)
wandb: ⣷ uploading history steps 79-85, summary, console lines 80-86 (6.7s)
wandb: ⣯ uploading history steps 79-85, summary, console lines 80-86 (6.7s)
wandb: ⣟ uploading history steps 79-85, summary, console lines 80-86 (6.7s)
wandb: ⡿ uploading history steps 79-85, summary, console lines 80-86 (6.7s)
wandb: ⢿ uploading history steps 79-85, summary, console lines 80-86 (6.7s)
wandb: ⣻ uploading history steps 79-85, summary, console lines 80-86 (7.2s)
wandb: ⣽ uploading history steps 79-85, summary, console lines 80-86 (7.2s)
wandb: ⣾ uploading history steps 79-85, summary, console lines 80-86 (7.2s)
wandb: ⣷ uploading history steps 79-85, summary, console lines 80-86 (7.2s)
wandb: ⣯ uploading history steps 79-85, summary, console lines 80-86 (7.2s)
wandb: ⣟ uploading history steps 79-85, summary, console lines 80-86 (7.7s)
wandb: ⡿ uploading history steps 79-85, summary, console lines 80-86 (7.7s)
wandb: ⢿ uploading history steps 79-85, summary, console lines 80-86 (7.7s)
wandb: ⣻ uploading history steps 79-85, summary, console lines 80-86 (7.7s)
wandb: ⣽ uploading history steps 79-85, summary, console lines 80-86 (7.7s)
wandb: ⣾ uploading history steps 79-85, summary, console lines 80-86 (8.2s)
wandb: ⣷ uploading history steps 79-85, summary, console lines 80-86 (8.2s)
wandb: ⣯ uploading history steps 79-85, summary, console lines 80-86 (8.2s)
wandb: ⣟ uploading history steps 79-85, summary, console lines 80-86 (8.2s)
wandb: ⡿ uploading history steps 79-85, summary, console lines 80-86 (8.2s)
wandb:
wandb: Run history:
wandb:               best/epoch ▁▁▁▂▂▃▃▄▄▅▅▆▇▇▇█████████████████████████
wandb:        best/valid_metric ▁▁▃▃▄▅▅▅▆▆▆▆▆▇▇▇▇▇██████████████████████
wandb: classification_threshold ▆▆▆▆▆▇▇▆▆▆▆▆▆▅▄▃▃▃▇▇▇▆▆▇▇▇▇██▁▂▂▂▂▂▂▁▁▁▁
wandb:                    epoch ▁▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▆▆▆▆▇▇▇▇▇▇▇██

In [1]:
#single run (not multiple parameters, one target)
!python src/train_lp.py model=gnn_lp_attr model.conv_type=gat data=dataset_syn training.epochs=200 data.target="Hospitalization" training.early_stopping_patience=100 num_layers=4,5,6

python3: can't open file '/content/src/train_lp.py': [Errno 2] No such file or directory

In [ ]:
!python src/train_lp.py --multirun model=gnn_lp_attr model.conv_type=gat data=dataset_syn training.epochs=500 data.target="Falls" training.early_stopping_patience=100 model.num_layers=2,3,4,5,6

[2026-07-19 17:26:42,006][HYDRA] Launching 5 jobs locally
[2026-07-19 17:26:42,006][HYDRA] 	#0 : model=gnn_lp_attr model.conv_type=gat data=dataset_syn training.epochs=500 data.target=Falls training.early_stopping_patience=100 model.num_layers=2
data:
  name: syn
  target: Falls
  evaluator_type: synthetic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_1_edges_audited.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_samples_no_overlap.csv
      multihospital: synthetic_pharmacotherapy_v2_samples_multihospital.csv
      hidden: synthetic_pharmacotherapy_v2_samples_hidden_confounder.csv
      doc: synthetic_pharmacotherapy_v2_samples_noisy_documentation.csv
      bias: synthetic_pharmacotherapy_v2_samples_selection_bias.csv
    scenario: clean
model:
  name: gnn_lp_attr
  conv_type: gat
  hidden_dim: 64
  num_layers: 2
  dropout: 0.2
  batch_norm: true
  activation: relu
  aggr: sum
  heads: 4
training:
  lr: 0.001
  epochs: 500
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
  heads: 4
  dropout: 0.2
  pooling: mean
  batch_norm: true
  conv_type: null
  eval_per_endpoint: true
  early_stopping_patience: 100
  early_stopping_min_delta: 0.0
  weight_decay: 0.0005
  oversmoothing_excluded_models:
  - linear
  auto_threshold: true
  eval_threshold: 0.5
meta:
  owner_initials: MO
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: oskardmonika (politechnika-gnn-thesis) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: ⢿ setting up run py0w2opy (0.0s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/GraphNeuralNetwork_Thesis/GraphNeuralNetwork_Thesis/wandb/run-20260719_172645-py0w2opy
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run MO_gnn_lp_attr_syn_Falls_gat_clean_ep500_layer2_lr0.001_bs32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/py0w2opy
{'oversmoothing/cosine_sim_variable': 0.9410710776055705, 'oversmoothing/mad_variable': 0.19985405222601688, 'oversmoothing/numerical_rank_variable': 0.046875, 'oversmoothing/feature_std_variable': 0.6881100535392761, 'oversmoothing/cosine_sim_patient': 0.9998856928464233, 'oversmoothing/mad_patient': 0.015401220538758384, 'oversmoothing/numerical_rank_patient': 0.1875, 'oversmoothing/feature_std_patient': 0.026339106261730194, 'oversmoothing/cosine_sim_mean': 0.9704783852259968, 'oversmoothing/mad_mean': 0.10762763638238763, 'oversmoothing/numerical_rank_mean': 0.1171875, 'oversmoothing/feature_std_mean': 0.35722457990050316, 'oversmoothing/dirichlet_energy': 12.450843969980875}
Epoch 001 | train loss 1.4357 | train AUC 0.4757 | train AUPRC 0.0629 | valid loss 1.1485 | test loss 1.1685 | valid AUC 0.4806 | valid AUPRC 0.0647 | test AUC 0.4444 | test AUPRC 0.0587
{'oversmoothing/cosine_sim_variable': 0.9408673419249776, 'oversmoothing/mad_variable': 0.202233161718467, 'oversmoothing/numerical_rank_variable': 0.0625, 'oversmoothing/feature_std_variable': 0.6777139902114868, 'oversmoothing/cosine_sim_patient': 0.9998779389694847, 'oversmoothing/mad_patient': 0.015701690253426468, 'oversmoothing/numerical_rank_patient': 0.203125, 'oversmoothing/feature_std_patient': 0.02604789100587368, 'oversmoothing/cosine_sim_mean': 0.9703726404472311, 'oversmoothing/mad_mean': 0.10896742598594673, 'oversmoothing/numerical_rank_mean': 0.1328125, 'oversmoothing/feature_std_mean': 0.35188094060868025, 'oversmoothing/dirichlet_energy': 11.793627977371216}
Epoch 002 | train loss 1.3623 | train AUC 0.4649 | train AUPRC 0.0613 | valid loss 1.1879 | test loss 1.1772 | valid AUC 0.4726 | valid AUPRC 0.0630 | test AUC 0.4409 | test AUPRC 0.0583
{'oversmoothing/cosine_sim_variable': 0.9398702479222821, 'oversmoothing/mad_variable': 0.20067839389006875, 'oversmoothing/numerical_rank_variable': 0.0625, 'oversmoothing/feature_std_variable': 0.668393075466156, 'oversmoothing/cosine_sim_patient': 0.9998811905952977, 'oversmoothing/mad_patient': 0.015610094556949653, 'oversmoothing/numerical_rank_patient': 0.1875, 'oversmoothing/feature_std_patient': 0.025065016001462936, 'oversmoothing/cosine_sim_mean': 0.9698757192587899, 'oversmoothing/mad_mean': 0.1081442442235092, 'oversmoothing/numerical_rank_mean': 0.125, 'oversmoothing/feature_std_mean': 0.34672904573380947, 'oversmoothing/dirichlet_energy': 11.197803020477295}
Epoch 003 | train loss 1.3745 | train AUC 0.4766 | train AUPRC 0.0630 | valid loss 1.0061 | test loss 0.9869 | valid AUC 0.4834 | valid AUPRC 0.0656 | test AUC 0.4584 | test AUPRC 0.0610
{'oversmoothing/cosine_sim_variable': 0.9381315630615453, 'oversmoothing/mad_variable': 0.19822894727959678, 'oversmoothing/numerical_rank_variable': 0.0625, 'oversmoothing/feature_std_variable': 0.6564744114875793, 'oversmoothing/cosine_sim_patient': 0.9990869184592296, 'oversmoothing/mad_patient': 0.016425536849784463, 'oversmoothing/numerical_rank_patient': 0.109375, 'oversmoothing/feature_std_patient': 0.047196466475725174, 'oversmoothing/cosine_sim_mean': 0.9686092407603875, 'oversmoothing/mad_mean': 0.10732724206469062, 'oversmoothing/numerical_rank_mean': 0.0859375, 'oversmoothing/feature_std_mean': 0.35183543898165226, 'oversmoothing/dirichlet_energy': 10.545453866322836}
Epoch 004 | train loss 1.5709 | train AUC 0.4839 | train AUPRC 0.0640 | valid loss 0.7434 | test loss 0.7384 | valid AUC 0.4933 | valid AUPRC 0.0665 | test AUC 0.4751 | test AUPRC 0.0631
{'oversmoothing/cosine_sim_variable': 0.9374722736972148, 'oversmoothing/mad_variable': 0.1973218619526575, 'oversmoothing/numerical_rank_variable': 0.0625, 'oversmoothing/feature_std_variable': 0.6503400802612305, 'oversmoothing/cosine_sim_patient': 0.9990457728864433, 'oversmoothing/mad_patient': 0.017519044280703003, 'oversmoothing/numerical_rank_patient': 0.109375, 'oversmoothing/feature_std_patient': 0.046567827463150024, 'oversmoothing/cosine_sim_mean': 0.968259023291829, 'oversmoothing/mad_mean': 0.10742045311668025, 'oversmoothing/numerical_rank_mean': 0.0859375, 'oversmoothing/feature_std_mean': 0.34845395386219025, 'oversmoothing/dirichlet_energy': 10.055394490559896}
Epoch 005 | train loss 1.3543 | train AUC 0.5091 | train AUPRC 0.0678 | valid loss 0.5261 | test loss 0.5201 | valid AUC 0.4996 | valid AUPRC 0.0670 | test AUC 0.4895 | test AUPRC 0.0648
{'oversmoothing/cosine_sim_variable': 0.9375991478548967, 'oversmoothing/mad_variable': 0.1959274195572573, 'oversmoothing/numerical_rank_variable': 0.0625, 'oversmoothing/feature_std_variable': 0.6392743587493896, 'oversmoothing/cosine_sim_patient': 0.9998466733366683, 'oversmoothing/mad_patient': 0.0173011329797774, 'oversmoothing/numerical_rank_patient': 0.171875, 'oversmoothing/feature_std_patient': 0.024838725104928017, 'oversmoothing/cosine_sim_mean': 0.9687229105957825, 'oversmoothing/mad_mean': 0.10661427626851734, 'oversmoothing/numerical_rank_mean': 0.1171875, 'oversmoothing/feature_std_mean': 0.33205654192715883, 'oversmoothing/dirichlet_energy': 9.637390693028768}
Epoch 006 | train loss 1.3394 | train AUC 0.5158 | train AUPRC 0.0691 | valid loss 0.4412 | test loss 0.4322 | valid AUC 0.5247 | valid AUPRC 0.0716 | test AUC 0.5161 | test AUPRC 0.0690
{'oversmoothing/cosine_sim_variable': 0.9372671341531896, 'oversmoothing/mad_variable': 0.1964367201392774, 'oversmoothing/numerical_rank_variable': 0.0625, 'oversmoothing/feature_std_variable': 0.6240109205245972, 'oversmoothing/cosine_sim_patient': 0.9998287268634317, 'oversmoothing/mad_patient': 0.017730544568573942, 'oversmoothing/numerical_rank_patient': 0.1875, 'oversmoothing/feature_std_patient': 0.024364624172449112, 'oversmoothing/cosine_sim_mean': 0.9685479305083107, 'oversmoothing/mad_mean': 0.10708363235392568, 'oversmoothing/numerical_rank_mean': 0.125, 'oversmoothing/feature_std_mean': 0.32418777234852314, 'oversmoothing/dirichlet_energy': 9.186829249064127}
Epoch 007 | train loss 1.6036 | train AUC 0.5165 | train AUPRC 0.0694 | valid loss 0.4705 | test loss 0.4610 | valid AUC 0.5223 | valid AUPRC 0.0716 | test AUC 0.4960 | test AUPRC 0.0659
{'oversmoothing/cosine_sim_variable': 0.9364657036163522, 'oversmoothing/mad_variable': 0.19602397085344914, 'oversmoothing/numerical_rank_variable': 0.0625, 'oversmoothing/feature_std_variable': 0.6124911904335022, 'oversmoothing/cosine_sim_patient': 0.9990017508754377, 'oversmoothing/mad_patient': 0.01904483840381353, 'oversmoothing/numerical_rank_patient': 0.125, 'oversmoothing/feature_std_patient': 0.04360833019018173, 'oversmoothing/cosine_sim_mean': 0.967733727245895, 'oversmoothing/mad_mean': 0.10753440462863133, 'oversmoothing/numerical_rank_mean': 0.09375, 'oversmoothing/feature_std_mean': 0.32804976031184196, 'oversmoothing/dirichlet_energy': 8.864708264668783}
Epoch 008 | train loss 1.3846 | train AUC 0.5149 | train AUPRC 0.0697 | valid loss 0.5331 | test loss 0.5227 | valid AUC 0.5072 | valid AUPRC 0.0690 | test AUC 0.4956 | test AUPRC 0.0665
{'oversmoothing/cosine_sim_variable': 0.9356031172787511, 'oversmoothing/mad_variable': 0.19651540988059327, 'oversmoothing/numerical_rank_variable': 0.0625, 'oversmoothing/feature_std_variable': 0.6010441184043884, 'oversmoothing/cosine_sim_patient': 0.9998003376688345, 'oversmoothing/mad_patient': 0.018062823084639083, 'oversmoothing/numerical_rank_patient': 0.1875, 'oversmoothing/feature_std_patient': 0.023578494787216187, 'oversmoothing/cosine_sim_mean': 0.9677017274737928, 'oversmoothing/mad_mean': 0.10728911648261617, 'oversmoothing/numerical_rank_mean': 0.125, 'oversmoothing/feature_std_mean': 0.3123113065958023, 'oversmoothing/dirichlet_energy': 8.556851784388224}
Epoch 009 | train loss 1.5205 | train AUC 0.4974 | train AUPRC 0.0669 | valid loss 0.6265 | test loss 0.6104 | valid AUC 0.4866 | valid AUPRC 0.0650 | test AUC 0.4855 | test AUPRC 0.0653
{'oversmoothing/cosine_sim_variable': 0.9348375730008984, 'oversmoothing/mad_variable': 0.1958017266620764, 'oversmoothing/numerical_rank_variable': 0.0625, 'oversmoothing/feature_std_variable': 0.5885915756225586, 'oversmoothing/cosine_sim_patient': 0.9997750125062531, 'oversmoothing/mad_patient': 0.01887009486568115, 'oversmoothing/numerical_rank_patient': 0.171875, 'oversmoothing/feature_std_patient': 0.02399815432727337, 'oversmoothing/cosine_sim_mean': 0.9673062927535758, 'oversmoothing/mad_mean': 0.10733591076387877, 'oversmoothing/numerical_rank_mean': 0.1171875, 'oversmoothing/feature_std_mean': 0.306294864974916, 'oversmoothing/dirichlet_energy': 8.332300901412964}
Epoch 010 | train loss 1.3875 | train AUC 0.4851 | train AUPRC 0.0646 | valid loss 0.7333 | test loss 0.7116 | valid AUC 0.4801 | valid AUPRC 0.0634 | test AUC 0.4792 | test AUPRC 0.0638
{'oversmoothing/cosine_sim_variable': 0.9346985905211141, 'oversmoothing/mad_variable': 0.1949316657528289, 'oversmoothing/numerical_rank_variable': 0.0625, 'oversmoothing/feature_std_variable': 0.576019287109375, 'oversmoothing/cosine_sim_patient': 0.9997314282141071, 'oversmoothing/mad_patient': 0.019830577765861623, 'oversmoothing/numerical_rank_patient': 0.15625, 'oversmoothing/feature_std_patient': 0.024496205151081085, 'oversmoothing/cosine_sim_mean': 0.9672150093676106, 'oversmoothing/mad_mean': 0.10738112175934525, 'oversmoothing/numerical_rank_mean': 0.109375, 'oversmoothing/feature_std_mean': 0.30025774613022804, 'oversmoothing/dirichlet_energy': 8.11968723932902}
Epoch 011 | train loss 1.4114 | train AUC 0.4837 | train AUPRC 0.0641 | valid loss 0.8430 | test loss 0.8238 | valid AUC 0.4757 | valid AUPRC 0.0641 | test AUC 0.4731 | test AUPRC 0.0637
{'oversmoothing/cosine_sim_variable': 0.9347494805705301, 'oversmoothing/mad_variable': 0.1941693950401362, 'oversmoothing/numerical_rank_variable': 0.0625, 'oversmoothing/feature_std_variable': 0.5638415813446045, 'oversmoothing/cosine_sim_patient': 0.9996738994497248, 'oversmoothing/mad_patient': 0.02144429438540224, 'oversmoothing/numerical_rank_patient': 0.15625, 'oversmoothing/feature_std_patient': 0.025854427367448807, 'oversmoothing/cosine_sim_mean': 0.9672116900101275, 'oversmoothing/mad_mean': 0.10780684471276922, 'oversmoothing/numerical_rank_mean': 0.109375, 'oversmoothing/feature_std_mean': 0.29484800435602665, 'oversmoothing/dirichlet_energy': 7.9081956545511884}
Epoch 012 | train loss 1.3370 | train AUC 0.4807 | train AUPRC 0.0636 | valid loss 0.9173 | test loss 0.8927 | valid AUC 0.4758 | valid AUPRC 0.0645 | test AUC 0.4713 | test AUPRC 0.0635
{'oversmoothing/cosine_sim_variable': 0.9350176184860737, 'oversmoothing/mad_variable': 0.19448025570815153, 'oversmoothing/numerical_rank_variable': 0.0625, 'oversmoothing/feature_std_variable': 0.5505814552307129, 'oversmoothing/cosine_sim_patient': 0.999677963981991, 'oversmoothing/mad_patient': 0.021319030323794213, 'oversmoothing/numerical_rank_patient': 0.15625, 'oversmoothing/feature_std_patient': 0.025266392156481743, 'oversmoothing/cosine_sim_mean': 0.9673477912340324, 'oversmoothing/mad_mean': 0.10789964301597287, 'oversmoothing/numerical_rank_mean': 0.109375, 'oversmoothing/feature_std_mean': 0.2879239236935973, 'oversmoothing/dirichlet_energy': 7.6143990357716875}
Epoch 013 | train loss 1.5223 | train AUC 0.4793 | train AUPRC 0.0633 | valid loss 0.9268 | test loss 0.8987 | valid AUC 0.4743 | valid AUPRC 0.0636 | test AUC 0.4638 | test AUPRC 0.0622
{'oversmoothing/cosine_sim_variable': 0.9353398928852201, 'oversmoothing/mad_variable': 0.19601442108977993, 'oversmoothing/numerical_rank_variable': 0.0625, 'oversmoothing/feature_std_variable': 0.5402155518531799, 'oversmoothing/cosine_sim_patient': 0.9996535767883942, 'oversmoothing/mad_patient': 0.022362847616933697, 'oversmoothing/numerical_rank_patient': 0.15625, 'oversmoothing/feature_std_patient': 0.02600754052400589, 'oversmoothing/cosine_sim_mean': 0.9674967348368071, 'oversmoothing/mad_mean': 0.10918863435335681, 'oversmoothing/numerical_rank_mean': 0.109375, 'oversmoothing/feature_std_mean': 0.2831115461885929, 'oversmoothing/dirichlet_energy': 7.343980471293132}
Epoch 014 | train loss 1.4509 | train AUC 0.4764 | train AUPRC 0.0628 | valid loss 0.8972 | test loss 0.8712 | valid AUC 0.4722 | valid AUPRC 0.0626 | test AUC 0.4618 | test AUPRC 0.0619
{'oversmoothing/cosine_sim_variable': 0.9355270454290207, 'oversmoothing/mad_variable': 0.19755335818217895, 'oversmoothing/numerical_rank_variable': 0.0625, 'oversmoothing/feature_std_variable': 0.5308058261871338, 'oversmoothing/cosine_sim_patient': 0.9996671460730365, 'oversmoothing/mad_patient': 0.0220263946508118, 'oversmoothing/numerical_rank_patient': 0.171875, 'oversmoothing/feature_std_patient': 0.025231709703803062, 'oversmoothing/cosine_sim_mean': 0.9675970957510286, 'oversmoothing/mad_mean': 0.10978987641649537, 'oversmoothing/numerical_rank_mean': 0.1171875, 'oversmoothing/feature_std_mean': 0.2780187679454684, 'oversmoothing/dirichlet_energy': 7.114423910776774}
Epoch 015 | train loss 1.2996 | train AUC 0.4760 | train AUPRC 0.0626 | valid loss 0.8697 | test loss 0.8487 | valid AUC 0.4717 | valid AUPRC 0.0623 | test AUC 0.4743 | test AUPRC 0.0641
{'oversmoothing/cosine_sim_variable': 0.9356760304357592, 'oversmoothing/mad_variable': 0.198327589893322, 'oversmoothing/numerical_rank_variable': 0.0625, 'oversmoothing/feature_std_variable': 0.5218480825424194, 'oversmoothing/cosine_sim_patient': 0.9997065407703852, 'oversmoothing/mad_patient': 0.021298593814826787, 'oversmoothing/numerical_rank_patient': 0.171875, 'oversmoothing/feature_std_patient': 0.0236146729439497, 'oversmoothing/cosine_sim_mean': 0.9676912856030722, 'oversmoothing/mad_mean': 0.1098130918540744, 'oversmoothing/numerical_rank_mean': 0.1171875, 'oversmoothing/feature_std_mean': 0.27273137774318457, 'oversmoothing/dirichlet_energy': 6.9043839772542315}
Epoch 016 | train loss 1.3260 | train AUC 0.4821 | train AUPRC 0.0632 | valid loss 0.8324 | test loss 0.8190 | valid AUC 0.4742 | valid AUPRC 0.0626 | test AUC 0.4865 | test AUPRC 0.0658
{'oversmoothing/cosine_sim_variable': 0.9357621925539084, 'oversmoothing/mad_variable': 0.19839282327605856, 'oversmoothing/numerical_rank_variable': 0.0625, 'oversmoothing/feature_std_variable': 0.5122829079627991, 'oversmoothing/cosine_sim_patient': 0.9997080415207604, 'oversmoothing/mad_patient': 0.021316705801492766, 'oversmoothing/numerical_rank_patient': 0.171875, 'oversmoothing/feature_std_patient': 0.022971412166953087, 'oversmoothing/cosine_sim_mean': 0.9677351170373344, 'oversmoothing/mad_mean': 0.10985476453877566, 'oversmoothing/numerical_rank_mean': 0.1171875, 'oversmoothing/feature_std_mean': 0.2676271600648761, 'oversmoothing/dirichlet_energy': 6.685602108637492}
Epoch 017 | train loss 1.3587 | train AUC 0.5055 | train AUPRC 0.0671 | valid loss 0.7825 | test loss 0.7654 | valid AUC 0.4927 | valid AUPRC 0.0646 | test AUC 0.4953 | test AUPRC 0.0661
{'oversmoothing/cosine_sim_variable': 0.9357525409928122, 'oversmoothing/mad_variable': 0.19836425299802865, 'oversmoothing/numerical_rank_variable': 0.0625, 'oversmoothing/feature_std_variable': 0.5036249160766602, 'oversmoothing/cosine_sim_patient': 0.9996900950475237, 'oversmoothing/mad_patient': 0.02181573956568835, 'oversmoothing/numerical_rank_patient': 0.171875, 'oversmoothing/feature_std_patient': 0.023268746212124825, 'oversmoothing/cosine_sim_mean': 0.967721318020168, 'oversmoothing/mad_mean': 0.1100899962818585, 'oversmoothing/numerical_rank_mean': 0.1171875, 'oversmoothing/feature_std_mean': 0.2634468311443925, 'oversmoothing/dirichlet_energy': 6.508206844329834}
Epoch 018 | train loss 1.2976 | train AUC 0.4952 | train AUPRC 0.0659 | valid loss 0.7399 | test loss 0.7216 | valid AUC 0.4772 | valid AUPRC 0.0623 | test AUC 0.4998 | test AUPRC 0.0658
{'oversmoothing/cosine_sim_variable': 0.9359013505166217, 'oversmoothing/mad_variable': 0.1986063224493726, 'oversmoothing/numerical_rank_variable': 0.0625, 'oversmoothing/feature_std_variable': 0.4958152770996094, 'oversmoothing/cosine_sim_patient': 0.9997067283641821, 'oversmoothing/mad_patient': 0.021708158708731044, 'oversmoothing/numerical_rank_patient': 0.171875, 'oversmoothing/feature_std_patient': 0.022425774484872818, 'oversmoothing/cosine_sim_mean': 0.9678040394404019, 'oversmoothing/mad_mean': 0.11015724057905182, 'oversmoothing/numerical_rank_mean': 0.1171875, 'oversmoothing/feature_std_mean': 0.2591205257922411, 'oversmoothing/dirichlet_energy': 6.339603503545125}
Epoch 019 | train loss 1.3041 | train AUC 0.4634 | train AUPRC 0.0597 | valid loss 0.6931 | test loss 0.6696 | valid AUC 0.4557 | valid AUPRC 0.0600 | test AUC 0.4655 | test AUPRC 0.0604
{'oversmoothing/cosine_sim_variable': 0.936005236410602, 'oversmoothing/mad_variable': 0.19902465796412824, 'oversmoothing/numerical_rank_variable': 0.0625, 'oversmoothing/feature_std_variable': 0.4885115623474121, 'oversmoothing/cosine_sim_patient': 0.9997116683341671, 'oversmoothing/mad_patient': 0.02177044637724561, 'oversmoothing/numerical_rank_patient': 0.171875, 'oversmoothing/feature_std_patient': 0.021888568997383118, 'oversmoothing/cosine_sim_mean': 0.9678584523723845, 'oversmoothing/mad_mean': 0.11039755217068692, 'oversmoothing/numerical_rank_mean': 0.1171875, 'oversmoothing/feature_std_mean': 0.2552000656723976, 'oversmoothing/dirichlet_energy': 6.1743483543396}
Epoch 020 | train loss 1.3227 | train AUC 0.4614 | train AUPRC 0.0592 | valid loss 0.6700 | test loss 0.6445 | valid AUC 0.4570 | valid AUPRC 0.0602 | test AUC 0.4668 | test AUPRC 0.0606

In [ ]:
!python src/train_lp.py model=gnn_lp model.conv_type=sage data=dataset_syn training.epochs=50 data.target="AKI"

data:
  name: syn
  target: AKI
  evaluator_type: synthetic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_1_edges_audited.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_samples_no_overlap.csv
      multihospital: synthetic_pharmacotherapy_v2_samples_multihospital.csv
      hidden: synthetic_pharmacotherapy_v2_samples_hidden_confounder.csv
      doc: synthetic_pharmacotherapy_v2_samples_noisy_documentation.csv
      bias: synthetic_pharmacotherapy_v2_samples_selection_bias.csv
    scenario: clean
model:
  name: gnn_lp
  conv_type: sage
  hidden_dim: 64
  num_layers: 3
  dropout: 0.2
  batch_norm: true
  activation: relu
  aggr: sum
  heads: 4
training:
  lr: 0.001
  epochs: 50
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
  heads: 4
  dropout: 0.2
  pooling: mean
  batch_norm: true
  conv_type: null
  eval_per_endpoint: true
meta:
  owner_initials: MO
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: oskardmonika (politechnika-gnn-thesis) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: ⢿ setting up run lsy9qcyp (0.0s)
wandb: ⣻ setting up run lsy9qcyp (0.0s)
wandb: ⣽ setting up run lsy9qcyp (0.0s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/GraphNeuralNetwork_Thesis/GraphNeuralNetwork_Thesis/GraphNeuralNetwork_Thesis/GraphNeuralNetwork_Thesis/GraphNeuralNetwork_Thesis/wandb/run-20260717_172835-lsy9qcyp
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run MO_gnn_lp_syn_AKI_None_clean_ep50_layer3_lr0.001_bs32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/lsy9qcyp
Epoch 001 | train loss 1.3460 | train AUC 0.4875 | train AUPRC 0.0351 | valid loss 0.8714 | test loss 0.8501 | valid AUC 0.4581 | valid AUPRC 0.0338 | test AUC 0.4966 | test AUPRC 0.0364
Epoch 002 | train loss 1.3994 | train AUC 0.5112 | train AUPRC 0.0374 | valid loss 0.7424 | test loss 0.7186 | valid AUC 0.4854 | valid AUPRC 0.0354 | test AUC 0.5234 | test AUPRC 0.0380
Epoch 003 | train loss 1.3467 | train AUC 0.5123 | train AUPRC 0.0388 | valid loss 0.6531 | test loss 0.6282 | valid AUC 0.4900 | valid AUPRC 0.0357 | test AUC 0.5171 | test AUPRC 0.0378
Epoch 004 | train loss 1.3428 | train AUC 0.5527 | train AUPRC 0.0436 | valid loss 0.5902 | test loss 0.5556 | valid AUC 0.5527 | valid AUPRC 0.0405 | test AUC 0.5527 | test AUPRC 0.0414
Epoch 005 | train loss 1.3415 | train AUC 0.5659 | train AUPRC 0.0461 | valid loss 0.5690 | test loss 0.5318 | valid AUC 0.5679 | valid AUPRC 0.0430 | test AUC 0.5680 | test AUPRC 0.0437
Epoch 006 | train loss 1.3468 | train AUC 0.5658 | train AUPRC 0.0456 | valid loss 0.5743 | test loss 0.5385 | valid AUC 0.5678 | valid AUPRC 0.0431 | test AUC 0.5752 | test AUPRC 0.0454
Epoch 007 | train loss 1.3380 | train AUC 0.5708 | train AUPRC 0.0466 | valid loss 0.5884 | test loss 0.5595 | valid AUC 0.5799 | valid AUPRC 0.0480 | test AUC 0.5846 | test AUPRC 0.0488
Epoch 008 | train loss 1.3387 | train AUC 0.5710 | train AUPRC 0.0471 | valid loss 0.6232 | test loss 0.6054 | valid AUC 0.5812 | valid AUPRC 0.0518 | test AUC 0.5897 | test AUPRC 0.0507
Epoch 009 | train loss 1.3667 | train AUC 0.5380 | train AUPRC 0.0417 | valid loss 0.6865 | test loss 0.6885 | valid AUC 0.5807 | valid AUPRC 0.0523 | test AUC 0.5774 | test AUPRC 0.0507
Epoch 010 | train loss 1.3411 | train AUC 0.5314 | train AUPRC 0.0407 | valid loss 0.7605 | test loss 0.7873 | valid AUC 0.5862 | valid AUPRC 0.0551 | test AUC 0.5700 | test AUPRC 0.0486
Epoch 011 | train loss 1.3394 | train AUC 0.5397 | train AUPRC 0.0417 | valid loss 0.8138 | test loss 0.8605 | valid AUC 0.5886 | valid AUPRC 0.0567 | test AUC 0.5770 | test AUPRC 0.0506
Epoch 012 | train loss 1.4070 | train AUC 0.5478 | train AUPRC 0.0420 | valid loss 0.8011 | test loss 0.8451 | valid AUC 0.5819 | valid AUPRC 0.0572 | test AUC 0.5836 | test AUPRC 0.0514
Epoch 013 | train loss 1.3477 | train AUC 0.5586 | train AUPRC 0.0442 | valid loss 0.7754 | test loss 0.8103 | valid AUC 0.5821 | valid AUPRC 0.0578 | test AUC 0.5931 | test AUPRC 0.0543
Epoch 014 | train loss 1.3455 | train AUC 0.5614 | train AUPRC 0.0450 | valid loss 0.7380 | test loss 0.7619 | valid AUC 0.5815 | valid AUPRC 0.0534 | test AUC 0.5899 | test AUPRC 0.0525
Epoch 015 | train loss 1.3735 | train AUC 0.5597 | train AUPRC 0.0446 | valid loss 0.6877 | test loss 0.6989 | valid AUC 0.5834 | valid AUPRC 0.0474 | test AUC 0.5829 | test AUPRC 0.0479
Epoch 016 | train loss 1.3377 | train AUC 0.5657 | train AUPRC 0.0461 | valid loss 0.6491 | test loss 0.6488 | valid AUC 0.5825 | valid AUPRC 0.0467 | test AUC 0.5845 | test AUPRC 0.0481
Epoch 017 | train loss 1.3542 | train AUC 0.5688 | train AUPRC 0.0473 | valid loss 0.6299 | test loss 0.6239 | valid AUC 0.5796 | valid AUPRC 0.0463 | test AUC 0.5816 | test AUPRC 0.0474
Epoch 018 | train loss 1.3544 | train AUC 0.5692 | train AUPRC 0.0477 | valid loss 0.6259 | test loss 0.6231 | valid AUC 0.5778 | valid AUPRC 0.0459 | test AUC 0.5792 | test AUPRC 0.0475
Epoch 019 | train loss 1.3409 | train AUC 0.5717 | train AUPRC 0.0485 | valid loss 0.6309 | test loss 0.6308 | valid AUC 0.5704 | valid AUPRC 0.0455 | test AUC 0.5815 | test AUPRC 0.0487
Epoch 020 | train loss 1.3371 | train AUC 0.5719 | train AUPRC 0.0486 | valid loss 0.6384 | test loss 0.6383 | valid AUC 0.5740 | valid AUPRC 0.0472 | test AUC 0.5836 | test AUPRC 0.0497
Epoch 021 | train loss 1.3360 | train AUC 0.5723 | train AUPRC 0.0492 | valid loss 0.6458 | test loss 0.6480 | valid AUC 0.5763 | valid AUPRC 0.0478 | test AUC 0.5847 | test AUPRC 0.0501
Epoch 022 | train loss 1.3368 | train AUC 0.5737 | train AUPRC 0.0498 | valid loss 0.6513 | test loss 0.6548 | valid AUC 0.5790 | valid AUPRC 0.0487 | test AUC 0.5851 | test AUPRC 0.0504
Epoch 023 | train loss 1.3384 | train AUC 0.5753 | train AUPRC 0.0500 | valid loss 0.6596 | test loss 0.6647 | valid AUC 0.5793 | valid AUPRC 0.0492 | test AUC 0.5851 | test AUPRC 0.0509
Epoch 024 | train loss 1.3355 | train AUC 0.5758 | train AUPRC 0.0497 | valid loss 0.6690 | test loss 0.6759 | valid AUC 0.5786 | valid AUPRC 0.0490 | test AUC 0.5833 | test AUPRC 0.0500
Epoch 025 | train loss 1.3356 | train AUC 0.5752 | train AUPRC 0.0496 | valid loss 0.6761 | test loss 0.6847 | valid AUC 0.5780 | valid AUPRC 0.0491 | test AUC 0.5824 | test AUPRC 0.0497
Epoch 026 | train loss 1.3360 | train AUC 0.5744 | train AUPRC 0.0488 | valid loss 0.6807 | test loss 0.6909 | valid AUC 0.5792 | valid AUPRC 0.0497 | test AUC 0.5820 | test AUPRC 0.0497
Epoch 027 | train loss 1.3347 | train AUC 0.5735 | train AUPRC 0.0481 | valid loss 0.6869 | test loss 0.6992 | valid AUC 0.5797 | valid AUPRC 0.0489 | test AUC 0.5817 | test AUPRC 0.0491
Epoch 028 | train loss 1.3365 | train AUC 0.5735 | train AUPRC 0.0478 | valid loss 0.6934 | test loss 0.7079 | valid AUC 0.5790 | valid AUPRC 0.0481 | test AUC 0.5818 | test AUPRC 0.0488
Epoch 029 | train loss 1.3349 | train AUC 0.5737 | train AUPRC 0.0478 | valid loss 0.6979 | test loss 0.7135 | valid AUC 0.5784 | valid AUPRC 0.0480 | test AUC 0.5831 | test AUPRC 0.0490
Epoch 030 | train loss 1.3367 | train AUC 0.5747 | train AUPRC 0.0479 | valid loss 0.6973 | test loss 0.7127 | valid AUC 0.5798 | valid AUPRC 0.0484 | test AUC 0.5843 | test AUPRC 0.0491
Epoch 031 | train loss 1.3367 | train AUC 0.5768 | train AUPRC 0.0483 | valid loss 0.6915 | test loss 0.7055 | valid AUC 0.5820 | valid AUPRC 0.0490 | test AUC 0.5857 | test AUPRC 0.0495
Epoch 032 | train loss 1.3347 | train AUC 0.5777 | train AUPRC 0.0484 | valid loss 0.6823 | test loss 0.6950 | valid AUC 0.5845 | valid AUPRC 0.0500 | test AUC 0.5874 | test AUPRC 0.0499
Epoch 033 | train loss 1.3333 | train AUC 0.5782 | train AUPRC 0.0485 | valid loss 0.6713 | test loss 0.6830 | valid AUC 0.5864 | valid AUPRC 0.0516 | test AUC 0.5884 | test AUPRC 0.0498
Epoch 034 | train loss 1.3328 | train AUC 0.5789 | train AUPRC 0.0485 | valid loss 0.6593 | test loss 0.6698 | valid AUC 0.5874 | valid AUPRC 0.0523 | test AUC 0.5886 | test AUPRC 0.0499
Epoch 035 | train loss 1.3353 | train AUC 0.5794 | train AUPRC 0.0486 | valid loss 0.6536 | test loss 0.6639 | valid AUC 0.5878 | valid AUPRC 0.0526 | test AUC 0.5887 | test AUPRC 0.0501
Epoch 036 | train loss 1.3335 | train AUC 0.5795 | train AUPRC 0.0487 | valid loss 0.6456 | test loss 0.6545 | valid AUC 0.5877 | valid AUPRC 0.0528 | test AUC 0.5887 | test AUPRC 0.0500
Epoch 037 | train loss 1.3323 | train AUC 0.5796 | train AUPRC 0.0487 | valid loss 0.6422 | test loss 0.6501 | valid AUC 0.5875 | valid AUPRC 0.0528 | test AUC 0.5882 | test AUPRC 0.0500
Epoch 038 | train loss 1.3328 | train AUC 0.5797 | train AUPRC 0.0485 | valid loss 0.6466 | test loss 0.6545 | valid AUC 0.5881 | valid AUPRC 0.0526 | test AUC 0.5880 | test AUPRC 0.0499
Epoch 039 | train loss 1.3301 | train AUC 0.5798 | train AUPRC 0.0486 | valid loss 0.6494 | test loss 0.6574 | valid AUC 0.5888 | valid AUPRC 0.0524 | test AUC 0.5876 | test AUPRC 0.0499
Epoch 040 | train loss 1.3331 | train AUC 0.5797 | train AUPRC 0.0484 | valid loss 0.6542 | test loss 0.6626 | valid AUC 0.5888 | valid AUPRC 0.0522 | test AUC 0.5874 | test AUPRC 0.0499
Epoch 041 | train loss 1.3349 | train AUC 0.5797 | train AUPRC 0.0484 | valid loss 0.6677 | test loss 0.6778 | valid AUC 0.5891 | valid AUPRC 0.0528 | test AUC 0.5874 | test AUPRC 0.0498
Epoch 042 | train loss 1.3280 | train AUC 0.5798 | train AUPRC 0.0484 | valid loss 0.6770 | test loss 0.6888 | valid AUC 0.5891 | valid AUPRC 0.0530 | test AUC 0.5875 | test AUPRC 0.0498
Epoch 043 | train loss 1.3312 | train AUC 0.5800 | train AUPRC 0.0484 | valid loss 0.6818 | test loss 0.6948 | valid AUC 0.5894 | valid AUPRC 0.0531 | test AUC 0.5876 | test AUPRC 0.0498
Epoch 044 | train loss 1.3319 | train AUC 0.5803 | train AUPRC 0.0484 | valid loss 0.6757 | test loss 0.6881 | valid AUC 0.5892 | valid AUPRC 0.0530 | test AUC 0.5879 | test AUPRC 0.0498
Epoch 045 | train loss 1.3280 | train AUC 0.5805 | train AUPRC 0.0485 | valid loss 0.6704 | test loss 0.6825 | valid AUC 0.5893 | valid AUPRC 0.0531 | test AUC 0.5884 | test AUPRC 0.0499
Epoch 046 | train loss 1.3278 | train AUC 0.5807 | train AUPRC 0.0484 | valid loss 0.6697 | test loss 0.6820 | valid AUC 0.5900 | valid AUPRC 0.0536 | test AUC 0.5887 | test AUPRC 0.0499
Epoch 047 | train loss 1.3293 | train AUC 0.5810 | train AUPRC 0.0484 | valid loss 0.6664 | test loss 0.6792 | valid AUC 0.5905 | valid AUPRC 0.0541 | test AUC 0.5889 | test AUPRC 0.0499
Epoch 048 | train loss 1.3290 | train AUC 0.5814 | train AUPRC 0.0485 | valid loss 0.6692 | test loss 0.6831 | valid AUC 0.5910 | valid AUPRC 0.0543 | test AUC 0.5891 | test AUPRC 0.0500
Epoch 049 | train loss 1.3266 | train AUC 0.5817 | train AUPRC 0.0484 | valid loss 0.6752 | test loss 0.6903 | valid AUC 0.5917 | valid AUPRC 0.0552 | test AUC 0.5892 | test AUPRC 0.0501
Epoch 050 | train loss 1.3278 | train AUC 0.5819 | train AUPRC 0.0484 | valid loss 0.6856 | test loss 0.7022 | valid AUC 0.5919 | valid AUPRC 0.0567 | test AUC 0.5896 | test AUPRC 0.0502
wandb: ⢿ updating run metadata (0.0s)
wandb: ⣻ updating run metadata (0.0s)
wandb: ⣽ updating run metadata (0.0s)
wandb: ⣾ updating run metadata (0.0s)
wandb: ⣷ uploading history steps 45-49, summary, console lines 46-49 (0.1s)
wandb: ⣯ uploading history steps 45-49, summary, console lines 46-49 (0.1s)
wandb: ⣟ uploading history steps 45-49, summary, console lines 46-49 (0.1s)
wandb:
wandb: Run history:
wandb:        best/epoch ▁▂▂▃▃▅▅▆▆▇██████████████████████████████
wandb: best/valid_metric ▁▁▂▃▄▅▆▆▇███████████████████████████████
wandb:             epoch ▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▆▇▇▇▇▇███
wandb:                lr ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:          test/auc ▁▃▂▅▆▇█▇▆▇██▇▇▇▇▇▇▇▇▇▇▇▇▇███████████████
wandb:      test/auc_AKI ▁▃▃▅▆██▇▇▇█▇█▇▇█████▇▇▇█████████████████
wandb:        test/auprc ▁▂▂▄▅▇▆▇▇█▅▆▅▅▆▆▆▇▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆
wandb:    test/auprc_AKI ▁▂▂▃▄▆▇▇▆▇█▇▅▆▅▆▆▆▆▇▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆
wandb:        test/brier █▃▁▁▁▃▄▆██▆▅▃▃▃▃▃▄▄▄▅▅▅▅▅▄▄▄▄▄▄▄▄▄▄▄▄▄▄▅
wandb:         test/loss █▅▃▂▁▂▃▄▆█▇▆▅▃▃▃▃▃▄▄▄▅▅▅▅▄▄▄▄▄▄▄▄▄▄▄▄▄▄▅
wandb:               +13 ...
wandb:
wandb: Run summary:
wandb:        best/epoch 13
wandb: best/valid_metric 0.05776
wandb:        best_epoch 13
wandb:  best_valid_AUPRC 0.05776
wandb:   checkpoint_path /content/GraphNeural...
wandb:             epoch 50
wandb:                lr 0.001
wandb:          test/auc 0.58956
wandb:      test/auc_AKI 0.58956
wandb:        test/auprc 0.05022
wandb:               +16 ...
wandb:
wandb: 🚀 View run MO_gnn_lp_syn_AKI_None_clean_ep50_layer3_lr0.001_bs32 at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/lsy9qcyp
wandb: ⭐️ View project at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260717_172835-lsy9qcyp/logs
Saved checkpoint to: /content/GraphNeuralNetwork_Thesis/GraphNeuralNetwork_Thesis/GraphNeuralNetwork_Thesis/GraphNeuralNetwork_Thesis/GraphNeuralNetwork_Thesis/GraphNeuralNetwork_Thesis/outputs/2026-07-17/17-28-32/best_model.pt
Hydra run dir: /content/GraphNeuralNetwork_Thesis/GraphNeuralNetwork_Thesis/GraphNeuralNetwork_Thesis/GraphNeuralNetwork_Thesis/GraphNeuralNetwork_Thesis/GraphNeuralNetwork_Thesis/outputs/2026-07-17/17-28-32

In [ ]:
#multirun
!python src/train.py --multirun model=gcn data=dataset_syn training.epochs=50 data.target="Hospitalization" model.num_layers=2,3,4,6,8,12

[2026-07-09 10:59:35,246][HYDRA] Launching 6 jobs locally
[2026-07-09 10:59:35,247][HYDRA] 	#0 : model=gcn data=dataset_syn training.epochs=50 data.target=Hospitalization model.num_layers=2
data:
  name: syn
  target: Hospitalization
  evaluator_type: synthethic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_edges.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_samples_nooverlap.csv
      multihospital: synthetic_pharmacotherapy_v2_samples_multihospital.csv
    scenario: clean
model:
  name: gcn
  hidden_dim: 64
  num_layers: 2
  dropout: 0.2
  batch_norm: true
  activation: relu
training:
  lr: 0.001
  epochs: 50
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
meta:
  owner_initials: mo
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis
  run_name: ${meta.owner_initials}_${model.name}_${data.name}_${data.target}_${data.dataset.scenario}_ep${training.epochs}_layer${model.num_layers}_hidden${model.hidden_dim}_lr${training.lr}_bs${training.batch_size}

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: oskardmonika (politechnika-gnn-thesis) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: ⢿ setting up run bdtlnkhi (0.0s)
wandb: ⣻ setting up run bdtlnkhi (0.0s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260709_105935-bdtlnkhi
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run mo_gcn_syn_Hospitalization_clean_ep50_layer2_hidden64_lr0.001_bs32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/bdtlnkhi
Epoch 001 | train loss 0.4027 | val AUC 0.4810 | val AP 0.1368 | test AUC 0.5024 | test AP 0.1580
Epoch 002 | train loss 0.3817 | val AUC 0.5418 | val AP 0.1744 | test AUC 0.5489 | test AP 0.1576
Epoch 003 | train loss 0.3780 | val AUC 0.6062 | val AP 0.2163 | test AUC 0.5836 | test AP 0.1587
Epoch 004 | train loss 0.3752 | val AUC 0.6501 | val AP 0.2282 | test AUC 0.6002 | test AP 0.1689
Epoch 005 | train loss 0.3728 | val AUC 0.6699 | val AP 0.2244 | test AUC 0.6051 | test AP 0.1671
Epoch 006 | train loss 0.3716 | val AUC 0.6744 | val AP 0.2202 | test AUC 0.6051 | test AP 0.1803
Epoch 007 | train loss 0.3716 | val AUC 0.6735 | val AP 0.2197 | test AUC 0.6038 | test AP 0.1832
Epoch 008 | train loss 0.3701 | val AUC 0.6745 | val AP 0.2213 | test AUC 0.6062 | test AP 0.1854
Epoch 009 | train loss 0.3700 | val AUC 0.6728 | val AP 0.2218 | test AUC 0.6066 | test AP 0.1899
Epoch 010 | train loss 0.3700 | val AUC 0.6691 | val AP 0.2193 | test AUC 0.6046 | test AP 0.1917
Epoch 011 | train loss 0.3692 | val AUC 0.6715 | val AP 0.2219 | test AUC 0.6071 | test AP 0.1927
Epoch 012 | train loss 0.3691 | val AUC 0.6727 | val AP 0.2235 | test AUC 0.6082 | test AP 0.1931
Epoch 013 | train loss 0.3694 | val AUC 0.6695 | val AP 0.2227 | test AUC 0.6076 | test AP 0.1962
Epoch 014 | train loss 0.3691 | val AUC 0.6690 | val AP 0.2222 | test AUC 0.6069 | test AP 0.1961
Epoch 015 | train loss 0.3682 | val AUC 0.6702 | val AP 0.2237 | test AUC 0.6090 | test AP 0.1975
Epoch 016 | train loss 0.3691 | val AUC 0.6664 | val AP 0.2223 | test AUC 0.6071 | test AP 0.1983
Epoch 017 | train loss 0.3678 | val AUC 0.6721 | val AP 0.2285 | test AUC 0.6123 | test AP 0.2004
Epoch 018 | train loss 0.3677 | val AUC 0.6682 | val AP 0.2252 | test AUC 0.6109 | test AP 0.1993
Epoch 019 | train loss 0.3683 | val AUC 0.6702 | val AP 0.2275 | test AUC 0.6128 | test AP 0.2014
Epoch 020 | train loss 0.3666 | val AUC 0.6726 | val AP 0.2327 | test AUC 0.6157 | test AP 0.2038
Epoch 021 | train loss 0.3672 | val AUC 0.6684 | val AP 0.2292 | test AUC 0.6141 | test AP 0.2035
Epoch 022 | train loss 0.3670 | val AUC 0.6738 | val AP 0.2370 | test AUC 0.6181 | test AP 0.2071
Epoch 023 | train loss 0.3663 | val AUC 0.6758 | val AP 0.2397 | test AUC 0.6193 | test AP 0.2079
Epoch 024 | train loss 0.3661 | val AUC 0.6718 | val AP 0.2367 | test AUC 0.6196 | test AP 0.2084
Epoch 025 | train loss 0.3655 | val AUC 0.6727 | val AP 0.2401 | test AUC 0.6206 | test AP 0.2091
Epoch 026 | train loss 0.3647 | val AUC 0.6722 | val AP 0.2381 | test AUC 0.6213 | test AP 0.2109
Epoch 027 | train loss 0.3657 | val AUC 0.6767 | val AP 0.2473 | test AUC 0.6244 | test AP 0.2122
Epoch 028 | train loss 0.3650 | val AUC 0.6755 | val AP 0.2477 | test AUC 0.6247 | test AP 0.2127
Epoch 029 | train loss 0.3642 | val AUC 0.6749 | val AP 0.2452 | test AUC 0.6254 | test AP 0.2137
Epoch 030 | train loss 0.3642 | val AUC 0.6770 | val AP 0.2488 | test AUC 0.6274 | test AP 0.2150
Epoch 031 | train loss 0.3648 | val AUC 0.6767 | val AP 0.2469 | test AUC 0.6278 | test AP 0.2164
Epoch 032 | train loss 0.3644 | val AUC 0.6748 | val AP 0.2452 | test AUC 0.6268 | test AP 0.2170
Epoch 033 | train loss 0.3642 | val AUC 0.6749 | val AP 0.2463 | test AUC 0.6275 | test AP 0.2194
Epoch 034 | train loss 0.3643 | val AUC 0.6786 | val AP 0.2513 | test AUC 0.6312 | test AP 0.2193
Epoch 035 | train loss 0.3649 | val AUC 0.6806 | val AP 0.2566 | test AUC 0.6330 | test AP 0.2205
Epoch 036 | train loss 0.3625 | val AUC 0.6832 | val AP 0.2590 | test AUC 0.6356 | test AP 0.2234
Epoch 037 | train loss 0.3636 | val AUC 0.6829 | val AP 0.2625 | test AUC 0.6355 | test AP 0.2224
Epoch 038 | train loss 0.3633 | val AUC 0.6814 | val AP 0.2573 | test AUC 0.6343 | test AP 0.2262
Epoch 039 | train loss 0.3606 | val AUC 0.6841 | val AP 0.2607 | test AUC 0.6380 | test AP 0.2285
Epoch 040 | train loss 0.3626 | val AUC 0.6838 | val AP 0.2586 | test AUC 0.6378 | test AP 0.2305
Epoch 041 | train loss 0.3608 | val AUC 0.6881 | val AP 0.2659 | test AUC 0.6427 | test AP 0.2315
Epoch 042 | train loss 0.3599 | val AUC 0.6888 | val AP 0.2674 | test AUC 0.6436 | test AP 0.2336
Epoch 043 | train loss 0.3589 | val AUC 0.6915 | val AP 0.2712 | test AUC 0.6462 | test AP 0.2353
Epoch 044 | train loss 0.3613 | val AUC 0.6918 | val AP 0.2704 | test AUC 0.6466 | test AP 0.2361
Epoch 045 | train loss 0.3579 | val AUC 0.6953 | val AP 0.2767 | test AUC 0.6506 | test AP 0.2387
Epoch 046 | train loss 0.3606 | val AUC 0.6948 | val AP 0.2762 | test AUC 0.6509 | test AP 0.2393
Epoch 047 | train loss 0.3581 | val AUC 0.6943 | val AP 0.2758 | test AUC 0.6497 | test AP 0.2387
Epoch 048 | train loss 0.3596 | val AUC 0.6998 | val AP 0.2820 | test AUC 0.6569 | test AP 0.2472
Epoch 049 | train loss 0.3572 | val AUC 0.6989 | val AP 0.2824 | test AUC 0.6552 | test AP 0.2451
Epoch 050 | train loss 0.3564 | val AUC 0.7043 | val AP 0.2881 | test AUC 0.6624 | test AP 0.2505
wandb: ⢿ updating run metadata (0.0s)
wandb: ⣻ updating run metadata (0.0s)
wandb: ⣽ updating run metadata (0.0s)
wandb: ⣾ updating run metadata (0.0s)
wandb: ⣷ updating run metadata (0.0s)
wandb: ⣯ uploading output.log 4.8KB/4.8KB (0.1s)
wandb: ⣯ uploading wandb-summary.json 364B/364B (0.1s)
wandb: ⣯ uploading config.yaml 3.5KB/3.5KB (0.1s)
wandb: ⣟ uploading output.log 4.8KB/4.8KB (0.1s)
wandb: ⣟ uploading wandb-summary.json 364B/364B (0.1s)
wandb: ⣟ uploading config.yaml 3.5KB/3.5KB (0.1s)
wandb: ⡿ uploading output.log 4.8KB/4.8KB (0.1s)
wandb: ⡿ uploading wandb-summary.json 364B/364B (0.1s)
wandb: ⡿ uploading config.yaml 3.5KB/3.5KB (0.1s)
wandb:
wandb: Run history:
wandb:      epoch ▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:    test/ap ▁▁▁▂▂▃▃▃▄▄▄▄▄▄▄▄▄▄▅▅▅▅▅▅▅▅▅▆▆▆▆▆▆▆▇▇▇▇██
wandb:   test/auc ▁▃▅▅▅▅▆▆▅▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▇▇▇▇▇▇▇▇▇▇▇▇█
wandb:  test/loss █▆▅▅▅▅▄▅▅▅▄▄▅▅▄▄▅▄▆▄▅▄▃▃▄▃▃▄▆▃▂▃▂▂▂▂▁▃▁▁
wandb: train/loss █▅▄▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▂▂▂▂▂▁▁▂▁▁▁
wandb:     val/ap ▁▃▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▆▆▆▆▆▆▆▆▆▆▇▇▇▇▇▇▇▇▇▇██
wandb:    val/auc ▁▃▅▆▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇██████
wandb:   val/loss █▇▆▅▅▄▄▄▄▄▃▃▃▄▃▃▄▃▃▃▃▃▂▃▂▃▂▃▄▂▂▂▂▁▁▁▁▂▁▁
wandb:
wandb: Run summary:
wandb:   best_epoch 50
wandb: best_val_auc 0.70435
wandb:        epoch 50
wandb:      test/ap 0.25053
wandb:     test/auc 0.66237
wandb:    test/loss 0.35887
wandb:   train/loss 0.35635
wandb:       val/ap 0.28809
wandb:      val/auc 0.70435
wandb:     val/loss 0.35343
wandb:
wandb: 🚀 View run mo_gcn_syn_Hospitalization_clean_ep50_layer2_hidden64_lr0.001_bs32 at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/bdtlnkhi
wandb: ⭐️ View project at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260709_105935-bdtlnkhi/logs
[2026-07-09 10:59:54,822][HYDRA] 	#1 : model=gcn data=dataset_syn training.epochs=50 data.target=Hospitalization model.num_layers=3
data:
  name: syn
  target: Hospitalization
  evaluator_type: synthethic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_edges.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_samples_nooverlap.csv
      multihospital: synthetic_pharmacotherapy_v2_samples_multihospital.csv
    scenario: clean
model:
  name: gcn
  hidden_dim: 64
  num_layers: 3
  dropout: 0.2
  batch_norm: true
  activation: relu
training:
  lr: 0.001
  epochs: 50
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
meta:
  owner_initials: mo
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis
  run_name: ${meta.owner_initials}_${model.name}_${data.name}_${data.target}_${data.dataset.scenario}_ep${training.epochs}_layer${model.num_layers}_hidden${model.hidden_dim}_lr${training.lr}_bs${training.batch_size}

wandb: ⢿ setting up run zt1026ll (0.0s)
wandb: ⣻ setting up run zt1026ll (0.0s)
wandb: ⣽ setting up run zt1026ll (0.0s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260709_105954-zt1026ll
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run mo_gcn_syn_Hospitalization_clean_ep50_layer3_hidden64_lr0.001_bs32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/zt1026ll
Epoch 001 | train loss 0.3955 | val AUC 0.5143 | val AP 0.1530 | test AUC 0.5337 | test AP 0.1632
Epoch 002 | train loss 0.3789 | val AUC 0.6116 | val AP 0.2083 | test AUC 0.5839 | test AP 0.1571
Epoch 003 | train loss 0.3741 | val AUC 0.6626 | val AP 0.2126 | test AUC 0.5978 | test AP 0.1624
Epoch 004 | train loss 0.3727 | val AUC 0.6708 | val AP 0.2143 | test AUC 0.6005 | test AP 0.1685
Epoch 005 | train loss 0.3734 | val AUC 0.6719 | val AP 0.2144 | test AUC 0.6005 | test AP 0.1750
Epoch 006 | train loss 0.3712 | val AUC 0.6716 | val AP 0.2129 | test AUC 0.6021 | test AP 0.1789
Epoch 007 | train loss 0.3711 | val AUC 0.6723 | val AP 0.2143 | test AUC 0.6051 | test AP 0.1798
Epoch 008 | train loss 0.3723 | val AUC 0.6729 | val AP 0.2164 | test AUC 0.6060 | test AP 0.1822
Epoch 009 | train loss 0.3709 | val AUC 0.6735 | val AP 0.2178 | test AUC 0.6076 | test AP 0.1826
Epoch 010 | train loss 0.3702 | val AUC 0.6734 | val AP 0.2197 | test AUC 0.6104 | test AP 0.1872
Epoch 011 | train loss 0.3691 | val AUC 0.6746 | val AP 0.2220 | test AUC 0.6121 | test AP 0.1893
Epoch 012 | train loss 0.3699 | val AUC 0.6763 | val AP 0.2259 | test AUC 0.6167 | test AP 0.1937
Epoch 013 | train loss 0.3699 | val AUC 0.6758 | val AP 0.2267 | test AUC 0.6187 | test AP 0.1974
Epoch 014 | train loss 0.3679 | val AUC 0.6736 | val AP 0.2277 | test AUC 0.6200 | test AP 0.2009
Epoch 015 | train loss 0.3682 | val AUC 0.6751 | val AP 0.2315 | test AUC 0.6226 | test AP 0.2027
Epoch 016 | train loss 0.3681 | val AUC 0.6751 | val AP 0.2347 | test AUC 0.6244 | test AP 0.2020
Epoch 017 | train loss 0.3665 | val AUC 0.6761 | val AP 0.2386 | test AUC 0.6260 | test AP 0.2043
Epoch 018 | train loss 0.3668 | val AUC 0.6804 | val AP 0.2429 | test AUC 0.6290 | test AP 0.2060
Epoch 019 | train loss 0.3671 | val AUC 0.6737 | val AP 0.2406 | test AUC 0.6290 | test AP 0.2089
Epoch 020 | train loss 0.3670 | val AUC 0.6811 | val AP 0.2470 | test AUC 0.6323 | test AP 0.2101
Epoch 021 | train loss 0.3640 | val AUC 0.6805 | val AP 0.2471 | test AUC 0.6338 | test AP 0.2122
Epoch 022 | train loss 0.3646 | val AUC 0.6831 | val AP 0.2540 | test AUC 0.6371 | test AP 0.2119
Epoch 023 | train loss 0.3667 | val AUC 0.6838 | val AP 0.2545 | test AUC 0.6394 | test AP 0.2154
Epoch 024 | train loss 0.3638 | val AUC 0.6840 | val AP 0.2567 | test AUC 0.6413 | test AP 0.2194
Epoch 025 | train loss 0.3646 | val AUC 0.6875 | val AP 0.2603 | test AUC 0.6436 | test AP 0.2214
Epoch 026 | train loss 0.3619 | val AUC 0.6898 | val AP 0.2655 | test AUC 0.6471 | test AP 0.2235
Epoch 027 | train loss 0.3618 | val AUC 0.6934 | val AP 0.2706 | test AUC 0.6526 | test AP 0.2272
Epoch 028 | train loss 0.3635 | val AUC 0.6915 | val AP 0.2667 | test AUC 0.6504 | test AP 0.2261
Epoch 029 | train loss 0.3597 | val AUC 0.6941 | val AP 0.2708 | test AUC 0.6562 | test AP 0.2296
Epoch 030 | train loss 0.3597 | val AUC 0.7025 | val AP 0.2807 | test AUC 0.6669 | test AP 0.2348
Epoch 031 | train loss 0.3606 | val AUC 0.7044 | val AP 0.2943 | test AUC 0.6689 | test AP 0.2382
Epoch 032 | train loss 0.3624 | val AUC 0.7040 | val AP 0.3036 | test AUC 0.6682 | test AP 0.2396
Epoch 033 | train loss 0.3575 | val AUC 0.7096 | val AP 0.3081 | test AUC 0.6771 | test AP 0.2437
Epoch 034 | train loss 0.3620 | val AUC 0.7100 | val AP 0.3034 | test AUC 0.6784 | test AP 0.2432
Epoch 035 | train loss 0.3584 | val AUC 0.7083 | val AP 0.3032 | test AUC 0.6737 | test AP 0.2430
Epoch 036 | train loss 0.3562 | val AUC 0.7138 | val AP 0.3094 | test AUC 0.6811 | test AP 0.2458
Epoch 037 | train loss 0.3544 | val AUC 0.7185 | val AP 0.3125 | test AUC 0.6890 | test AP 0.2502
Epoch 038 | train loss 0.3546 | val AUC 0.7241 | val AP 0.3275 | test AUC 0.6935 | test AP 0.2578
Epoch 039 | train loss 0.3510 | val AUC 0.7392 | val AP 0.3485 | test AUC 0.7147 | test AP 0.2743
Epoch 040 | train loss 0.3525 | val AUC 0.7400 | val AP 0.3437 | test AUC 0.7175 | test AP 0.2709
Epoch 041 | train loss 0.3483 | val AUC 0.7414 | val AP 0.3421 | test AUC 0.7148 | test AP 0.2727
Epoch 042 | train loss 0.3465 | val AUC 0.7487 | val AP 0.3508 | test AUC 0.7240 | test AP 0.2786
Epoch 043 | train loss 0.3441 | val AUC 0.7563 | val AP 0.3581 | test AUC 0.7330 | test AP 0.2844
Epoch 044 | train loss 0.3433 | val AUC 0.7692 | val AP 0.3786 | test AUC 0.7502 | test AP 0.2981
Epoch 045 | train loss 0.3395 | val AUC 0.7781 | val AP 0.3883 | test AUC 0.7588 | test AP 0.3080
Epoch 046 | train loss 0.3392 | val AUC 0.7816 | val AP 0.3972 | test AUC 0.7624 | test AP 0.3124
Epoch 047 | train loss 0.3406 | val AUC 0.7867 | val AP 0.4274 | test AUC 0.7655 | test AP 0.3206
Epoch 048 | train loss 0.3357 | val AUC 0.8022 | val AP 0.4354 | test AUC 0.7938 | test AP 0.3422
Epoch 049 | train loss 0.3304 | val AUC 0.8067 | val AP 0.4438 | test AUC 0.7925 | test AP 0.3417
Epoch 050 | train loss 0.3267 | val AUC 0.8214 | val AP 0.4450 | test AUC 0.8134 | test AP 0.3587
wandb: ⢿ updating run metadata (0.0s)
wandb: ⣻ updating run metadata (0.0s)
wandb: ⣽ updating run metadata (0.0s)
wandb: ⣾ updating run metadata (0.0s)
wandb: ⣷ Finishing up...
wandb: ⣯ Finishing up...
wandb: ⣟ Finishing up...
wandb: ⡿ Finishing up...
wandb: ⢿ Finishing up...
wandb: ⣻ uploading history steps 37-49, summary, console lines 38-49 (0.3s)
wandb: ⣽ uploading history steps 37-49, summary, console lines 38-49 (0.3s)
wandb: ⣾ uploading history steps 37-49, summary, console lines 38-49 (0.3s)
wandb: ⣷ uploading history steps 37-49, summary, console lines 38-49 (0.3s)
wandb: ⣯ uploading history steps 37-49, summary, console lines 38-49 (0.3s)
wandb:
wandb: Run history:
wandb:      epoch ▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▄▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:    test/ap ▁▁▁▁▂▂▂▂▂▂▃▃▃▃▃▃▃▃▃▃▃▃▄▄▄▄▄▄▄▄▅▅▅▅▅▆▆▇▇█
wandb:   test/auc ▁▂▃▃▃▃▃▃▃▃▃▃▃▃▃▄▄▄▄▄▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇██
wandb:  test/loss ███▇███▇█▇▇▇▇▇█▇▇▇▇▇▇▇▇▇▇▇▆▆▆▆▆▅▅▅▄▄▅▄▂▁
wandb: train/loss █▆▆▆▆▆▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▄▄▄▄▅▄▄▄▃▄▃▃▃▂▂▂▂▁
wandb:     val/ap ▁▂▂▂▂▃▃▃▃▃▃▃▃▃▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇███
wandb:    val/auc ▁▃▄▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇██
wandb:   val/loss █▇▇▇▆▇▇▆▆▆▆▆▆▆▇▆▆▆▆▆▅▆▅▆▅▅▅▅▅▅▄▄▄▄▄▃▄▃▂▁
wandb:
wandb: Run summary:
wandb:   best_epoch 50
wandb: best_val_auc 0.82144
wandb:        epoch 50
wandb:      test/ap 0.35866
wandb:     test/auc 0.81336
wandb:    test/loss 0.32065
wandb:   train/loss 0.32674
wandb:       val/ap 0.44498
wandb:      val/auc 0.82144
wandb:     val/loss 0.3157
wandb:
wandb: 🚀 View run mo_gcn_syn_Hospitalization_clean_ep50_layer3_hidden64_lr0.001_bs32 at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/zt1026ll
wandb: ⭐️ View project at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260709_105954-zt1026ll/logs
[2026-07-09 11:00:17,727][HYDRA] 	#2 : model=gcn data=dataset_syn training.epochs=50 data.target=Hospitalization model.num_layers=4
data:
  name: syn
  target: Hospitalization
  evaluator_type: synthethic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_edges.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_samples_nooverlap.csv
      multihospital: synthetic_pharmacotherapy_v2_samples_multihospital.csv
    scenario: clean
model:
  name: gcn
  hidden_dim: 64
  num_layers: 4
  dropout: 0.2
  batch_norm: true
  activation: relu
training:
  lr: 0.001
  epochs: 50
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
meta:
  owner_initials: mo
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis
  run_name: ${meta.owner_initials}_${model.name}_${data.name}_${data.target}_${data.dataset.scenario}_ep${training.epochs}_layer${model.num_layers}_hidden${model.hidden_dim}_lr${training.lr}_bs${training.batch_size}

wandb: ⢿ setting up run m00r2515 (0.0s)
wandb: ⣻ setting up run m00r2515 (0.0s)
wandb: ⣽ setting up run m00r2515 (0.0s)
wandb: ⣾ setting up run m00r2515 (0.0s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260709_110017-m00r2515
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run mo_gcn_syn_Hospitalization_clean_ep50_layer4_hidden64_lr0.001_bs32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/m00r2515
Epoch 001 | train loss 0.4096 | val AUC 0.5091 | val AP 0.1515 | test AUC 0.5307 | test AP 0.1641
Epoch 002 | train loss 0.3802 | val AUC 0.6041 | val AP 0.2066 | test AUC 0.5801 | test AP 0.1558
Epoch 003 | train loss 0.3770 | val AUC 0.6469 | val AP 0.2084 | test AUC 0.5907 | test AP 0.1590
Epoch 004 | train loss 0.3748 | val AUC 0.6654 | val AP 0.2087 | test AUC 0.5979 | test AP 0.1633
Epoch 005 | train loss 0.3752 | val AUC 0.6674 | val AP 0.2096 | test AUC 0.5972 | test AP 0.1648
Epoch 006 | train loss 0.3728 | val AUC 0.6720 | val AP 0.2120 | test AUC 0.5991 | test AP 0.1717
Epoch 007 | train loss 0.3718 | val AUC 0.6713 | val AP 0.2118 | test AUC 0.5997 | test AP 0.1740
Epoch 008 | train loss 0.3716 | val AUC 0.6716 | val AP 0.2130 | test AUC 0.6016 | test AP 0.1754

In [ ]:
#multirun gin
!python src/train.py --multirun model=gin data=dataset_syn training.epochs=50 data.target="Hospitalization" model.num_layers=2,3,4,6

[2026-07-09 13:09:45,748][HYDRA] Launching 4 jobs locally
[2026-07-09 13:09:45,748][HYDRA] 	#0 : model=gin data=dataset_syn training.epochs=50 data.target=Hospitalization model.num_layers=2
data:
  name: syn
  target: Hospitalization
  evaluator_type: synthetic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_edges.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_samples_nooverlap.csv
      multihospital: synthetic_pharmacotherapy_v2_samples_multihospital.csv
    scenario: clean
model:
  name: gin
  hidden_dim: 64
  num_layers: 2
  dropout: 0.2
  batch_norm: true
  activation: relu
training:
  lr: 0.001
  epochs: 50
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
  heads: 4
  dropout: 0.0
  pooling: mean
  batch_norm: true
meta:
  owner_initials: mo
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis
  run_name: ${meta.owner_initials}_${model.name}_${data.name}_${data.target}_${data.dataset.scenario}_ep${training.epochs}_layer${model.num_layers}_hidden${model.hidden_dim}_lr${training.lr}_bs${training.batch_size}

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: oskardmonika (politechnika-gnn-thesis) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: ⢿ setting up run gls11sow (0.0s)
wandb: ⣻ setting up run gls11sow (0.0s)
wandb: ⣽ setting up run gls11sow (0.0s)
wandb: ⣾ setting up run gls11sow (0.0s)
wandb: ⣷ setting up run gls11sow (0.5s)
wandb: ⣯ setting up run gls11sow (0.5s)
wandb: ⣟ setting up run gls11sow (0.5s)
wandb: ⡿ setting up run gls11sow (0.5s)
wandb: ⢿ setting up run gls11sow (0.5s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260709_130946-gls11sow
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run mo_gin_syn_Hospitalization_clean_ep50_layer2_hidden64_lr0.001_bs32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/gls11sow
Epoch 001 | train loss 0.3931 | train AUC 0.5244 | train AUPRC 0.1344 | val AUC 0.5599 | val AUPRC 0.1742 | test AUC 0.5405 | test AUPRC 0.1526
Epoch 002 | train loss 0.3798 | train AUC 0.5716 | train AUPRC 0.1499 | val AUC 0.6207 | val AUPRC 0.2373 | test AUC 0.5752 | test AUPRC 0.1608
Epoch 003 | train loss 0.3764 | train AUC 0.5898 | train AUPRC 0.1612 | val AUC 0.6460 | val AUPRC 0.2265 | test AUC 0.5855 | test AUPRC 0.1631
Epoch 004 | train loss 0.3745 | train AUC 0.6021 | train AUPRC 0.1702 | val AUC 0.6512 | val AUPRC 0.2159 | test AUC 0.5986 | test AUPRC 0.1579
Epoch 005 | train loss 0.3756 | train AUC 0.6098 | train AUPRC 0.1756 | val AUC 0.6588 | val AUPRC 0.2150 | test AUC 0.6026 | test AUPRC 0.1624
Epoch 006 | train loss 0.3753 | train AUC 0.6130 | train AUPRC 0.1781 | val AUC 0.6611 | val AUPRC 0.2090 | test AUC 0.6027 | test AUPRC 0.1643
Epoch 007 | train loss 0.3718 | train AUC 0.6170 | train AUPRC 0.1810 | val AUC 0.6573 | val AUPRC 0.2055 | test AUC 0.6063 | test AUPRC 0.1687
Epoch 008 | train loss 0.3726 | train AUC 0.6200 | train AUPRC 0.1832 | val AUC 0.6592 | val AUPRC 0.2060 | test AUC 0.6073 | test AUPRC 0.1719
Epoch 009 | train loss 0.3722 | train AUC 0.6269 | train AUPRC 0.1889 | val AUC 0.6650 | val AUPRC 0.2115 | test AUC 0.6128 | test AUPRC 0.1758
Epoch 010 | train loss 0.3722 | train AUC 0.6302 | train AUPRC 0.1916 | val AUC 0.6656 | val AUPRC 0.2130 | test AUC 0.6141 | test AUPRC 0.1786
Epoch 011 | train loss 0.3707 | train AUC 0.6375 | train AUPRC 0.1985 | val AUC 0.6688 | val AUPRC 0.2180 | test AUC 0.6203 | test AUPRC 0.1836
Epoch 012 | train loss 0.3691 | train AUC 0.6414 | train AUPRC 0.2025 | val AUC 0.6719 | val AUPRC 0.2238 | test AUC 0.6216 | test AUPRC 0.1846
Epoch 013 | train loss 0.3651 | train AUC 0.6558 | train AUPRC 0.2201 | val AUC 0.6832 | val AUPRC 0.2441 | test AUC 0.6345 | test AUPRC 0.1948
Epoch 014 | train loss 0.3632 | train AUC 0.6696 | train AUPRC 0.2354 | val AUC 0.6939 | val AUPRC 0.2663 | test AUC 0.6494 | test AUPRC 0.2076
Epoch 015 | train loss 0.3604 | train AUC 0.6826 | train AUPRC 0.2467 | val AUC 0.7052 | val AUPRC 0.2728 | test AUC 0.6639 | test AUPRC 0.2172
Epoch 016 | train loss 0.3573 | train AUC 0.6993 | train AUPRC 0.2573 | val AUC 0.7192 | val AUPRC 0.2784 | test AUC 0.6824 | test AUPRC 0.2303
Epoch 017 | train loss 0.3509 | train AUC 0.7214 | train AUPRC 0.2753 | val AUC 0.7372 | val AUPRC 0.2887 | test AUC 0.7103 | test AUPRC 0.2500
Epoch 018 | train loss 0.3490 | train AUC 0.7229 | train AUPRC 0.2999 | val AUC 0.7384 | val AUPRC 0.3195 | test AUC 0.7102 | test AUPRC 0.2509
Epoch 019 | train loss 0.3454 | train AUC 0.7410 | train AUPRC 0.3420 | val AUC 0.7536 | val AUPRC 0.3450 | test AUC 0.7281 | test AUPRC 0.2632
Epoch 020 | train loss 0.3425 | train AUC 0.7602 | train AUPRC 0.3480 | val AUC 0.7698 | val AUPRC 0.3417 | test AUC 0.7473 | test AUPRC 0.2761
Epoch 021 | train loss 0.3339 | train AUC 0.7720 | train AUPRC 0.3904 | val AUC 0.7832 | val AUPRC 0.3794 | test AUC 0.7619 | test AUPRC 0.2856
Epoch 022 | train loss 0.3272 | train AUC 0.7848 | train AUPRC 0.3909 | val AUC 0.7930 | val AUPRC 0.3730 | test AUC 0.7738 | test AUPRC 0.2966
Epoch 023 | train loss 0.3258 | train AUC 0.7921 | train AUPRC 0.4190 | val AUC 0.8017 | val AUPRC 0.3975 | test AUC 0.7781 | test AUPRC 0.3180
Epoch 024 | train loss 0.3195 | train AUC 0.8025 | train AUPRC 0.4227 | val AUC 0.8111 | val AUPRC 0.3971 | test AUC 0.7895 | test AUPRC 0.3296
Epoch 025 | train loss 0.3145 | train AUC 0.8123 | train AUPRC 0.4426 | val AUC 0.8209 | val AUPRC 0.4129 | test AUC 0.8008 | test AUPRC 0.3456
Epoch 026 | train loss 0.3078 | train AUC 0.8230 | train AUPRC 0.4646 | val AUC 0.8323 | val AUPRC 0.4400 | test AUC 0.8133 | test AUPRC 0.3516
Epoch 027 | train loss 0.3003 | train AUC 0.8245 | train AUPRC 0.4649 | val AUC 0.8385 | val AUPRC 0.4486 | test AUC 0.8106 | test AUPRC 0.3473
Epoch 028 | train loss 0.2993 | train AUC 0.8483 | train AUPRC 0.4976 | val AUC 0.8566 | val AUPRC 0.4712 | test AUC 0.8408 | test AUPRC 0.3875
Epoch 029 | train loss 0.2860 | train AUC 0.8540 | train AUPRC 0.5023 | val AUC 0.8644 | val AUPRC 0.4935 | test AUC 0.8465 | test AUPRC 0.4005
Epoch 030 | train loss 0.2827 | train AUC 0.8673 | train AUPRC 0.5244 | val AUC 0.8763 | val AUPRC 0.5213 | test AUC 0.8640 | test AUPRC 0.4322
Epoch 031 | train loss 0.2751 | train AUC 0.8801 | train AUPRC 0.5516 | val AUC 0.8879 | val AUPRC 0.5284 | test AUC 0.8777 | test AUPRC 0.4575
Epoch 032 | train loss 0.2673 | train AUC 0.8893 | train AUPRC 0.5605 | val AUC 0.8971 | val AUPRC 0.5680 | test AUC 0.8845 | test AUPRC 0.4813
Epoch 033 | train loss 0.2570 | train AUC 0.9023 | train AUPRC 0.5875 | val AUC 0.9107 | val AUPRC 0.5962 | test AUC 0.8986 | test AUPRC 0.5127
Epoch 034 | train loss 0.2447 | train AUC 0.9092 | train AUPRC 0.6153 | val AUC 0.9205 | val AUPRC 0.6295 | test AUC 0.9089 | test AUPRC 0.5420
Epoch 035 | train loss 0.2410 | train AUC 0.9206 | train AUPRC 0.6615 | val AUC 0.9323 | val AUPRC 0.6802 | test AUC 0.9252 | test AUPRC 0.6044
Epoch 036 | train loss 0.2329 | train AUC 0.9260 | train AUPRC 0.6723 | val AUC 0.9369 | val AUPRC 0.6947 | test AUC 0.9289 | test AUPRC 0.6175
Epoch 037 | train loss 0.2206 | train AUC 0.9321 | train AUPRC 0.6863 | val AUC 0.9423 | val AUPRC 0.7000 | test AUC 0.9335 | test AUPRC 0.6356
Epoch 038 | train loss 0.2170 | train AUC 0.9351 | train AUPRC 0.6988 | val AUC 0.9465 | val AUPRC 0.7105 | test AUC 0.9345 | test AUPRC 0.6385
Epoch 039 | train loss 0.2085 | train AUC 0.9358 | train AUPRC 0.6962 | val AUC 0.9486 | val AUPRC 0.7312 | test AUC 0.9380 | test AUPRC 0.6577
Epoch 040 | train loss 0.2036 | train AUC 0.9409 | train AUPRC 0.7308 | val AUC 0.9539 | val AUPRC 0.7465 | test AUC 0.9417 | test AUPRC 0.6757
Epoch 041 | train loss 0.1979 | train AUC 0.9423 | train AUPRC 0.7363 | val AUC 0.9564 | val AUPRC 0.7622 | test AUC 0.9449 | test AUPRC 0.6936
Epoch 042 | train loss 0.1918 | train AUC 0.9469 | train AUPRC 0.7557 | val AUC 0.9591 | val AUPRC 0.7599 | test AUC 0.9453 | test AUPRC 0.6919
Epoch 043 | train loss 0.1904 | train AUC 0.9506 | train AUPRC 0.7628 | val AUC 0.9615 | val AUPRC 0.7636 | test AUC 0.9489 | test AUPRC 0.7049
Epoch 044 | train loss 0.1874 | train AUC 0.9484 | train AUPRC 0.7856 | val AUC 0.9638 | val AUPRC 0.8056 | test AUC 0.9486 | test AUPRC 0.7107
Epoch 045 | train loss 0.1791 | train AUC 0.9545 | train AUPRC 0.7826 | val AUC 0.9656 | val AUPRC 0.8007 | test AUC 0.9554 | test AUPRC 0.7281
Epoch 046 | train loss 0.1809 | train AUC 0.9542 | train AUPRC 0.7948 | val AUC 0.9682 | val AUPRC 0.8335 | test AUC 0.9593 | test AUPRC 0.7522
Epoch 047 | train loss 0.1730 | train AUC 0.9556 | train AUPRC 0.8182 | val AUC 0.9706 | val AUPRC 0.8449 | test AUC 0.9591 | test AUPRC 0.7555
Epoch 048 | train loss 0.1658 | train AUC 0.9591 | train AUPRC 0.8242 | val AUC 0.9713 | val AUPRC 0.8426 | test AUC 0.9629 | test AUPRC 0.7663
Epoch 049 | train loss 0.1689 | train AUC 0.9628 | train AUPRC 0.8107 | val AUC 0.9712 | val AUPRC 0.8176 | test AUC 0.9650 | test AUPRC 0.7755
Epoch 050 | train loss 0.1604 | train AUC 0.9634 | train AUPRC 0.8125 | val AUC 0.9725 | val AUPRC 0.8317 | test AUC 0.9633 | test AUPRC 0.7610
wandb: ⢿ updating run metadata (0.0s)
wandb: ⣻ updating run metadata (0.0s)
wandb: ⣽ updating run metadata (0.0s)
wandb: ⣾ updating run metadata (0.0s)
wandb: ⣷ Finishing up...
wandb: ⣯ Finishing up...
wandb: ⣟ Finishing up...
wandb: ⡿ Finishing up...
wandb: ⢿ Finishing up...
wandb: ⣻ uploading history steps 34-49, summary, console lines 35-49 (0.2s)
wandb: ⣽ uploading history steps 34-49, summary, console lines 35-49 (0.2s)
wandb: ⣾ uploading history steps 34-49, summary, console lines 35-49 (0.2s)
wandb:
wandb: Run history:
wandb:       epoch ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:    test/auc ▁▂▂▂▂▂▂▂▂▂▃▃▃▃▄▄▄▅▅▅▅▆▅▆▆▇▇▇▇███████████
wandb:  test/auprc ▁▁▁▁▁▁▁▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▅▅▅▆▆▇▇▇▇▇█████
wandb:  test/brier ██████████▇▇▇▇▇▇▇▇▇▇█▆▆▅▅▄▄▅▃▃▂▂▂▂▂▂▂▁▁▁
wandb:   test/loss ████████▇▇▇▇▇▇▇▇▇▆▆▆▆▇▅▅▅▄▄▄▃▂▂▂▂▂▂▁▁▁▁▁
wandb:   train/auc ▁▂▂▂▂▃▃▃▃▃▃▄▄▄▄▅▅▅▅▆▆▆▆▆▇▇▇▇▇███████████
wandb: train/auprc ▁▁▁▁▁▁▁▂▂▂▂▂▂▂▂▃▃▄▄▄▄▄▄▅▅▅▅▆▆▆▇▇▇▇▇█████
wandb: train/brier ██████████▇▇▇▇▇▇▆▆▆▆▇▅▅▅▅▄▄▅▄▃▃▂▂▂▂▂▂▁▁▁
wandb:  train/loss ██▇▇▇▇▇▇▇▇▇▇▇▇▇▇▆▆▆▆▅▅▅▅▅▄▄▃▃▃▂▂▂▂▂▂▂▁▁▁
wandb:     val/auc ▁▂▂▃▃▃▃▃▃▃▃▃▄▄▄▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇██████████
wandb:          +3 ...
wandb:
wandb: Run summary:
wandb:     best_epoch 47
wandb:   best_val_auc -1
wandb: best_val_auprc 0.84492
wandb:          epoch 50
wandb:       test/auc 0.9633
wandb:     test/auprc 0.76096
wandb:     test/brier 0.05034
wandb:      test/loss 0.17628
wandb:      train/auc 0.96341
wandb:    train/auprc 0.81245
wandb:             +6 ...
wandb:
wandb: 🚀 View run mo_gin_syn_Hospitalization_clean_ep50_layer2_hidden64_lr0.001_bs32 at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/gls11sow
wandb: ⭐️ View project at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260709_130946-gls11sow/logs
[2026-07-09 13:10:11,704][HYDRA] 	#1 : model=gin data=dataset_syn training.epochs=50 data.target=Hospitalization model.num_layers=3
data:
  name: syn
  target: Hospitalization
  evaluator_type: synthetic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_edges.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_samples_nooverlap.csv
      multihospital: synthetic_pharmacotherapy_v2_samples_multihospital.csv
    scenario: clean
model:
  name: gin
  hidden_dim: 64
  num_layers: 3
  dropout: 0.2
  batch_norm: true
  activation: relu
training:
  lr: 0.001
  epochs: 50
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
  heads: 4
  dropout: 0.0
  pooling: mean
  batch_norm: true
meta:
  owner_initials: mo
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis
  run_name: ${meta.owner_initials}_${model.name}_${data.name}_${data.target}_${data.dataset.scenario}_ep${training.epochs}_layer${model.num_layers}_hidden${model.hidden_dim}_lr${training.lr}_bs${training.batch_size}

wandb: ⢿ setting up run zai6zkdg (0.0s)
wandb: ⣻ setting up run zai6zkdg (0.0s)
wandb: ⣽ setting up run zai6zkdg (0.0s)
wandb: ⣾ setting up run zai6zkdg (0.0s)
wandb: ⣷ setting up run zai6zkdg (0.5s)
wandb: ⣯ setting up run zai6zkdg (0.5s)
wandb: ⣟ setting up run zai6zkdg (0.5s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260709_131012-zai6zkdg
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run mo_gin_syn_Hospitalization_clean_ep50_layer3_hidden64_lr0.001_bs32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/zai6zkdg
Epoch 001 | train loss 0.4006 | train AUC 0.5087 | train AUPRC 0.1317 | val AUC 0.5371 | val AUPRC 0.1612 | test AUC 0.5319 | test AUPRC 0.1550
Epoch 002 | train loss 0.3811 | train AUC 0.5665 | train AUPRC 0.1483 | val AUC 0.6095 | val AUPRC 0.2175 | test AUC 0.5774 | test AUPRC 0.1725
Epoch 003 | train loss 0.3777 | train AUC 0.5824 | train AUPRC 0.1571 | val AUC 0.6352 | val AUPRC 0.2015 | test AUC 0.5845 | test AUPRC 0.1636
Epoch 004 | train loss 0.3788 | train AUC 0.5876 | train AUPRC 0.1607 | val AUC 0.6390 | val AUPRC 0.1964 | test AUC 0.5875 | test AUPRC 0.1645
Epoch 005 | train loss 0.3748 | train AUC 0.5962 | train AUPRC 0.1660 | val AUC 0.6472 | val AUPRC 0.1923 | test AUC 0.5904 | test AUPRC 0.1683
Epoch 006 | train loss 0.3746 | train AUC 0.5971 | train AUPRC 0.1671 | val AUC 0.6441 | val AUPRC 0.1921 | test AUC 0.5922 | test AUPRC 0.1700
Epoch 007 | train loss 0.3762 | train AUC 0.5984 | train AUPRC 0.1681 | val AUC 0.6458 | val AUPRC 0.1938 | test AUC 0.5918 | test AUPRC 0.1707
Epoch 008 | train loss 0.3754 | train AUC 0.6002 | train AUPRC 0.1699 | val AUC 0.6472 | val AUPRC 0.1954 | test AUC 0.5919 | test AUPRC 0.1716
Epoch 009 | train loss 0.3752 | train AUC 0.6016 | train AUPRC 0.1715 | val AUC 0.6487 | val AUPRC 0.1961 | test AUC 0.5934 | test AUPRC 0.1755
Epoch 010 | train loss 0.3747 | train AUC 0.6025 | train AUPRC 0.1723 | val AUC 0.6480 | val AUPRC 0.1944 | test AUC 0.5932 | test AUPRC 0.1760
Epoch 011 | train loss 0.3753 | train AUC 0.6038 | train AUPRC 0.1733 | val AUC 0.6471 | val AUPRC 0.1922 | test AUC 0.5924 | test AUPRC 0.1763
Epoch 012 | train loss 0.3743 | train AUC 0.6038 | train AUPRC 0.1734 | val AUC 0.6472 | val AUPRC 0.1940 | test AUC 0.5929 | test AUPRC 0.1763
Epoch 013 | train loss 0.3727 | train AUC 0.6047 | train AUPRC 0.1743 | val AUC 0.6465 | val AUPRC 0.1957 | test AUC 0.5951 | test AUPRC 0.1763
Epoch 014 | train loss 0.3736 | train AUC 0.6059 | train AUPRC 0.1763 | val AUC 0.6466 | val AUPRC 0.1931 | test AUC 0.5931 | test AUPRC 0.1765
Epoch 015 | train loss 0.3730 | train AUC 0.6054 | train AUPRC 0.1762 | val AUC 0.6436 | val AUPRC 0.1922 | test AUC 0.5934 | test AUPRC 0.1765
Epoch 016 | train loss 0.3728 | train AUC 0.6067 | train AUPRC 0.1778 | val AUC 0.6445 | val AUPRC 0.1934 | test AUC 0.5947 | test AUPRC 0.1685
Epoch 017 | train loss 0.3735 | train AUC 0.6072 | train AUPRC 0.1781 | val AUC 0.6455 | val AUPRC 0.1950 | test AUC 0.5948 | test AUPRC 0.1676
Epoch 018 | train loss 0.3727 | train AUC 0.6090 | train AUPRC 0.1781 | val AUC 0.6479 | val AUPRC 0.1972 | test AUC 0.5964 | test AUPRC 0.1674
Epoch 019 | train loss 0.3724 | train AUC 0.6110 | train AUPRC 0.1797 | val AUC 0.6501 | val AUPRC 0.1986 | test AUC 0.5982 | test AUPRC 0.1696
Epoch 020 | train loss 0.3731 | train AUC 0.6114 | train AUPRC 0.1802 | val AUC 0.6494 | val AUPRC 0.1990 | test AUC 0.5984 | test AUPRC 0.1694
Epoch 021 | train loss 0.3732 | train AUC 0.6135 | train AUPRC 0.1819 | val AUC 0.6497 | val AUPRC 0.2009 | test AUC 0.6010 | test AUPRC 0.1700
Epoch 022 | train loss 0.3730 | train AUC 0.6146 | train AUPRC 0.1824 | val AUC 0.6486 | val AUPRC 0.1987 | test AUC 0.6010 | test AUPRC 0.1704
Epoch 023 | train loss 0.3723 | train AUC 0.6163 | train AUPRC 0.1839 | val AUC 0.6496 | val AUPRC 0.2004 | test AUC 0.6030 | test AUPRC 0.1717
Epoch 024 | train loss 0.3716 | train AUC 0.6160 | train AUPRC 0.1842 | val AUC 0.6505 | val AUPRC 0.2030 | test AUC 0.6032 | test AUPRC 0.1712
Epoch 025 | train loss 0.3715 | train AUC 0.6186 | train AUPRC 0.1859 | val AUC 0.6518 | val AUPRC 0.2014 | test AUC 0.6053 | test AUPRC 0.1732
Epoch 026 | train loss 0.3716 | train AUC 0.6212 | train AUPRC 0.1879 | val AUC 0.6541 | val AUPRC 0.2034 | test AUC 0.6083 | test AUPRC 0.1752
Epoch 027 | train loss 0.3717 | train AUC 0.6229 | train AUPRC 0.1895 | val AUC 0.6543 | val AUPRC 0.2044 | test AUC 0.6099 | test AUPRC 0.1758
Epoch 028 | train loss 0.3703 | train AUC 0.6251 | train AUPRC 0.1925 | val AUC 0.6568 | val AUPRC 0.2080 | test AUC 0.6124 | test AUPRC 0.1766
Epoch 029 | train loss 0.3694 | train AUC 0.6453 | train AUPRC 0.2107 | val AUC 0.6732 | val AUPRC 0.2277 | test AUC 0.6379 | test AUPRC 0.1992
Epoch 030 | train loss 0.3640 | train AUC 0.7002 | train AUPRC 0.2692 | val AUC 0.7207 | val AUPRC 0.3164 | test AUC 0.7081 | test AUPRC 0.2664
Epoch 031 | train loss 0.3543 | train AUC 0.7829 | train AUPRC 0.3864 | val AUC 0.7893 | val AUPRC 0.4363 | test AUC 0.7874 | test AUPRC 0.3974
Epoch 032 | train loss 0.2835 | train AUC 0.9408 | train AUPRC 0.7238 | val AUC 0.9435 | val AUPRC 0.7625 | test AUC 0.9554 | test AUPRC 0.8095
Epoch 033 | train loss 0.1908 | train AUC 0.9736 | train AUPRC 0.8591 | val AUC 0.9825 | val AUPRC 0.9014 | test AUC 0.9772 | test AUPRC 0.9154
Epoch 034 | train loss 0.1536 | train AUC 0.9826 | train AUPRC 0.9054 | val AUC 0.9902 | val AUPRC 0.9387 | test AUC 0.9808 | test AUPRC 0.9255
Epoch 035 | train loss 0.1188 | train AUC 0.9902 | train AUPRC 0.9537 | val AUC 0.9953 | val AUPRC 0.9740 | test AUC 0.9854 | test AUPRC 0.9517
Epoch 036 | train loss 0.0957 | train AUC 0.9959 | train AUPRC 0.9776 | val AUC 0.9987 | val AUPRC 0.9922 | test AUC 0.9915 | test AUPRC 0.9629
Epoch 037 | train loss 0.0625 | train AUC 0.9979 | train AUPRC 0.9863 | val AUC 0.9995 | val AUPRC 0.9971 | test AUC 0.9951 | test AUPRC 0.9758
Epoch 038 | train loss 0.0566 | train AUC 0.9985 | train AUPRC 0.9931 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 0.9970 | test AUPRC 0.9863
Epoch 039 | train loss 0.0363 | train AUC 0.9991 | train AUPRC 0.9960 | val AUC 0.9998 | val AUPRC 0.9987 | test AUC 0.9979 | test AUPRC 0.9901
Epoch 040 | train loss 0.0308 | train AUC 0.9978 | train AUPRC 0.9919 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 0.9964 | test AUPRC 0.9839
Epoch 041 | train loss 0.0255 | train AUC 0.9999 | train AUPRC 0.9992 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 0.9991 | test AUPRC 0.9954
Epoch 042 | train loss 0.0131 | train AUC 0.9999 | train AUPRC 0.9996 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 0.9997 | test AUPRC 0.9980
Epoch 043 | train loss 0.0155 | train AUC 0.9997 | train AUPRC 0.9985 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 0.9993 | test AUPRC 0.9960
Epoch 044 | train loss 0.0078 | train AUC 0.9999 | train AUPRC 0.9995 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 0.9998 | test AUPRC 0.9987
Epoch 045 | train loss 0.0099 | train AUC 0.9999 | train AUPRC 0.9995 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 0.9997 | test AUPRC 0.9982

In [ ]:
#multirun gat
!python src/train.py --multirun model=gat data=dataset_syn training.epochs=50 data.target="Hospitalization" model.num_layers=2,4,6

[2026-07-09 13:21:23,984][HYDRA] Launching 3 jobs locally
[2026-07-09 13:21:23,985][HYDRA] 	#0 : model=gat data=dataset_syn training.epochs=50 data.target=Hospitalization model.num_layers=2
data:
  name: syn
  target: Hospitalization
  evaluator_type: synthetic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_edges.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_samples_nooverlap.csv
      multihospital: synthetic_pharmacotherapy_v2_samples_multihospital.csv
    scenario: clean
model:
  name: gat
  hidden_dim: 64
  num_layers: 2
  dropout: 0.2
  batch_norm: true
  activation: relu
  heads: 4
training:
  lr: 0.001
  epochs: 50
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
  heads: 4
  dropout: 0.0
  pooling: mean
  batch_norm: true
meta:
  owner_initials: mo
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis
  run_name: ${meta.owner_initials}_${model.name}_${data.name}_${data.target}_${data.dataset.scenario}_ep${training.epochs}_layer${model.num_layers}_hidden${model.hidden_dim}_lr${training.lr}_bs${training.batch_size}

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: oskardmonika (politechnika-gnn-thesis) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: ⢿ setting up run f0t15u5i (0.0s)
wandb: ⣻ setting up run f0t15u5i (0.0s)
wandb: ⣽ setting up run f0t15u5i (0.0s)
wandb: ⣾ setting up run f0t15u5i (0.0s)
wandb: ⣷ setting up run f0t15u5i (0.5s)
wandb: ⣯ setting up run f0t15u5i (0.5s)
wandb: ⣟ setting up run f0t15u5i (0.5s)
wandb: ⡿ setting up run f0t15u5i (0.5s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260709_132124-f0t15u5i
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run mo_gat_syn_Hospitalization_clean_ep50_layer2_hidden64_lr0.001_bs32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/f0t15u5i
Epoch 001 | train loss 0.4178 | train AUC 0.4645 | train AUPRC 0.1195 | val AUC 0.4741 | val AUPRC 0.1453 | test AUC 0.4980 | test AUPRC 0.1447
Epoch 002 | train loss 0.3847 | train AUC 0.4692 | train AUPRC 0.1210 | val AUC 0.4805 | val AUPRC 0.1521 | test AUC 0.5025 | test AUPRC 0.1465
Epoch 003 | train loss 0.3836 | train AUC 0.4812 | train AUPRC 0.1246 | val AUC 0.4944 | val AUPRC 0.1733 | test AUC 0.5119 | test AUPRC 0.1499
Epoch 004 | train loss 0.3813 | train AUC 0.5041 | train AUPRC 0.1313 | val AUC 0.5241 | val AUPRC 0.1968 | test AUC 0.5306 | test AUPRC 0.1544
Epoch 005 | train loss 0.3800 | train AUC 0.5341 | train AUPRC 0.1413 | val AUC 0.5624 | val AUPRC 0.2043 | test AUC 0.5546 | test AUPRC 0.1491
Epoch 006 | train loss 0.3780 | train AUC 0.5691 | train AUPRC 0.1545 | val AUC 0.6066 | val AUPRC 0.2079 | test AUC 0.5820 | test AUPRC 0.1633
Epoch 007 | train loss 0.3762 | train AUC 0.6059 | train AUPRC 0.1723 | val AUC 0.6514 | val AUPRC 0.2087 | test AUC 0.6060 | test AUPRC 0.1579
Epoch 008 | train loss 0.3766 | train AUC 0.6195 | train AUPRC 0.1807 | val AUC 0.6657 | val AUPRC 0.2153 | test AUC 0.6133 | test AUPRC 0.1638
Epoch 009 | train loss 0.3731 | train AUC 0.6266 | train AUPRC 0.1860 | val AUC 0.6713 | val AUPRC 0.2170 | test AUC 0.6145 | test AUPRC 0.1692
Epoch 010 | train loss 0.3725 | train AUC 0.6293 | train AUPRC 0.1894 | val AUC 0.6714 | val AUPRC 0.2165 | test AUC 0.6131 | test AUPRC 0.1731
Epoch 011 | train loss 0.3720 | train AUC 0.6311 | train AUPRC 0.1924 | val AUC 0.6717 | val AUPRC 0.2159 | test AUC 0.6125 | test AUPRC 0.1776
Epoch 012 | train loss 0.3712 | train AUC 0.6293 | train AUPRC 0.1922 | val AUC 0.6696 | val AUPRC 0.2136 | test AUC 0.6072 | test AUPRC 0.1777
Epoch 013 | train loss 0.3706 | train AUC 0.6283 | train AUPRC 0.1921 | val AUC 0.6679 | val AUPRC 0.2118 | test AUC 0.6045 | test AUPRC 0.1785
Epoch 014 | train loss 0.3712 | train AUC 0.6284 | train AUPRC 0.1923 | val AUC 0.6680 | val AUPRC 0.2117 | test AUC 0.6055 | test AUPRC 0.1792
Epoch 015 | train loss 0.3699 | train AUC 0.6290 | train AUPRC 0.1926 | val AUC 0.6686 | val AUPRC 0.2121 | test AUC 0.6066 | test AUPRC 0.1788
Epoch 016 | train loss 0.3710 | train AUC 0.6277 | train AUPRC 0.1921 | val AUC 0.6667 | val AUPRC 0.2102 | test AUC 0.6035 | test AUPRC 0.1797
Epoch 017 | train loss 0.3694 | train AUC 0.6286 | train AUPRC 0.1925 | val AUC 0.6682 | val AUPRC 0.2117 | test AUC 0.6064 | test AUPRC 0.1786
Epoch 018 | train loss 0.3707 | train AUC 0.6273 | train AUPRC 0.1922 | val AUC 0.6664 | val AUPRC 0.2094 | test AUC 0.6039 | test AUPRC 0.1795
Epoch 019 | train loss 0.3700 | train AUC 0.6271 | train AUPRC 0.1924 | val AUC 0.6656 | val AUPRC 0.2089 | test AUC 0.6032 | test AUPRC 0.1791
Epoch 020 | train loss 0.3694 | train AUC 0.6268 | train AUPRC 0.1926 | val AUC 0.6649 | val AUPRC 0.2080 | test AUC 0.6019 | test AUPRC 0.1791
Epoch 021 | train loss 0.3693 | train AUC 0.6258 | train AUPRC 0.1920 | val AUC 0.6633 | val AUPRC 0.2057 | test AUC 0.6003 | test AUPRC 0.1791
Epoch 022 | train loss 0.3698 | train AUC 0.6263 | train AUPRC 0.1924 | val AUC 0.6641 | val AUPRC 0.2069 | test AUC 0.6012 | test AUPRC 0.1790
Epoch 023 | train loss 0.3695 | train AUC 0.6268 | train AUPRC 0.1927 | val AUC 0.6643 | val AUPRC 0.2073 | test AUC 0.6017 | test AUPRC 0.1792
Epoch 024 | train loss 0.3695 | train AUC 0.6266 | train AUPRC 0.1928 | val AUC 0.6641 | val AUPRC 0.2072 | test AUC 0.6016 | test AUPRC 0.1789
Epoch 025 | train loss 0.3701 | train AUC 0.6256 | train AUPRC 0.1920 | val AUC 0.6633 | val AUPRC 0.2064 | test AUC 0.6004 | test AUPRC 0.1791
Epoch 026 | train loss 0.3693 | train AUC 0.6255 | train AUPRC 0.1923 | val AUC 0.6635 | val AUPRC 0.2062 | test AUC 0.6004 | test AUPRC 0.1794
Epoch 027 | train loss 0.3691 | train AUC 0.6261 | train AUPRC 0.1926 | val AUC 0.6634 | val AUPRC 0.2069 | test AUC 0.6006 | test AUPRC 0.1793
Epoch 028 | train loss 0.3697 | train AUC 0.6261 | train AUPRC 0.1925 | val AUC 0.6634 | val AUPRC 0.2066 | test AUC 0.6002 | test AUPRC 0.1792
Epoch 029 | train loss 0.3697 | train AUC 0.6259 | train AUPRC 0.1925 | val AUC 0.6628 | val AUPRC 0.2059 | test AUC 0.5999 | test AUPRC 0.1798
Epoch 030 | train loss 0.3688 | train AUC 0.6276 | train AUPRC 0.1936 | val AUC 0.6654 | val AUPRC 0.2092 | test AUC 0.6030 | test AUPRC 0.1817
Epoch 031 | train loss 0.3692 | train AUC 0.6265 | train AUPRC 0.1931 | val AUC 0.6629 | val AUPRC 0.2067 | test AUC 0.6000 | test AUPRC 0.1815
Epoch 032 | train loss 0.3694 | train AUC 0.6261 | train AUPRC 0.1932 | val AUC 0.6622 | val AUPRC 0.2060 | test AUC 0.5996 | test AUPRC 0.1815
Epoch 033 | train loss 0.3692 | train AUC 0.6266 | train AUPRC 0.1936 | val AUC 0.6624 | val AUPRC 0.2068 | test AUC 0.5999 | test AUPRC 0.1810
Epoch 034 | train loss 0.3689 | train AUC 0.6271 | train AUPRC 0.1937 | val AUC 0.6628 | val AUPRC 0.2074 | test AUC 0.6004 | test AUPRC 0.1819
Epoch 035 | train loss 0.3690 | train AUC 0.6271 | train AUPRC 0.1940 | val AUC 0.6624 | val AUPRC 0.2079 | test AUC 0.6006 | test AUPRC 0.1817
Epoch 036 | train loss 0.3689 | train AUC 0.6272 | train AUPRC 0.1941 | val AUC 0.6617 | val AUPRC 0.2069 | test AUC 0.5998 | test AUPRC 0.1821
Epoch 037 | train loss 0.3684 | train AUC 0.6274 | train AUPRC 0.1942 | val AUC 0.6621 | val AUPRC 0.2075 | test AUC 0.6000 | test AUPRC 0.1826
Epoch 038 | train loss 0.3687 | train AUC 0.6272 | train AUPRC 0.1942 | val AUC 0.6617 | val AUPRC 0.2070 | test AUC 0.5991 | test AUPRC 0.1825
Epoch 039 | train loss 0.3687 | train AUC 0.6281 | train AUPRC 0.1949 | val AUC 0.6622 | val AUPRC 0.2092 | test AUC 0.6010 | test AUPRC 0.1848
Epoch 040 | train loss 0.3692 | train AUC 0.6282 | train AUPRC 0.1949 | val AUC 0.6627 | val AUPRC 0.2098 | test AUC 0.6017 | test AUPRC 0.1848
Epoch 041 | train loss 0.3690 | train AUC 0.6270 | train AUPRC 0.1946 | val AUC 0.6611 | val AUPRC 0.2072 | test AUC 0.5982 | test AUPRC 0.1837
Epoch 042 | train loss 0.3682 | train AUC 0.6282 | train AUPRC 0.1950 | val AUC 0.6620 | val AUPRC 0.2088 | test AUC 0.6010 | test AUPRC 0.1855
Epoch 043 | train loss 0.3685 | train AUC 0.6274 | train AUPRC 0.1950 | val AUC 0.6613 | val AUPRC 0.2078 | test AUC 0.5989 | test AUPRC 0.1852
Epoch 044 | train loss 0.3681 | train AUC 0.6269 | train AUPRC 0.1947 | val AUC 0.6605 | val AUPRC 0.2078 | test AUC 0.5981 | test AUPRC 0.1844
Epoch 045 | train loss 0.3693 | train AUC 0.6274 | train AUPRC 0.1950 | val AUC 0.6612 | val AUPRC 0.2083 | test AUC 0.5988 | test AUPRC 0.1859
Epoch 046 | train loss 0.3684 | train AUC 0.6281 | train AUPRC 0.1953 | val AUC 0.6618 | val AUPRC 0.2089 | test AUC 0.5994 | test AUPRC 0.1858
Epoch 047 | train loss 0.3683 | train AUC 0.6276 | train AUPRC 0.1953 | val AUC 0.6607 | val AUPRC 0.2086 | test AUC 0.5993 | test AUPRC 0.1872
Epoch 048 | train loss 0.3681 | train AUC 0.6288 | train AUPRC 0.1958 | val AUC 0.6622 | val AUPRC 0.2104 | test AUC 0.6001 | test AUPRC 0.1854
Epoch 049 | train loss 0.3683 | train AUC 0.6285 | train AUPRC 0.1956 | val AUC 0.6619 | val AUPRC 0.2093 | test AUC 0.5999 | test AUPRC 0.1859
Epoch 050 | train loss 0.3698 | train AUC 0.6264 | train AUPRC 0.1949 | val AUC 0.6597 | val AUPRC 0.2066 | test AUC 0.5962 | test AUPRC 0.1857
wandb: ⢿ updating run metadata (0.0s)
wandb: ⣻ updating run metadata (0.0s)
wandb: ⣽ updating run metadata (0.0s)
wandb: ⣾ updating run metadata (0.0s)
wandb: ⣷ updating run metadata (0.5s)
wandb: ⣯ updating run metadata (0.5s)
wandb: ⣟ updating run metadata (0.5s)
wandb: ⡿ updating run metadata (0.5s)
wandb: ⢿ updating run metadata (0.5s)
wandb: ⣻ updating run metadata (1.0s)
wandb: ⣽ updating run metadata (1.0s)
wandb: ⣾ updating run metadata (1.0s)
wandb: ⣷ updating run metadata (1.0s)
wandb: ⣯ updating run metadata (1.0s)
wandb: ⣟ uploading output.log 7.0KB/7.0KB (0.1s)
wandb: ⣟ uploading wandb-summary.json 560B/560B (0.1s)
wandb: ⣟ uploading config.yaml 3.6KB/3.6KB (0.1s)
wandb: ⡿ uploading output.log 7.0KB/7.0KB (0.1s)
wandb: ⡿ uploading wandb-summary.json 560B/560B (0.1s)
wandb: ⡿ uploading config.yaml 3.6KB/3.6KB (0.1s)
wandb: ⢿ uploading output.log 7.0KB/7.0KB (0.1s)
wandb: ⢿ uploading wandb-summary.json 560B/560B (0.1s)
wandb: ⢿ uploading config.yaml 3.6KB/3.6KB (0.1s)
wandb: ⣻ uploading output.log 7.0KB/7.0KB (0.1s)
wandb: ⣻ uploading wandb-summary.json 560B/560B (0.1s)
wandb: ⣻ uploading config.yaml 3.6KB/3.6KB (0.1s)
wandb: ⣽ uploading output.log 7.0KB/7.0KB (0.1s)
wandb: ⣽ uploading wandb-summary.json 560B/560B (0.1s)
wandb: ⣽ uploading config.yaml 3.6KB/3.6KB (0.1s)
wandb: ⣾ uploading history steps 44-49, summary, console lines 45-49 (0.3s)
wandb: ⣷ uploading history steps 44-49, summary, console lines 45-49 (0.3s)
wandb: ⣯ uploading history steps 44-49, summary, console lines 45-49 (0.3s)
wandb: ⣟ uploading history steps 44-49, summary, console lines 45-49 (0.3s)
wandb: ⡿ uploading history steps 44-49, summary, console lines 45-49 (0.3s)
wandb: ⢿ uploading history steps 44-49, summary, console lines 45-49 (0.8s)
wandb: ⣻ uploading history steps 44-49, summary, console lines 45-49 (0.8s)
wandb:
wandb: Run history:
wandb:       epoch ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:    test/auc ▁▁▂▃▄▇████▇▇█▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇
wandb:  test/auprc ▁▁▂▃▂▃▄▅▆▆▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇██▇███████
wandb:  test/brier ▇█▆▆▆▄▃▃▃▃▃▂▂▂▃▁▁▂▁▁▁▁▁▁▃▁▁▁▁▁▁▁▁▂▁▃▂▁▁▄
wandb:   test/loss ▇█▅▅▅▄▃▂▂▂▃▂▁▂▃▁▁▂▁▁▁▁▁▁▃▁▁▁▁▁▁▁▂▁▁▁▁▁▁▄
wandb:   train/auc ▁▁▂▃▄▇██████████████████████████████████
wandb: train/auprc ▁▁▁▂▃▆▇▇▇███████████████████████████████
wandb: train/brier ▇█▆▆▄▃▃▃▂▃▂▂▃▂▂▂▁▂▁▁▂▁▁▃▁▁▁▁▁▁▁▂▂▁▁▁▁▁▁▃
wandb:  train/loss █▃▃▃▃▂▂▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:     val/auc ▁▂▃▄▆███████████████████████████████████
wandb:          +3 ...
wandb:
wandb: Run summary:
wandb:     best_epoch 9
wandb:   best_val_auc -1
wandb: best_val_auprc 0.21698
wandb:          epoch 50
wandb:       test/auc 0.59619
wandb:     test/auprc 0.18569
wandb:     test/brier 0.10889
wandb:      test/loss 0.37383
wandb:      train/auc 0.62635
wandb:    train/auprc 0.1949
wandb:             +6 ...
wandb:
wandb: 🚀 View run mo_gat_syn_Hospitalization_clean_ep50_layer2_hidden64_lr0.001_bs32 at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/f0t15u5i
wandb: ⭐️ View project at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260709_132124-f0t15u5i/logs
[2026-07-09 13:22:02,543][HYDRA] 	#1 : model=gat data=dataset_syn training.epochs=50 data.target=Hospitalization model.num_layers=4
data:
  name: syn
  target: Hospitalization
  evaluator_type: synthetic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_edges.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_samples_nooverlap.csv
      multihospital: synthetic_pharmacotherapy_v2_samples_multihospital.csv
    scenario: clean
model:
  name: gat
  hidden_dim: 64
  num_layers: 4
  dropout: 0.2
  batch_norm: true
  activation: relu
  heads: 4
training:
  lr: 0.001
  epochs: 50
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
  heads: 4
  dropout: 0.0
  pooling: mean
  batch_norm: true
meta:
  owner_initials: mo
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis
  run_name: ${meta.owner_initials}_${model.name}_${data.name}_${data.target}_${data.dataset.scenario}_ep${training.epochs}_layer${model.num_layers}_hidden${model.hidden_dim}_lr${training.lr}_bs${training.batch_size}

wandb: ⢿ setting up run 1fnuy4dc (0.0s)
wandb: ⣻ setting up run 1fnuy4dc (0.0s)
wandb: ⣽ setting up run 1fnuy4dc (0.0s)
wandb: ⣾ setting up run 1fnuy4dc (0.0s)
wandb: ⣷ setting up run 1fnuy4dc (0.5s)
wandb: ⣯ setting up run 1fnuy4dc (0.5s)
wandb: ⣟ setting up run 1fnuy4dc (0.5s)
wandb: ⡿ setting up run 1fnuy4dc (0.5s)
wandb: ⢿ setting up run 1fnuy4dc (0.5s)
wandb: ⣻ setting up run 1fnuy4dc (1.0s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260709_132202-1fnuy4dc
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run mo_gat_syn_Hospitalization_clean_ep50_layer4_hidden64_lr0.001_bs32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/1fnuy4dc
Epoch 001 | train loss 0.4346 | train AUC 0.4635 | train AUPRC 0.1224 | val AUC 0.4717 | val AUPRC 0.1419 | test AUC 0.5002 | test AUPRC 0.1503
Epoch 002 | train loss 0.3850 | train AUC 0.5128 | train AUPRC 0.1347 | val AUC 0.5263 | val AUPRC 0.1696 | test AUC 0.5447 | test AUPRC 0.1568
Epoch 003 | train loss 0.3783 | train AUC 0.5713 | train AUPRC 0.1532 | val AUC 0.6160 | val AUPRC 0.1992 | test AUC 0.5815 | test AUPRC 0.1488
Epoch 004 | train loss 0.3756 | train AUC 0.6223 | train AUPRC 0.1871 | val AUC 0.6828 | val AUPRC 0.2224 | test AUC 0.6022 | test AUPRC 0.1644
Epoch 005 | train loss 0.3736 | train AUC 0.6273 | train AUPRC 0.1931 | val AUC 0.6822 | val AUPRC 0.2240 | test AUC 0.6037 | test AUPRC 0.1690
Epoch 006 | train loss 0.3721 | train AUC 0.6303 | train AUPRC 0.1978 | val AUC 0.6822 | val AUPRC 0.2267 | test AUC 0.6050 | test AUPRC 0.1720
Epoch 007 | train loss 0.3710 | train AUC 0.6366 | train AUPRC 0.2077 | val AUC 0.6860 | val AUPRC 0.2371 | test AUC 0.6103 | test AUPRC 0.1786
Epoch 008 | train loss 0.3710 | train AUC 0.6402 | train AUPRC 0.2127 | val AUC 0.6888 | val AUPRC 0.2416 | test AUC 0.6126 | test AUPRC 0.1817
Epoch 009 | train loss 0.3716 | train AUC 0.6416 | train AUPRC 0.2177 | val AUC 0.6851 | val AUPRC 0.2374 | test AUC 0.6126 | test AUPRC 0.1869
Epoch 010 | train loss 0.3701 | train AUC 0.6437 | train AUPRC 0.2221 | val AUC 0.6847 | val AUPRC 0.2391 | test AUC 0.6132 | test AUPRC 0.1900
Epoch 011 | train loss 0.3708 | train AUC 0.6453 | train AUPRC 0.2245 | val AUC 0.6850 | val AUPRC 0.2419 | test AUC 0.6138 | test AUPRC 0.1908
Epoch 012 | train loss 0.3676 | train AUC 0.6473 | train AUPRC 0.2314 | val AUC 0.6807 | val AUPRC 0.2439 | test AUC 0.6144 | test AUPRC 0.1941
Epoch 013 | train loss 0.3663 | train AUC 0.6483 | train AUPRC 0.2348 | val AUC 0.6766 | val AUPRC 0.2446 | test AUC 0.6150 | test AUPRC 0.1965
Epoch 014 | train loss 0.3667 | train AUC 0.6485 | train AUPRC 0.2350 | val AUC 0.6764 | val AUPRC 0.2462 | test AUC 0.6148 | test AUPRC 0.1968
Epoch 015 | train loss 0.3643 | train AUC 0.6489 | train AUPRC 0.2371 | val AUC 0.6748 | val AUPRC 0.2463 | test AUC 0.6142 | test AUPRC 0.1969
Epoch 016 | train loss 0.3655 | train AUC 0.6496 | train AUPRC 0.2383 | val AUC 0.6743 | val AUPRC 0.2477 | test AUC 0.6147 | test AUPRC 0.1966
Epoch 017 | train loss 0.3648 | train AUC 0.6501 | train AUPRC 0.2419 | val AUC 0.6704 | val AUPRC 0.2482 | test AUC 0.6126 | test AUPRC 0.1945
Epoch 018 | train loss 0.3682 | train AUC 0.6490 | train AUPRC 0.2370 | val AUC 0.6746 | val AUPRC 0.2457 | test AUC 0.6137 | test AUPRC 0.1965
Epoch 019 | train loss 0.3647 | train AUC 0.6492 | train AUPRC 0.2365 | val AUC 0.6740 | val AUPRC 0.2480 | test AUC 0.6144 | test AUPRC 0.1953
Epoch 020 | train loss 0.3644 | train AUC 0.6500 | train AUPRC 0.2405 | val AUC 0.6718 | val AUPRC 0.2475 | test AUC 0.6142 | test AUPRC 0.1963
Epoch 021 | train loss 0.3648 | train AUC 0.6503 | train AUPRC 0.2407 | val AUC 0.6726 | val AUPRC 0.2484 | test AUC 0.6150 | test AUPRC 0.1976
Epoch 022 | train loss 0.3671 | train AUC 0.6497 | train AUPRC 0.2397 | val AUC 0.6724 | val AUPRC 0.2464 | test AUC 0.6134 | test AUPRC 0.1977
Epoch 023 | train loss 0.3639 | train AUC 0.6502 | train AUPRC 0.2387 | val AUC 0.6727 | val AUPRC 0.2494 | test AUC 0.6166 | test AUPRC 0.1978
Epoch 024 | train loss 0.3642 | train AUC 0.6501 | train AUPRC 0.2420 | val AUC 0.6681 | val AUPRC 0.2471 | test AUC 0.6106 | test AUPRC 0.1944
Epoch 025 | train loss 0.3640 | train AUC 0.6501 | train AUPRC 0.2403 | val AUC 0.6723 | val AUPRC 0.2470 | test AUC 0.6140 | test AUPRC 0.1976
Epoch 026 | train loss 0.3644 | train AUC 0.6499 | train AUPRC 0.2413 | val AUC 0.6708 | val AUPRC 0.2446 | test AUC 0.6127 | test AUPRC 0.1965
Epoch 027 | train loss 0.3638 | train AUC 0.6504 | train AUPRC 0.2413 | val AUC 0.6697 | val AUPRC 0.2477 | test AUC 0.6150 | test AUPRC 0.1971
Epoch 028 | train loss 0.3680 | train AUC 0.6501 | train AUPRC 0.2409 | val AUC 0.6715 | val AUPRC 0.2472 | test AUC 0.6139 | test AUPRC 0.1968
Epoch 029 | train loss 0.3635 | train AUC 0.6506 | train AUPRC 0.2415 | val AUC 0.6709 | val AUPRC 0.2480 | test AUC 0.6148 | test AUPRC 0.1975
Epoch 030 | train loss 0.3649 | train AUC 0.6508 | train AUPRC 0.2417 | val AUC 0.6715 | val AUPRC 0.2487 | test AUC 0.6151 | test AUPRC 0.1967
Epoch 031 | train loss 0.3630 | train AUC 0.6507 | train AUPRC 0.2429 | val AUC 0.6671 | val AUPRC 0.2484 | test AUC 0.6119 | test AUPRC 0.1939
Epoch 032 | train loss 0.3636 | train AUC 0.6507 | train AUPRC 0.2429 | val AUC 0.6677 | val AUPRC 0.2450 | test AUC 0.6119 | test AUPRC 0.1949
Epoch 033 | train loss 0.3658 | train AUC 0.6322 | train AUPRC 0.2156 | val AUC 0.6557 | val AUPRC 0.2361 | test AUC 0.5935 | test AUPRC 0.1813
Epoch 034 | train loss 0.3673 | train AUC 0.6478 | train AUPRC 0.2368 | val AUC 0.6702 | val AUPRC 0.2481 | test AUC 0.6132 | test AUPRC 0.1963
Epoch 035 | train loss 0.3659 | train AUC 0.6527 | train AUPRC 0.2446 | val AUC 0.6722 | val AUPRC 0.2501 | test AUC 0.6164 | test AUPRC 0.1980

In [ ]:
#multirun sage
!python src/train.py --multirun meta.owner_initials="MO" model=sage data=dataset_syn training.epochs=50 data.target="Hospitalization" model.num_layers=2,4,6

[2026-07-09 13:28:56,636][HYDRA] Launching 3 jobs locally
[2026-07-09 13:28:56,636][HYDRA] 	#0 : meta.owner_initials=MO model=sage data=dataset_syn training.epochs=50 data.target=Hospitalization model.num_layers=2
data:
  name: syn
  target: Hospitalization
  evaluator_type: synthetic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_edges.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_samples_nooverlap.csv
      multihospital: synthetic_pharmacotherapy_v2_samples_multihospital.csv
    scenario: clean
model:
  name: sage
  hidden_dim: 64
  num_layers: 2
  dropout: 0.2
  batch_norm: true
  activation: relu
training:
  lr: 0.001
  epochs: 50
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
  heads: 4
  dropout: 0.0
  pooling: mean
  batch_norm: true
meta:
  owner_initials: MO
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis
  run_name: ${meta.owner_initials}_${model.name}_${data.name}_${data.target}_${data.dataset.scenario}_ep${training.epochs}_layer${model.num_layers}_hidden${model.hidden_dim}_lr${training.lr}_bs${training.batch_size}

wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /root/.netrc.
wandb: Currently logged in as: oskardmonika (politechnika-gnn-thesis) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Using an existing wandb-core service via WANDB_SERVICE.
wandb: ⢿ setting up run wmk0tr5y (0.0s)
wandb: ⣻ setting up run wmk0tr5y (0.0s)
wandb: ⣽ setting up run wmk0tr5y (0.0s)
wandb: ⣾ setting up run wmk0tr5y (0.0s)
wandb: ⣷ setting up run wmk0tr5y (0.5s)
wandb: ⣯ setting up run wmk0tr5y (0.5s)
wandb: ⣟ setting up run wmk0tr5y (0.5s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260709_132856-wmk0tr5y
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run MO_sage_syn_Hospitalization_clean_ep50_layer2_hidden64_lr0.001_bs32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/wmk0tr5y
Epoch 001 | train loss 0.3994 | train AUC 0.4790 | train AUPRC 0.1250 | val AUC 0.5030 | val AUPRC 0.1342 | test AUC 0.5057 | test AUPRC 0.1517
Epoch 002 | train loss 0.3823 | train AUC 0.5306 | train AUPRC 0.1372 | val AUC 0.5697 | val AUPRC 0.1807 | test AUC 0.5465 | test AUPRC 0.1565
Epoch 003 | train loss 0.3790 | train AUC 0.5890 | train AUPRC 0.1615 | val AUC 0.6478 | val AUPRC 0.2162 | test AUC 0.5899 | test AUPRC 0.1601
Epoch 004 | train loss 0.3757 | train AUC 0.6030 | train AUPRC 0.1730 | val AUC 0.6631 | val AUPRC 0.2318 | test AUC 0.5937 | test AUPRC 0.1558
Epoch 005 | train loss 0.3747 | train AUC 0.6116 | train AUPRC 0.1821 | val AUC 0.6682 | val AUPRC 0.2264 | test AUC 0.5939 | test AUPRC 0.1638
Epoch 006 | train loss 0.3759 | train AUC 0.6177 | train AUPRC 0.1878 | val AUC 0.6696 | val AUPRC 0.2210 | test AUC 0.5967 | test AUPRC 0.1699
Epoch 007 | train loss 0.3717 | train AUC 0.6202 | train AUPRC 0.1906 | val AUC 0.6687 | val AUPRC 0.2178 | test AUC 0.5979 | test AUPRC 0.1731
Epoch 008 | train loss 0.3721 | train AUC 0.6224 | train AUPRC 0.1919 | val AUC 0.6716 | val AUPRC 0.2207 | test AUC 0.6010 | test AUPRC 0.1734
Epoch 009 | train loss 0.3707 | train AUC 0.6259 | train AUPRC 0.1941 | val AUC 0.6765 | val AUPRC 0.2284 | test AUC 0.6077 | test AUPRC 0.1766
Epoch 010 | train loss 0.3709 | train AUC 0.6233 | train AUPRC 0.1948 | val AUC 0.6654 | val AUPRC 0.2166 | test AUC 0.5981 | test AUPRC 0.1776
Epoch 011 | train loss 0.3712 | train AUC 0.6289 | train AUPRC 0.1991 | val AUC 0.6719 | val AUPRC 0.2205 | test AUC 0.6063 | test AUPRC 0.1806
Epoch 012 | train loss 0.3701 | train AUC 0.6317 | train AUPRC 0.2012 | val AUC 0.6747 | val AUPRC 0.2241 | test AUC 0.6084 | test AUPRC 0.1817
Epoch 013 | train loss 0.3700 | train AUC 0.6322 | train AUPRC 0.2021 | val AUC 0.6734 | val AUPRC 0.2242 | test AUC 0.6075 | test AUPRC 0.1830
Epoch 014 | train loss 0.3684 | train AUC 0.6369 | train AUPRC 0.2066 | val AUC 0.6785 | val AUPRC 0.2276 | test AUC 0.6148 | test AUPRC 0.1846
Epoch 015 | train loss 0.3693 | train AUC 0.6378 | train AUPRC 0.2060 | val AUC 0.6770 | val AUPRC 0.2270 | test AUC 0.6138 | test AUPRC 0.1860
Epoch 016 | train loss 0.3683 | train AUC 0.6410 | train AUPRC 0.2100 | val AUC 0.6791 | val AUPRC 0.2288 | test AUC 0.6182 | test AUPRC 0.1896
Epoch 017 | train loss 0.3676 | train AUC 0.6436 | train AUPRC 0.2125 | val AUC 0.6810 | val AUPRC 0.2313 | test AUC 0.6222 | test AUPRC 0.1913
Epoch 018 | train loss 0.3667 | train AUC 0.6455 | train AUPRC 0.2140 | val AUC 0.6822 | val AUPRC 0.2317 | test AUC 0.6243 | test AUPRC 0.1932
Epoch 019 | train loss 0.3684 | train AUC 0.6470 | train AUPRC 0.2154 | val AUC 0.6817 | val AUPRC 0.2318 | test AUC 0.6243 | test AUPRC 0.1965
Epoch 020 | train loss 0.3649 | train AUC 0.6504 | train AUPRC 0.2184 | val AUC 0.6844 | val AUPRC 0.2343 | test AUC 0.6299 | test AUPRC 0.1990
Epoch 021 | train loss 0.3661 | train AUC 0.6522 | train AUPRC 0.2199 | val AUC 0.6856 | val AUPRC 0.2358 | test AUC 0.6312 | test AUPRC 0.2007
Epoch 022 | train loss 0.3660 | train AUC 0.6561 | train AUPRC 0.2236 | val AUC 0.6886 | val AUPRC 0.2376 | test AUC 0.6382 | test AUPRC 0.2036
Epoch 023 | train loss 0.3642 | train AUC 0.6581 | train AUPRC 0.2253 | val AUC 0.6896 | val AUPRC 0.2389 | test AUC 0.6407 | test AUPRC 0.2063
Epoch 024 | train loss 0.3629 | train AUC 0.6609 | train AUPRC 0.2277 | val AUC 0.6918 | val AUPRC 0.2409 | test AUC 0.6453 | test AUPRC 0.2082
Epoch 025 | train loss 0.3628 | train AUC 0.6634 | train AUPRC 0.2302 | val AUC 0.6931 | val AUPRC 0.2423 | test AUC 0.6473 | test AUPRC 0.2112
Epoch 026 | train loss 0.3624 | train AUC 0.6648 | train AUPRC 0.2312 | val AUC 0.6929 | val AUPRC 0.2397 | test AUC 0.6482 | test AUPRC 0.2121
Epoch 027 | train loss 0.3634 | train AUC 0.6685 | train AUPRC 0.2357 | val AUC 0.6957 | val AUPRC 0.2429 | test AUC 0.6533 | test AUPRC 0.2152
Epoch 028 | train loss 0.3623 | train AUC 0.6693 | train AUPRC 0.2361 | val AUC 0.6966 | val AUPRC 0.2445 | test AUC 0.6525 | test AUPRC 0.2152
Epoch 029 | train loss 0.3600 | train AUC 0.6732 | train AUPRC 0.2407 | val AUC 0.6998 | val AUPRC 0.2481 | test AUC 0.6581 | test AUPRC 0.2186
Epoch 030 | train loss 0.3598 | train AUC 0.6738 | train AUPRC 0.2413 | val AUC 0.6991 | val AUPRC 0.2450 | test AUC 0.6570 | test AUPRC 0.2191
Epoch 031 | train loss 0.3608 | train AUC 0.6777 | train AUPRC 0.2454 | val AUC 0.7020 | val AUPRC 0.2496 | test AUC 0.6626 | test AUPRC 0.2225
Epoch 032 | train loss 0.3585 | train AUC 0.6800 | train AUPRC 0.2479 | val AUC 0.7038 | val AUPRC 0.2537 | test AUC 0.6659 | test AUPRC 0.2254
Epoch 033 | train loss 0.3576 | train AUC 0.6827 | train AUPRC 0.2517 | val AUC 0.7052 | val AUPRC 0.2567 | test AUC 0.6694 | test AUPRC 0.2261
Epoch 034 | train loss 0.3575 | train AUC 0.6845 | train AUPRC 0.2534 | val AUC 0.7059 | val AUPRC 0.2566 | test AUC 0.6713 | test AUPRC 0.2283
Epoch 035 | train loss 0.3561 | train AUC 0.6861 | train AUPRC 0.2551 | val AUC 0.7070 | val AUPRC 0.2574 | test AUC 0.6728 | test AUPRC 0.2296
Epoch 036 | train loss 0.3553 | train AUC 0.6894 | train AUPRC 0.2587 | val AUC 0.7095 | val AUPRC 0.2626 | test AUC 0.6774 | test AUPRC 0.2321
Epoch 037 | train loss 0.3540 | train AUC 0.6922 | train AUPRC 0.2618 | val AUC 0.7127 | val AUPRC 0.2747 | test AUC 0.6829 | test AUPRC 0.2324
Epoch 038 | train loss 0.3583 | train AUC 0.6941 | train AUPRC 0.2642 | val AUC 0.7131 | val AUPRC 0.2723 | test AUC 0.6836 | test AUPRC 0.2360
Epoch 039 | train loss 0.3535 | train AUC 0.6947 | train AUPRC 0.2640 | val AUC 0.7133 | val AUPRC 0.2670 | test AUC 0.6823 | test AUPRC 0.2381
Epoch 040 | train loss 0.3522 | train AUC 0.6979 | train AUPRC 0.2674 | val AUC 0.7159 | val AUPRC 0.2738 | test AUC 0.6867 | test AUPRC 0.2389
Epoch 041 | train loss 0.3552 | train AUC 0.6993 | train AUPRC 0.2692 | val AUC 0.7163 | val AUPRC 0.2712 | test AUC 0.6873 | test AUPRC 0.2420
Epoch 042 | train loss 0.3530 | train AUC 0.7014 | train AUPRC 0.2716 | val AUC 0.7186 | val AUPRC 0.2736 | test AUC 0.6895 | test AUPRC 0.2443
Epoch 043 | train loss 0.3526 | train AUC 0.7041 | train AUPRC 0.2761 | val AUC 0.7206 | val AUPRC 0.2834 | test AUC 0.6955 | test AUPRC 0.2471
Epoch 044 | train loss 0.3510 | train AUC 0.7059 | train AUPRC 0.2776 | val AUC 0.7221 | val AUPRC 0.2853 | test AUC 0.6967 | test AUPRC 0.2482
Epoch 045 | train loss 0.3510 | train AUC 0.7078 | train AUPRC 0.2810 | val AUC 0.7227 | val AUPRC 0.2914 | test AUC 0.7004 | test AUPRC 0.2505
Epoch 046 | train loss 0.3498 | train AUC 0.7102 | train AUPRC 0.2837 | val AUC 0.7242 | val AUPRC 0.2925 | test AUC 0.7021 | test AUPRC 0.2515
Epoch 047 | train loss 0.3487 | train AUC 0.7120 | train AUPRC 0.2850 | val AUC 0.7262 | val AUPRC 0.2893 | test AUC 0.7014 | test AUPRC 0.2544
Epoch 048 | train loss 0.3483 | train AUC 0.7111 | train AUPRC 0.2825 | val AUC 0.7256 | val AUPRC 0.2812 | test AUC 0.6968 | test AUPRC 0.2543
Epoch 049 | train loss 0.3512 | train AUC 0.7152 | train AUPRC 0.2890 | val AUC 0.7290 | val AUPRC 0.2943 | test AUC 0.7042 | test AUPRC 0.2582
Epoch 050 | train loss 0.3496 | train AUC 0.7168 | train AUPRC 0.2904 | val AUC 0.7300 | val AUPRC 0.2954 | test AUC 0.7047 | test AUPRC 0.2589
wandb: ⢿ updating run metadata (0.0s)
wandb: ⣻ updating run metadata (0.0s)
wandb: ⣽ updating run metadata (0.0s)
wandb: ⣾ updating run metadata (0.0s)
wandb: ⣷ Finishing up...
wandb: ⣯ Finishing up...
wandb: ⣟ Finishing up...
wandb: ⡿ Finishing up...
wandb: ⢿ Finishing up...
wandb: ⣻ uploading history steps 34-49, summary, console lines 35-49 (0.2s)
wandb: ⣽ uploading history steps 34-49, summary, console lines 35-49 (0.2s)
wandb:
wandb: Run history:
wandb:       epoch ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:    test/auc ▁▂▄▄▄▄▄▅▄▅▅▅▅▅▅▅▅▅▆▆▆▆▆▆▆▇▇▇▇▇▇▇▇▇██████
wandb:  test/auprc ▁▁▂▁▂▂▂▃▃▃▃▃▃▃▄▄▄▄▅▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇████
wandb:  test/brier █▇▇▆▆▆▇█▆▆▆▅▅▅▅▅▅▅▄▄▄▅▄▄▃▃▃▃▂▃▂▂▂▃▂▂▂▁█▂
wandb:   test/loss ███▆▆▆▆██▆▆▆▅▅▅▆▅▅▅▅▄▄▅▄▄▃▃▃▂▃▂▂▂▃▁▂▁▁▆▂
wandb:   train/auc ▁▃▄▅▅▅▅▅▅▅▆▆▆▆▆▆▆▆▆▆▆▇▇▇▇▇▇▇▇▇▇▇▇▇██████
wandb: train/auprc ▁▂▃▃▃▄▄▄▄▄▄▄▄▅▅▅▅▅▅▅▅▆▆▆▆▆▆▆▇▇▇▇▇▇▇█████
wandb: train/brier ██▇▇▆▆▆▇▇▆▆▅▅▅▅▅▅▅▅▄▄▄▄▄▄▃▃▃▃▄▂▂▂▂▂▃▂▁▅▁
wandb:  train/loss █▆▅▅▅▄▄▄▄▄▄▄▄▄▄▃▃▃▃▃▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▁▁▁▁▁
wandb:     val/auc ▁▃▅▆▆▆▆▆▆▆▆▆▆▆▆▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇█████████
wandb:          +3 ...
wandb:
wandb: Run summary:
wandb:     best_epoch 50
wandb:   best_val_auc -1
wandb: best_val_auprc 0.29535
wandb:          epoch 50
wandb:       test/auc 0.70471
wandb:     test/auprc 0.25887
wandb:     test/brier 0.1039
wandb:      test/loss 0.35325
wandb:      train/auc 0.71682
wandb:    train/auprc 0.29044
wandb:             +6 ...
wandb:
wandb: 🚀 View run MO_sage_syn_Hospitalization_clean_ep50_layer2_hidden64_lr0.001_bs32 at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/wmk0tr5y
wandb: ⭐️ View project at: https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: ./wandb/run-20260709_132856-wmk0tr5y/logs
[2026-07-09 13:29:22,236][HYDRA] 	#1 : meta.owner_initials=MO model=sage data=dataset_syn training.epochs=50 data.target=Hospitalization model.num_layers=4
data:
  name: syn
  target: Hospitalization
  evaluator_type: synthetic_evaluator
  dataset:
    root_dir: ${oc.env:PHARMA_DATA_ROOT}
    nodes_file: synthetic_pharmacotherapy_v2_nodes.csv
    edges_file: synthetic_pharmacotherapy_v2_edges.csv
    samples:
      clean: synthetic_pharmacotherapy_v2_samples_clean.csv
      nooverlap: synthetic_pharmacotherapy_v2_samples_nooverlap.csv
      multihospital: synthetic_pharmacotherapy_v2_samples_multihospital.csv
    scenario: clean
model:
  name: sage
  hidden_dim: 64
  num_layers: 4
  dropout: 0.2
  batch_norm: true
  activation: relu
training:
  lr: 0.001
  epochs: 50
  batch_size: 32
  optimizer: adam
  to_undirected: true
  seed: 42
  val_size: 0.1
  test_size: 0.1
  heads: 4
  dropout: 0.0
  pooling: mean
  batch_norm: true
meta:
  owner_initials: MO
wandb:
  project: politechnika-gnn-thesis
  entity: politechnika-gnn-thesis
  run_name: ${meta.owner_initials}_${model.name}_${data.name}_${data.target}_${data.dataset.scenario}_ep${training.epochs}_layer${model.num_layers}_hidden${model.hidden_dim}_lr${training.lr}_bs${training.batch_size}

wandb: ⢿ setting up run t3b0k0m5 (0.0s)
wandb: ⣻ setting up run t3b0k0m5 (0.0s)
wandb: ⣽ setting up run t3b0k0m5 (0.0s)
wandb: ⣾ setting up run t3b0k0m5 (0.0s)
wandb: ⣷ setting up run t3b0k0m5 (0.5s)
wandb: ⣯ setting up run t3b0k0m5 (0.5s)
wandb: ⣟ setting up run t3b0k0m5 (0.5s)
wandb: ⡿ setting up run t3b0k0m5 (0.5s)
wandb: ⢿ setting up run t3b0k0m5 (0.5s)
wandb: Tracking run with wandb version 0.28.0
wandb: Run data is saved locally in /content/GraphNeuralNetwork_Thesis/wandb/run-20260709_132922-t3b0k0m5
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run MO_sage_syn_Hospitalization_clean_ep50_layer4_hidden64_lr0.001_bs32
wandb: ⭐️ View project at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis
wandb: 🚀 View run at https://wandb.ai/politechnika-gnn-thesis/politechnika-gnn-thesis/runs/t3b0k0m5
Epoch 001 | train loss 0.3966 | train AUC 0.5047 | train AUPRC 0.1323 | val AUC 0.5270 | val AUPRC 0.1538 | test AUC 0.5356 | test AUPRC 0.1591
Epoch 002 | train loss 0.3815 | train AUC 0.5825 | train AUPRC 0.1575 | val AUC 0.6414 | val AUPRC 0.2089 | test AUC 0.5796 | test AUPRC 0.1600
Epoch 003 | train loss 0.3759 | train AUC 0.6047 | train AUPRC 0.1732 | val AUC 0.6659 | val AUPRC 0.2057 | test AUC 0.5882 | test AUPRC 0.1569
Epoch 004 | train loss 0.3748 | train AUC 0.6089 | train AUPRC 0.1775 | val AUC 0.6690 | val AUPRC 0.2092 | test AUC 0.5923 | test AUPRC 0.1608
Epoch 005 | train loss 0.3739 | train AUC 0.6133 | train AUPRC 0.1830 | val AUC 0.6723 | val AUPRC 0.2110 | test AUC 0.5977 | test AUPRC 0.1647
Epoch 006 | train loss 0.3723 | train AUC 0.6164 | train AUPRC 0.1860 | val AUC 0.6731 | val AUPRC 0.2111 | test AUC 0.6013 | test AUPRC 0.1704
Epoch 007 | train loss 0.3729 | train AUC 0.6203 | train AUPRC 0.1899 | val AUC 0.6769 | val AUPRC 0.2155 | test AUC 0.6068 | test AUPRC 0.1736
Epoch 008 | train loss 0.3731 | train AUC 0.6211 | train AUPRC 0.1906 | val AUC 0.6761 | val AUPRC 0.2162 | test AUC 0.6074 | test AUPRC 0.1755
Epoch 009 | train loss 0.3750 | train AUC 0.6239 | train AUPRC 0.1951 | val AUC 0.6773 | val AUPRC 0.2180 | test AUC 0.6090 | test AUPRC 0.1764
Epoch 010 | train loss 0.3702 | train AUC 0.6292 | train AUPRC 0.2014 | val AUC 0.6802 | val AUPRC 0.2231 | test AUC 0.6143 | test AUPRC 0.1825
Epoch 011 | train loss 0.3713 | train AUC 0.6366 | train AUPRC 0.2095 | val AUC 0.6825 | val AUPRC 0.2310 | test AUC 0.6210 | test AUPRC 0.1918
Epoch 012 | train loss 0.3688 | train AUC 0.6449 | train AUPRC 0.2204 | val AUC 0.6828 | val AUPRC 0.2391 | test AUC 0.6290 | test AUPRC 0.2018
Epoch 013 | train loss 0.3673 | train AUC 0.6673 | train AUPRC 0.2456 | val AUC 0.7012 | val AUPRC 0.2727 | test AUC 0.6543 | test AUPRC 0.2240
Epoch 014 | train loss 0.3622 | train AUC 0.6884 | train AUPRC 0.2667 | val AUC 0.7118 | val AUPRC 0.3018 | test AUC 0.6783 | test AUPRC 0.2417
Epoch 015 | train loss 0.3572 | train AUC 0.7130 | train AUPRC 0.2958 | val AUC 0.7294 | val AUPRC 0.3489 | test AUC 0.7091 | test AUPRC 0.2590
Epoch 016 | train loss 0.3441 | train AUC 0.7622 | train AUPRC 0.3581 | val AUC 0.7620 | val AUPRC 0.3862 | test AUC 0.7512 | test AUPRC 0.3162
Epoch 017 | train loss 0.3362 | train AUC 0.8122 | train AUPRC 0.4316 | val AUC 0.8019 | val AUPRC 0.4449 | test AUC 0.7982 | test AUPRC 0.3727
Epoch 018 | train loss 0.3107 | train AUC 0.8643 | train AUPRC 0.5262 | val AUC 0.8514 | val AUPRC 0.5138 | test AUC 0.8490 | test AUPRC 0.4813
Epoch 019 | train loss 0.2889 | train AUC 0.9146 | train AUPRC 0.6459 | val AUC 0.9020 | val AUPRC 0.6102 | test AUC 0.8979 | test AUPRC 0.6023
Epoch 020 | train loss 0.2447 | train AUC 0.9683 | train AUPRC 0.8100 | val AUC 0.9605 | val AUPRC 0.7697 | test AUC 0.9578 | test AUPRC 0.7940
Epoch 021 | train loss 0.1804 | train AUC 0.9894 | train AUPRC 0.9002 | val AUC 0.9842 | val AUPRC 0.8622 | test AUC 0.9853 | test AUPRC 0.8966
Epoch 022 | train loss 0.1228 | train AUC 0.9943 | train AUPRC 0.9331 | val AUC 0.9904 | val AUPRC 0.9020 | test AUC 0.9934 | test AUPRC 0.9304
Epoch 023 | train loss 0.0792 | train AUC 0.9968 | train AUPRC 0.9645 | val AUC 0.9944 | val AUPRC 0.9484 | test AUC 0.9967 | test AUPRC 0.9716
Epoch 024 | train loss 0.0732 | train AUC 0.9976 | train AUPRC 0.9750 | val AUC 0.9957 | val AUPRC 0.9606 | test AUC 0.9977 | test AUPRC 0.9809
Epoch 025 | train loss 0.0425 | train AUC 0.9989 | train AUPRC 0.9899 | val AUC 0.9980 | val AUPRC 0.9852 | test AUC 0.9993 | test AUPRC 0.9947
Epoch 026 | train loss 0.0323 | train AUC 0.9995 | train AUPRC 0.9961 | val AUC 0.9993 | val AUPRC 0.9954 | test AUC 0.9996 | test AUPRC 0.9969
Epoch 027 | train loss 0.0247 | train AUC 0.9997 | train AUPRC 0.9980 | val AUC 0.9996 | val AUPRC 0.9971 | test AUC 0.9998 | test AUPRC 0.9988
Epoch 028 | train loss 0.0231 | train AUC 1.0000 | train AUPRC 0.9997 | val AUC 0.9998 | val AUPRC 0.9990 | test AUC 0.9999 | test AUPRC 0.9996
Epoch 029 | train loss 0.0228 | train AUC 1.0000 | train AUPRC 0.9998 | val AUC 0.9998 | val AUPRC 0.9990 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 030 | train loss 0.0128 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 0.9998 | test AUC 0.9999 | test AUPRC 0.9996
Epoch 031 | train loss 0.0103 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 0.9999 | val AUPRC 0.9997 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 032 | train loss 0.0091 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 033 | train loss 0.0066 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 034 | train loss 0.0057 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 035 | train loss 0.0048 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 036 | train loss 0.0093 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 037 | train loss 0.0031 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 038 | train loss 0.0024 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 039 | train loss 0.0018 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 040 | train loss 0.0015 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 041 | train loss 0.0012 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 042 | train loss 0.0037 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 043 | train loss 0.0011 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 044 | train loss 0.0018 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000
Epoch 045 | train loss 0.0008 | train AUC 1.0000 | train AUPRC 1.0000 | val AUC 1.0000 | val AUPRC 1.0000 | test AUC 1.0000 | test AUPRC 1.0000

In [10]:
import sys
import pandas as pd
sys.path.insert(0, "/content/GraphNeuralNetwork_Thesis/src")

In [ ]:
train = 0
test = 0
valid = 0

In [13]:
nodes = pd.read_csv("/content/drive/MyDrive/GSN Graphs dysertation 2026/2. Data/dataset_v2_2/synthetic_pharmacotherapy_v2_2_nodes.csv")
edges = pd.read_csv("/content/drive/MyDrive/GSN Graphs dysertation 2026/2. Data/dataset_v2_2/synthetic_pharmacotherapy_v2_2_edges_audited.csv")
samples = pd.read_csv("/content/drive/MyDrive/GSN Graphs dysertation 2026/2. Data/dataset_v2_2/synthetic_pharmacotherapy_v2_2_samples_clean.csv")

In [ ]:
!python notebooks/link_prediction_experiments.py

Traceback (most recent call last):
  File "/content/GraphNeuralNetwork_Thesis/GraphNeuralNetwork_Thesis/GraphNeuralNetwork_Thesis/notebooks/link_prediction_experiments.py", line 499, in <module>
    main()
  File "/content/GraphNeuralNetwork_Thesis/GraphNeuralNetwork_Thesis/GraphNeuralNetwork_Thesis/notebooks/link_prediction_experiments.py", line 394, in main
    features = pd.read_csv(args.hcr_dir / "edge_pair_features_train_only.csv")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'synthetic_pharmacotherapy_v2_1_nn_benchmark/hcr_link_prediction/edge_pair_features_train_only.csv'

In [ ]:
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

In [ ]:
SCORE_MODELS = [
    "hcr_score_only",
    "cmi_score_only",
    "hcr_perm_score",
    "hcr_excess_score",
]

NUMERIC_FEATURES = {
    "structural_only": [
        "source_layer_rank",
        "target_layer_rank",
        "layer_delta",
        "same_layer",
        "target_is_endpoint",
    ],
    "hcr_basic": [
        "conditional_mutual_information",
        "hcr_information_weight",
        "permutation_p_value",
        "hcr_above_null_q95",
        "conditioning_dimension",
        "n_complete",
    ],
    "hcr_extended": [
        "entropy_target",
        "entropy_target_given_source",
        "entropy_target_given_z",
        "mutual_information",
        "conditional_mutual_information",
        "hcr_information_weight",
        "information_removed_by_conditioning",
        "pearson_signed",
        "risk_difference_if_binary_source",
        "permutation_p_value",
        "permutation_null_mean",
        "permutation_null_sd",
        "permutation_null_q95",
        "hcr_above_null_q95",
        "conditioning_dimension",
        "n_complete",
    ],
}
NUMERIC_FEATURES["hcr_plus_structural"] = (
    NUMERIC_FEATURES["hcr_extended"] + NUMERIC_FEATURES["structural_only"]
)

CATEGORICAL_FEATURES = {
    "structural_only": ["source_node_type", "target_node_type"],
    "hcr_basic": [],
    "hcr_extended": [],
    "hcr_plus_structural": ["source_node_type", "target_node_type"],
}

In [ ]:
def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--hcr-dir",
        type=Path,
        default=Path("synthetic_pharmacotherapy_v2_1_nn_benchmark/hcr_link_prediction"),
    )
    p.add_argument("--output-dir", type=Path, default=Path("experiments/link_prediction_outputs"))
    p.add_argument("--full-oracle", action="store_true",
                   help="Use edge_splits.csv / edge_candidates.csv including latent node.")
    p.add_argument("--scenarios", nargs="*", default=None,
                   help="Optional subset, e.g. clean hidden_confounder selection_bias")
    p.add_argument("--ridge", type=float, default=1.0)
    p.add_argument("--max-iterations", type=int, default=80)
    return p.parse_args()


def sigmoid(x: np.ndarray) -> np.ndarray:
    x = np.clip(x, -30, 30)
    return 1.0 / (1.0 + np.exp(-x))


def fit_weighted_logistic(
    x: np.ndarray, y: np.ndarray, ridge: float, max_iterations: int
) -> np.ndarray:
    x_design = np.column_stack([np.ones(len(x)), x])
    beta = np.zeros(x_design.shape[1], dtype=float)
    prevalence = np.clip(y.mean(), 1e-4, 1 - 1e-4)
    beta[0] = np.log(prevalence / (1 - prevalence))

    positive_weight = max(1.0, float((y == 0).sum()) / max(1, int((y == 1).sum())))
    sample_weight = np.where(y == 1, positive_weight, 1.0)
    penalty = np.eye(x_design.shape[1]) * ridge
    penalty[0, 0] = 0.0

    def objective(candidate: np.ndarray) -> float:
        probability = np.clip(sigmoid(x_design @ candidate), 1e-12, 1 - 1e-12)
        data_loss = -np.sum(
            sample_weight
            * (y * np.log(probability) + (1 - y) * np.log(1 - probability))
        )
        return float(data_loss + 0.5 * candidate @ penalty @ candidate)

    for _ in range(max_iterations):
        probability = sigmoid(x_design @ beta)
        variance_weight = sample_weight * np.maximum(probability * (1 - probability), 1e-6)
        gradient = x_design.T @ (sample_weight * (probability - y)) + penalty @ beta
        hessian = x_design.T @ (variance_weight[:, None] * x_design) + penalty
        try:
            step = np.linalg.solve(hessian, gradient)
        except np.linalg.LinAlgError:
            step = np.linalg.pinv(hessian) @ gradient

        old_objective = objective(beta)
        scale = 1.0
        accepted = False
        while scale >= 1e-6:
            proposal = beta - scale * step
            if objective(proposal) <= old_objective + 1e-10:
                beta = proposal
                accepted = True
                break
            scale *= 0.5
        if not accepted or np.max(np.abs(scale * step)) < 1e-7:
            break
    return beta


def average_precision(y: np.ndarray, score: np.ndarray) -> float:
    positives = int(y.sum())
    if positives == 0:
        return float("nan")
    order = np.argsort(-score, kind="mergesort")
    ranked = y[order]
    sorted_score = score[order]
    cumulative = np.cumsum(ranked)
    block_end = np.r_[np.where(sorted_score[:-1] != sorted_score[1:])[0], len(y) - 1]
    true_positives = cumulative[block_end]
    precision = true_positives / (block_end + 1)
    recall = true_positives / positives
    return float(np.sum(np.diff(np.r_[0.0, recall]) * precision))


def roc_auc(y: np.ndarray, score: np.ndarray) -> float:
    n_pos, n_neg = int(y.sum()), int((1 - y).sum())
    if n_pos == 0 or n_neg == 0:
        return float("nan")
    ranks = pd.Series(score).rank(method="average").to_numpy()
    return float((ranks[y == 1].sum() - n_pos * (n_pos + 1) / 2) / (n_pos * n_neg))


def classification_metrics(y: np.ndarray, score: np.ndarray, threshold: float) -> dict[str, float]:
    pred = score >= threshold
    tp = int(np.sum((pred == 1) & (y == 1)))
    fp = int(np.sum((pred == 1) & (y == 0)))
    fn = int(np.sum((pred == 0) & (y == 1)))
    tn = int(np.sum((pred == 0) & (y == 0)))
    precision = tp / max(1, tp + fp)
    recall = tp / max(1, tp + fn)
    f1 = 2 * precision * recall / max(1e-12, precision + recall)
    return {
        "n": len(y),
        "positives": int(y.sum()),
        "negatives": int((1 - y).sum()),
        "average_precision": average_precision(y, score),
        "roc_auc": roc_auc(y, score),
        "brier_score": float(np.mean((score - y) ** 2)),
        "threshold": float(threshold),
        "precision": precision,
        "recall": recall,
        "f1": f1,
        "tp": tp,
        "fp": fp,
        "fn": fn,
        "tn": tn,
    }


def best_f1_threshold(y: np.ndarray, score: np.ndarray) -> float:
    if len(np.unique(y)) < 2:
        return 0.5
    candidates = np.unique(np.quantile(score, np.linspace(0.02, 0.98, 97)))
    best_score, best_threshold = float("-inf"), 0.5
    for threshold in candidates:
        f1 = classification_metrics(y, score, float(threshold))["f1"]
        if f1 > best_score:
            best_score = f1
            best_threshold = float(threshold)
    return best_threshold


def impute_score(values: pd.Series, train_mask: np.ndarray) -> np.ndarray:
    numeric = pd.to_numeric(values, errors="coerce").to_numpy(dtype=float)
    train_values = numeric[train_mask]
    median = np.nanmedian(train_values)
    if not np.isfinite(median):
        median = 0.0
    return np.where(np.isfinite(numeric), numeric, median)


def make_score(group: pd.DataFrame, model: str, train_mask: np.ndarray) -> np.ndarray:
    if model == "hcr_score_only":
        return impute_score(group["hcr_information_weight"], train_mask)
    if model == "cmi_score_only":
        return impute_score(group["conditional_mutual_information"], train_mask)
    if model == "hcr_perm_score":
        hcr = impute_score(group["hcr_information_weight"], train_mask)
        pval = impute_score(group["permutation_p_value"], train_mask)
        return hcr * (1.0 - np.clip(pval, 0.0, 1.0))
    if model == "hcr_excess_score":
        cmi = impute_score(group["conditional_mutual_information"], train_mask)
        q95 = impute_score(group["permutation_null_q95"], train_mask)
        return cmi - q95
    raise ValueError(f"Unknown score model: {model}")


def encode_features(
    frame: pd.DataFrame, model: str, train_mask: np.ndarray
) -> tuple[np.ndarray, list[str]]:
    numeric_columns = NUMERIC_FEATURES[model]
    numeric = frame[numeric_columns].apply(pd.to_numeric, errors="coerce").to_numpy(dtype=float)
    medians = np.nanmedian(numeric[train_mask], axis=0)
    medians = np.where(np.isfinite(medians), medians, 0.0)
    numeric = np.where(np.isfinite(numeric), numeric, medians)

    means = numeric[train_mask].mean(axis=0)
    scales = numeric[train_mask].std(axis=0)
    scales[scales < 1e-8] = 1.0
    encoded = (numeric - means) / scales
    feature_names = list(numeric_columns)

    cat_columns = []
    for column in CATEGORICAL_FEATURES[model]:
        train_categories = sorted(frame.loc[train_mask, column].astype(str).unique())
        for category in train_categories:
            cat_columns.append((frame[column].astype(str) == category).astype(float).to_numpy())
            feature_names.append(f"{column}={category}")
    if cat_columns:
        encoded = np.column_stack([encoded] + cat_columns)
    return encoded, feature_names


def run_score_model(
    group: pd.DataFrame,
    model: str,
    masks: dict[str, np.ndarray],
    group_key: tuple[str, int, int],
) -> tuple[dict[str, object], list[dict[str, object]]]:
    y = group["edge_label"].to_numpy(dtype=int)
    score = make_score(group, model, masks["train"])
    threshold = best_f1_threshold(y[masks["validation"]], score[masks["validation"]])
    metrics = classification_metrics(y[masks["test"]], score[masks["test"]], threshold)
    scenario, replicate_id, edge_repeat = group_key
    metrics.update(
        {
            "dataset_scenario": scenario,
            "replicate_id": int(replicate_id),
            "edge_repeat": int(edge_repeat),
            "model": model,
        }
    )
    predictions = prediction_rows(group, model, score, threshold, masks["test"])
    return metrics, predictions


def run_logistic_model(
    group: pd.DataFrame,
    model: str,
    masks: dict[str, np.ndarray],
    group_key: tuple[str, int, int],
    ridge: float,
    max_iterations: int,
) -> tuple[dict[str, object], list[dict[str, object]], list[dict[str, object]]]:
    y = group["edge_label"].to_numpy(dtype=int)
    x, feature_names = encode_features(group, model, masks["train"])
    beta = fit_weighted_logistic(x[masks["train"]], y[masks["train"]], ridge, max_iterations)
    probability = sigmoid(np.column_stack([np.ones(len(x)), x]) @ beta)
    threshold = best_f1_threshold(y[masks["validation"]], probability[masks["validation"]])
    metrics = classification_metrics(y[masks["test"]], probability[masks["test"]], threshold)

    scenario, replicate_id, edge_repeat = group_key
    metrics.update(
        {
            "dataset_scenario": scenario,
            "replicate_id": int(replicate_id),
            "edge_repeat": int(edge_repeat),
            "model": model,
        }
    )
    predictions = prediction_rows(group, model, probability, threshold, masks["test"])
    coefficients = [
        {
            "dataset_scenario": scenario,
            "replicate_id": int(replicate_id),
            "edge_repeat": int(edge_repeat),
            "model": model,
            "feature": name,
            "coefficient": float(value),
        }
        for name, value in zip(["intercept"] + feature_names, beta)
    ]
    return metrics, predictions, coefficients


def prediction_rows(
    group: pd.DataFrame,
    model: str,
    score: np.ndarray,
    threshold: float,
    test_mask: np.ndarray,
) -> list[dict[str, object]]:
    rows = []
    for idx in np.where(test_mask)[0]:
        rows.append(
            {
                "dataset_scenario": group.loc[idx, "dataset_scenario"],
                "replicate_id": int(group.loc[idx, "replicate_id"]),
                "edge_repeat": int(group.loc[idx, "edge_repeat"]),
                "candidate_id": group.loc[idx, "candidate_id"],
                "source": group.loc[idx, "source"],
                "target": group.loc[idx, "target"],
                "edge_label": int(group.loc[idx, "edge_label"]),
                "model": model,
                "score": float(score[idx]),
                "threshold": float(threshold),
                "predicted_label": int(score[idx] >= threshold),
            }
        )
    return rows


def add_error_analysis(predictions: pd.DataFrame, metadata: pd.DataFrame) -> pd.DataFrame:
    audit_columns = [
        "candidate_id",
        "target_edge_type",
        "layer_transition",
        "source_node_type",
        "target_node_type",
    ]
    merged = predictions.merge(metadata[audit_columns], on="candidate_id", how="left")
    merged["error_type"] = np.select(
        [
            (merged["edge_label"] == 1) & (merged["predicted_label"] == 1),
            (merged["edge_label"] == 0) & (merged["predicted_label"] == 0),
            (merged["edge_label"] == 0) & (merged["predicted_label"] == 1),
            (merged["edge_label"] == 1) & (merged["predicted_label"] == 0),
        ],
        ["TP", "TN", "FP", "FN"],
        default="unknown",
    )
    return merged


def summarise_errors(enriched_predictions: pd.DataFrame, by: list[str]) -> pd.DataFrame:
    summary = (
        enriched_predictions.groupby(["dataset_scenario", "model"] + by + ["error_type"])
        .size()
        .rename("n")
        .reset_index()
    )
    total = (
        enriched_predictions.groupby(["dataset_scenario", "model"] + by)
        .size()
        .rename("group_total")
        .reset_index()
    )
    summary = summary.merge(total, on=["dataset_scenario", "model"] + by, how="left")
    summary["rate_within_group"] = summary["n"] / summary["group_total"]
    return summary.sort_values(["dataset_scenario", "model"] + by + ["error_type"])

In [ ]:
def main() -> None:
    args = parse_args()
    args.output_dir.mkdir(parents=True, exist_ok=True)

    split_file = "edge_splits.csv" if args.full_oracle else "edge_splits_observed.csv"
    candidate_file = "edge_candidates.csv" if args.full_oracle else "edge_candidates_observed.csv"
    features = pd.read_csv(args.hcr_dir / "edge_pair_features_train_only.csv")
    splits = pd.read_csv(args.hcr_dir / split_file)
    metadata = pd.read_csv(args.hcr_dir / candidate_file)

    data = features.merge(
        splits[["edge_repeat", "candidate_id", "edge_split"]],
        on="candidate_id",
        how="inner",
    )
    data = data[data["pair_available"] == 1].copy()
    if args.scenarios:
        data = data[data["dataset_scenario"].isin(args.scenarios)].copy()

    metric_rows = []
    prediction_rows_all = []
    coefficient_rows = []
    group_columns = ["dataset_scenario", "replicate_id", "edge_repeat"]

    for group_key, group in data.groupby(group_columns, sort=True):
        group = group.reset_index(drop=True)
        masks = {
            "train": group["edge_split"].eq("train").to_numpy(),
            "validation": group["edge_split"].eq("validation").to_numpy(),
            "test": group["edge_split"].eq("test").to_numpy(),
        }
        y = group["edge_label"].to_numpy(dtype=int)
        if y[masks["train"]].sum() == 0 or (1 - y[masks["train"]]).sum() == 0:
            continue

        for model in SCORE_MODELS:
            metrics, predictions = run_score_model(group, model, masks, group_key)
            metric_rows.append(metrics)
            prediction_rows_all.extend(predictions)

        for model in NUMERIC_FEATURES:
            metrics, predictions, coefficients = run_logistic_model(
                group, model, masks, group_key, args.ridge, args.max_iterations
            )
            metric_rows.append(metrics)
            prediction_rows_all.extend(predictions)
            coefficient_rows.extend(coefficients)

    metrics_df = pd.DataFrame(metric_rows)
    predictions_df = pd.DataFrame(prediction_rows_all)
    coefficients_df = pd.DataFrame(coefficient_rows)
    enriched_predictions = add_error_analysis(predictions_df, metadata)

    summary = (
        metrics_df.groupby(["dataset_scenario", "model"])
        .agg(
            n_runs=("average_precision", "size"),
            average_precision_mean=("average_precision", "mean"),
            average_precision_sd=("average_precision", "std"),
            roc_auc_mean=("roc_auc", "mean"),
            roc_auc_sd=("roc_auc", "std"),
            f1_mean=("f1", "mean"),
            f1_sd=("f1", "std"),
            brier_mean=("brier_score", "mean"),
        )
        .reset_index()
    )

    metrics_df.to_csv(args.output_dir / "link_prediction_metrics.csv", index=False)
    summary.to_csv(args.output_dir / "link_prediction_summary.csv", index=False)
    predictions_df.to_csv(args.output_dir / "link_prediction_test_predictions.csv", index=False)
    coefficients_df.to_csv(args.output_dir / "link_prediction_coefficients.csv", index=False)
    enriched_predictions.to_csv(
        args.output_dir / "link_prediction_test_predictions_with_audit_metadata.csv",
        index=False,
    )
    summarise_errors(enriched_predictions, ["target_edge_type"]).to_csv(
        args.output_dir / "error_analysis_by_edge_type.csv",
        index=False,
    )
    summarise_errors(enriched_predictions, ["layer_transition"]).to_csv(
        args.output_dir / "error_analysis_by_layer_transition.csv",
        index=False,
    )

    config = {
        "hcr_dir": str(args.hcr_dir),
        "split_file": split_file,
        "candidate_file": candidate_file,
        "target": "edge_label",
        "scenario_filter": args.scenarios,
        "ridge": args.ridge,
        "max_iterations": args.max_iterations,
        "forbidden_predictor_columns": [
            "edge_label",
            "target_edge_type",
            "target_effect_sign",
            "target_effect_size",
            "reference_edge_id",
            "reference_hcr_conditioning_hint",
        ],
    }
    (args.output_dir / "run_config.json").write_text(
        json.dumps(config, indent=2), encoding="utf-8"
    )

    print(summary.to_string(index=False))
    print(f"\nSaved outputs to: {args.output_dir}")


if __name__ == "__main__":
    main()

In [15]:
from omegaconf import OmegaConf
from data.load_split_benchmark_data import load_split_benchmark_data, build_patient_graph_for_split, load_structural_graph, _build_patient_node_features
from data.load_split_benchmark_data import build_combined_splits

cfg = OmegaConf.create({
    "data": {
        "name": "syn",
        "target": "DILI",
        "dataset": {
            "root_dir": "/content/drive/MyDrive/synthetic_pharmacotherapy_v2 2/synthetic_pharmacotherapy_v2_1_nn_benchmark",
            "nodes_file": "synthetic_pharmacotherapy_v2_nodes.csv",
            "edges_file": "synthetic_pharmacotherapy_v2_1_edges_audited.csv",
            "include_external_test": False,
            "keep_scenario": False,
            "scenarios": {
                "clean": "synthetic_pharmacotherapy_v2_samples_clean.csv"
                #"no_overlap": "synthetic_pharmacotherapy_v2_samples_no_overlap.csv",
                #"multihospital": "synthetic_pharmacotherapy_v2_samples_multihospital.csv",
                #"hidden":   "synthetic_pharmacotherapy_v2_samples_hidden_confounder.csv",
                #"doc": "synthetic_pharmacotherapy_v2_samples_noisy_documentation.csv",
                #"bias": "synthetic_pharmacotherapy_v2_samples_selection_bias.csv"
            },
        }
    }
})

In [16]:
train, valid, test = load_split_benchmark_data(cfg)
structural = load_structural_graph(cfg)
#x = _build_patient_node_features(train, )
#splits=build_combined_splits(cfg)

In [17]:
splits=build_combined_splits(cfg)

In [18]:
all=splits['all']
train=splits['train']
valid=splits['valid']
test=splits['test']

In [ ]:
valid['Falls'].value_counts()

Falls
0    4660
1     340
Name: count, dtype: int64

In [27]:
#dag - struktura grafu
node_to_idx = structural['node_to_idx']
structural_edges = structural['structural_edges']
node_index = structural['node_index']

In [28]:
node_index['recommended_use'].value_counts()

recommended_use
feature_or_target              105
exclude_from_observed_model      1
Name: count, dtype: int64

In [29]:
ID_COLS = ["patient_id", "hospital_id"]
META_COLS = [
    "benchmark_split", "benchmark_scenario", "replicate_id",
    "generation_seed", "paired_patient_key",
]

In [31]:
patient_graph =build_patient_graph_for_split(train, node_to_idx, ["Hospitalization"], train)

In [32]:
patient_graph['link_labels']

       patient_local_idx      target_node  target_node_idx  label
0                      0  Hospitalization              102      0
1                      1  Hospitalization              102      0
2                      2  Hospitalization              102      0
3                      3  Hospitalization              102      0
4                      4  Hospitalization              102      0
...                  ...              ...              ...    ...
29995              29995  Hospitalization              102      0
29996              29996  Hospitalization              102      0
29997              29997  Hospitalization              102      0
29998              29998  Hospitalization              102      0
29999              29999  Hospitalization              102      0

[30000 rows x 4 columns]

In [33]:
f=patient_graph['feature_cols']

In [34]:
patient_graph['patient_index']

       patient_id  patient_local_idx
0               1                  0
1               2                  1
2               4                  2
3               7                  3
4               8                  4
...           ...                ...
29995       49994              29995
29996       49996              29996
29997       49997              29997
29998       49998              29998
29999       49999              29999

[30000 rows x 2 columns]

In [35]:
#struktura grafu DAG
out = {
        "structural": {
            "node_index": structural["node_index"],
            "structural_edges": structural["structural_edges"],
        }
      }

In [36]:
out #struktura grafu DAG edges & nodes

{'structural': {'node_index':      node_idx                         node          node_type  \
  0           0                          age    patient_context
  1           1                  alcohol_use    patient_context
  2           2             baseline_alt_ast    patient_context
  3           3                baseline_egfr    patient_context
  4           4  baseline_mood_vulnerability    patient_context
  ..        ...                          ...                ...
  101       101                  GI_bleeding  clinical_endpoint
  102       102              Hospitalization  clinical_endpoint
  103       103                 Hyperkalemia  clinical_endpoint
  104       104                 Hyponatremia  clinical_endpoint
  105       105                QT_arrhythmia  clinical_endpoint

                   layer                                    description  \
  0    1_patient_context                       Age in years, continuous
  1    1_patient_context                   Alcohol exposure/risk marker
  2    1_patient_context              Continuous baseline liver enzymes
  3    1_patient_context            Continuous baseline kidney function
  4    1_patient_context  Synthetic latent-ish mood vulnerability proxy
  ..                 ...                                            ...
  101        6_endpoints                                    GI bleeding
  102        6_endpoints        Hospitalization or prolongation of stay
  103        6_endpoints                          Hyperkalemia endpoint
  104        6_endpoints                          Hyponatremia endpoint
  105        6_endpoints          QT prolongation / arrhythmia endpoint

       base_prevalence frequency_class  severity_weight  observability  \
  0                NaN             NaN                1           1.00
  1              0.110          common                3           0.65
  2                NaN             NaN                4           0.75
  3                NaN             NaN                4           0.90
  4              0.120          common                3           0.65
  ..               ...             ...              ...            ...
  101            0.020      occasional                5           0.75
  102            0.120          common                3           0.85
  103            0.040      occasional                5           0.85
  104            0.060        frequent                4           0.85
  105            0.012      occasional                5           0.60

       rarity_weight  node_priority_weight  is_endpoint  is_rare_signal  \
  0              NaN                   NaN        False           False
  1            1.371                 4.473        False           False
  2              NaN                   NaN        False           False
  3              NaN                   NaN        False           False
  4            1.312                 4.280        False           False
  ..             ...                   ...          ...             ...
  101          3.214                10.000         True            True
  102          1.312                 4.084         True           False
  103          2.273                10.000         True            True
  104          1.856                 7.702         True           False
  105          4.149                10.000         True            True

       is_latent    recommended_use
  0        False  feature_or_target
  1        False  feature_or_target
  2        False  feature_or_target
  3        False  feature_or_target
  4        False  feature_or_target
  ..         ...                ...
  101      False  feature_or_target
  102      False  feature_or_target
  103      False  feature_or_target
  104      False  feature_or_target
  105      False  feature_or_target

  [106 rows x 15 columns],
  'structural_edges':      source_idx  target_idx edge_id                source  \
  0             0          11    e001                   age
  1             0           3    e002                   age
  2            10           8    e003              diabetes
  3            12           8    e004         heart_failure
  4            14           2    e005         liver_disease
  ..          ...         ...     ...                   ...
  203          15          91    e204  monitoring_intensity
  204          15          92    e205  monitoring_intensity
  205          15          93    e206  monitoring_intensity
  206          15          94    e207  monitoring_intensity
  207          15          95    e208  monitoring_intensity

                    target            edge_type  effect_sign  effect_size  \
  0                frailty        risk_modifier            1         0.60
  1          baseline_egfr        risk_modifier           -1         0.50
  2                    ckd        risk_modifier            1         0.70
  3                    ckd        risk_modifier            1         0.50
  4       baseline_alt_ast        risk_modifier            1         0.80
  ..                   ...                  ...          ...          ...
  203        fall_reported  observation_process            1         0.75
  204     hospital_contact  observation_process            1         0.75
  205           lft_tested  observation_process            1         0.75
  206  mood_screening_done  observation_process            1         0.75
  207          qt_recorded  observation_process            1         0.75

       activation_frequency  mechanistic_confidence  evidence_weight  \
  0                    0.40                    0.70             0.60
  1                    0.80                    0.90             0.80
  2                    0.30                    0.85             0.80
  3                    0.25                    0.80             0.75
  4                    0.60                    0.90             0.80
  ..                    ...                     ...              ...
  203                  0.90                    0.70             0.50
  204                  0.90                    0.70             0.50
  205                  0.90                    0.70             0.50
  206                  0.90                    0.70             0.50
  207                  0.90                    0.70             0.50

      temporal_lag      dag_motif      clinical_pathway hcr_conditioning_hint  \
  0           long     confounder  global_vulnerability     ckd,heart_failure
  1           long  risk_modifier                   AKI          ckd,diabetes
  2           long          chain                   AKI                   age
  3           long          chain                   AKI                   age
  4           long  risk_modifier                  DILI           alcohol_use
  ..           ...            ...                   ...                   ...
  203  observation      selection         documentation  monitoring_intensity
  204  observation      selection         documentation  monitoring_intensity
  205  observation      selection         documentation  monitoring_intensity
  206  observation      selection         documentation  monitoring_intensity
  207  observation      selection         documentation  monitoring_intensity

       hcr_information_weight  gnn_edge_weight
  0                       NaN              NaN
  1                       NaN              NaN
  2                       NaN              NaN
  3                       NaN              NaN
  4                       NaN              NaN
  ..                      ...              ...
  203                     NaN              NaN
  204                     NaN              NaN
  205                     NaN              NaN
  206                     NaN              NaN
  207                     NaN              NaN

  [208 rows x 17 columns]}}

In [37]:
#from build_gnn_link_prediction_inputs = dict output with frames train, valid, test
for split_name in ["train", "valid", "test"]:
        out[split_name] = build_patient_graph_for_split(
            df=splits[split_name],
            node_to_idx=node_to_idx,
            target_endpoints=['Falls'],
            split_name=split_name,
        )
        out[split_name]["frame"] = splits[split_name]

In [40]:
#train_out from build_gnn_link_prediction_inputs
train_out=out['train']

In [41]:
#feature edges between patient id and node id
feature_edges=train_out['feature_edges']
#w feature edges nie mam Falls czyli ostatecznego targetu

In [43]:
feature_edges[feature_edges['node_idx']==1]

        patient_local_idx  node_idx  value
0                       0         1    1.0
26                      2         1    1.0
54                      5         1    1.0
107                    10         1    1.0
118                    11         1    1.0
...                   ...       ...    ...
313082              29977         1    1.0
313130              29982         1    1.0
313180              29987         1    1.0
313193              29988         1    1.0
313280              29997         1    1.0

[4479 rows x 3 columns]

In [44]:
#train node features from build_gnn_link_prediction_inputs
train_node_features=train_out['node_features']

In [45]:
train_node_features[train_node_features['node_idx']==100]
#node_features nie ma 100

Empty DataFrame
Columns: [patient_local_idx, node_idx, value]
Index: []

In [ ]:
patient_0=train_node_features[train_node_features['patient_local_idx']==0]

In [ ]:
patient_0[patient_0['node_idx']==105]

     patient_local_idx  node_idx  value
104                  0       105    0.0

In [46]:
import pandas as pd
from omegaconf import DictConfig
from data.load_split_benchmark_data import build_gnn_link_prediction_inputs

def compute_feature_endpoint_correlations(cfg: DictConfig, endpoint_name: str, split: str = "train") -> pd.Series:
    """
    Zwraca korelacje (Pearson) między wybranym endpointem a wszystkimi feature_cols
    dla wskazanego splitu (train/valid/test).
    """
    gnn_inputs = build_gnn_link_prediction_inputs(cfg)
    block = gnn_inputs[split]

    frame_df = train_out["frame"]          # tabela pacjentów
    feature_cols = train_out["feature_cols"]

    if endpoint_name not in frame_df.columns:
        raise ValueError(f"Endpoint '{endpoint_name}' nie występuje w kolumnach frame_df.")

    y = pd.to_numeric(frame_df[endpoint_name], errors="coerce")

    # weź tylko kolumny z feature_cols i rzutuj na float
    X = frame_df[feature_cols].apply(pd.to_numeric, errors="coerce")

    # oblicz korelacje kolumn X z endpointem y
    # pandas ma wygodną metodę corrwith
    corr_series = X.corrwith(y, method="spearman")

    # posortuj od najsilniejszej zależności (w sensie absolutnej wartości)
    corr_series = corr_series.reindex(corr_series.abs().sort_values(ascending=False).index)

    return corr_series

# przykładowe użycie:
# cfg = ... # załadowany config Hydry
# corr = compute_feature_endpoint_correlations(cfg, endpoint_name="Falls", split="train")
# print(corr.head(20))  # top 20 najbardziej skorelowanych feature'ów

In [48]:
compute_feature_endpoint_correlations(cfg, "DILI", "train")

DILI                   1.000000
hospital_contact       0.037959
alt_ast_rise           0.030512
hepatotoxic_drug_A     0.024323
unobserved_severity    0.021640
                         ...
alcohol_use            0.000292
ssri                  -0.000281
Depression            -0.000225
thiazide              -0.000124
hyperkalemia_state     0.000010
Length: 105, dtype: float64

In [ ]:
patient_graph['link_labels']['label'].value_counts()

label
0    27976
1     2024
Name: count, dtype: int64

In [ ]:
splits=build_combined_splits(cfg)

In [ ]:
all['benchmark_split'].value_counts()

benchmark_split
train    30000
test     15000
valid     5000
Name: count, dtype: int64

In [ ]:
train

hospital_id
1    30000
Name: count, dtype: int64

In [ ]:
structural['structural_edges']

,source_idx,target_idx,edge_id,source,target,edge_type,effect_sign,effect_size,activation_frequency,mechanistic_confidence,evidence_weight,temporal_lag,dag_motif,clinical_pathway,hcr_conditioning_hint,hcr_information_weight,gnn_edge_weight
0,0,11,e001,age,frailty,risk_modifier,1,0.60,0.40,0.70,0.60,long,confounder,global_vulnerability,"ckd,heart_failure",NaN,NaN
1,0,3,e002,age,baseline_egfr,risk_modifier,-1,0.50,0.80,0.90,0.80,long,risk_modifier,AKI,"ckd,diabetes",NaN,NaN
2,10,8,e003,diabetes,ckd,risk_modifier,1,0.70,0.30,0.85,0.80,long,chain,AKI,age,NaN,NaN
3,12,8,e004,heart_failure,ckd,risk_modifier,1,0.50,0.25,0.80,0.75,long,chain,AKI,age,NaN,NaN
4,14,2,e005,liver_disease,baseline_alt_ast,risk_modifier,1,0.80,0.60,0.90,0.80,long,risk_modifier,DILI,alcohol_use,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
203,15,91,e204,monitoring_intensity,fall_reported,observation_process,1,0.75,0.90,0.70,0.50,observation,selection,documentation,monitoring_intensity,NaN,NaN
204,15,92,e205,monitoring_intensity,hospital_contact,observation_process,1,0.75,0.90,0.70,0.50,observation,selection,documentation,monitoring_intensity,NaN,NaN
205,15,93,e206,monitoring_intensity,lft_tested,observation_process,1,0.75,0.90,0.70,0.50,observation,selection,documentation,monitoring_intensity,NaN,NaN
206,15,94,e207,monitoring_intensity,mood_screening_done,observation_process,1,0.75,0.90,0.70,0.50,observation,selection,documentation,monitoring_intensity,NaN,NaN
207,15,95,e208,monitoring_intensity,qt_recorded,observation_process,1,0.75,0.90,0.70,0.50,observation,selection,documentation,monitoring_intensity,NaN,NaN

In [ ]:
train_pd = pd.DataFrame(train, columns=['kol1', 'kol2'])

In [ ]:
train

{'patient_index':        patient_id  patient_local_idx
 0               1                  0
 1               2                  1
 2               4                  2
 3               7                  3
 4               8                  4
 ...           ...                ...
 29995       49994              29995
 29996       49996              29996
 29997       49997              29997
 29998       49998              29998
 29999       49999              29999

 [30000 rows x 2 columns],
 'node_features':          patient_local_idx  node_idx  value
 0                        0         0   80.5
 1                        0         1    1.0
 2                        0         2   29.9
 3                        0         3   38.2
 4                        0         4    0.0
 ...                    ...       ...    ...
 3149995              29999       101    0.0
 3149996              29999       102    0.0
 3149997              29999       103    0.0
 3149998              29999       104    0.0
 3149999              29999       105    0.0

 [3150000 rows x 3 columns],
 'feature_edges':         patient_local_idx  node_idx  value
 0                       0         1    1.0
 1                       0        10    1.0
 2                       0        11    1.0
 3                       0        13    1.0
 4                       0        17    1.0
 ...                   ...       ...    ...
 315014              29999        47    1.0
 315015              29999        75    1.0
 315016              29999        83    1.0
 315017              29999        85    1.0
 315018              29999        92    1.0

 [315019 rows x 3 columns],
 'link_labels':        patient_local_idx target_node  target_node_idx  label
 0                      0        DILI               97      0
 1                      1        DILI               97      0
 2                      2        DILI               97      0
 3                      3        DILI               97      0
 4                      4        DILI               97      0
 ...                  ...         ...              ...    ...
 29995              29995        DILI               97      0
 29996              29996        DILI               97      0
 29997              29997        DILI               97      0
 29998              29998        DILI               97      0
 29999              29999        DILI               97      0

 [30000 rows x 4 columns],
 'feature_cols': ['age',
  'alcohol_use',
  'baseline_alt_ast',
  'baseline_egfr',
  'baseline_mood_vulnerability',
  'baseline_potassium',
  'baseline_qt_risk',
  'baseline_sodium',
  'ckd',
  'depression_history',
  'diabetes',
  'frailty',
  'heart_failure',
  'infection',
  'liver_disease',
  'monitoring_intensity',
  'polypharmacy_burden',
  'sex_female',
  'unobserved_severity',
  'acei_arb',
  'aminoglycoside',
  'antibiotic_hepatic_risk',
  'anticholinergic',
  'anticoagulant',
  'antiplatelet',
  'benzodiazepine',
  'beta_blocker',
  'contrast_agent',
  'corticosteroid',
  'diuretic',
  'hepatotoxic_drug_A',
  'herbal_exposure',
  'nsaid',
  'opioid',
  'ppi',
  'qt_prolonging_drug',
  'snri',
  'ssri',
  'thiazide',
  'valproate_like_drug',
  'anticholinergic_burden',
  'cardiac_repolarization_delay',
  'cholestatic_pattern',
  'cns_sedation',
  'coagulation_impairment',
  'electrolyte_disturbance',
  'fatigue_pathway',
  'gastric_mucosal_injury',
  'gastric_protection',
  'hepatic_metabolic_stress',
  'hepatocellular_injury',
  'monoamine_disruption',
  'nephrotoxic_stress',
  'oxidative_hepatic_stress',
  'platelet_inhibition',
  'potassium_retention',
  'psychomotor_impairment',
  'reduced_renal_perfusion',
  'serotonergic_shift',
  'sleep_disruption',
  'sodium_water_imbalance',
  'tubular_injury',
  'volume_depletion',
  'alt_ast_rise',
  'anhedonia_like_symptom',
  'bilirubin_rise',
  'cognitive_slowing',
  'confusion_state',
  'creatinine_rise',
  'dehydration',
  'dizziness',
  'fatigue_symptom',
  'gi_irritation',
  'hyperkalemia_state',
  'hyponatremia_state',
  'hypotension',
  'jaundice',
  'mood_lowering',
  'nausea',
  'occult_bleeding',
  'overt_bleeding',
  'qt_prolongation_state',
  'sedation_state',
  'sleep_disturbance_symptom',
  'adr_reported',
  'creatinine_tested',
  'ecg_performed',
  'electrolyte_abnormality_recorded',
  'electrolytes_tested',
  'elevated_alt_ast_recorded',
  'elevated_creatinine_recorded',
  'fall_reported',
  'hospital_contact',
  'lft_tested',
  'mood_screening_done',
  'qt_recorded',
  'AKI',
  'Delirium',
  'Depression',
  'Falls',
  'GI_bleeding',
  'Hospitalization',
  'Hyperkalemia',
  'Hyponatremia',
  'QT_arrhythmia'],
 'frame':        patient_id  hospital_id benchmark_split  replicate_id  generation_seed  \
 0               1            1           train             1       1654771777
 1               2            1           train             1       1654771777
 2               4            1           train             1       1654771777
 3               7            1           train             1       1654771777
 4               8            1           train             1       1654771777
 ...           ...          ...             ...           ...              ...
 29995       49994            1           train             5       2120901198
 29996       49996            1           train             5       2120901198
 29997       49997            1           train             5       2120901198
 29998       49998            1           train             5       2120901198
 29999       49999            1           train             5       2120901198

       paired_patient_key   age  alcohol_use  baseline_alt_ast  baseline_egfr  \
 0          rep01::p00001  80.5            1              29.9           38.2
 1          rep01::p00002  78.3            0              19.1           26.6
 2          rep01::p00004  63.5            1              40.1           32.2
 3          rep01::p00007  80.2            0              32.4           52.7
 4          rep01::p00008  68.9            0              29.9           42.8
 ...                  ...   ...          ...               ...            ...
 29995      rep05::p09994  48.5            0              26.3           75.9
 29996      rep05::p09996  54.3            0              34.8           55.8
 29997      rep05::p09997  64.8            1              34.2           61.5
 29998      rep05::p09998  75.3            0              24.5           45.5
 29999      rep05::p09999  78.3            0               8.0           54.3

        ...  AKI  DILI  Delirium  Depression  Falls  GI_bleeding  \
 0      ...    0     0         0           1      0            0
 1      ...    0     0         0           0      0            0
 2      ...    0     0         0           0      0            0
 3      ...    0     0         0           0      1            0
 4      ...    0     0         0           0      0            0
 ...    ...  ...   ...       ...         ...    ...          ...
 29995  ...    0     0         0           0      0            0
 29996  ...    0     0         0           0      0            0
 29997  ...    0     0         0           0      0            0
 29998  ...    0     0         0           0      0            0
 29999  ...    0     0         0           0      0            0

        Hospitalization  Hyperkalemia  Hyponatremia  QT_arrhythmia
 0                    0             0             0              0
 1                    0             0             0              0
 2                    0             0             0              0
 3                    0             0             0              0
 4                    0             0             0              0
 ...                ...           ...           ...            ...
 29995                0             0             0              0
 29996                0             0             0              0
 29997                0             0             0              0
 29998                0             0             0              0
 29999                0             0             0              0

 [30000 rows x 112 columns]}

In [ ]:
import pandas as pd

In [ ]:
clean=pd.read_csv("/content/drive/MyDrive/synthetic_pharmacotherapy_v2 2/synthetic_pharmacotherapy_v2_1_nn_benchmark/synthetic_pharmacotherapy_v2_samples_clean.csv")

In [ ]:
nodes=pd.read_csv("/content/drive/MyDrive/synthetic_pharmacotherapy_v2 2/synthetic_pharmacotherapy_v2_1_nn_benchmark/synthetic_pharmacotherapy_v2_nodes.csv")

In [ ]:
columns = clean.columns.tolist()

In [ ]:
columns

['patient_id',
 'hospital_id',
 'age',
 'alcohol_use',
 'baseline_alt_ast',
 'baseline_egfr',
 'baseline_mood_vulnerability',
 'baseline_potassium',
 'baseline_qt_risk',
 'baseline_sodium',
 'ckd',
 'depression_history',
 'diabetes',
 'frailty',
 'heart_failure',
 'infection',
 'liver_disease',
 'monitoring_intensity',
 'polypharmacy_burden',
 'sex_female',
 'unobserved_severity',
 'acei_arb',
 'aminoglycoside',
 'antibiotic_hepatic_risk',
 'anticholinergic',
 'anticoagulant',
 'antiplatelet',
 'benzodiazepine',
 'beta_blocker',
 'contrast_agent',
 'corticosteroid',
 'diuretic',
 'hepatotoxic_drug_A',
 'herbal_exposure',
 'nsaid',
 'opioid',
 'ppi',
 'qt_prolonging_drug',
 'snri',
 'ssri',
 'thiazide',
 'valproate_like_drug',
 'anticholinergic_burden',
 'cardiac_repolarization_delay',
 'cholestatic_pattern',
 'cns_sedation',
 'coagulation_impairment',
 'electrolyte_disturbance',
 'fatigue_pathway',
 'gastric_mucosal_injury',
 'gastric_protection',
 'hepatic_metabolic_stress',
 'hepatocellular_injury',
 'monoamine_disruption',
 'nephrotoxic_stress',
 'oxidative_hepatic_stress',
 'platelet_inhibition',
 'potassium_retention',
 'psychomotor_impairment',
 'reduced_renal_perfusion',
 'serotonergic_shift',
 'sleep_disruption',
 'sodium_water_imbalance',
 'tubular_injury',
 'volume_depletion',
 'alt_ast_rise',
 'anhedonia_like_symptom',
 'bilirubin_rise',
 'cognitive_slowing',
 'confusion_state',
 'creatinine_rise',
 'dehydration',
 'dizziness',
 'fatigue_symptom',
 'gi_irritation',
 'hyperkalemia_state',
 'hyponatremia_state',
 'hypotension',
 'jaundice',
 'mood_lowering',
 'nausea',
 'occult_bleeding',
 'overt_bleeding',
 'qt_prolongation_state',
 'sedation_state',
 'sleep_disturbance_symptom',
 'adr_reported',
 'creatinine_tested',
 'ecg_performed',
 'electrolyte_abnormality_recorded',
 'electrolytes_tested',
 'elevated_alt_ast_recorded',
 'elevated_creatinine_recorded',
 'fall_reported',
 'hospital_contact',
 'lft_tested',
 'mood_screening_done',
 'qt_recorded',
 'AKI',
 'DILI',
 'Delirium',
 'Depression',
 'Falls',
 'GI_bleeding',
 'Hospitalization',
 'Hyperkalemia',
 'Hyponatremia',
 'QT_arrhythmia',
 'replicate_id',
 'generation_seed',
 'benchmark_split',
 'paired_patient_key',
 'benchmark_scenario']

In [ ]:
nodes[nodes['node'].isin(columns)]

,node,node_type,layer,description,base_prevalence,frequency_class,severity_weight,observability,rarity_weight,node_priority_weight,is_endpoint,is_rare_signal,is_latent,recommended_use
0,age,patient_context,1_patient_context,"Age in years, continuous",NaN,NaN,1,1.00,NaN,NaN,False,False,False,feature_or_target
1,alcohol_use,patient_context,1_patient_context,Alcohol exposure/risk marker,0.110,common,3,0.65,1.371,4.473,False,False,False,feature_or_target
2,baseline_alt_ast,patient_context,1_patient_context,Continuous baseline liver enzymes,NaN,NaN,4,0.75,NaN,NaN,False,False,False,feature_or_target
3,baseline_egfr,patient_context,1_patient_context,Continuous baseline kidney function,NaN,NaN,4,0.90,NaN,NaN,False,False,False,feature_or_target
4,baseline_mood_vulnerability,patient_context,1_patient_context,Synthetic latent-ish mood vulnerability proxy,0.120,common,3,0.65,1.312,4.280,False,False,False,feature_or_target
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,GI_bleeding,clinical_endpoint,6_endpoints,GI bleeding,0.020,occasional,5,0.75,3.214,10.000,True,True,False,feature_or_target
102,Hospitalization,clinical_endpoint,6_endpoints,Hospitalization or prolongation of stay,0.120,common,3,0.85,1.312,4.084,True,False,False,feature_or_target
103,Hyperkalemia,clinical_endpoint,6_endpoints,Hyperkalemia endpoint,0.040,occasional,5,0.85,2.273,10.000,True,True,False,feature_or_target
104,Hyponatremia,clinical_endpoint,6_endpoints,Hyponatremia endpoint,0.060,frequent,4,0.85,1.856,7.702,True,False,False,feature_or_target
105,QT_arrhythmia,clinical_endpoint,6_endpoints,QT prolongation / arrhythmia endpoint,0.012,occasional,5,0.60,4.149,10.000,True,True,False,feature_or_target

In [ ]:
train['node_features']['value'].isna() == True

0           False
1           False
2           False
3           False
4           False
            ...
17870575    False
17870576    False
17870577    False
17870578    False
17870579    False
Name: value, Length: 17870580, dtype: bool

In [ ]:
import torch

In [ ]:
import torch
import pandas as pd

# The original code expected `train` to be a torch_geometric.data.HeteroData object,
# where 'patient_id' and 'variable' would be node types and
# ('patient_id', 'has', 'variable') an edge type.
# However, `train` is a dictionary of pandas DataFrames.

# To check for NaNs and Infs in the relevant numeric columns of the DataFrames:

# Check 'node_features' DataFrame's 'value' column
if 'node_features' in train and 'value' in train['node_features'].columns:
    node_features_values = torch.tensor(train['node_features']['value'].values, dtype=torch.float32)
    print(f"Node features (all nodes): NaN presence: {torch.isnan(node_features_values).any()}, Inf presence: {torch.isinf(node_features_values).any()}")
else:
    print("Warning: 'node_features' or 'value' column not found in train dictionary.")

# Check 'feature_edges' DataFrame's 'value' column
if 'feature_edges' in train and 'value' in train['feature_edges'].columns:
    edge_attributes_values = torch.tensor(train['feature_edges']['value'].values, dtype=torch.float32)
    print(f"Edge attributes (all edges): NaN presence: {torch.isnan(edge_attributes_values).any()}, Inf presence: {torch.isinf(edge_attributes_values).any()}")
else:
    print("Warning: 'feature_edges' or 'value' column not found in train dictionary.")

# Note: 'patient_id' and 'variable' are not direct keys for node types in the current
# `train` dictionary structure, nor is `("patient_id", "has", "variable")` an edge type key.

Node features (all nodes): NaN presence: True, Inf presence: False
Edge attributes (all edges): NaN presence: False, Inf presence: False

In [ ]:
type(train)

dict

In [ ]:
ENDPOINTS = [
    "AKI", "DILI", "Depression", "Falls", "Delirium",
    "GI_bleeding", "Hyponatremia", "Hyperkalemia",
    "QT_arrhythmia", "Hospitalization",
]

N_total = len(samples)
stats = []

for ep in ENDPOINTS:
    #if ep not in samples.columns:
    #    continue
    N_pos = samples[ep].sum()
    N_neg = N_total - N_pos
    prevalence = N_pos / N_total
    stats.append((ep, int(N_pos), int(N_neg), prevalence))

for ep, N_pos, N_neg, prev in stats:
    print(f"{ep}: pos={N_pos}, neg={N_neg}, prev={prev:.4f}")

KeyError: 'AKI'

In [ ]:
import pandas as pd

ENDPOINTS = [
    "AKI", "DILI", "Depression", "Falls", "Delirium",
    "GI_bleeding", "Hyponatremia", "Hyperkalemia",
    "QT_arrhythmia", "Hospitalization",
]

# tylko endpointy
E = samples[ENDPOINTS].astype(int)

# macierz współwystępowania: liczba pacjentów z ep_i=1 i ep_j=1
coocc_counts = pd.DataFrame(index=ENDPOINTS, columns=ENDPOINTS, dtype=int)

for ep_i in ENDPOINTS:
    for ep_j in ENDPOINTS:
        coocc_counts.loc[ep_i, ep_j] = ((E[ep_i] == 1) & (E[ep_j] == 1)).sum()

print(coocc_counts)

                   AKI  DILI  Depression  Falls  Delirium  GI_bleeding  \
AKI              225.0   3.0        12.0   18.0      11.0          3.0
DILI               3.0  64.0         2.0    4.0       4.0          2.0
Depression        12.0   2.0       258.0   18.0       9.0          4.0
Falls             18.0   4.0        18.0  411.0      23.0          1.0
Delirium          11.0   4.0         9.0   23.0     233.0          0.0
GI_bleeding        3.0   2.0         4.0    1.0       0.0         58.0
Hyponatremia       8.0   2.0        11.0   15.0       6.0          0.0
Hyperkalemia       9.0   1.0         8.0   11.0       5.0          1.0
QT_arrhythmia      1.0   0.0         0.0    3.0       2.0          0.0
Hospitalization   61.0  22.0        39.0  106.0      74.0          6.0

                 Hyponatremia  Hyperkalemia  QT_arrhythmia  Hospitalization
AKI                       8.0           9.0            1.0             61.0
DILI                      2.0           1.0            0.0             22.0
Depression               11.0           8.0            0.0             39.0
Falls                    15.0          11.0            3.0            106.0
Delirium                  6.0           5.0            2.0             74.0
GI_bleeding               0.0           1.0            0.0              6.0
Hyponatremia            228.0           5.0            2.0             27.0
Hyperkalemia              5.0         181.0            0.0             21.0
QT_arrhythmia             2.0           0.0           41.0             10.0
Hospitalization          27.0          21.0           10.0            756.0